### ISSUE TITLE
cannot send post method in "request" function from Axios instance with  Array params

### ISSUE THREAD

**Issue by somewhereMrli** [mzabriskie/axios#1001]
When I try to send POST method using this params Object:

{"orgId":"1","loginId":"anonymoususer","phone":"","email":"anonymous@localhost1","roleIdList":["43186a6c08d247c098ea357e28cc75f4","5faa80a30a374148b5e0943f2a6fcb47"],"status":0,"id":"2"}

but I get this:

{"orgId":"1","loginId":"anonymoususer","phone":"","email":"anonymous@localhost1","roleIdList":{"0":"43186a6c08d247c098ea357e28cc75f4","1":"5faa80a30a374148b5e0943f2a6fcb47"},"status":0,"id":"2"}

the array become object  !!!!!!!!!  

I think this line https://github.com/mzabriskie/axios/blob/master/lib/utils.js#L203 should be: repair

**Comment by rubennorte** [comment]
Could you please attach the code you've used to send that request?

**Comment by rubennorte** [comment]
Closing until more information is provided.
