### ISSUE TITLE
[Question] axios.options request body support

### ISSUE THREAD

**Issue by enheit** [mzabriskie/axios#1003]
Why `axios.options` doesn't support body as request parameter?

**Comment by rubennorte** [comment]
Because in the spec, at the moment, the OPTIONS method isn't meant to have a body

**Comment by enheit** [comment]
@rubennorte Could you please provide link to spec? Looks like I read deprecated article.

**Comment by rubennorte** [comment]
Here you have:

https://tools.ietf.org/html/rfc2616#section-9.2

Specifically:

> this
   specification does not define any use for such a body

In the future they may but not for now.
