### ISSUE TITLE
Prevent Axios from submitting parent form

### ISSUE THREAD

**Issue by cyal8ermate** [mzabriskie/axios#1008]
HI,

So I'm building a file upload tool with axios, plain js and with laravel as a back end.
I have mostly everything functioning correctly including uploading the file and then deleting from the server, however, I'm running into a bit of an issue when sending the delete request in that it is submitting the form that the widget is inside.

I don't want this to happen as the uploading is just one part of the form, with inputs before and after the upload widget.

I have tried altering the axios request to make use of a post instead of a delete request but to no avail.
What is strange is that the initial post (to upload the file) does not submit the form, only the subsequent delete.

- axios version: 0.15.3

**Comment by bram1028** [comment]
Are you calling `preventDefault()` on the form submit event? Something like this:

```javascript
$('form').on('submit', (e) => {
    e.preventDefault()
    axios.delete(...)
})
```

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.

**Comment by cyal8ermate** [comment]
This was because I was being a bit stupid and not realising the default action of a button is to submit. 

We live and we learn!
