### ISSUE TITLE
Does Axios have a way to queue X simultaneous requests?

### ISSUE THREAD

**Issue by donpinkus** [mzabriskie/axios#1010]
Let's say I need to do 20 ajax requests, and my server supports doing 3 at a time.

Does Axios have a way to queue up the 20 requests, and run 3 concurrently? 

It doesn't seem like `.all()` or `.spread()` support this.

**Comment by Bashkir15** [comment]
No, you will need some sort of outside scheduler to handle the execution of your requests. Depending on what your needs are, [an Observable library](http://reactivex.io/rxjs/variable/index.html#static-variable-queue) will  probably be your best bet for managing the queue and handling side-effects.

**Comment by rubennorte** [comment]
You can use `Bluebird.map` to control the concurrency of any Promise-based code. See http://bluebirdjs.com/docs/api/promise.map.html

This is out of the scope of Axios.

**Comment by sergkr** [comment]
I was able to achieve this using another helper library [cwait](https://github.com/charto/cwait) (in combination with axios):

```
import axios from 'axios';
import { TaskQueue } from 'cwait';

const MAX_SIMULTANEOUS_DOWNLOADS = 6;

const urls = [/* Array of URLs to download... */];

const queue = new TaskQueue(Promise, MAX_SIMULTANEOUS_DOWNLOADS);
const results = await Promise.all(urls.map(queue.wrap(async url => await axios.get(url))));
```

**Comment by dmitry** [comment]
Simple implementation is here: https://github.com/bernawil/axios-concurrency

**Comment by cerlestes** [comment]
I think it's sad that this is considered out of scope for a HTTP client library. Ideally axios should support a setting that limits the simultaneously running requests per axios instance. A lot of APIs require sequential requests (i.e. one request at a time), and a HTTP client should be able to support that. I don't see how this is out of scope of this project.

**Comment by leobetosouza** [comment]
@cerlestes there's a way to do it using interceptors, like this: https://medium.com/@matthew_1129/axios-js-maximum-concurrent-requests-b15045eb69d0

I think this code can be catched by a race condition, but it's an idea.
