### ISSUE TITLE
CORS + POST-request + Cancelation = no next POST-request

### ISSUE THREAD

**Issue by comerc** [mzabriskie/axios#1013]
#### Summary

The following OPTIONS and POST requests are not executed if the previous POST request was terminated when the OPTIONS request was executed.

```js
    if (source) {
      source.cancel()
    }
    source = axios.CancelToken.source()
    axios.defaults.cancelToken = source.token
```

#### Context

- axios version: v0.16.2
- Environment: node v7.4.0, chrome 58, ubuntu 14.04

**Comment by rubennorte** [comment]
You must create a new cancel token for each request. If you use the same one and cancel it, all requests will be cancelled. It works this way by design.

**Comment by comerc** [comment]
But when I call axios.post(), axios performs two network requests: OPTIONS and POST.
