### ISSUE TITLE
Typescript definition for AxiosError should include `request?`

### ISSUE THREAD

**Issue by mmarvick** [mzabriskie/axios#1014]
#### Summary

The current [Typescript definition for AxiosError](https://github.com/mzabriskie/axios/blob/master/index.d.ts#L55-L59) has all of the fields that can be on an error except for the optional `request?` param.

See [this code](https://github.com/mzabriskie/axios/blob/master/lib/core/enhanceError.js) where these errors are created.

#### Context

- axios version: v0.16.2
- Environment: React Native 0.42.0 (this is irrelevant)

**Comment by rubennorte** [comment]
Merged. Thanks for your contribution.

**Comment by rsimp** [comment]
@rubennorte I don't believe you published this correctly. I can see the updated index.d.ts on github, but npm is serving up an old version still.

**Comment by mmarvick** [comment]
A new version hasn't been released yet: https://github.com/axios/axios/releases
