### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by alihalabyah** [mzabriskie/axios#1019]
The error handling does not provide sufficient information because of the below piece of code:

```
// Handle low level network errors
    request.onerror = function handleError() {
      // Real errors are hidden from us by the browser
      // onerror should only fire if it's a network error
      reject(createError('Network Error', config, null, request));

      // Clean up request
      request = null;
    };
```

How can this be resolved?

**Comment by marcacyr** [comment]
Just came looking for answers to this exact issue. Finding that an HTTP error from the ELB is coming through as:

```
Error: Network Error
    at createError (app.3a4d14b….js:106920)
    at XMLHttpRequest.handleError (app.3a4d14b….js:106778)
```
This really throws a wrench in trying to show users messages specific to an ELB timeout (504).

**Comment by rubennorte** [comment]
When Axios returns those errors it's because it's a browser error and the browser doesn't provide the library with more information (Axios can't know what happened). They're usually security errors 
 (such as CORS errors) and you must see the console to check them.
