### ISSUE TITLE
Axios gives a 504 error on a Windows VM

### ISSUE THREAD

**Issue by nareshbhatia** [mzabriskie/axios#1021]
#### Summary

The following node.js app using Axios works correctly on Windows and Mac:

```
var SERVER_URL = 'http://localhost:3000';

var axios = require("axios");

function getBooks() {
    return axios
        .get(SERVER_URL + '/books')
        .then(function(response) {
            return response.data;
        });
}

getBooks()
    .then(function(books) {
        console.log(JSON.stringify(books, null, '    '));
    });
```

However, if I run it on a Windows 7 or Windows 10 VDI (essentially a virtual machine), it fails with the following error message:

> (node:12000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Request failed with status code 504

**If I replace the axios call with node-fetch, the error goes away and the fetch works.** What could be the problem with axios or the way I am using it?

#### Context

- axios version: v0.16.2
- Environment: node v6.11.0, windows 7, Windows 10 running in a VDI

**Comment by ZhangYiJiang** [comment]
That warning means that the Promise is getting rejected - you should attach a rejection handler to catch it and see what the error is 

```
getBooks()
    .then(...)
    .catch(function(error) { 
        // Do something with error, like logging
    }); 
```

**Comment by nareshbhatia** [comment]
@ZhangYiJiang, thanks for helping out. I am now catching and logging the error returned by axios. It says:

> (node:13728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Converting circular structure to JSON.

Unfortunately, there is no circular structure in the returned JSON. I can hit the same URL from the browser and I get simple objects with two properties (id and name):

```
[
  {
    "id": "design-patters",
    "name": "Design Patterns"
  },
  ...
]
```

**Comment by nareshbhatia** [comment]
If I put a breakpoint in the catch clause, and inspect the error object, I am getting a 504 error from a gateway inside the firewall. The response is an HTML page displaying the 504 error. I wonder the app it is trying to reach an outside port instead of localhost where the server is running.

**Comment by nareshbhatia** [comment]
Ok, I think I have determined the root cause of this issue, but don't know the solution.

The Windows VM has HTTP proxy settings by setting the environment variable `HTTP_PROXY` (there is also one called `HTTPS_PROXY`). For some reason, Axios thinks that it needs to go through the proxy to access `http://localhost:3000`. If I remove the environment variable, then the problem goes away.

So the question is, should Axios be going through the proxy to access local ports when `HTTP_PROXY` is set? What is the right way to solve this issue? The `HTTP_PROXY` variable is required for other applications to work correctly.

BTW, node-fetch seems to be ignoring the `HTTP_PROXY` variable and works fine even if it is set. I don't know if that's good or bad!

**Comment by nareshbhatia** [comment]
After a bit of research, I found that I should set `NO_PROXY` to exclude hosts that should not go through the proxy. So I set up `NO_PROXY` as follows:

    set NO_PROXY=localhost,127.0.0.*

Unfortunately that doesn't work. Then I stumbled across https://github.com/mzabriskie/axios/issues/434 which has been open since Sep, 2016. Furthermore there is a PR for it, ready to be merged since Dec, 2016: https://github.com/mzabriskie/axios/pull/565. I am baffled why something as important as this has not been merged in 8 months! My faith in Axios is shaken :-(. Please prove me wrong.

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.

**Comment by rubennorte** [comment]
We'll review that PR so I'm closing this as duplicate.
