### ISSUE TITLE
How to set custom headers with axios instance?

### ISSUE THREAD

**Issue by herryliq** [mzabriskie/axios#1023]
I use axios in a Node project, the follow is my wrapper code:

    class HttpClient {
        constructor(options) {
            this.instance = axios.create(options)
        }
       
        async postWithJsonData(apiPath, params = {}) {
            return await this.instance.post(apiPath, params);
        }
    }

and the follows is how to use it:

    const options = {
        baseURL: dataService.url,
        headers: { "token": dataService.token }
    };

    const httpClient = new HttpClient(options)
    class TicketSourceService {
        constructor() {
    
        }

        async changeTicketPrice(params) {
            return await httpClient.postWithJsonData('/ticket/price/change', params)
        }
    }

When I want set custom headers in method changeTicketPrice, I can not find how to use axios Instance methods with custom config.

I can find the description from official guide, but I do not know how to use it, Is there have some exampe about it?
### Instance methods
The available instance methods are listed below. The specified config will be merged with the instance config.

#### axios#options(url[, config])
**#### axios#post(url[, data[, config]])**
#### axios#patch(url[, data[, config]])

- axios version: *v0.16.0*
- Environment: *node v8.1.0*

**Comment by AlbinoDrought** [comment]
The function for the methods that accept data, `post`, `put`, and `patch`, looks like this:

```js
  Axios.prototype[method] = function(url, data, config) {
    return this.request(utils.merge(config || {}, {
      method: method,
      url: url,
      data: data
    }));
};
```

To attach headers, you could do the following:

```js
axios.post(apiPath, params, {
  headers: {
    'Foo': 'bar',
  },
}); 
```

Alternatively, you could swap the method you are calling, `axios.post`, with `axios.request`:

```js
axios.request('POST', {
  data: params,
  headers: {...},
});
```

**Comment by herryliq** [comment]
@AlbinoDrought Thanks for your suggestion, I had found how to set custom headers with axios instance as follows:

    async createTicketPriceException(params, operatorCode) {
        let requestParams = {
            data: params
        }
        let config = {
            headers: {
                operatorCode: operatorCode
            }
        }
        return await httpClient.postWithJsonData('/ticket/price/exception', params, config)
    }

It was worked well for me.

**Comment by ShaharyarMaroof** [comment]
Hey, I'm having the same issue, I'm trying to send FormData using my axiosInstance, but the headers don't get added to the request. Any Idea what could be wrong?

```
const config = {
      'headers': {
        'Content-Type': 'multipart/form-data'
      },
      'timeout': 60000
    }
const response = await axiosInstance.post(APP_ENDPOINTS.UPLOAD_AVATAR, data, config)
```
`data` is the JS FormData object. in the request it shows up as [Object object].
