### ISSUE TITLE
How to post body JSON array with Axios?

### ISSUE THREAD

**Issue by hackidozone** [mzabriskie/axios#1024]
SO Far i only found how to post for json object, but how if my post body must like this :

`{
    "resource": [
        {
            "login_id": "",
            "name": "",
            "username": "",
            "photo_url": "",
            "email": ""
        }
    ]
}`

anyone can help?

**Comment by cristianrosu** [comment]
@hackidozone it seems to me like you're trying to post object data, not an array. Remove the square brackets and it should work.
`{
  "resource":  { 
    "login_id": "", 
    "name": "", 
    "username": "",
    "photo_url": "", 
    "email": "" }
}`

**Comment by hackidozone** [comment]
nope dude, resource is a key for json array

**Comment by yugasun** [comment]
@hackidozone Did you post your json data using [qs](https://github.com/ljharb/qs) to stringify?

**Comment by hackidozone** [comment]
nope @yugasun , im not using anything to post data except axios its self

**Comment by yugasun** [comment]
@hackidozone can you display you method how to post json object, so I can find your problems.

**Comment by xyclouds** [comment]
I have a question. updata json is {public：{a:1,b:2}，reqdata:{c:3}}, I have used qs to stringify,but in network
I see the format of the uploaded data is public[a]=1;public[b]=2.   I can not  send request

**Comment by yugasun** [comment]
@xyclouds Yes, before you use qs to post nested obj, you should traverse the properties of the obj, and JSON.stringify the properties whose type is object/array, then use qs to stringify. This is my method to post nested obj data.

**Comment by hackidozone** [comment]
its solved guys. thanks btw

**Comment by RJustice** [comment]
@hackidozone What is the solution and can you share it?

**Comment by TitanKing** [comment]
It would be nice if you could post your solution. Everyone helps you out, the least you can do is give back a little.

**Comment by yugasun** [comment]
@TitanKing You can refer to my vue-axios-plugin code:
https://github.com/yugasun/vue-axios-plugin/blob/master/index.js#L77

**Comment by TitanKing** [comment]
Thanks that is very kind of you :)

**Comment by yugasun** [comment]
@TitanKing You're welcome~
BTW, if you use axios with projects created by vue-cli, you can try to use my [vue-axios-plugin](https://github.com/yugasun/vue-axios-plugin), it's helpful~

**Comment by TitanKing** [comment]
Well thank you very much.

**Comment by omarqe** [comment]
@hackidozone really hope that you can share your solution.

**Comment by adrianoresende** [comment]
@hackidozone

**Comment by seedlinktech-william** [comment]
I have a workaround way, see: 
https://github.com/axios/axios/issues/1641#issuecomment-442723844
