### ISSUE TITLE
How do I get all response headers?

### ISSUE THREAD

**Issue by Kunoky** [mzabriskie/axios#1025]
![kt3d9e_v6ozhf4 3n t3](https://user-images.githubusercontent.com/26639880/28833117-0559e1b2-7711-11e7-9f64-2f95ffd34805.png)
![rmc7fo23hgl983 cvy2t ro](https://user-images.githubusercontent.com/26639880/28833251-5ea036f4-7711-11e7-8ee2-2e0deb5c1aa6.png)

**Comment by Kunoky** [comment]
It turns out that I need to set the Access-Control-Expose-Headers  header on the server:
Access-Control-Expose-Headers: Access-Token, Uid

**Comment by sahir** [comment]
what solution you found?
