### ISSUE TITLE
Error response is undefined on 401 HTTP Code

### ISSUE THREAD

**Issue by abraztsov** [mzabriskie/axios#1026]
Server return 401 error after request. I trying to handle it like this but error response is undefined (and only on 401 error!!).

```
axios.interceptors.response.use(null, (error) => {
      // error.repsonse - undefined
      if (error.response.status === 401) {
         // do smth
      }
      return Promise.reject(error);
    });
```

In Chrome Console I see this

<img width="604" alt="i47 pimgpsh_fullsize_distr" src="https://user-images.githubusercontent.com/19175580/28834281-7c3a9c3a-76ea-11e7-8738-eff991f871ba.png">

**Comment by abraztsov** [comment]
Finally. This is problem with the CORS headers in response.

**Comment by Mohanrau** [comment]
@abraztsov can u help me on the CORS what r the changes u did't.can u share if can

**Comment by abraztsov** [comment]
@Mohanrau changes done on backend side. Don't know exactly what it was.
