### ISSUE TITLE
Handle response and callback function

### ISSUE THREAD

**Issue by Luckyfella73** [mzabriskie/axios#1027]
Hi,

I implemented Axios successfully so far but I don't get it to work to fire a callback function after the response is send back.

What I want to achieve:
I call my helper function doing a request and when the result is send back I want to call my callback function sending the result as a parameter.

What I have:
My Helper function:

```
export function fetchData(ajaxUrl, postParams) {
  const params = new URLSearchParams()
  _.forEach(postParams, (value, key) => {
    params.append(key, value)
  })

  axios.post(ajaxUrl, params)
  .then((response) => {
    console.log('axios log: ', response)
    return response
  })
  .catch(error => Promise.reject(error))
}
```

I call the helper function like this:
```
// call the helper function in my app.js:
fetchData(ajaxUrl, postParams).then(
        (response) => {
          this.initOffices(response)
        })
```
The `console.log('axios log: ', response)` logs a correct result comming from my database.
But in the calling code block (app.js) `response` is undefined.

I'm new to javascript so I don't have a understanding of promises in general. If somebody can tell me what I'm doing wrong or how to write the code I would appreciate it!

#### Context

- axios version:0.16.2
- Environment: *e.g.: node v7.7.0, mac El Captain 10.11.6

**Comment by Luckyfella73** [comment]
I got help from a friend - it turned out that I placed the return at the wrong place..
This way it works:
```
export function fetchData(ajaxUrl, postParams) {
  const params = new URLSearchParams()
  _.forEach(postParams, (value, key) => {
    params.append(key, value)
  })

  return axios.post(ajaxUrl, params) // return here
      .then(response => response.data)
      .catch(error => error)
}
```

and the calling block:
```
fetchData(ajaxUrl, postParams)
	.then((response) => {
		this.myCallbackFunction(response)
	})
	.catch(error => error)
```

Or maybe return the response completely and just pass response.data to the callback function..

**Comment by antoniodiazduran** [comment]
Same results but a little different, first created a function for refresh the list with axios

`
 // refresh the list on the template using php file 
 function allRecords(tablx,callback) {
   axios.post('/module/ajax_sites.php', {
    request: 1,
    files: tablx,
 }).then(function (response) { 
    products = response.data; 
    callback();
 }).catch(function (error) {
    console.log(error);
 });
}`

then on the template where I was trying to delete a record and then update the list

` allRecords('sites',function() { 
          console.log('loading..');
          router.push('/'); 
   });
`
Here you can see the call back function, the method to delete and then refresh the list is below.

`deleteProduct: function () {
      //this will delete data in the php file
      axios.post('/module/ajax_sites.php', {
        request: 4,
        files: 'sites',
        id: this.$route.params.product_id
      })
      .then(function (response) {
        console.log('deleted..');
        **allRecords('sites',function() { 
          console.log('loading..');
          router.push('/'); 
        });**
      })
      .catch(function (error) {
        console.log(error);
      });
    }
`
The previous method uses the axios premise to delete the record, and also refresh the list using allRecords function, also using another promise and a callback function to wait for the data to come back, and then route.push to display the list again on the screen.

**Comment by antoniodiazduran** [comment]
Same results but a little different, first created a function to refresh the list with axios, notice the callback();

```
// refresh the list on the template using php file function
allRecords(tablx,callback) { 
  axios.post('/module/ajax_sites.php', {
  request: 1, 
  files: tablx, 
})
.then(function (response) { 
  products = response.data; 
  callback(); 
})
.catch(function (error) { 
  console.log(error); 
}); 
}
```

Here is the method for the template. It's going to the database twice, first to delete, then to refresh. The callback in allRecords() waits for the data to come back before routing back to the list using route.push().

```
method:
  deleteProduct: function () { 
      //this will delete data in the php file 
      axios.post('/module/ajax_sites.php', { 
        request: 4, 
        files: 'sites', 
        id: this.$route.params.product_id 
      }) 
      .then(function (response) { 
        console.log('deleted..');
        allRecords('sites',function() { 
            console.log('loading..'); 
            router.push('/'); });
      })
      .catch(function (error) { 
         console.log(error); 
      });
   }
```
