### ISSUE TITLE
Always failed when POST data with json (body: raw)

### ISSUE THREAD

**Issue by pisangGoreng** [mzabriskie/axios#1033]
Hi, im have trouble when send data to my server. 
im working with react native & axios ver ^0.16.2

    let input = {
      'longitude': -6.3922782,
      'latitude': 106.8268856,
      'content': 'uget - uget sampai kaki lemes',
      'pictures': []
    }

      axios({
        method: 'POST',
        url,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': this.state.headers.authorization
        },
        data: input
      })                                                                     
      .then((resultAxios) => {
        console.log('hasil axios', resultAxios)
      })

and the status result always error 500.

If im try send data with postman, everything is fine  
in postman, i set

headers: {
     Authorization: ''',
     Content-Type: application/json
}

body = raw, JSON

How can solve this problem? Thanks :)

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.

**Comment by themre** [comment]
I also came across this issue. when I'm doing POST and server returns code 500, I get no response, although I see response on my network tab. Here is fiddle demo: https://jsfiddle.net/8r3dh6hw/61/

**Comment by gmkhussain** [comment]
Try this.. it will work for POST data via axios

	   const params = {
                  'longitude': -6.3922782,
                  'latitude': 106.8268856
        };

		axios.post('http://localhost/react/submit.php', params, {
			 headers: {
				  'content-type': 'application/json',
			 },
		})

**Comment by ciprianvf9** [comment]
> headers: { 'content-type': 'application/json', }

You're my hero!

**Comment by gauravsbagul** [comment]
thank you! it worked @gmkhussain

**Comment by Macilias** [comment]
JS word is cruel, reposnseType is declared directly while content-type must sit in the header.  
Thanks Man!

**Comment by Troy1b4** [comment]
I am also having this issue.  I have an object that works perfectly fine when posting via Postman, which is fully Pascal cased, but will not post via Axios unless I hyphenate the properties.  However, my .net core app does not get the data due to the properties not matching any longer.  I even created hyphenated json attributes on my object and that did not work.  I have used JSON.stringify on the object too, but no luck.  No matter what I do, I cannot successfully perform a post and receive all my data.

const handleAddSubmit = e => {
    e.preventDefault();

    let current_datetime = new Date();
    let formatted_date =
      current_datetime.getFullYear() +
      "-" +
      (current_datetime.getMonth() + 1) +
      "-" +
      current_datetime.getDate() +
      " " +
      current_datetime.getHours() +
      ":" +
      current_datetime.getMinutes() +
      ":" +
      current_datetime.getSeconds();

    let threshold = JSON.stringify({
      ThresholdId: "",
      Company: company.toString(),
      ThresholdType: thresholdType.toString(),
      ThresholdValue: thresholdValue.toString(),
      AccountNumber: account.toString(),
      LocationNumber: location == "undefined" ? "" : location.toString(),
      ExpectedAmount: expectedAmount.toString(),
      CreatedDate: formatted_date.toString(),
      CreatedBy: "System",
      UpdatedDate: "1900-00-00 00:00:00.000",
      UpdatedBy: ""
    });

    Axios({
      method: "post",
      url: "https://localhost:44394/Threshold/AddThreshold/",
      data: threshold,
      headers: { "Content-Type": "application/json" }
    })
      .then(function(response) {
        //handle success
        console.log(threshold);
        props.handleAddClose();
      })
      .catch(function(response) {
        //handle error
        console.log(threshold);
      });
  };

My .net core method looks like this:
[HttpPost]
        [Route("AddThreshold", Name = "AddThreshold")]
        public ActionResult<ThresholdDTO> AddThreshold([FromBody] ThresholdDTO threshold)
        {
            var thr = _thresholdService.AddThreshold(threshold);

            if (thr == null)
                return NoContent();

            return Ok(threshold);
        }

**Comment by Troy1b4** [comment]
I forgot to also mention that the data shows in my Chrome dev tools as all provided.  I will note also that the properties of the json are not within quotes.  Could that be the reason, I am not sure?

**Comment by giansalex** [comment]
@Troy1b4 if json payload appear in devtools, then error is on server.
