### ISSUE TITLE
Can't identify request type

### ISSUE THREAD

**Issue by JuanWilde** [mzabriskie/axios#1034]
I'm using axios to make calls to a Laravel App but when I try to know if `$request->ajax()` or `$request->isXmlHttpRequest()` it always fails. This only happens with Axios, but $.ajax().

**Comment by rubennorte** [comment]
Can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.
