### ISSUE TITLE
I use Put method to update some data,but not work

### ISSUE THREAD

**Issue by huangche007** [mzabriskie/axios#1035]
In my project,i found i can not make  update some data work,
some codes as follows:
`export function edtiNewsById(id,title,content,tags,article_type,image,caregory) {
    return axios.put(`/api1.0/articles/${id}/`,{
        title:title,
        body:content,
        tags:tags,
        article_type:article_type,//0表示新闻
        image:image,
        category:caregory
    },{
        maxContentLength: 90000000000000000,
    })
}`
` edtiNewsById(this.$route.params.newsId,this.title,this.editorContent,this.checkedRoles,0,this.imgUrls,this.checkedCategory.id).then((res)=>{
                    this.showWMsg("修改成功!",true);
                    setTimeout(()=>{
                        _this.$router.push({path: '/news/index', replace: true});
                    },1000)
                },(err)=>{
                    this.fetchData(this.$route.params.newsId);
                    this.showWMsg("修改失败，请重试!",false);
                });`

when content is large , it can not work？ please help me solve this problem

**Comment by huangche007** [comment]
I solved my problem

**Comment by jeimz143** [comment]
@huangche007  can you post your solution sir? i am having the same error :) thanks
