### ISSUE TITLE
Pass a callback to default.common.headers

### ISSUE THREAD

**Issue by peterorosz** [mzabriskie/axios#1036]
Hi, currently I do this:

```
function headers() {
  return {
    headers: {
      Authorization: `Bearer ${getJwtFromLocalStorage()}`,
    },
  };
}

// ...
// ...

axios.get(`endpoint`, { ...headers() });
```
This ensures that the `headers` part of the configuration object is 'immediately-invoked' if you get what I mean.

If I just do `` axios.defaults.headers.common.Authorization = `Bearer ${getJwtFromLocalStorage()}` ``, I set the header before actually sending a request (at which time the token is not yet present in the local storage).

Perhaps I am missing something and there is an even better way to deal with this.

But would it be possible to send a callback somehow to the common header?

```
// at the moment of actually doing the request, the callback would be fired
// token() would return "Bearer xxxxxxxxxxxxx"
axios.defaults.headers.common.Authorization = token;
```

Thank you very much for your answers

**Comment by motia** [comment]
You have to use an interceptor for this:

     axios.interceptors.request.use(function(config){
       const token = getToken()
       if (token) {
       config.headers.common['Authorization'] = 'Bearer ' + token
      }
      return config
    });

**Comment by peterorosz** [comment]
Thank you, works like a charm.

**Comment by Vincent2015** [comment]
@motia 
axios.interceptors.request.use(function(config){
   const token = getToken()
   if (token) {
   config.headers.common['Authorization'] = 'Bearer ' + token
  }
  return config
});

if the "getToken()" function is async request, how to do herer,thanks.

**Comment by motia** [comment]
@Vincent2015 , it all depends on your project setup, in case it supports async await:

       axios.interceptors.request.use(async function(config){
       try {
         const token = await getToken()
             config.headers.common['Authorization'] = 'Bearer ' + token
      catch (e) {
        // handle any error or re-throw it if you want
       }
         return config
       });

Otherwise return a promise here:

       axios.interceptors.request.use(function(config){
       return getToken().then(() => {
                   config.headers.common['Authorization'] = 'Bearer ' + token
                   return Promise.resolve(config)
               }).catch(e => {
                     // handle error
                    // or reject it with Promise.reject(e)
            })
        });
