### ISSUE TITLE
Error: Network Error in edge but perfect in chrome and the project after built is working in edge

### ISSUE THREAD

**Issue by fionsay** [mzabriskie/axios#1037]
Hi, 
I'm wondering why get the error  in edge when using developing mode but perfect in chrome, 
and  the project after built (npm run build) is working in edge (so weird ). 

```
Here is the code: 

axios.get(api_url, {....})
.then(()=>{
     // code...
}).catch((error)=>{
     // error.response war undefined
     console.log(error, error.response)
})

Here is the error:
Error: Network Error
at createError 
at handleError 
```
- axios version: ^0.16.2
- vue: ^2.3.3
- vue-router: ^2.3.1
- vuex: ^2.3.1

**Comment by YUFENGWANG** [comment]
let me see see

**Comment by fionsay** [comment]
@YUFENGWANG 

```
stack "Error: Network Error
at createError  (eval code:16:3)
at handleError (eval code:87:7)"
```

I got the error  when I ran the vue project by developing mode. 
I thought  maybe the edge don't allow localhost loopback for websockets, but it don't work even if enabling loopback.:(

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.

**Comment by rianran1993** [comment]
mark, i meet the same problem

**Comment by darthmooguy** [comment]
I've got the same problem too!

**Comment by Jiangyue-way** [comment]
I've got the same problem too! How do you solve it finally?

**Comment by xeleoss** [comment]
Такая же проблева, в разработке, а в проде норм.

**Comment by nadilas** [comment]
Same here

**Comment by Cnordbo** [comment]
Im getting the same problem on Edge when i am behind a proxy. 

Response snapshot: 

![image](https://user-images.githubusercontent.com/385693/71070149-7754e300-217a-11ea-937c-efdb75dbdb97.png)

2 headers included (`Authorization` and `accept`)

Chrome works fine. 

Turning off the proxy and vpn connection makes the error disappear for me.

**Comment by marco9446** [comment]
I have the same error described before. I'm not using any vpn or proxy. Do someone has any tips or idea on what should i do to fix this problem with Edge ?
