### ISSUE TITLE
when i use this send a nodejs post request, server client (php) doesn't receive any data, code like this

### ISSUE THREAD

**Issue by zwsf** [mzabriskie/axios#104]
```javascript
nodejs code (post.js):

var axios = require('axios');

axios.post(
    'http://localhost:9002/post.php',
    {
        lastName: 'Lu',
        firstName: 'Rain'
    }
)
.then(function (res) {
    console.log(res.data);
})
.catch(function (err) {
    console.log(err);
});
```
```
php client code(post.php):

$ret = array(
    'status' => 0,
    'data' => $_POST
);

echo json_encode($ret);

```

use command node post.js get receive:
```
{ status: 0, data: [] }
```

**Comment by zwsf** [comment]
sorry, I doesnot set transformRequest to handle the request data... please ignore this question.

**Comment by marcoscssno** [comment]
How did you solve it?

**Comment by zwsf** [comment]
@marcoscssno use transformRequest function to handler the request data and return a string or an ArrayBuffer, then server-side can receive the data.

**Comment by AlbertoTorre** [comment]
Hello, my problem with the following:
![img](https://cloud.githubusercontent.com/assets/13709013/19076553/e0625532-8a0e-11e6-89df-38b92675f1ab.png)

And the code is executed:
`	componentWillMount(){

		const peticion = this;
		const config = { 
							headers: {'X-Requested-With': 'XMLHttpRequest'},
							transformRequest: [function (data) { return data; }],
							transformResponse: [function (data) { return data; }],
						};

		Axios.get('process/list.php', config)
		.then(function(r) {

			console.log(r);
			
			peticion.setState({
				datos:[r.data] | []
			});
		})
		.catch(function (error) {
			console.log(error);
		});
	}`

First of all, Thanks.
