### ISSUE TITLE
Use axios response outside code block

### ISSUE THREAD

**Issue by adl1995** [mzabriskie/axios#1043]
#### Summary

The code below sends a GET request and receives the response in JSON format. However, I haven't been able to use this outside the code block. I have tried looking up for a solution elsewhere, but no luck. To my understanding, axios returns a Promise object since it's asynchronous, so I can't just `return` the response as I did below:

```
	var threads = axios.get('https://a.4cdn.org/a/threads.json', {
		}).then(function (response) {
			return response.data;
```

When I do `console.log(threads)`, I get an empty `{}` response. I also tried wrapping the `get` part in a separate function as explained [here](https://hashnode.com/post/how-can-i-use-the-data-of-axioss-response-outside-cj2yddlhx003kcfk8h8czfo7k), but that does not work.

Is there any other way I can use this data after the request has finished executing?

**Comment by rubennorte** [comment]
As it's asyncronous code you need to put the code that uses the response inside a `then` block. You can't the result to `threads` as if it were sync code.

Closing as this has nothing to do with Axios anyway.
