### ISSUE TITLE
how to set token before each requeset.

### ISSUE THREAD

**Issue by Vincent2015** [mzabriskie/axios#1048]
axios.interceptors.request.use(function(config){
const token = getToken()
if (token) {
config.headers.common['Authorization'] = 'Bearer ' + token
}
return config
});

**if the "getToken()" function is async request, how to do herer,thanks.**

**Comment by Vincent2015** [comment]
@mzabriskie

**Comment by rubennorte** [comment]
Please take a look at https://github.com/mzabriskie/axios/issues/934#issuecomment-322003342
