### ISSUE TITLE
https rquest with cdn return no statusText in header

### ISSUE THREAD

**Issue by SnowFlowers** [mzabriskie/axios#1050]
i used interceptors to verify the response with the response.statusText. It was ok for the http request.but i got empty string when i use https.
![image](https://user-images.githubusercontent.com/16875486/29483050-d1c5be3e-84d0-11e7-837f-cdf09030a0dc.png)

**Comment by lucysyt** [comment]
you can set a "console.log(response)" and see has a error


------------------ 原始邮件 ------------------
发件人: "SnowFlowers";<notifications@github.com>;
发送时间: 2017年8月19日(星期六) 中午11:23
收件人: "mzabriskie/axios"<axios@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [mzabriskie/axios] https rquest with cdn return no statusText inheader (#1050)




i used interceptors to verify the response with the response.statusText. It was ok for the http request.but i got empty string when i use https.

**Comment by SnowFlowers** [comment]
@lucysyt 我知道问题在哪儿，只是确定一下这是不是个bug。

**Comment by rubennorte** [comment]
That should be an issue in that CDN or the browser. Axios just returns the statusText in the XHR response.
