### ISSUE TITLE
Axios does not work on older mobile browsers

### ISSUE THREAD

**Issue by hazratgs** [mzabriskie/axios#1052]
Hi friends, I have a problem, I'm using axios to send a request with some headers, and everything seems to work fine, but in older browsers, in the default browser in Android (Meizu M20, Samsung Galaxy A5 and others), an error occurs , What can be wrong? Maybe these browsers do not support something? Promises I added with the help of a babel-polyfil

![photo_2017-08-20_16-53-37](https://user-images.githubusercontent.com/4028580/29497542-506f0fca-85f2-11e7-9a4e-013ad50cc2c3.jpg)

**Comment by rubennorte** [comment]
With the information you provided is hard to say what's wrong. We'd have to see the logs of the browser and the exact response axios is returning to see what's happening. Please add that and we'll reopen the issue.

**Comment by ketabi** [comment]
Yes Promise wasn't introduced for Android until 4.4.4 .
look at this answer:
https://stackoverflow.com/a/48203092/6200607
