### ISSUE TITLE
Chaining .then() breaks unchained .then()s

### ISSUE THREAD

**Issue by foundryspatial-duncan** [mzabriskie/axios#1057]
## Summary

If you mix chained and unchained `.then()` callbacks, the unchained `.then`s don't get the response parameter.

For example: 
```javascript
const ajaxPromise = axios({
    method: "get",
    url: "https://httpbin.org/get?foo=baz"
}).then(response => {
 // response parameter is set as expected
});

ajaxPromise.then(response => {
 // this gets called when the promise fulfills too,
 // but the response parameter is undefined
});

// however: 

const otherPromise = axios({
    method: "get",
    url: "https://httpbin.org/get?foo=baz"
});

otherPromise.then(response => {
 // response parameter is set as expected
});

otherPromise.then(response => {
 // this gets called when the promise fulfills too,
 // response parameter is set as expected
});

```
Some demos on Codepen.io:
[One chained, and 3 unchained callbacks](https://codepen.io/foundryspatial-duncan/pen/ayKbBV) - Only the chained callback gets the response parameter

[Two chained, and 3 unchained callbacks](https://codepen.io/foundryspatial-duncan/pen/vJrYrM) - Only the chained callbacks get called? And only one gets the response parameter

[No chained callbacks, and 3 unchained callbacks](https://codepen.io/foundryspatial-duncan/pen/ayKbjK) - All 3 callbacks are called with the correct response parameter.

## Context

- axios version: v0.16.2 (also tested with v0.16.1)
- Environment: Chrome 60, OSX El Capitan

**Comment by rubennorte** [comment]
That isn't an issue in Axios but it's how promise chaining works.

In this case:

```javascript
const ajaxPromise = axios({
    method: "get",
    url: "https://httpbin.org/get?foo=baz"
}).then(response => {
 // This return value will be used to resolve `ajaxPromise`
});

ajaxPromise.then(response => {
 // this gets called when the promise fulfills too,
 // but the response parameter is undefined
});
```

`ajaxPromise` will resolve with what the callback in the first `.then()` returns.

**Comment by foundryspatial-duncan** [comment]
Woah! I didn't know that. Thanks for the quick response!
