### ISSUE TITLE
axios hits "then" even on error when refreshing expired token

### ISSUE THREAD

**Issue by robmpreston** [mzabriskie/axios#1063]
I am using axios in my Laravel/Vue app for all requests. I am using JWT for authentication and want to refresh the token when it is expired and then retry the request.

What is currently happening is:
1) Attempt to get the user object of current logged in user
2) 401 error is returned
3) axios enters the "then" block for the get user call and gives an error because the data isn't there
4) axios hits my interceptor and refreshes the token
5) axios retries the user call, its successful, but it never hits the "then" block of code so the user object isn't saved and the callback isn't called

So basically #3 shouldn't happen since a 401 error is being returned, it should happen after #5 when the call is successful

Here's the relevant code:

call:
```
AuthService.user()
```

interceptor:
```
axios.interceptors.response.use(undefined, error => {
 let errorResponse = error.response
 if (errorResponse.status === 401 && errorResponse.config && !errorResponse.config.__isRetryRequest) {
    return AuthService.refresh(response => {
      console.log('token refreshed')
      errorResponse.config.__isRetryRequest = true
      errorResponse.config.headers.Authorization = AuthService.authorizationHeader()
      return axios(errorResponse.config)
    }, errorCallback => {
      window.location = '/login'
    })
  }
})
```
service call:
```
user (callback, errorCallback) {
    axios.get('/api/user')
      .then(response => {
        let result = response.data
        if (result.success) {
          console.log('saving user')
          this.saveUser(result.data.user)
          if (callback) {
            callback(result)
          }
        }
      })
      .catch(error => {
        console.log(error)
        if (errorCallback) {
          errorCallback(error)
        }
      })
  },
```
Please advise, I'm sure I'm doing something stupid :)

**Comment by robmpreston** [comment]
Sorry, I see that I had to return a Promise from the interceptor instead and now it works :)

**Comment by Jenan** [comment]
How do you fix it? :)

**Comment by KrishnaPG** [comment]
Came across this while facing similar problem, and here is what works:
````
this.axiosInstance.interceptors.response.use(null, error => { 
	if (error.response && (error.response.status === 401 || error.response.status == 403))
		return this.login().then(() => this.axiosInstance.request(error.config)); // make the request again after updating the login token
	return Promise.reject(error); // <- important piece
});
````
I noted that you have to **return** the promise.reject() in the interceptor for the catch handler to work at the calling site.
