### ISSUE TITLE
params empty(null) on backend (axios post)

### ISSUE THREAD

**Issue by cahyowhy** [mzabriskie/axios#1067]
i'am trying to post json, this is my script
```
return axios({
      method: this.method,
      url: api,
      headers:{
        'Content-Type':'applictaion/json'
      },
      data: JSON.stringify(body),
    }).catch(function(err){
      console.log(err);
    });
```

but unfortunately on my rails app, it doesnt receive any params
![image](https://user-images.githubusercontent.com/18083469/29992837-c9eb94b8-8fcf-11e7-85d9-ca4e37fdcbcd.png)
(those red line are empty value)

but its work when i post with postman
![image](https://user-images.githubusercontent.com/18083469/29992849-ed573cc2-8fcf-11e7-975a-a4dd9184e6b0.png)

and this is my browser network console
![image](https://user-images.githubusercontent.com/18083469/29992863-361872a0-8fd0-11e7-81ff-32d86cb6e722.png)

can anyone solve this..
sory for bad english

**Comment by rubennorte** [comment]
There's a typo in the content type
