### ISSUE TITLE
avoid requiring package.json into library

### ISSUE THREAD

**Issue by FredericHeem** [mzabriskie/axios#1068]
Would it be possible to avoid including the whole `package.json` into the library? It is used in `lib/adapters/http.js` to get the version.
Every little bytes helps to get leaner.

**Comment by rubennorte** [comment]
The HTTP adapter is only loaded in Node.js, where the package.json is always optional, so that wouldn't have any real benefit.

**Comment by indolent-developer** [comment]
this causes my build to fail. babel doesnt copy package.json file in final version. may be we can avoid this call ?
