### ISSUE TITLE
Cookies not send automatically with post request!

### ISSUE THREAD

**Issue by varmeh** [mzabriskie/axios#1076]
**Summary:**
Cookies received in previous _get_ call not send with following _post_ command.

**Details:**
I am using the following sequence of calls to login into the backend.

```
axios.get(Url.csrfToken(), { withCredentials: true })
            .then(response => response.data)
            .then(token => axios.post(Url.authenticate(), { username, password }, {
                    headers: {
                        'content-type' : 'application/x-www-form-urlencoded',
                        'crsf-token' : `${token.csrfToken}`
                    },
                    withCredentials: true
                })
            )
            .then(response => console.log('completed'))
            .catch(error => console.log(error))
```
Cookies returned in `set-cookie` in response headers for _get()_ is required by _post()_.

**But post() does not have any cookie in its header**, leading to failure.

How could I fix it, please help?

**Environment**

- react: 16.0.0-alpha.12
- react-native: 0.47.2
- iOS Simulator - version 10.0

**Comment by MidnightP** [comment]
@varmeh How did you fix this?

**Comment by chrisgillis** [comment]
Also curious

**Comment by MidnightP** [comment]
is this helpful?

https://stackoverflow.com/questions/46288437/set-cookie-header-has-no-effect
