### ISSUE TITLE
.catch() is silently taking errors from .then()

### ISSUE THREAD

**Issue by sofuxro** [mzabriskie/axios#1103]
#### Summary

I have this code:

    axios.delete(base + '/addresses/' + params)
        .then(data => { // Success
            Vue.delete(/* somthing */);

        }).catch(error => { // Failed
            notifyError('The Address couldn\'t be deleted!');
        });

Usualy it will go to .then() (Success)  for any  **2xx server response** and the rest will go .catch() (Fail)

But in the case you have errors in your code inside the .then(), for example forget to import Vue, they (the errors) won't be shown in console, instead the .catch() will be triggered simulating a server error response ( jumping to blame the backend developer :P )

Which makes things harder to debug.

#### Possible solution

Wrapping the promise and providing custom callback functions (for example **onSucces** and **onFail**)

#### Context
- axios version: : v0.16.2*
- Environment: : node v8.5.0 chrome 60, windows 10

**Comment by nickuraltsev** [comment]
@sofuxro It can easily be avoided by passing both callbacks to `then` instead of using `catch`:

```js
axios.delete(base + '/addresses/' + params)
    .then(data => { // Success
        Vue.delete(/* something */);
    }, error => { // Failed
        notifyError('The Address couldn\'t be deleted!');
    });
```

See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) for details.

Hope this helps!

**Comment by sofuxro** [comment]
Why isn't this a practice then ?

The axios docs suggest using `.catch()` instead of the second callback to `.then()`

**Comment by moos** [comment]
@sofuxro This is common practice -- exceptions in then() are caught by further catch()'s.  You can either follow @nickuraltsev's suggestion, or simply check the error type in catch.

**Comment by Buzu** [comment]
If this is common practice, please say so in the docs. The docs have nothing that I found that suggest this behaviour, or that the preferred way to handle ajax-exclusive errors is to use the second param on `then`. This is definitely something that can easily surprise new comers. The "fix" is as easy as stating this behaviour in the docs.
