### ISSUE TITLE
v0.6.0: default timeout is not applied to http adaptor, fails on Node v4 and io.js

### ISSUE THREAD

**Issue by lovell** [mzabriskie/axios#111]
Hi Matt, thanks for maintaining this very useful module.

I've discovered commit ffc0237 introduces a new timeout setting.

A value of `0` is set in `defaults.js` but this doesn't seem to make its way into the `config` object.

The following error occurs when no timeout option is passed to axios' constructor and the `http` adaptor is used with Node v4 (and io.js):
```
TypeError: Uncaught error: msecs must be a number
at Object.exports.enroll (timers.js:138:11)
at Socket.setTimeout (net.js:306:12)
at ClientRequest.<anonymous> (_http_client.js:558:10)
...
```

io.js v1.3.0+ and therefore Node v4+ has more strict socket timeout parameter checking since https://github.com/nodejs/node/commit/0cff0521c333df8649bc6a2b1f40adbf899b1261

My best guess of how to fix this would be to pass timeout along approximately [here](https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L9) - I'm happy to submit a PR if you agree. (I'll update the Travis CI to run the tests on Node v4 also.)

**Comment by lovell** [comment]
Great, thanks both.

**Comment by resistdesign** [comment]
@mzabriskie I'm still getting `msecs must be a number` with v 0.7.0 on node 0.12.x if I set it to `undefined`. Can I not set it to `undefined`, explicitly?
