### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by ivitivan** [mzabriskie/axios#118]
Hi!

I'm trying to use your library but I get an error:
```
Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
```
I was using your example
```js
axios.get('https://api.github.com/users/benjamingeorge')
  .then(function (res) {
    console.log(res.data);
  })
  .catch(function(res) {
    if(res instanceof Error) {
      console.log(res.message);
    } else {
      console.log(res.data);
    }
  });
```
The error happens [here] (https://github.com/mzabriskie/axios/blob/eca2ac88ebd28db1ebff3757574974a6fcdd0bf6/lib/helpers/urlIsSameOrigin.js#L56).
I'm using browserify and chrome 45.

**Comment by ivitivan** [comment]
I messed up in the code. Everything works fine now.

**Comment by mzabriskie** [comment]
Would you mind sharing what you did wrong for future reference?

**Comment by ivitivan** [comment]
Actually, I can not even reproduce the error now.

**Comment by aljones** [comment]
I got this error from: `axios.post('/api' [this.props.query])`  If you don't see it, the comma is missing between the arguments. I tested this in node too.
```
> var f = function(s, a) { return { s, a }};                                      
> f('s', ['a'])                                 
{ s: 's', a: [ 'a' ] }                          
> f('s' ['a'])                                  
{ s: undefined, a: undefined }
```

So I guess the error is related to an argument being undefined.  I'm surprised that isn't a syntax error.

**Comment by zhangjinling** [comment]
I also meet this question.But I can send get and post request.
I use it in VUE,when I use `Vue.use(axios);`,not do otherthing .The errir occured.
`isURLSameOrigin.js?94c0:57 Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined`
chrome : 55.0.2883.87 m

**Comment by vpiskunov** [comment]
Any solution? I am also using it with `Vue.use(axios)`
`isURLSameOrigin.js?142d:61 Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined`
Perhaps could be about the way we import it into VueJS? There doesn't seem to be any docs on how to properly import it to Vue, especially when using Webpack...

Any ideas greatly appreciated!

**Comment by rookiebulls** [comment]
@vpiskunov Maybe it's because you are using the origin axios, not a vue plugin, you should use Vue.prototype.$axios = axios if you want vue's instance to call it

**Comment by cuihj** [comment]
https://github.com/imcvampire/vue-axios

**Comment by dannypule** [comment]
I was getting this error due to the url being undefined. Was easy to fix. 

![image](https://cloud.githubusercontent.com/assets/8937911/22823525/faf4c8da-ef7b-11e6-98f4-539c901ef935.png)

**Comment by dannypule** [comment]
I was getting this error due to the url being undefined. Was easy to fix.

![image](https://cloud.githubusercontent.com/assets/8937911/22823674/8f838f22-ef7c-11e6-8878-dcfd9c88b527.png)

**Comment by rohmanhm** [comment]
I got same problems guys, but I'm not using Vue.
It's happend when I process the `response.data` using `window object`, but when I just `console.log(response.data)` this not show any errors.

**Comment by vpiskunov** [comment]
@rohmanhm That's because the Ajax request runs on a separate isolated "thread"-like environment. You might have some luck by calling .bind(this) or .bind(window)

**Comment by rohmanhm** [comment]
@vpiskunov would you give me some example?

**Comment by qinyueshang** [comment]
I am also using it with Vue.use(axios)
isURLSameOrigin.js?142d:61 Uncaught (in promise) TypeError: Cannot read property 'protocol' of undefined
when I remove 'Vue.use(axios)',it is ok

**Comment by EmadAdly** [comment]
If you use vue or another just 
```js
import axios from 'axios'
```
And use Axios normally without using  ` Vue.use(axios)`

Everything works fine

**Comment by PhPPgAdminBug** [comment]
**it is not working no way, even with plugin or prototyping.**

**Comment by neorganic** [comment]
I have this issue, it seems that axios is not being inherited like other libs and when you are trying to import axios in the same file where are you importing something that imports axios inside it you get the very exact strange error - at least in my code. My code:
my  **bootstrap.js** file

````
import Vue from 'vue'
import $ from 'jquery'
import Axios from 'axios'
import Echo from 'laravel-echo'
import VueTimeago from 'vue-timeago'
import Pusher from 'pusher-js'
Vue.use(VueTimeago, {
  locale: 'en-US',
  locales: { 'en-US': require('json-loader!vue-timeago/locales/en-US.json') }
});

window.Vue = Vue;
window.jQuery = window.$ = $;
require('bootstrap-sass/assets/javascripts/bootstrap');
require('quasar-extras/material-icons');
// Configure Laravel Echo
const { key, cluster } = window.etc.pusher;
if (key) {
  window.Echo = new Echo({
    broadcaster: 'pusher',
    key: key,
    cluster:cluster
  });

  Axios.interceptors.request.use(
    config => {
      config.headers['X-Socket-ID'] = window.Echo.socketId();
      return config
    },
    error => Promise.reject(error)
  )
}

window.axios = Axios;
````

my main.js file:
```

import Axios from 'axios'
import './bootstrap'

var Child = {
    template: `<div>
      <q-knob
                        v-model="model"            
                        :min="min"
                        :max="max"
                        url="/api/etc"                                   
                >{{model}} %
                </q-knob>

</div>`,
    data(){
        return{
      model:0
        }
    },
    props:{
        url: '',
        min: 0,
        max: 100,
    },
    methods:{
        getCircle(range) {
            Axios.post(this.url, {range})
                .then((response) =>   this.model = response.data;           
                    }
                )
        },
    },
    mounted(){
        this.getCircle(this.range);
    }
};

import {DateRangeMixin} from './mixins/shared_data'
const app1 = new Vue({
    mixins: [DateRangeMixin],
    el: '#app',
    components: {
        Child
    },
});
```

**Comment by huainanhai** [comment]
If you use:
`import axios from 'axios';`
`axios.defaults.baseURL = process.env.BASE_URL;
export default axios;`

The error occurs

**Comment by Twady77** [comment]
Using Laravel VUE JS, I experienced this same issue. This fixed it for me however - 
`window.axios = require('axios');` in resources/js/bootstrap.js already scaffolds axios. You wouldn't need to do `Vue.use(require('axios')); ` in resources/js/app.js.
In my own case, this was the issue, so I removed it from app.js.

**Comment by bagaskarala** [comment]
i solved my own with deleting Vue.use(axios)

**Comment by zhaoweih** [comment]
> I was getting this error due to the url being undefined. Was fixed after I addressed that issue.

this work for me,thank you

**Comment by Lustellz** [comment]
> I got same problems guys, but I'm not using Vue.
> It's happend when I process the `response.data` using `window object`, but when I just `console.log(response.data)` this not show any errors.

Same here. I'm not using axios, though.

**Comment by krisunni** [comment]
> i solved my own with deleting Vue.use(axios)

This worked for me.

**Comment by xyznaveen** [comment]
> i solved my own with deleting Vue.use(axios)

Same here don't know why tho.

**Comment by MichaelTimbes** [comment]
I think it was mentioned in an earlier comment by @rookiebulls , I am using Axios as a plug-in via  Vue.use(VueAxios, axios) and what worked for me was calling axios from the Vue context by using Vue.$axios .

**Comment by vitvnua** [comment]
> i solved my own with deleting Vue.use(axios)

thanks! This worcked for me!!

**Comment by rabar1995** [comment]
install both of axios and vue-axios

 import axios from 'axios'
import VueAxios from 'vue-axios'

Vue.use(VueAxios, axios)

that's worked for me

**Comment by azamatz** [comment]
my issue for this problem:
1. 
import axios from 'axios';
import VueAxios from 'vue-axios';

2.
Vue.use(VueAxios, axios);  // order important

**Comment by franpesca** [comment]
I solved it by removing the import in my main.js file. 
So, I removed both 
import axios from "axios",
and Vue.use(axios)

**Comment by andrey-lazarev** [comment]
Had the same error with bootstrap form. `$form.on('submit', (event) => event.preventDefault()` solved the issue.

**Comment by mamadfar** [comment]
GuyyyyyyyyyyyyyyyyyyyyyyyyyYYYYYYYYYYYYYYYYYYYYYYYYYYYyyyyyyyyyyyyyyyyyyyyyyyyyyyS

just use this 4 line code and DONE !

import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'

Vue.use(VueAxios, axios)

.
.
.
JUST DO THIS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mossa-Sammer** [comment]
I faced this in React.js and no solution
