### ISSUE TITLE
.catch transformRequest / transformResponse errors

### ISSUE THREAD

**Issue by giogonzo** [mzabriskie/axios#119]
I might be missing something here (saw #61 and #110 related), but..

Looks like there's no way to `.catch` in the Promise control flow any error occurring during the transform phase, e.g. here: https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L12-L17 you'd need to `try {} catch {}` `transformData()` and `reject` accordingly the Promise

Is this deliberate?

I think It's ok to have your own error handlers in `transformResponse` like you say here: https://github.com/mzabriskie/axios/issues/110#issuecomment-142682301 , but what if the user wants to handle errors down the Promise chain? (In my experience this is the expected way of handling errors when dealing with a Promise-based api)

**Comment by mzabriskie** [comment]
The `try/catch` is happening further up the chain. It is being done by `dispatchRequest`, which is what invokes the adapter. https://github.com/mzabriskie/axios/blob/master/lib/core/dispatchRequest.js#L22

**Comment by giogonzo** [comment]
Right, my bad, this doesn't apply to `transformRequest` but only to `transformResponse`: unfortunately there's no `try/catch` inside the `onreadystatechange`, where `transformResponse` happens, which is of course async..

Basically, in this code below, I'd like "reject transform response error" to log
```js
const err = () => {
  throw new Error('transform response error');
};
axios({
  url: 'http://google.com',
  transformResponse: [err]
}).then(
  console.log.bind(console, 'resolve'),
  console.error.bind(console, 'reject')
);
```

while currently that exception is unhandled by construction

Here's an example implementation of the changes I'm talking about: https://github.com/mzabriskie/axios/compare/master...giogonzo:reject-on-transform-response-errors?expand=1

**Comment by giogonzo** [comment]
just realized you can use `axios.interceptors.response.use` and override default `transformResponse` with `[]` to obtain what I was describing above

Thank you anyway!

**Comment by lynnard** [comment]
Can we reopen this issue? I just stumbled upon this as well. Promised based api should handle all errors as reject or at least provide a mechanism for the user to call reject. With the current api I have to do this

```
axios({
  transformResponse: [data => {
    try {
      //... data
    } catch(e) {
    }
    return null;
  }]
}).then(resp => {
  if (resp == null) {
    throw new Error('NULL!');
  }
  return resp;
})
```

Which is not ideal.

**Comment by rubennorte** [comment]
This was solved after a refactor a few versions ago.
