### ISSUE TITLE
Make axios instantiable

### ISSUE THREAD

**Issue by nickuraltsev** [mzabriskie/axios#122]
It would be nice if axios can be instantiated. This can be useful in cases where the application consumes multiple APIs which require different configuration options (e.g., transformRequest, transformResponse, headers, timeout). This would also solve the problem that it's not possible to use different interceptors for different APIs (see issue #108). 

Proposed API:

```
var instance = axios.createNew(instanceConfig);

instance.interceptors.add(function (config), function (error));

instance.request(config);

instance.get(url[, config]);
instance.head(url[, config]);
instance.delete(url[, config]);
instance.post(url[, config]);
instance.put(url[, config]);
instance.patch(url[, config]);
```

**Comment by angelxmoreno** [comment]
came here after doing a quick search. I was going to ask if the module can do this. It would be pretty amazing if we could add this feature.
