### ISSUE TITLE
Invalidate or Cancel previous requests if a new request has been sent

### ISSUE THREAD

**Issue by af7** [mzabriskie/axios#125]
There are times (when typing on a text field for example) that multiple requests are sent to the server.

How can we handle this case, so that only the last one is to be processed on the client? (I assume there should be a way to invalidate or cancel the previous requests so that when the response comes from the server this is ignored). 

Is there something out-of-the-box for this use case in *axios* or I will need to implement it on the client myself?

Thank you.

**Comment by pstoica** [comment]
You should consider RxJS for these kinds of problems (this is a common demo). Aborting requests isn't currently implemented: https://github.com/mzabriskie/axios/issues/50

**Comment by mzabriskie** [comment]
As @pstoica said, this isn't currently supported. There have been several proposals made, and a couple attempts to implement, but Promises by nature make it quite challenging to solve this. I hope to find some solution, but nothing has made it into master yet.

**Comment by jmullo** [comment]
Has someone managed to combine axios & RxJS like this:

http://stackoverflow.com/questions/34612746/wrapping-promise-based-javascript-http-client-with-rxjs-observable

That "common demo" isn't really a solution unless you want to use RxJS mode widely in your application.

**Comment by Braunson** [comment]
Any solutions to this issue since?
