### ISSUE TITLE
Does axios provide IE9 cross domain requests support?

### ISSUE THREAD

**Issue by vineethawal** [mzabriskie/axios#131]
has the  IE9 cross domain issue especially cross domain post requests issue been taken care of?

**Comment by mzabriskie** [comment]
I assume that you're asking about `XDomainRequest`? This is something that still needs to be addressed. Though it shouldn't be terribly complicated.

**Comment by vineethawal** [comment]
Ok, will look into it, see what I can do.

**Comment by vineethawal** [comment]
#140

**Comment by vineethawal** [comment]
Feature added
