### ISSUE TITLE
fetchStart and fetchError missing

### ISSUE THREAD

**Issue by JacquesBonet** [mzabriskie/axios#134]
Hello,

Why there isn't fetchStart and fetchError on the axios reducer?

Regards.

**Comment by mzabriskie** [comment]
I'm not sure what you're asking. Can you provide more details?

**Comment by JacquesBonet** [comment]
Sorry, Matt, I made a mistake, the issue is for redux-crud, not axios.

**Comment by mzabriskie** [comment]
No problem. Are we okay to close the issue?

**Comment by JacquesBonet** [comment]
Sure

2015-10-27 21:56 GMT+01:00 Matt Zabriskie <notifications@github.com>:

> No problem. Are we okay to close the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mzabriskie/axios/issues/134#issuecomment-151641201>.
>



-- 
*Jacques Bonet*

res Margaut, app 44
411 cours de la Liberation,
33400 Talence
France

✆ +33 6 35495090
✉ jacques.bonet@gmail.com
