### ISSUE TITLE
Error in IE11, "'Promise' is undefined"

### ISSUE THREAD

**Issue by musbaig** [mzabriskie/axios#135]
Seeing the following error trying to use `axios` under IE11 (via parallels): `'Promise' is undefined.`

Inspector seems to attribute the error to this line: https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L29

**Comment by mzabriskie** [comment]
You need to polyfill `Promise` yourself. You can see specifics in the upgrade guide https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#es6-promise-polyfill

**Comment by musbaig** [comment]
Wow, suggestion worked perfectly. Thanks for the superfast response!! 
Great work btw on `axios`, loving it.

**Comment by velopert** [comment]
es6-promise-polyfill did not work for me when I was using webpack + babel.
This one solved my issue: https://babeljs.io/docs/usage/polyfill/

**Comment by dogotaru** [comment]
thanks a lot velopert, your suggestion worked

**Comment by jflayhart** [comment]
I'm running webpack and was able to add babel-polyfill as a vendor file to resolve the issue.

**Comment by jmathew** [comment]
Regarding usage with webpack 2: 

I was already using BlueBird in my project and axios is part of the bundle. So I used the ProvidePlugin to give axios wings:

```
module.exports = {
  plugins:[     
        new webpack.ProvidePlugin({
            Promise: "bluebird"
        })
    ],
}
```

**Comment by shlomisas** [comment]
do anyone know if the polyfill will create a global Promise in the page or just in the Webpack's scope?

**Comment by mgashraf** [comment]
importing promise from core-js solved the issue for me as below
import 'core-js/fn/promise';

**Comment by marktolson** [comment]
@mgashraf thanks this is the only solution that worked for me.

**Comment by bigsee** [comment]
@velopert thank you! worked for me... :)

**Comment by mqliutie** [comment]
None of your suggestions solved my problem....


action.js

```
import axios from "axios";
import 'core-js/fn/promise';
export let GetCarouselList = async (type = 1) => {
    let response = await axios(`http://api.dufe.online/getCarouselList?type=${type}`);
    //return response.data;
}
```

webpack.config
```
entry: {
    polyfill: 'babel-polyfill',
    app: './src/app.js'
}
```

Who can help me

**Comment by mqliutie** [comment]
@mgashraf import every file or entry file?
