### ISSUE TITLE
baseUrl config parameter

### ISSUE THREAD

**Issue by nickuraltsev** [mzabriskie/axios#137]
What do you think about adding `baseUrl` config parameter?

```js
var github = axios.create({baseUrl: 'https://api.github.com/'});
github.get('/users/nickuraltsev');
```

I'd be happy to create a PR for this.

**Comment by ruscoder** [comment]
+1

**Comment by iam4x** [comment]
I agree with @nickuraltsev, I've made a little wrapper around axios for my own usage:

https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/shared%2Fapi-client.js

**Comment by JoshZA** [comment]
:+1:

**Comment by mzabriskie** [comment]
@nickuraltsev happy to accept a PR

**Comment by nickuraltsev** [comment]
Great, I'll create a PR soon.

**Comment by diessica** [comment]
Awesome!

**Comment by SkateFreak** [comment]
is that why this doesn't work:
axios('/user')

and this does?
axios('http://localhost:3000/user')

**Comment by nickuraltsev** [comment]
@SkateFreak Do you have this issue when using axios in the browser or node.js? If the former, relative URLs should work fine as far as I know.
