### ISSUE TITLE
Send XSRF tokens with CORS requests when withCredentials is true

### ISSUE THREAD

**Issue by tamasd** [mzabriskie/axios#138]

**Comment by samjulien** [comment]
First-timer here. Can you point me to where this is? I'm guessing perhaps the Axios.prototype.request method?

**Comment by mzabriskie** [comment]
@samjulien take a look at the [xhr adapter](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L91) (that should take you to the very line). Currently we only send the XSRF values if the request is being sent to the sam URL as the origin. To solve this issue we would want to also check if `config.withCredentials` is `true`.

**Comment by kentcdodds** [comment]
:tada: :confetti_ball: awesome to see a `first-timers-only` issue on axios :+1: :clap:

**Comment by samjulien** [comment]
Cool, thanks @mzabriskie - I will give the PR a shot. Stand by...

**Comment by mzabriskie** [comment]
@samjulien I am adding a failing test. Your mission should you choose to accept it, is to make the test go from red to green :)

**Comment by samjulien** [comment]
Perfect, was just going to ask about a test.

**Comment by mzabriskie** [comment]
Wait to fork from master until I commit the test.

**Comment by samjulien** [comment]
:white_check_mark:

**Comment by mzabriskie** [comment]
It's all yours. Let me know if you have any questions.

**Comment by samjulien** [comment]
Thanks, will do!

**Comment by mzabriskie** [comment]
A few pointers as you get ready to submit your PR:

- Make sure the tests are passing with `npm test` (be sure you've run `npm install` first)
- Only commit your code change, no generated files (i.e. `dist/`)

**Comment by samjulien** [comment]
Okay, I just submitted it. Hopefully I did the PR right. But all tests are passing.

**Comment by samjulien** [comment]
And thank you for the opportunity, @mzabriskie! I've been trying to figure out how to get started with OSS contributing.

**Comment by mzabriskie** [comment]
PR looks great and is merged! Exactly how I would have done it. Glad to provide the opportunity.

**Comment by miguelc1221** [comment]
i was just about to submit too = ), thanks for guiding us!

**Comment by mzabriskie** [comment]
@miguelc1221 there will be many more opportunities. Stay tuned :)
