### ISSUE TITLE
Uncaught TypeError: _axios2.default.create is not a function

### ISSUE THREAD

**Issue by jsdmc** [mzabriskie/axios#142]
Hi there)
In documentation I see that it's possible now to create an instance like this 
```javascript```
axios.create([config])
```
When this will be available in version published to npm?

Thanks

**Comment by iam4x** [comment]
@jsdmc You can use `npm i -S mzabriskie/axios#master` until the new version is released

**Comment by jsdmc** [comment]
@iam4x Yeah, I know) Just curios why this merged to master and highlighted in docs but not published.

**Comment by ferdinandsalis** [comment]
Yes, this just tripped me to.

**Comment by mzabriskie** [comment]
Sorry for the confusion. I'll work on getting a new release out soon.

**Comment by ferdinandsalis** [comment]
@mzabriskie thanks. no worries. It also seems that when you use an instance by using `var instance = axios.create()` you can not use it like this `instance({method: 'patch', data: {…}})`.

**Comment by nickuraltsev** [comment]
@ferdinandsalis No, but you can use `instance.request({url: '...', method: 'patch', data: {...}})` instead. There is also `instance.patch`.

**Comment by ferdinandsalis** [comment]
thanks @nickuraltsev. Still I was expecting it to work because it works with the default instance.

**Comment by CezarLuiz0** [comment]
+1
