### ISSUE TITLE
Where are the headers in the response interceptor?

### ISSUE THREAD

**Issue by ir-fuel** [mzabriskie/axios#143]
I just implemented a response interceptor. This is the response from the server (as can be seen in the Chrome Developer Tools)
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Headers: X-Requested-With,Content-Type,authorization
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6Impvc2tlIiwiZW1haWwiOiJqb3Jpc0Bhc3R1cy5iZSIsInBhc3N3b3JkSGFzaCI6IiQyYSQxMCQwN0JYOTdGMmR3YXd6VFdoLnEvUEZPWXJhYUVOMlN5NjlobkZEWUplRnExNTVtTTluUVByVyIsImlhdCI6MTQ0NjYzMDU4MywiZXhwIjoxNDQ2NjQxMzgzfQ.9oVyVAzIAvcgNCrzW_9cMDmqxeAH3qo5cMArP71xDXs
Date: Wed, 04 Nov 2015 09:49:43 GMT
Connection: keep-alive
Content-Length: 14
```

However when inspecting the object I get in my response interceptor
```
axios.interceptors.response.use(function(response) {
 ...
```

I see only this

```
console.log(response.headers)    ----> {}
```
The only relevant info I find in the response object is `status`, `statusText` and `data`

**Comment by ir-fuel** [comment]
The result is the same when logging the response object in this call:
```
  return axios.get(BaseUrl+path).then(function(response) {
    responseInterceptor(response)
    return Promise.resolve(response)
  })

```

**Comment by mzabriskie** [comment]
This is strange. Here is the code that processes the response headers and passes it along to `resolve`/`reject`. Theoretically the only point of failure would be `parseHeaders`.

https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L61-L77

**Comment by ir-fuel** [comment]
I found why. It had to do with CORS. You need to set which reponse headers are allowed to 'survive' a CORS request.

**Comment by mzabriskie** [comment]
Glad that you figured it out. Sorry for the delayed response.
