### ISSUE TITLE
Is it possible to cancel the outgoing request from the request interceptor

### ISSUE THREAD

**Issue by corbanbrook** [mzabriskie/axios#148]
I need to build a plugable caching interceptor

request interceptor will check the route, see if it exists in my localStorage cache/Redis  and then either serve up the cache and cancel the outgoing request or doesn't have cache and continue with the request. Is this possible with the current interceptors design?

**Comment by mzabriskie** [comment]
This is not currently possible. There are plans for implementing cache #31. Ideally this would also support using an external caching mechanism like Redis.

**Comment by buley** [comment]
The `$http` way of doing things is a promise that represents cancellation. Support could be extended to axios without breaking anything by reusing the existing `timeout` parameter but adding support for a simple promise to cancel an outbound request if that promise resolves.
