### ISSUE TITLE
axios.create does not seem to exist

### ISSUE THREAD

**Issue by echlebek** [mzabriskie/axios#153]
The documentation states that instances of axios can be created by axios.create. However, when I try to do this it appears that the definition does not exist. Indeed, in dist/axios.js the function doesn't seem to exist as of version 0.7.

**Comment by mzabriskie** [comment]
This feature will be available in the next version. I'm working on getting something out soon.

**Comment by jetien** [comment]
Hi, so why write it in the doc ?

**Comment by mzabriskie** [comment]
The feature came in with a PR which included the docs. After it merged it ended up in master.
