### ISSUE TITLE
Documented axios.create method missing

### ISSUE THREAD

**Issue by guncha** [mzabriskie/axios#157]
Looking through the source, it seems like it has been removed in favor of using global configuration. Is that the case?

**Comment by guncha** [comment]
Actually, it's in the master, just not on NPM, is all. `npm publish` !! :smile:

**Comment by mzabriskie** [comment]
Working on getting a PR merged, then will release.

**Comment by dnutels** [comment]
Hi.

I must be misunderstanding something - this still is the case as of __0.7.0__, why would you close the issue?
