### ISSUE TITLE
Using in webpage doesn't send XHR but refresh

### ISSUE THREAD

**Issue by DIMPLY** [mzabriskie/axios#159]
```javascript
<script src="scripts/axios/axios.js"></script>
<script>
    var bug=document.forms.bug;
    function submit(){
        axios.post('http://xxx.xxx.xxx/sendMail',{
            title:bug.title.value,
            content:bug.content.value,
            from:bug.from.value
        }).then(function(response){
              console.log(response);
          }).catch(function(response){
              console.log(response);
          });
    }
</script>
```
Why this doesn't work? It doesn't send an XHR but refresh the present page with my data and go to:
```
index.html?from=aaa&title=aaa&content=aaa
```

**Comment by mzabriskie** [comment]
Can you try running the examples locally?

```bash
npm run examples
```

Then open http://127.0.0.1:3000/post in your browser, enter some valid JSON, and click `POST`.

**Comment by DIMPLY** [comment]
the output for `npm run examples`:

> axios@0.7.0 examples /Users/yanyang/axios
> node ./examples/server.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/yanyang/axios/examples/server.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

npm ERR! axios@0.7.0 examples: `node ./examples/server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the axios@0.7.0 examples script.
npm ERR! This is most likely a problem with the axios package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./examples/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls axios
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "run" "examples"
npm ERR! cwd /Users/yanyang/axios
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/yanyang/axios/npm-debug.log
npm ERR! not ok code 0

**Comment by DIMPLY** [comment]
I can get "POST data received" on the server part.
But this time the query address is the same with the browser address.
What should I do if I want to post to an outer address such as "http://google.com"?

**Comment by DIMPLY** [comment]
I have test through it using `title=example&content=abccc&from=axios@a.com` instead of JSON format. And I also added a request header according to my server's CORS settings.
Sorry for bothering before enough trials.
