### ISSUE TITLE
Path params possible with axios?

### ISSUE THREAD

**Issue by dasniko** [mzabriskie/axios#162]
Hi,

is it in any way possible to have path params in axios which will be replaced by the `param` values?
e.g.

    axios.get('http://localhost/users/:userid', {params: {userid: '1234'}})

I know, I can implement it on my own using interceptors, but IMO this is an option which could be used by many users. This is also possible and a common way in many other frameworks and/or languages. Additionally
- the url string gets re-usable over multiple requests and
- the url gets more readable then concatenating values

Thoughts?

**Comment by mzabriskie** [comment]
With 0.8.0 you can provide your own `paramsSerializer` option. This will allow you to format your params anyway you'd like.

**Comment by qrqhuang** [comment]
Is there any e.g. for it ?
