### ISSUE TITLE
Wait for promise to provide additional options

### ISSUE THREAD

**Issue by mhelvens** [mzabriskie/axios#165]
For my own convenience I've implemented a shell around axios. One of its features that may be useful for others is to have axios wait for a promise to provide additional options. For example, here I use that feature to fetch an access token, required to make Google API queries (simplified):

```javascript
let myAxios = axios.create({

	waitForOptions:
		new Promise((resolve) => {
			window.gapi_callback = () => { resolve(window.gapi) };
			$('<script src="https://apis.google.com/js/auth.js?onload=gapi_callback">')
				.appendTo('head');
		}).then(gapi => gapi.auth.authorize({
			client_id: CLIENT_ID,
			scope:     SCOPE
		})).then(({access_token}) => ({
			headers: { 'Authorization': `Bearer ${access_token}` }
		}))

});

myAxios.get(`https://www.googleapis.com/gmail/v1/users/me/threads/${threadID}`);
```

This example assumes that axios waits for the given promise to resolve, then processes the resulting object as additional axios options (in this case additional headers).

It occurs to me there may be a way to do this with interceptors, but this is not clear from the documentation.

**Comment by mzabriskie** [comment]
You can certainly do this with interceptors:

```js
let googleAPIClient = axios.create();

googleAPIClient.interceptors.request.use((config) => {
  return new Promise((resolve) => {
    window.gapi_callback = () => { resolve(window.gapi) };
    $('<script src="https://apis.google.com/js/auth.js?onload=gapi_callback">')
      .appendTo('head');
  }).then(gapi => gapi.auth.authorize({
    client_id: CLIENT_ID,
    scope: SCOPE
  })).then(({access_token}) => ({
    config.headers: { 'Authorization': `Bearer ${access_token}` }
  }));
});

googleAPIClient.get(`https://www.googleapis.com/gmail/v1/users/me/threads/${threadID}`);
```

This will wait for the auth request to resolve then add the access token as a header to the original request and finally make your request for the thread.

**Comment by mhelvens** [comment]
OK, thanks!

Your example code does have invalid syntax on line 10-12. I think I know what you meant to do there, but could you correct the code for the record?
