### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by clayreimann** [mzabriskie/axios#166]
It's been 2 months since the last release and a lot of things have gone in (especially following redirects!), any thoughts on when all that hard work will get released?

**Comment by mzabriskie** [comment]
I've been traveling a ton combined with deadlines at my day job which result in little time for open source at the moment. I will try to get something out in the coming week.

**Comment by clayreimann** [comment]
Understandable. No rush, I actually figured out a work around for following redirects

**Comment by dfournier** [comment]
:+1:

**Comment by mzabriskie** [comment]
Just released [0.8.0](https://github.com/mzabriskie/axios/blob/master/CHANGELOG.md#080-dec-11-2015). Enjoy!

**Comment by clayreimann** [comment]
Nice! Thanks :smile:

**Comment by dfournier** [comment]
:clap:
