### ISSUE TITLE
Basic auth via Authorization header extra colon

### ISSUE THREAD

**Issue by ersab** [mzabriskie/axios#169]
Current implementation adds extra colon after word "Basic" which is invalid
(https://en.wikipedia.org/wiki/Basic_access_authentication)
	  // HTTP basic authentication
	  if (config.auth) {
	    var username = config.auth.username || '';
	    var password = config.auth.password || '';
	    requestHeaders['Authorization'] = 'Basic: ' + btoa(username + ':' + password);
	  }

**Comment by sashashakun** [comment]
First timer here! Is it correct that i should remove extra colon in http basic authentication implementation?

**Comment by mzabriskie** [comment]
Yes that is correct. If you look at `test/specs/__setupBasicAuthTest.js` you will find a test commented out on line 24. We need to make this test pass.

1. Fork repo
1. `$ npm install`
1. Uncomment that test
1. `$ npm test` (will fail)
1. Fix code
1. Run tests again (should pass)

**Comment by sashashakun** [comment]
Thanks. Start right now.

**Comment by mzabriskie** [comment]
Awesome! Let me know if you have any questions.
