### ISSUE TITLE
Error response with application/json body throws InvalidStateError

### ISSUE THREAD

**Issue by aukevanleeuwen** [mzabriskie/axios#171]
When I return a validation error message from my server as with content type `application/json` with status code `400` this throws  the following error:

```
Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
```

on this line: https://github.com/mzabriskie/axios/blob/f9c46c5c1da731c150febd347708f229e9bc74ab/lib/adapters/xhr.js#L75. Apparently it's not allowed to access the responseText property if the responseType does not match '' or 'text'. 

You seem to be aware of this since you are checking exactly this a few lines earlier (https://github.com/mzabriskie/axios/blob/f9c46c5c1da731c150febd347708f229e9bc74ab/lib/adapters/xhr.js#L62). 

I'd submit a pull request, but I'm not entirely sure what case is meant by the `(request.responseText && xDomain)` code...

**Comment by mzabriskie** [comment]
I think this could be resolved by switching the order of the conditional check:

```js
(xDomain && request.responseText)
```

This way we only reference `request.responseText` if it's valid.

**Comment by aukevanleeuwen** [comment]
Sorry I was doing something else, but had this fix commited on my fork already before I saw your comment. Not sure what you prefer, but you seemed to have the check already in place so I just thought I'd use it.

**Comment by mzabriskie** [comment]
I think it would be safer to do as I suggested above. Thanks for the PR!

**Comment by tomoya** [comment]
A few minutes ago, I encountered same issue. but, is was already fixed. very nice! :+1:

**Comment by solepano** [comment]
Hi, I'm getting same error
```

**Comment by GerryFudd** [comment]
I just encountered the same problem.

**Comment by ihorml** [comment]
@GerryFudd do you use [redux-axios-middleware](https://github.com/svrcekmichal/redux-axios-middleware) ? If yes just take a look at [this issue](https://github.com/svrcekmichal/redux-axios-middleware/issues/50)

**Comment by qtttttttttting** [comment]
I encounter similar problem @0.16.2.
ajaxInject.js:1 Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').
Thank you for your help~
