### ISSUE TITLE
Content type header removed if data is `false`

### ISSUE THREAD

**Issue by jboolean** [mzabriskie/axios#184]
xhr.js:93 removes the custom "content-type" header if data is the boolean "false" despite the comment that it should be removed if it is undefined. The boolean false is valid body data.

**Comment by mzabriskie** [comment]
You're referring to this line?

```js
if (!requestData && key.toLowerCase() === 'content-type') {
```

I think you're right. Looks like a bug.

**Comment by mzabriskie** [comment]
To verify that this issue is fixed get this test to pass: https://github.com/mzabriskie/axios/blob/master/test/specs/headers.spec.js#L102-L114
