### ISSUE TITLE
custom headers are not present

### ISSUE THREAD

**Issue by abdelacivitas** [mzabriskie/axios#186]
Hi guys, looks like axios is not setting a custom header im getting this issue:

`XMLHttpRequest cannot load http://xxxxxxxx/api/1.0/stores/getall. Response for preflight has invalid HTTP status code 401`

and make sense because the header is not set in the request headers.

![headers](http://content.screencast.com/users/abdeltatz/folders/Jing/media/518c88e5-5a44-4d7f-aa49-7e456f38245d/00000259.png)

this is the interceptor

```javascript
   Axios.interceptors.request.use((config) => {
      config.headers.Authorization = `Bearer ${this.props.authToken}`;
      return config;
    }, (error) => {
      return Promise.reject(error);
    });
```

I appreciate any help, thanks!

**Comment by abdelacivitas** [comment]
This was not an Axios issue is a CORS issue, great lib. thanks!

**Comment by AykutCevik** [comment]
@abdelacivitas how did you solve this? If I'm setting a custom header (X-...), axios is always performing a request with OPTIONS-method like the one in your screenshot.
