### ISSUE TITLE
axios not work on android 4.4.2

### ISSUE THREAD

**Issue by 9nix00** [mzabriskie/axios#188]
Dear all,

axios is great but not works on android 4.4.2 :(

**Comment by Ma27** [comment]
I'm not an android expert, but could you please a bit more precise about what your issue is?

**Comment by 9nix00** [comment]
It hard to say, I can't capture the output because I didn't install android development too.
but I tried other rest lib like https://github.com/cujojs/rest later. it not  works too.

I guess maybe some promise feature is not working on this version and previous version.
my boss push me to finish my job, so I use jQuery to resolve my work. so sad.

**Comment by 9nix00** [comment]
It hard to say, I can't capture the output because I didn't install android development too.
but I tried other rest lib like https://github.com/cujojs/rest later. it not  works too.

I guess maybe some promise feature is not working on this version and previous version.
my boss push me to finish my job, so I use jQuery to resolve my work. so sad.

**Comment by mzabriskie** [comment]
Are you polyfilling `Promise`? Maybe Android doesn't have native support.

**Comment by mzabriskie** [comment]
Looks like `Promise` wasn't introduced for Android until 4.4.4 (http://caniuse.com/#feat=promises). I recommend using [es6-promise](https://www.npmjs.com/package/es6-promise) as a polyfill.
