### ISSUE TITLE
[RFC] more http methods should be available as instance functions

### ISSUE THREAD

**Issue by Ma27** [mzabriskie/axios#189]
1.: What's the problem with the *axios* function?
-------------------------------------------------------------

When using sinon.js as mocking engine, you'll see after very short time that I works with functions exported in another module, but not with an exported function. This issue has been discussed here: https://github.com/sinonjs/sinon/issues/664
Now there are a lot of http methods such as "LINK" or "LOCK" that are not present as instance functions, so the *axios* function must be used. I'm pretty sure that I'll run in the next time into such issues, so I've thinked about a solution for this issue.

2.: Configurable API
--------------------------

The simplest solution to pass more http verbs to the arrays in the __axios.js__ (https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L110) is IMHO not a good solution since there are approaches for custom http verbs which cannot use instance methods.

3.: How it could look like
------------------------------

The *axios.create* function in order to provide custom http verbs that should be supported as instance function:

``` javascript
import axios from 'axios';
// ...

const instance = axios.create({
    // ...
    http_verbs: [
        { name: 'LOCK', with_data: false },
        { name: 'LINK', with_data: true }
    ]
});
```

**Comment by mzabriskie** [comment]
Sorry, I have a lot of other things demanding my attention and haven't given this a close look yet.

I think that any valid HTTP verb should be supported natively. Additionally it would be nice to allow adding custom verbs as you suggest.

**Comment by Ma27** [comment]
@mzabriskie ok - the PR #190 aims to implement this :)
I think that exactly this will be quite difficult: there are a lot of RFCs like the RFC-2518 for enhanced authoring actions and some more.
I'll rebase my PR on master and there are some things I'd like to do before talking about merging.
Could you please have a look at the way it is implemented?
