### ISSUE TITLE
TypeError: Cannot assign to read only property 'key' 

### ISSUE THREAD

**Issue by cressie176** [mzabriskie/axios#192]
We've encountered an intermittent error with the following code

```js
      axios.get(service)
        .then((response) => {
            response.data.key = key; // Blows up here
            return resolve();
        .catch((err) => {
          return reject(err);
        });
```

Following a ETIMEOUT error we got 

```
TypeError: Cannot assign to read only property 'key' of ��Z�r�6~�{cY�d���A�񌳱7J�������Ep�e�U�y�<�v� ؖ@I&�'�?_��n4��u��Z��������e&FW���U�p�egl)x�
��S�Q���0�QY��G<�G�����u$x0S1/���~�W"�Kw�%Y�
y�_��4��>�_~���Z�7���N؏2_'j�����.��'r�H�\2�r�Qe�D������|��GW��P�<_FW����L=�?�cg��B��<k5�a�r���Ձ���n��㴙vk�	���q�>y�
e�����K���o:�L[#X�c3�'�N�e��?���&�ul.�:f�}
```

My best guess is that instead of "catch" being triggered, "then" is called with the gzipped response. Whatever the underlying object is it has a read only key property, or is otherwise immutable.

We've received a few timeouts like this, but not had the TypeError problem before.

axios version: "0.7.0"

**Comment by cressie176** [comment]
Getting this on a daily basis. Also after 404s. Instead of an error being sent to catch, it's handled by then

**Comment by mzabriskie** [comment]
Have you tried updating to latest version (0.8.1)?

**Comment by cressie176** [comment]
Will try it today.

**Comment by mzabriskie** [comment]
@cressie176 any luck with this?

**Comment by cressie176** [comment]
Sorry - haven't had time to test yet.

**Comment by cressie176** [comment]
0.9.0 running in live now. Will close in a couple of days if the problem resolves.

**Comment by cressie176** [comment]
No - still errors with the same

**Comment by mzabriskie** [comment]
Strange. Are you running this in the browser or in Node?

**Comment by cressie176** [comment]
Both, but the logs we have are from when it's running on node. I tried to replicate in a standalone script with nock but couldn't. Will keep investigating

**Comment by mzabriskie** [comment]
Okay, I will try looking into what is happening in node adapter and see if we can get to the bottom of it.

**Comment by nickuraltsev** [comment]
@cressie176 Are you still having this problem?

**Comment by cressie176** [comment]
I've not worked on that part of the app for a while, but we started getting different errors on timeouts (calling then with no response object if I remember) in other parts so we switched it out Axios another isomorphic friendly library. Sorry.
