### ISSUE TITLE
Both then and catch executing in same call

### ISSUE THREAD

**Issue by dmt0** [mzabriskie/axios#199]
I'm doing this call:

    axios.get('/groups', {
      baseURL: 'http://localhost:5000',
      headers: { Authorization: 'Bearer ' + getAccessToken(),  'Content-Type': 'application/json; charset=utf-8' }
    })
      .then((response) => {
        console.log('then response',response)
        success(response.data)} )
      .catch((response) => {
        console.log('catch response',response)
        error(response.status, response.data.description)})

I'm calling this exactly once. I get a 200 OK response, `then` block executes, with `response` being an object I would normally expect. Right after that `catch` executes, response being a string:

    TypeError: Cannot read property 'groups' of null(…)

I thought the whole idea with promises is that only one executes. What am I getting wrong here?

**Comment by nilaybrahmbhatt** [comment]
I have the same error. Both then and catch executing in same call

**Comment by shin-monkey** [comment]
I am also getting this error. Is there an explanation for this?

**Comment by dmt0** [comment]
Basically it has to do with how promises works:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

The throw statement throws a user-defined exception. Execution of the current function will stop (the statements after throw won't be executed), and control will be passed to the first catch block in the call stack. If no catch block exists among caller functions, the program will terminate.

**Comment by tomasswood** [comment]
I had the same issue and mine was to do with having `.catch` before `.then`. Whoops.

**Comment by dengunya** [comment]
@greenzeal there is difference. this is strange, but the order does matter.
I wanted to use smth like
var func = () => axios.post(....).catch();
to implement error handling before calling this async function.
func().then(...)
But in this case "then" callback fires on error (ex. 404 status) and "catch" cb is ignored.

**Comment by spkvn** [comment]
Same issue. Make a post with response code 200 and get a js error saying a variable in my failure callback function was undefined. Shouldn't actually be called, right? 

dmt0 are you saying that an exception is being thrown during my success method, so my axios catch is responding? Sorry if I'm being an idiot :)

**Comment by greenzeal** [comment]
Yes, I was mistaken, there is a order in promises. First to use .then after .catch

**Comment by dacastro4** [comment]
This just happens to me and my problem was (correct me if I'm wrong) that any kind of error you have inside the `then()` callback it will be caught by the "catch" callback.

Example:

```
axios.get(url)
    .then( data => {
        //Happend some sort of error
    })
    .catch(error => {
        /it's gonna fall here. If you console log "error" is gonna be the error that happened in the then callback 
    })
```

**Comment by Jam0r85** [comment]
@dacastro4 THANK YOU! Was pulling my hair out trying to figure out why my request kept catching when it was successful. Re-read through my .then and found a bug 👍

**Comment by LuckyLam34** [comment]
@dacastro4 Thank you so much (y)

**Comment by zmechanic** [comment]
My problem was that I didn't need result in `then`, it was highlighted as unused, so in a hurry I removed it to the following:

        this.processDropFromPalette(data.component, data.dataTransfer.items)
            .then(this.setState(state => {
                data.component.isChanging = 1;
                return { connectedComponents: state.connectedComponents };
            }))
            .catch(reason => {
                this.ctx.publish(new Message.ShowErrorMessage(reason));
            });

And instead of being a lambda func declaration in `.then` it become a direct function call, so `this.setState()` was called as soon as `this.processDropFromPalette` returned, without waiting for `resolve()`.

**Comment by mohit61** [comment]
thanks.

**Comment by Tony-Ndichu** [comment]
I can see people 

> This just happens to me and my problem was (correct me if I'm wrong) that any kind of error you have inside the `then()` callback it will be caught by the "catch" callback.
> 
> Example:
> 
> ```
> axios.get(url)
>     .then( data => {
>         //some sort of error
>     })
>     .catch(error => {
>         /it's gonna fall here. If you console log "error" is gonna be the error that happened in the then callback 
>     })
> ```

I see several people have given a thumb's up to @dacastro4 's comment, could anyone please care to explain how his comment helped you guys with your specific situations? Am looking at the answer but I don't understand how to use it to prevent my `.then` and `.catch` both from executing at the same time.

**Comment by gabrieljcandia** [comment]
> > This just happens to me and my problem was (correct me if I'm wrong) that any kind of error you have inside the `then()` callback it will be caught by the "catch" callback.
> > Example:
> > ```
> > axios.get(url)
> >     .then( data => {
> >         //some sort of error
> >     })
> >     .catch(error => {
> >         /it's gonna fall here. If you console log "error" is gonna be the error that happened in the then callback 
> >     })
> > ```
> 
> I see several people have given a thumb's up to @dacastro4 's comment, could anyone please care to explain how his comment helped you guys with your specific situations? Am looking at the answer but I don't understand how to use it to prevent my `.then` and `.catch` both from executing at the same time.

I think it means that what could be happening, is that maybe there's an error in the "then" block, for what the "catch" block is being excecuted, and that being the reason why both blocks get excecuted. If that is true, doing console.log(error) in the "catch" block should show details. In my case that helped solve the problem.
