### ISSUE TITLE
Support file uploads

### ISSUE THREAD

**Issue by kentcdodds** [mzabriskie/axios#2]
[As suggested](https://twitter.com/geddski/status/510537967190806529) by @geddski. See docs for superaget's api [here](http://visionmedia.github.io/superagent/#multipart-requests)

**Comment by jimthedev** [comment]
This would be a fantastic feature. Since there is a polyfill already for fetch would it be a matter of adding a mapping for the property difference?

**Comment by nnarhinen** [comment]
After #22 file uploads using FormData should work just fine. There's an usage example in the PR.

**Comment by jimthedev** [comment]
@nnarhinen Thanks. I'll give it a shot.

**Comment by mzabriskie** [comment]
@nnarhinen @jimthedev #22 takes care of XHR file upload, but still need to handle file upload for node.js

**Comment by nnarhinen** [comment]
@mzabriskie oh yes, that is true

**Comment by luin** [comment]
really looking forward to the support for uploading file in node.js. any updates?

**Comment by mzabriskie** [comment]
Just a status update. I've looked into supporting file uploads with node.js. While it's not technically challenging, I'm trying to come up with a consistent API between node.js and the browser. While the browser uses `FormData`, node.js uses a `Stream`. For axios to be truly isomorphic it should allow using the same code in both environments.

**Comment by jimthedev** [comment]
Makes sense. It doesn't seem like there is any single standards-based or deprecated-standards based API for this, but there is [flow.js](https://github.com/flowjs/flow.js) (a fork of resumeablejs) which might provide at least a proven, successful API as a model. Although it looks primarily browser based, they seem to have a [Node example](https://github.com/flowjs/flow.js/blob/master/samples/Node.js/flow-node.js) although there is an [ambiguous open issue](https://github.com/flowjs/flow.js/issues/17) about it.

**Comment by revolunet** [comment]
hey...i'm a little confused. is it possible to upload a file from node using axios+streams ?

**Comment by andyhu** [comment]
+1

**Comment by stonexer** [comment]
maybe try [form-data](https://github.com/form-data/form-data) on the node side? like what fetch did.

**Comment by LowryTang** [comment]
does file upload support in axios for node.js?

**Comment by donaldparker** [comment]
https://github.com/mzabriskie/axios/blob/master/examples/upload/index.html

**Comment by LowryTang** [comment]
@donaldparker  this only work for browser. Do you know how to make it on node.js?

**Comment by andyhu** [comment]
Need node.js version too

**Comment by maotora** [comment]
Hi, I'm trying to upload a file from it's filename instead of uploading it as form-data using Electron.

I tried both the node.js solution & browser solution but both don't really workout as I get [object Object] as the file request on the server.

This is a sample code of what I'm doing ...

Getting the file from it's fileName Url.

```js
export function generateContract(url, customer) {
    const data = new FormData()
    const file = fs.createReadStream(url)

    data.append('names', customer.names)
    data.append('email', customer.email)
    data.append('contract', file)

    return data
}
```
Sending the returned formData using axios.
```js
export function sendEmail(formData) {
    return checkConnetion()
        .then(() => {
            return axios.post(emailUrl, formData)
        })
        .catch(() => {
            return axios.post(emailUrlOffline, formData)
        })
}
```

I also made [this question](https://stackoverflow.com/q/46476474/2405689) on stackoverflow if someone can take a look.

Thanks.

**Comment by euroclydon37** [comment]
This was closed after having the **in progress** tag removed. Has an alternative been found?

**Comment by maotora** [comment]
@euroclydon37 I couldn't solve my issue.

So I ended up using superagent for just one request! I had deadlines to meet so I gave the evil smile & went for it.

I will be glad to hear a solution, will update my program if I can test and make it work.

**Comment by douglasjunior** [comment]
I made it work with `FormData`.

```js
        // create the file object: https://developer.mozilla.org/en-US/docs/Web/API/File
        const file = {
            lastModifiedDate: ...,
            lastModified: ...,
            name: ...,
            size: ...,
            type: ...,
            uri: 'file:///path/to/file.txt', // required value
        };

        // create FormData
        const formData = new FormData();
        formData.append('field_name', file);

        // send with axios
        axios.post('http://your/url/', formData);
```
(Works on Node and React Native)

**Comment by SheldonLaw** [comment]
> ```js
> https://developer.mozilla.org/en-US/docs/Web/API/File
> ```

It take some time to understand how to create file object, and I finally made it work: 
```
const file = new File(
    [fs.readFileSync(YOUR_FILE_PATH)],
    fileName,
    { type: `image/${fileType}` } // what i upload is image.
  );
``` 

Thanks @douglasjunior
