### ISSUE TITLE
Set response encoding

### ISSUE THREAD

**Issue by nickdima** [mzabriskie/axios#20]
I wanted to get a buffer out of some binary data from a GET request but I couldn't get it to work unless I put `res.setEncoding('binary')` inside `http.js`
Any suggestions?

**Comment by mzabriskie** [comment]
@nickdima sorry I've totally neglected your issue. Yes, please submit a PR.

**Comment by nnarhinen** [comment]
Also loosely related, `responseType: 'arraybuffer'` does not work in the browser because `responseText` property is not readable in such responses. Has to be read from `response` instead.

![image](https://cloud.githubusercontent.com/assets/265438/5888884/3b353b70-a418-11e4-86f9-4fc95f91a4d9.png)

**Comment by sorenbs** [comment]
Looking forward to this. My use case is websites that don't properly specify encoding in headers, but do specify it in a meta tag. So I need to parse as utf-8 first, and then possibly re-parse as different content type.

**Comment by nickdima** [comment]
Sorry guys, I haven't use axios lately so I wont be able to work on that PR at this point. Maybe someone else could give it a try.

**Comment by mzabriskie** [comment]
I believe that this has been solved. See current http implementation https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L93-L96
