### ISSUE TITLE
Axios rejects on the successful request (204) in IE9

### ISSUE THREAD

**Issue by savantaparna** [mzabriskie/axios#201]
## Current behavior: 
Axios rejects the promise on successful request in IE9  on status code 204.

## Expected behavior:
Axios should resolve the promise when it receives status code as 204 in IE9.

I have found the discussion of this same issue - 
http://stackoverflow.com/questions/10046972/msie-returns-status-code-of-1223-for-ajax-request

IE coerces 204 to 1223 and this falls out range of success codes (>= 200 && < 300).

**Comment by mzabriskie** [comment]
Wouldn't expect anything less from IE :/

**Comment by mzabriskie** [comment]
This fix is available in 0.9.1
