### ISSUE TITLE
Promise not defined on Opera

### ISSUE THREAD

**Issue by divyenduz** [mzabriskie/axios#203]
Hi, I am getting the error  `Unhandled Error: Undefined variable: Promise`
on opera desktop version (screenshot) in the line https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L62

![screenshot from 2016-01-22 12-02-17](https://cloud.githubusercontent.com/assets/746482/12504053/15068750-c100-11e5-9881-78738c81944a.png)

Any pointers ?

**Comment by mzabriskie** [comment]
You may need to polyfill `Promise` as not all browsers support it natively yet. I recommend [es6-promise](https://www.npmjs.com/package/es6-promise).

**Comment by divyenduz** [comment]
I think this will occur only on old opera according to http://caniuse.com/#search=promise, I am closing this one. Thanks
