### ISSUE TITLE
Axios doesn't resolve/reject on network level errors (i.e. onerror)

### ISSUE THREAD

**Issue by latentflip** [mzabriskie/axios#204]
I've noticed that on current chrome (unsure how other browsers treat this) axios doesn't resolve or reject if I forget to start my api server. I believe it's because at the network level, onload never gets called on a request, but onerror does instead, and looking at https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js we don't handle onerror at all.

![localhost 3000 2016-01-22 15-16-05](https://cloud.githubusercontent.com/assets/78225/12514400/17ac83d6-c11b-11e5-8aa5-c48fbd3310f1.png)

Any reason not to add a `onerror` handler? Happy to attempt a PR if not.

**Comment by mzabriskie** [comment]
Yeah this is wrong. Happy to accept a PR.

**Comment by latentflip** [comment]
It _looks_ at first glance like `request.onload = request.onerror = function () {...` might work, since we're already handling `if (!request)`, will take a look.

**Comment by mzabriskie** [comment]
I don't know if that will work, because `request` will still exist, even if it's in error. Should be as simple as what the node adapter is doing.

```js
request.onerror = function(error) {
  reject(error);
};
```

**Comment by latentflip** [comment]
@mzabriskie oh, so you'd rather reject with the error, rather than a response object with a 0 status?

**Comment by mzabriskie** [comment]
I think so. Mostly for parity with nose adapter, but also there isn't any response data to return. Whereas the Error could provide meaningful information as to what happened.

**Comment by latentflip** [comment]
So it looks like onerror doesn't actually return an error, but a progress event. At least in the case of `http://localhost:5000` when the api isn't actually running.

![localhost 3000 2016-01-22 16-13-12](https://cloud.githubusercontent.com/assets/78225/12516014/204b391c-c123-11e5-9eb4-e3e8129e85c4.png)

Throwing that event I don't think makes sense since it's not even an error object. According to: http://stackoverflow.com/questions/4844643/is-it-possible-to-trap-cors-errors in at least the situation of cors errors, the actual error is not available to your JS code (just gets logged to the console).

So I guess we're back to: either rejecting with a 0 status, or just throwing something like `new Error('Unknown XHR error')` thoughts?

**Comment by mzabriskie** [comment]
After reading a bit, it looks like `onerror` only gets called when there's a network error. Let's just throw `new Error('Network error');`

**Comment by latentflip** [comment]
:+1: agreed, done: #205

**Comment by mzabriskie** [comment]
Thanks for your help!

**Comment by zbobyuan** [comment]
I run this issue too, when your plan release this fix?

**Comment by mzabriskie** [comment]
Will try and get a release out this weekend.

**Comment by mzabriskie** [comment]
This fix is available in 0.9.1

**Comment by nicklaw5** [comment]
I'm receiving "Network error" but server is responding with "500 Internal Server Error".

Would be great if this error response could be more explicit for better application handling. Is this possible?
