### ISSUE TITLE
Cookie handling

### ISSUE THREAD

**Issue by MMRandy** [mzabriskie/axios#207]
Is there anything in the lib that helps create/manage cookies?  I didn't see anything, so just wondering.  Thx.

**Comment by mzabriskie** [comment]
There is no special handling for cookies other than what the browser does automatically.

**Comment by naivefun** [comment]
@mzabriskie Is there a way to read cookies from response?

**Comment by nickuraltsev** [comment]
@naivefun I don't think it's possible. XMLHttpRequest does not allow to retrieve Set-Cookie header value from the response: https://www.w3.org/TR/XMLHttpRequest/#the-getresponseheader%28%29-method

**Comment by naivefun** [comment]
@nickuraltsev  thanks. I used chrome.cookies api to get it done.

**Comment by pbassut** [comment]
@naivefun Bother saying how you did it?
