### ISSUE TITLE
Change an axios instance's default headers?

### ISSUE THREAD

**Issue by smilingpoplar** [mzabriskie/axios#209]
I use token in the headers for authentication. So I firstly create an axios instance to login.  All the requests after login should carry the token in a header field. 

Q1: Should I use `instance.interceptors.request.use()` to inject the token?

In my integration test, I login as different users. The `instance.interceptors.request.use()` accumulates the token configs in an internal array, and the login result is not always right. So I must `instance.interceptors.request.eject()` before each `instance.interceptors.request.use()` just to clear the internal array.

Q2: Is there a better way to change an instance's default headers?

**Comment by mzabriskie** [comment]
If you always know the value of the header:

```js
axios.defaults.headers.common['Auth-Token'] = 'foo bar';
```

This will automatically add the header to every request.

**Comment by smilingpoplar** [comment]
@mzabriskie Thanks for the quick reply. It works. For instance only, I set: 

```
instance.defaultConfig.headers['Auth-Token'] = 'foo bar'
```

**Comment by mzabriskie** [comment]
Where are you getting `defaultConfig` from? It should just be `instance.defaults` https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L13

**Comment by smilingpoplar** [comment]
Yes, I should update the version.
https://github.com/mzabriskie/axios/blob/v0.8.1/lib/axios.js#L12

**Comment by mzabriskie** [comment]
Ah right. Glad it's working!

**Comment by XidongHuang** [comment]
hi I have the issue after setting `axios.defaults.headers.common[]`.
Requests all worked well before I tried to set the users' token in `request header`, but they send `OPTIONS` to my back-end and `404`, not matter `POST` or `GET` method I use there.
the pic from chrome devTools:
![postdev](https://user-images.githubusercontent.com/13139446/27104628-e45ff2da-505a-11e7-9c6f-db3b401b95f4.png)

the way I set headers is:
```
import axios from 'axios';

export default function setAuthorizationToken(token) {
    if(token) {
        axios.defaults.headers.common['authorization'] = `${token}`;
    } else {
        delete axios.defaults.headers.common['authorization'];
    }
}

```

I know it is about `CORS`, so I also set up on the server side:
```
//app.js
app.use((ctx, next) =>{

    // Website you wish to allow to connect
    ctx.res.setHeader('Access-Control-Allow-Origin', '*');

    // Request methods you wish to allow
    ctx.res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

    // Request headers you wish to allow
    ctx.res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type,authorization');

    // Set to true if you need the website to include cookies in the requests sent
    // to the API (e.g. in case you use sessions)
    ctx.res.setHeader('Access-Control-Allow-Credentials', true);
    ctx.res.setHeader('withCredentials', true);

    // Pass to next layer of middleware
    next();
});
...
```
and we can see these request features from the first `OPTIONS` request on the devTool pic.

So any hints about this?
Thank you.

**Comment by berdyshev** [comment]
But it seems that `instance.defaults.headers.common[HEADER_NAME] = 'some value'` changes the defaults not only for the instance but for the any axios request made even directly with `axios.get()` (not `instance.get()`)

**Comment by cmcleese** [comment]
I also have the same issue @berdyshev described.
If I need to make a new axios request by creating a new axiosInstance and this new request I need to remove some default header.
Lets say I need to remove the default Authorization header.

I would expect something like this:
`delete axiosInstance.defaults.headers.common.Authorization`
to be safe as it should only remove from the axiosInstance I created.

However I can confirm also that this seems to removing also from the main `axios` instance the header.

Anyone know of a work around for this?

**Comment by TAUnionEd** [comment]
> I also have the same issue @berdyshev described.
> If I need to make a new axios request by creating a new axiosInstance and this new request I need to remove some default header.
> Lets say I need to remove the default Authorization header.
> 
> I would expect something like this:
> `delete axiosInstance.defaults.headers.common.Authorization`
> to be safe as it should only remove from the axiosInstance I created.
> 
> However I can confirm also that this seems to removing also from the main `axios` instance the header.
> 
> Anyone know of a work around for this?

same question in 0.16.2

**Comment by lmj0011** [comment]
https://github.com/axios/axios/issues/209#issuecomment-174206234

This will not effect an "instance" of axios v0.18

You will need to also do for example:

```js
const axiosInstance = axios.create({
          baseURL: 'http://example.com',
          headers: {
            'Auth-Token': `Bearer ${this.apiToken}`,
          }
        });

axiosInstance.defaults.headers['Auth-Token'] = 'foo bar';
```

**Comment by flppv** [comment]
For me it works weird.

I create and instance with `const axiosInstance = axios.create()`, update it's header with 
`axiosInstance.defaults.headers.common['CUSTOM'] = 'blahblah`

After that I do two console logs: 
```
console.table(axios.defaults.headers.common)
console.table(axiosInstance.defaults.headers.common)
```

And guess what? They both have `CUSTOM` header 🤔

**Comment by msqar** [comment]
Guys, can anyone help me? I think i'm doing this wrong.
Before doing a new http request with my AxiosInstance, i attempt to change the headers accordingly, but sometimes the request is sent before the headers are changed. Do i need to add promises here?

Here's an example:

```
** USERSERVICES.JS **

getUserByToken: function(token) {
        var headers = [
            { key: 'Authorization', value: 'Bearer ' + token},
            { key: 'Content-Type', value: 'application/x-www-form-urlencoded'}
        ];

        setHeaders('get', headers);
        return AxiosInstance.get('/user');
    },
```

Here's my setHeaders function:

```
** SERVICECONFIG.JS **

export const setHeaders = (type, props) => {
    AxiosInstance.interceptors.request.use(config => {
        config.headers[type] = {};

        props.forEach((prop) => {
            config.headers[type][prop.key] = prop.value;
        });
        return config;
    });
}
```

I noticed that it's quite asynchronous... is my implementation good? seems i have to change it, prolly with Promises?
