### ISSUE TITLE
installation with jspm

### ISSUE THREAD

**Issue by alexisargyris** [mzabriskie/axios#214]
Hello,

I am trying to install [github-api](https://github.com/michael/github) which depends on axios like this:

````
"dependencies": {
    "axios": "https://github.com/github-tools/axios.git",
    "base-64": "^0.1.0",
    "es6-promise": "^3.0.2",
    "utf8": "^2.1.1"
  }
````
I am trying
````
jspm install npm:github-api
````
and I get back
````
Downloading npm:github-api@0.11.2

warn Error on processPackageConfig
     npm dependency format https://github.com/github-tools/axios.git not currently supported by jspm. Post an issue if required.

warn Error processing package config for npm:github-api.

err  Error processing package config for npm:github-api.
````
Am I doing something wrong? Should I approach this some other way?

Thanks

**Comment by mzabriskie** [comment]
It looks like jspm doesn't support depending on a repo directly from GitHub. I'm not sure why they are depending on a fork. I'd suggest opening an issue with github-api and encourage them to use the axios package directly from npm.

**Comment by alexisargyris** [comment]
will do, thanks

**Comment by AurelioDeRosa** [comment]
Hi.

To clarify why we use a fork is because we need to expose the XHR request to avoid any backward incompatibility. I proposed the fix we needed in [this PR](https://github.com/mzabriskie/axios/pull/200) but it hasn't been merged yet.

**Comment by mzabriskie** [comment]
I will take a look at your PR.
