### ISSUE TITLE
How is this project different from request-promise?

### ISSUE THREAD

**Issue by fatuhoku** [mzabriskie/axios#218]
I'm looking for a http request library with a Promise API that doesn't rely on Bluebird (i.e. to minimise dependencies). Will axios fit the bill?

**Comment by MarkHerhold** [comment]
@fatuhoku FYI, RequestPromise has an issue open for abstracting away from Bluebird. https://github.com/request/request-promise/issues/65

**Comment by fatuhoku** [comment]
@MarkHerhold Okay, good to know! I'm using axios now. Definitely works well for me.
