### ISSUE TITLE
Custom instance defaults can't be set as documented

### ISSUE THREAD

**Issue by ctimmerm** [mzabriskie/axios#220]
https://github.com/mzabriskie/axios#custom-instance-defaults

Because the defaults from `defaults.js` are not merged in here: https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L88, `instance.defaults.headers` will be `undefined`.

I'll try to make a PR some time soon.

**Comment by MMRandy** [comment]
+1  Any movement on this?

**Comment by SamuelNorbury** [comment]
This is an issue I'm dealing with too, forced to use global defaults instead, which is far from optimal.

**Comment by mzabriskie** [comment]
This has been fixed with 46eee26
