### ISSUE TITLE
ng-resource

### ISSUE THREAD

**Issue by cidevant** [mzabriskie/axios#222]
Hi, 

this project is awesome. I have my own component "[react-resource](https://github.com/cidevant/react-resource)", inspired by Angular's $resource module. Now it provides quite similar API, like `ng-resource`, but there is a lot of space for improvements (global config, file attachments, interceptors, transformRequest, transformResponse, etc). So I decided to rewrite it and use `axios` instead of `superagent`, because you have already implemented all this features in `axios`!!)

Maybe in future we could merge our projects in one ;-) I would like to ask you to help me in development ;-) I think, code review will be enough for the begining. I will let you know when I will start refactoring.

Best regards, Konstantin

**Comment by mzabriskie** [comment]
Hey, react-resource looks interesting. Glad that you find axios useful. I think it makes most sense to keep axios as a dependency of react-resource, instead of merging, as a lot of projects are using axios without React. Keep up the good work!
