### ISSUE TITLE
Injecting additional information to response

### ISSUE THREAD

**Issue by inertum** [mzabriskie/axios#223]
I'm using axios in redux (w/ redux-promise middleware). 

If the action returns anything else than type+payload, 
the request isn't detected as promise (as far as I know, stabbing at the dark here!)

So quetion is how can I inject the index value inside the payload?

```javascript
export function updateValue(props, index) {
  const axiosRequest = axios...();

  return 
    {
      type: *type*,
      payload: *axiosRequest*,
      **index,
    }
}
```

**Comment by ctimmerm** [comment]
Could you give some more information about what you're trying to do?
Any of the axios API calls returns a plain Promise (the `axiosRequest` in your example is just a Promise), so in that sense using axios isn't any different from using any other Promise for the payload.
If you used the `index` in the request and want to have access to it where you're processing the response, it should already be available in `response.config`.

**Comment by nickuraltsev** [comment]
`redux-promise` will dispatch the resolved value of the promise. If you would like to dispatch `index` in addition to the response, you can do something like this:

```js
export function updateValue(index) {
  const payload = axios.get(url).then(response => ({
    index,
    response,    
  }));
  return {
    type: ACTION_TYPE,
    payload,
  };
}
```
