### ISSUE TITLE
Possible to not make an OPTIONS call before POSTing?

### ISSUE THREAD

**Issue by Zensavona** [mzabriskie/axios#225]
Hey, I'm working with a Java backend which I do not have control over and it doesn't accept the OPTIONS calls axios likes to send before POSTing things, is it possible to skip the OPTIONS and just naively send a POST? I can't see an obvious way to do it. Am I missing something?

Thanks <3

**Comment by mzabriskie** [comment]
The `OPTIONS` is a preflight request for CORS to verify if it's okay to make the request. There's no way around it if you're sending requests from one origin to another.

**Comment by Zensavona** [comment]
All good, thanks anyway!
