### ISSUE TITLE
Support for axios.default.params?

### ISSUE THREAD

**Issue by reggi** [mzabriskie/axios#229]
Is there any way to get support for `axios.default.params`? Does this exist already? I really love the deafult functionality for headers, I think it makes a lot of sense.

**Comment by reggi** [comment]
This works:

```js
axios.defaults.params = {}
axios.defaults.params['public_key'] = publicKey
```

**Comment by Sokal21** [comment]
This is still working? I'm trying to use and the params are not being shown in the URL

**Comment by baumannzone** [comment]
It's not working for me neither.

Trying as @reggi said and with this:

```
axios.create( {
  baseURL: d3.url,
} );
axios.params = {};
// eslint-disable-next-line
axios.params[ 'locale' ] = d3.locale;
// eslint-disable-next-line
axios.params[ 'apikey' ] = d3.apikey;
```

Also in _dot_ notation

**Comment by pk936** [comment]
@reggi @baumannzone  I tried by copy pasting your code. The params are not appearing in URL.

**Comment by baumannzone** [comment]
It's ok. It shouldn't appear in the URL.
You may be confusing terms. 

For params in the URL, read this: https://github.com/axios/axios#request-config
```
// `params` are the URL parameters to be sent with the request
// Must be a plain object or a URLSearchParams object
  params: {
    ID: 12345
  },
```

**Comment by libasoles** [comment]
Issue, they say, is with v0.19. Downgrading to 0.18.1 should work. See:
https://github.com/axios/axios/issues/2190

There's a working demo of this:
https://runkit.com/philipbjorge/axios-regression

However, I downgraded and still can make it work.

**Comment by RomkaLTU** [comment]
Can confirm that downgrading to `"axios": "^0.18.1"` helps:

```
axios.defaults.params = {};
axios.defaults.params = {
  'foo': 'bar',
};
```

**Comment by karneaud** [comment]
+1

**Comment by buggedcom** [comment]
For people finding this issue before the other, here is a workaround with `0.19.0` using interceptors.

https://github.com/axios/axios/issues/1476#issuecomment-542958459
