### ISSUE TITLE
Deflate/gunzip

### ISSUE THREAD

**Issue by OliverJAsh** [mzabriskie/axios#23]
It would be nice to see support for deflating/gunzipping requests. Have you thought about this?

**Comment by jimthedev** [comment]
Looks like http://nodeca.github.io/pako/ does exactly this. Perhaps it would be worth figuring out if the two can work together so as to keep as much as possible outside of axios core.

**Comment by mzabriskie** [comment]
@jimthedev thanks for the tip. I'll take a look at it.

**Comment by mzabriskie** [comment]
@jimthedev @OliverJAsh I think I would recommend keeping this functionality out of axios. I want to keep the bloat down as much as possible from the core. Minified pako is 44k vs axios minified is 15k. Should be able to easily create an interceptor to inflate/deflate requests as needed.

**Comment by jimthedev** [comment]
Sounds good.
