### ISSUE TITLE
Rate-limit control within axios?

### ISSUE THREAD

**Issue by reggi** [mzabriskie/axios#230]
I'm working with an API that only allows you to send 2 request per 1000ms and I have this function where you can pass a achieve this.

```js
function promiseDebounce(fn, delay, count) {
  var working = 0, queue = []
  function work() {
    if ((queue.length === 0) || (working === count)) return
    working++
    Promise.delay(delay).tap(function () { working-- }).then(work)
    var next = queue.shift()
    next[2](fn.apply(next[0], next[1]))
  }
  return function debounced() {
    var args = arguments
    return new Promise(function(resolve){
      queue.push([this, args, resolve])
      if (working < count) work()
    }.bind(this))
  }
}
```

The following should work, but only for post requests:

```js
axios.post = promiseDebounce(axios.post, 1000, 2)
```

My question / issue is: is there a way for me to throttle all requests made by `axios`? So if someone runs `axios.post` or `axios.get` those requests are throttled. 

Also any interest in supporting this functionality within `axios`?

**Comment by reggi** [comment]
@mzabriskie If you have the time and this is a simple question would love to hear your thoughts?

**Comment by mzabriskie** [comment]
Not something I would support natively, but I believe this could be accomplished with interceptors.

**Comment by aasmm7x** [comment]
This is an really a+ feature that should be implemented in core, imo.

**Comment by aishek** [comment]
In case someone needs to rate limit API calls: https://www.npmjs.com/package/axios-rate-limit
