### ISSUE TITLE
optional size limit

### ISSUE THREAD

**Issue by jampy** [mzabriskie/axios#231]
Is there a way to abort requests if the response content exceeds a predefined size?

I'd like to avoid that my NodeJS process screws up just because axios is requested to load a URL that returns some gigabytes of data...

**Comment by mzabriskie** [comment]
This isn't currently possible, but could be done by adding a `maxContentLength` config option, then rejecting for requests that exceed that. I would be happy to accept a PR if you want to take a stab at this.

**Comment by bomsy** [comment]
looking into this..

**Comment by bomsy** [comment]
@mzabriskie Would we want reject with an err or with a response on this one?

**Comment by mzabriskie** [comment]
I'd go with an Error object

**Comment by bomsy** [comment]
I think we can close this issue.

**Comment by nickuraltsev** [comment]
Fixed by #275

**Comment by benbieler** [comment]
Is there anything new regarding this topic?
