### ISSUE TITLE
Option for sync

### ISSUE THREAD

**Issue by LestaD** [mzabriskie/axios#232]
I need option to enable sync loading.
I want to use `axios` on server with react

**Comment by mzabriskie** [comment]
You want to make a synchronous request? Why can't this be asynchronous? I know people are doing server rendering with React + axios this way.

**Comment by LestaD** [comment]
@mzabriskie can you help me?

**Comment by LestaD** [comment]
Or give me a link on projects react ssr+axios

**Comment by LestaD** [comment]
I don't know how to stop rendering until all requests will resolved.
I make request in `componentWillMount()`

**Comment by tquetano-r7** [comment]
Use axios.all to manage your dispatch rather than dispatching with each result.

**Comment by nettofarah** [comment]
@LestaD a way to solve this is to declare all requests you need to perform as a static array property in your react component.

Something like this:

```javascript
class Home extends React.Component {

  static dataDependencies = [
    fetchHome
  ]

  componentDidMount() {
    const { dispatch } = this.props
    dispatch(fetchHome())
  }

  render() {
    ...
  }
}
```

You can then write a function in your backend server that does something like this:

```javascript
const reqs = Home.dataDependencies.map((req) => ...)
Promise.all(reqs).then(function() {
  renderToString...
})
```

**Comment by LestaD** [comment]
@nettofarah good solution

**Comment by ashishd751** [comment]
@mzabriskie can you please provide an in-built solution to this problem. I know all AJAX calls are supposed to be async, but i am in a situation where the control of the program shouldn't proceed until the response arrives. 
To be more specicifc, i need to stop the render function from executing, before response arrives in the componentWillMount() of the same component.

**Comment by glenselle** [comment]
@mzabriskie I think I also have a pretty valid use-case. I am opening a new tab (to a different app on a different domain) when a network request completes with axios. Right now, Chrome blocks the new tab and treats it as a popup b/c it only wants to open a new tab/window on a new domain when you have the context of a "trusted event" -- usually, clicking a button. However, when AJAX requests are performed asynronously, you lose the context of this trusted event. Performing the request synchronously resolves this because you still have the "trusted event" context.

For more background & info see this SO answer: https://stackoverflow.com/a/20235765

**Comment by rubennorte** [comment]
@ashishd751 there are ways to accomplish that other than adding that feature to Axios. Please take a look at https://github.com/mzabriskie/axios/issues/681#issuecomment-290991749 for more details.

**Comment by richlloydmiles** [comment]
Check out await - https://github.com/gabrielstuff/async-await-vue/

**Comment by snorkellingcactus** [comment]
Ok. Then im doing an app which only:
- gets a token
- sends pings to an api with the requested token
- may receive some special response, which will pass to another process.

So no need of anything async there and im not on the browser.

Why should i pollute my code with an asynchronous keyword to make some simple and synchronous code ?

I mean, with an async keyword which was meant to solve a problem i dont need to solve ?

Do you love pollution ?
