### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by alexisargyris** [mzabriskie/axios#237]
Hi,

In package.json the only dependecy listed is "follow-redirects" but in "http.js" there seem to be more (e.g. url, zlib, buffer). Is this a problem?

**Comment by ctimmerm** [comment]
The http adapter is used when running axios on node.js. url, zlib and buffer are core modules included with node itself and thus do not need to be listed as external dependencies.

**Comment by alexisargyris** [comment]
Ok, thanks
