### ISSUE TITLE
Reject with error

### ISSUE THREAD

**Issue by OliverJAsh** [mzabriskie/axios#24]
It is good practice to reject promises with an error object because they have stack traces.

[When rejecting because of a bad status code](https://github.com/mzabriskie/axios/blob/d93df704a269d3cbf8f00bcd4b2b2489d5b74f49/lib/adapters/http.js#L73), I suggest rejecting with an error object, e.g. `BadStatusCodeError`. You could then attach the response object to the error object so it can be accessed in a rejection handler.

**Comment by jtmarmon** [comment]
+1 would love to be able to use this in tests

**Comment by jtmarmon** [comment]
see #32

**Comment by kilianc** [comment]
+1 on this, I was just about to open a new issue, throwing non errors is wrong, and if you `async` or `yield` this is exactly what happens.

This is for some reason not part of the promises specification, and it's a flaw imho.

**Comment by trueter** [comment]
+1

**Comment by helmus** [comment]
👍  Please raise the priority on this.

**Comment by naw** [comment]
It's possible to address this without breaking backward compatibility simply by making it configurable with a default that uses the current (legacy) behavior.  Then, for a major release, you can simply change the default from the legacy behavior to the new behavior.

**Comment by kilianc** [comment]
@naw this is a bug fix not a change in feature. It may make sense to be more conservative and bump minor. I hope the old behavior just goes away

**Comment by axross** [comment]
:+1:

**Comment by trueter** [comment]
Its been a month, can we please have this?
