### ISSUE TITLE
Cross domain requests on IE9 are timing out prematurely 

### ISSUE THREAD

**Issue by pborrego** [mzabriskie/axios#240]
# Current behavior
When IE9 is running cross domain requests, the requests are timing out before the timeout time that I set with the Axios configuration.

# Expected behavior
Axios should ensure that XDomainRequest object's timings does not cause it to time out prematurely.

Here are two source talking about the same issue I am seeing and how they solved it:
http://perrymitchell.net/article/xdomainrequest-cors-ie9/
http://cypressnorth.com/programming/internet-explorer-aborting-ajax-requests-fixed/

Running a quick test for myself I modified the adapter for XDomainRequest and set ontimeout and onprogress to empty functions and found that the premature timeouts stopped occurring for me.

**Comment by mzabriskie** [comment]
This should be fixed with #251.
