### ISSUE TITLE
Invalid axios.all TypeScript Definition

### ISSUE THREAD

**Issue by mjrister** [mzabriskie/axios#253]
The TypeScript definitions for axios.all are not correct in that they don't conform to the ES6 Promise.all interface. The first issue is that it assumes that the return value from axios.all is an array of promises whose resolve values are an array of Axios.AxiosXHR types. The resolve values could be of any type, not just Axios.AxiosXHR.

Second issue is that the .all interface is poorly designed. It has a hardcoded number of paramter types of maximum length 10. This is also incorrect as it could be of any size. Instead it should just use a generic array of type T[] where T can be of any (or some common base class).

My suggestion is to just look at ES6-Promise.d.ts and copy what they have there.

**Comment by mjrister** [comment]
The interface for all should just be         

all<T>(values: [T | IPromise<T>]): IPromise<T[]>;

**Comment by mjrister** [comment]
Also it looks like the spread function is also not correct as it only assumes there are two parameters, but destructuring has no limit to the number of attributes

**Comment by mzabriskie** [comment]
Thanks for catching this. I don't use TypeScript, so I am not well versed in how this stuff works. Would be happy to accept a PR to fix these issues.

**Comment by mjrister** [comment]
Thanks, I will try to do so soon as I really do like axios. As a workaround for this, I was able to utilizing Promise.all (by referencing es6-shim.d.ts) instead of axios.all to allow for my TS code to compile without errors.

**Comment by mzabriskie** [comment]
Closing in favor of a single issue for all typescript requests (#379).
