### ISSUE TITLE
trying to build using codeship but fails because it says axios.git is not a package

### ISSUE THREAD

**Issue by denniskkim** [mzabriskie/axios#256]
-npm ERR! not a package /tmp/npm-4127-dA97FOL3/github.com/github-tools/axios.git
\npm ERR! Error: ENOENT, open '/tmp/npm-4127-dA97FOL3/github.com/github-tools/axios.git-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-58-generic
npm ERR! command "/home/rof/.nvm/v0.10.42/bin/node" "/home/rof/.nvm/v0.10.42/bin/npm" "install"
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.4.29
npm ERR! path /tmp/npm-4127-dA97FOL3/github.com/github-tools/axios.git-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! not ok code 0

so im getting this error while trying to build my project with codeship. any ideas as to why im getting this? thanks

**Comment by mzabriskie** [comment]
Not really sure why this is happening, but it looks like you're using a fork of this project. Have you tried using this project instead?

**Comment by nickuraltsev** [comment]
Closing since it does not seem to be a problem with axios. Please reopen if you feel otherwise.
