### ISSUE TITLE
Allow customization of resolve/rejection handling for status codes

### ISSUE THREAD

**Issue by ajcrites** [mzabriskie/axios#258]
Currently any non-200 level status code will be rejected. In most cases this makes sense, but if you are anticipating a certain status code this can break control flow [as it does here](https://github.com/Team-Crites/lambdathrooms/blob/master/functions/status/src/index.js)

    const response = await axios.get(url);
    if (200 === response.statusCode) doA();
    if (422 === response.statusCode) doB();
    doC();   

There is currently no way to do this without handling the rejection on your own which can be unintuitive.

[request-promise handles this with the `simple` option](https://github.com/request/request-promise#rejected-promises-and-the-simple-option). I think it would be even better to allow users to define ranges or maybe a function that determines resolution / rejection based on header information.

**Comment by mzabriskie** [comment]
I actually agree with this idea. See my comment here https://github.com/mzabriskie/axios/issues/41#issuecomment-72732209.
