### ISSUE TITLE
Flow doesn't think axios has a patch method

### ISSUE THREAD

**Issue by ericwooley** [mzabriskie/axios#260]
Not sure how or where to deal with that. But it's mildly annoying.

**Comment by mzabriskie** [comment]
Is Flow aware of the other HTTP methods (`axios.get`, `axios.put`, etc)?

**Comment by ericwooley** [comment]
@mzabriskie Sorry I should have updated this issue.

My project is using the https://github.com/davezuko/react-redux-starter-kit, which included TechnologyAdvice/flow-interfaces automatically. Which is where flow was getting the information. Once I realized that, I submitted a PR to flow-interfaces, and that should work after their next publish.
