### ISSUE TITLE
axios : Response to preflight request doesn't pass access control.

### ISSUE THREAD

**Issue by 9tor** [mzabriskie/axios#262]
I have an error when executing a get request in a ReactJs app does generate the following
"XMLHttpRequest cannot load http://localhost:3002/api/users. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3005' is therefore not allowed access. The response had HTTP status code 404."

My Code.

const ROOT_URL = 'http://localhost:3002';

const AUTH_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhb..................';

axios.defaults.baseURL = ROOT_URL;
axios.defaults.headers.common['Authorization'] = AUTH_TOKEN;
axios.defaults.headers.post['Content-Type'] = 'application/json;charset=utf-8';

  axios.get('/api/users').then(function(response) {
    console.log(response.data);
    console.log(response.status);
    console.log(response.statusText);
    console.log(response.headers);
    console.log(response.config);
  });

**Comment by NarkLord** [comment]
This isn't an axios issue. You need to set your server to accept CORS requests. Look at the answer to http://stackoverflow.com/questions/20035101/no-access-control-allow-origin-header-is-present-on-the-requested-resource

**Comment by lucashungaro** [comment]
I'm having the same issue when trying to use axios to upload files to S3.

We have a CORS config that works fine with jQuery and xhr, here's the response I get when using curl to simulate a preflight request:

```$ curl -X OPTIONS -sI -H "Origin: http://development.stickermule.com:3000" -H "Access-Control-Request-Method: PUT" https://s3.amazonaws.com/printbear-development
HTTP/1.1 200 OK
x-amz-id-2: /+4+isVJN5R1XmWPrAKZdAVsSOOErUpcF1hs0XfkMOsBEGkeezfEpZVbFOkLgSkFrEmboaKwhM4=
x-amz-request-id: 66C6CB89813890FD
Date: Mon, 14 Mar 2016 19:59:54 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: PUT
Access-Control-Expose-Headers: Accept-Ranges, Content-Range, Content-Encoding, Content-Length, ETag
Access-Control-Max-Age: 3
Vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
Content-Length: 0
Server: AmazonS3```

But when I try to use axios, I get: 

```Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://development.stickermule.com:3000' is therefore not allowed access.```

Here's the Network tab from Chrome: http://cl.ly/1e100v3S1u22

So, I get a 200, but no headers besides x-amz-* stuff.

Any pointers?

**Comment by lucashungaro** [comment]
Ok, I have some additional info.

If I call `axios.put(signedS3URL, file)` (pseudo-code), I get that error (no headers on response).

If I call only `axios.put(bucketURL, file)`, the preflight request executes successfully and returns the correct headers, but now obviously I can't upload the file since I don't have the required parameters (signature, policy etc).

I'm looking for ways to "force" axios to ignore the parameters on the preflight request and only include them on the PUT request. Does anyone know a way to achieve this?

Thanks.

**Comment by 9tor** [comment]
Hi,
I've already used it. by fixed at server added 
"routes": {
          "cors": true
  }
at Hapi configuration connection
Thank you.

**Comment by meinou** [comment]
it looks like only node.js developers have this issue. I have perfectly set up cors at my JAVA backend which ALWAYS worked. But not today. Continue receive this stupid error, have no clue how to fix.

**Comment by PedroHFranco** [comment]
Hi @9tor have u resolve this problem?
