### ISSUE TITLE
Interceptors - how to prevent intercepted messages from resolving as error

### ISSUE THREAD

**Issue by dmt0** [mzabriskie/axios#266]
I'm trying to make an interceptor for 401 responses that result from expired token. Upon interception I want to login and retry the requests with the new token. My problem is that login is also done asynchronously, so by the time the retry happens, the original promises reject. Is there a way around that? Here's my code:

    axios.interceptors.response.use(undefined, err => {
      if (err.status === 401 && err.config && !err.config.__isRetryRequest) {
        refreshLogin(getRefreshToken(),
          success => {
            setTokens(success.access_token, success.refresh_token)
            err.config.__isRetryRequest = true
            err.config.headers.Authorization = 'Bearer ' + getAccessToken()
            axios(err.config)
          },
          error => { console.log('Refresh login error: ', error) }
        )
      }
    })

**Comment by mzabriskie** [comment]
Sorry for the delay, I am just seeing this issue.

You need to make a return statement from your interceptor which will keep the Promise alive. More or less change your `refreshLogin` to return a Promise and then return that from your interceptor.

Or if you can't refactor `refreshLogin` you can wrap it in a Promise.


```js
axios.interceptors.response.use(undefined, err => {
  let res = err.response;
  if (res.status === 401 && res.config && !res.config.__isRetryRequest) {
    return new Promise((resolve, reject) => {
      refreshLogin(getRefreshToken(),
        success => {
          setTokens(success.access_token, success.refresh_token)
          err.config.__isRetryRequest = true
          err.config.headers.Authorization = 'Bearer ' + getAccessToken()
          resolve(axios(err.config))
        },
        error => {
          console.log('Refresh login error: ', error)
          reject(error)
        }
      )
    });
  }
})
```

**Comment by dmt0** [comment]
Nope, doesn't do it.

The line "let res = err.response" doesn't work - there's no response in err. 

If I leave it out, than the success gets triggered - so login happens, but the original request doesn't get retried.

**Comment by mzabriskie** [comment]
What version of axios are you using?

**Comment by dmt0** [comment]
0.12.0

**Comment by dmt0** [comment]
That was with 0.12.0.
Now that I updated to 0.13.1, `err` has become a string with call stack.

**Comment by heeton** [comment]
@dmt0 Did you get this working?

**Comment by dmt0** [comment]
@heeton Nope, been busy with other things. Will keep you posted...

**Comment by geocine** [comment]
You could do something like this:

```js
axios.interceptors.response.use(function (response) {
  return response;
}, function (error) {

  const originalRequest = error.config;

  if (error.status === 401 && !originalRequest._retry) {

    originalRequest._retry = true;

    const refreshToken = window.localStorage.getItem('refreshToken');
    return axios.post('http://localhost:8000/auth/refresh', { refreshToken })
      .then(({data}) => {
        window.localStorage.setItem('token', data.token);
        window.localStorage.setItem('refreshToken', data.refreshToken);
        axios.defaults.headers.common['Authorization'] = 'Bearer ' + data.token;
        originalRequest.headers['Authorization'] = 'Bearer ' + data.token;
        return axios(originalRequest);
      });
  }

  return Promise.reject(error);
});
```

**Comment by BrunoQuaresma** [comment]
Here, error.response return undefined in 0.14.0 version.

**Comment by geocine** [comment]
may you try `error.status` please

**Comment by BrunoQuaresma** [comment]
```
axios.interceptors.response.use(undefined, error => {
      console.log(error.status)
      return Promise.reject(error)
    })
```

The console.log returns undefined.

**Comment by geocine** [comment]
I am pretty sure it should be `error.response.status` you could check out the error object if it has those properties. I don't know why it doesn't work on your end if you only have that isolated sample code similar to what you have posted above.

**Comment by marines** [comment]
Came here for a solution to that. In my case `error` is a strong and has no properties of course. However the string is exact Bluebird's error message so perhaps it just doesn't let Axios handle the error and just throws it.

**Comment by marines** [comment]
Same happens for me. The `error` is a string with stack trace. I'm using Bluebird as a polyfill. The stack trace is exactly the same as Bluebird's so I assume it catches the error before Axios can. Can we do anything about it?

**Comment by sripri** [comment]
Is this issue resolved?  I am using 0.15.2 and running into this weird problem

**Comment by Calvin92** [comment]
@dmt0 The same with you...   I am using 0.15.2 ... So, which version is okay for this ?

**Comment by rlambertsen** [comment]
I used @geocine example from Oct, 5th 2016. I am using `Vue.js 2.0` my solution was to watch the token for changes in the `Vuex` if it changed then to update anything that changed. I.E. if someone wanted to like a post but the JWT was expired, it intercepts the request and runs it again once the JWT has been refreshed.

**Comment by vijaythecoder** [comment]
is this solved yet? there is no `response` in error. it gives undefined. I want to check if the status is `401` and then redirect to login.

**Comment by ametad** [comment]
In the response interceptor rejection function, the ```error.response.status``` is returned correctly in the latest version (0.15.3).

**Comment by muhammadaser** [comment]
is this solved ? im using version 0.15.3 but `error.response` is `undefined`. i try to handle 401 error.
btw im using "Custom instance"

**Comment by rmoskal** [comment]
I was able to adapt @rlambertsen example.  Worked fine.

**Comment by dennis2k** [comment]
This is also an issue for me - v.0.15.3 - the response is just a callstack error string

**Comment by Toilal** [comment]
it works here, i'm running axios v0.16.1.

The only thing to note is that if you use baseURL in your configuration, you have to remove it from the error.config object before retrying the request with the new JWT token.

```javascript
this.responseInterceptor = this.axios.interceptors.response.use((response) => response, (error) => {
  let value = error.response;

  if (value.status === 401 && value.data.message === 'Expired JWT Token'
    && (!value.config || !value.config.renewToken)) {
    console.log('Token JWT expiré. Reconnexion ...');

    // renewToken performs authentication using username/password saved in sessionStorage/localStorage
    return this.renewToken().then(() => {
      error.config.baseURL = undefined; // baseURL is already present in url
      return this.axios.request(error.config);
    }).then((response) => {
      console.log('Reconnecté !');
      return response;
    });

  } else if (value.status === 401 && value.config && value.config.renewToken) {
    console.log('Echec de la reconnexion !');

    if (error.message) {
      error.message = 'Echec de la reconnexion ! ' + error.message + '.';
    } else {
      error.message = 'Echec de la reconnexion !';
    }

  } else if (value.status === 401) {
    console.log('Accès refusé.');
    // TODO: We could ask for username/password in a modal dialog...
  }

  return Promise.reject(error);
});
```

**Comment by vijaythecoder** [comment]
I looking for solution for the past 3 to 4 months on this and still nothing worked. I am using Laravel to return the error and browser is able to identify the **401 (Unauthorized)** but no help with axios. 
@Toilal I am trying for hours to fix this every time I see a comment which could help but no luck, today I tried again with `"axios": "^0.16.1"`  no luck. Can someone please help on this? there are lot of people who need help with this. 

The below code consoles `Undefined`. Simple the error doesn't have a response, no matter how you to try 

```javascript
axios.interceptors.response.use((response) => response, (error) => {
    let value = error.response
    console.log(value)
})
```

**Comment by Toilal** [comment]
Can you `console.log(error)` ? Maybe it's an internal error and fails before a response is actually read ?

**Comment by Toilal** [comment]
Can you `console.log(error)` ? Maybe it's an internal error and fails before a response is actually read ?

**Comment by Toilal** [comment]
Maybe Laravel (or something else) intercept the error before axios, and reject the promise with another data type ? I'm using axios in a VueJS app, it's currently a tiny app as it's a new project.

Try to find out if you have another axios interceptor running before this one ?

**Comment by vijaythecoder** [comment]
Its a string 
console.log(error)
```
Error: Network Error
    at createError (eval at <anonymous> (app.js:1611), <anonymous>:15:15)
    at XMLHttpRequest.handleError (eval at <anonymous> (app.js:1590), <anonymous>:87:14)
```

This is when I console `error.config`
![image](https://cloud.githubusercontent.com/assets/1809727/24918340/ae5fd5a8-1efd-11e7-93ab-a3bcd5240f6c.png)

**Comment by vijaythecoder** [comment]
Yes I am using the axios with Vuejs App, This is how I did 

```javascript
/* global API_URL */
window.axios = require('axios').create({
  baseURL: API_URL,
  timeout: false,
  params: {} // do not remove this, its added to add params later in the config
})

// Add a request interceptor
/* global window axios */
axios.interceptors.request.use(function (config) {
  /* global window Store */
  let token = Store.get('jwt.token')
  let location = Store.get('location')

  // console.log(location.id, location)
  if (token) {
    config.headers.common['Authorization'] = 'Bearer ' + token
  }
  // Append location id for every post/get request
  if (location) {
    if (config.data) {
      config.data.location_id = location.id
    }
    else if (config.params) {
      config.params.location_id = location.id
    }
  }

  return config
}, function (error) {
  // Do something with request error
  return Promise.reject(error)
})

axios.interceptors.response.use((response) => response, (error) => {
    console.log(error.config)
})
```

**Comment by vijaythecoder** [comment]
@Toilal I figured out the problem and not sure what could be the fix. If I remove
`axios.interceptors.request` part, it works great.  Should we use both request and response in same call ? if yes do you know a work around ?

**Comment by Toilal** [comment]
I use both and it works. Do you return the right objects in your request
interceptor promise ?

**Comment by vijaythecoder** [comment]
I solved it, the 401 doesn't have `cors`. If any one using Laravel with Laravel Cors Package then here is the solution and you will have `error.response` available

**Comment by felixbuenemann** [comment]
I had the problem, that `error` was `undefined` in a *response* interceptor and it was caused by not resolving the promise for `config` in a token refresh *request* interceptor, if the token refresh failed.

**Faulty code in request interceptor:**
```javascript
axios.interceptors.request.use(config => this.dispatch('refreshAuthToken').then(() => {
  // do stuff to set Authorization header
  return Promise.resolve(config);
}))
```

**Fixed code:**
```javascript
axios.interceptors.request.use(config => this.dispatch('refreshAuthToken').then(() => {
  // do stuff to set Authorization header
  return Promise.resolve(config);
// ensure we resolve config in error case
}), () => Promise.resolve(config));
```

**Comment by Jenan** [comment]
Based on this sample: https://github.com/axios/axios/issues/450#issuecomment-247446276

I have used this version for refreshing token - as is described on post above. This interceptor is created for prevent refresh token repeatly if it is created more request and you probable want to call this operation only once.

This is typescript version but I think it is very similiar to js version.
```ts
export default class AuthorizationHelper {

	authTokenRequest: Promise<any>;

	getNewAccessToken() {

		const refreshToken = window.localStorage.getItem("refreshToken");

		if (!this.authTokenRequest) {
			this.authTokenRequest = this.refreshToken(refreshToken);
			this.authTokenRequest.then(response => {
				this.resetGetAccessTokenRequest();
			}).catch(error => {
				this.resetGetAccessTokenRequest();
			});
		}

		return this.authTokenRequest;
	}

	resetGetAccessTokenRequest() {
		this.authTokenRequest = null;
	}

	refreshToken(refreshToken: string): Promise<any> {

		return axios.post('/api/token/refresh',
			{
				refreshToken: refreshToken
			});
	}

	registerAxiosInterceptor() {
		axios.interceptors.response.use((response) => {
			return response;
		}, err => {
			const error = err.response;

			if (error.status === 401 && error.config && !error.config.__isRetryRequest) {

				return this.getNewAccessToken().then(response => {
					error.config.__isRetryRequest = true;

					//set new access token after refreshing it
					axios.defaults.headers.common["Authorization"] = `Bearer ${response.access_token}`;
					error.config.headers["Authorization"] = `Bearer ${response.access_token}`;

					return axios(error.config);
				}).catch(error => {

					//refreshing has failed => redirect to login
					//clear cookie (with logout action) and return to identityserver to new login
					//(window as any).location = "/account/logout";

					return Promise.reject(error);
				});
			}

			return Promise.reject(error);
		});
	}
}
```

**Comment by Godofbrowser** [comment]
```javascript
// for multiple parallel requests
let isRefreshing = false;
let failedQueue = [];

const processQueue = (error, token = null) => {
  failedQueue.forEach(prom => {
    if (error) {
      prom.reject(error);
    } else {
      prom.resolve(token);
    }
  })
  
  failedQueue = [];
}

axios.interceptors.response.use(function (response) {
  return response;
}, function (error) {

  const originalRequest = error.config;

  if (error.response.status === 401 && !originalRequest._retry) {
      
      if (isRefreshing) {
        return new Promise(function(resolve, reject) {
          failedQueue.push({resolve, reject})
        }).then(token => {
          originalRequest.headers['Authorization'] = 'Bearer ' + token;
          return axios(originalRequest);
        }).catch(err => {
          return err
        })
      }

    originalRequest._retry = true;
    isRefreshing = true;

    const refreshToken = window.localStorage.getItem('refreshToken');
    return new Promise(function (resolve, reject) {
       axios.post('http://localhost:8000/auth/refresh', { refreshToken })
        .then(({data}) => {
            window.localStorage.setItem('token', data.token);
            window.localStorage.setItem('refreshToken', data.refreshToken);
            axios.defaults.headers.common['Authorization'] = 'Bearer ' + data.token;
            originalRequest.headers['Authorization'] = 'Bearer ' + data.token;
            processQueue(data.token);
            resolve(axios(originalRequest));
        })
        .catch((err) => {
            processQueue(null);
            reject(err);
        })
        .then(() => { isRefreshing = false })
    })
  }

  return Promise.reject(error);
});
```

**Comment by felix2056** [comment]
What you see in Axios version 0.13.* error response the string returned by the toString method of the error object.

In the newer versions, If a response has been received from the server, the error object will contain the response property:
So you can do something like:

`if (error.response) {
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } `
