### ISSUE TITLE
Ability to mocking/stub/fake responses?

### ISSUE THREAD

**Issue by BigstickCarpet** [mzabriskie/axios#269]
This has been [asked before](https://github.com/mzabriskie/axios/issues/40), and was originally planned to be included in v0.6.0, but never made it.

@aeirola posted a [workaround to enable mocking a response](https://github.com/mzabriskie/axios/issues/40#issuecomment-170529539), but it's a bit hacky.  It would be great if there was an easy, officially-supported way to do mocking in Axios.

**Comment by aeirola** [comment]
Axios supports custom adapters since 0.9.0, which can be used for testing. See commit https://github.com/mzabriskie/axios/commit/b9bb6ae7aacc7ec6053ae0551be7a403a33a5b18.

**Comment by ctimmerm** [comment]
I made this to enable easy mocking of requests made through axios, I thought it could be useful for others: https://www.npmjs.com/package/axios-mock-adapter

**Comment by nickuraltsev** [comment]
Thank you all! I am going to create a document that contains a list of `axios` related libraries and include `axios-mock-adapter` in that list.
