### ISSUE TITLE
Problem with basic auth on GET request

### ISSUE THREAD

**Issue by gveraa** [mzabriskie/axios#270]
Hi,
i am trying to do a GET request with basic auth, but the auth header are not send.

Here is the code:

`
axios.get(
	'api/example',
	{
		headers: { 'Accept': 'application/json' },
		auth: {
			username: 'example',
			password: 'passwdexample'
		},
		params: { sinceDays: 7 }
	}
`

[Image of header sent](https://www.ladochile.cl/tmp/request.jpg)

Thanks

**Comment by batjko** [comment]
Since you closed this yourself, can you mention what solved the problem for you?
