### ISSUE TITLE
Upload progress.

### ISSUE THREAD

**Issue by h3xed** [mzabriskie/axios#278]
Is any way to get progress status for file upload request?

In readme is progress configuration option but it not fire given function.

Update:
progress callback work correctly on master branch but not on current tag (0.9.1), it will be released in 1.0.0.

**Comment by xixilive** [comment]
:+1:

**Comment by bojueWjt** [comment]
useful

**Comment by theguxi** [comment]
+1

**Comment by eckenroed** [comment]
+1
