### ISSUE TITLE
Cannot pass data to GET request

### ISSUE THREAD

**Issue by alvinj01** [mzabriskie/axios#281]
Is there a way to pass a non-stringified data object to the GET request equivalent to the following?
```
$.ajax({
  url: SOME_URL
  type: "GET"
  data: {
    nested_data: {
      num1: 1,
      num2: 2,
    }
  }
});
```

With `axios` GET request, i can get the equivalent, but the nested_data is stringified.
```
axios({
  method: 'GET',
  url: "'',
  params: {
    nested_data: {
      num1: 1,
      num2: 2
    }
  }
});
```

**Comment by nickuraltsev** [comment]
Thank you for your question! This is not currently supported, but you can override the default behavior by using the `paramsSerializer` parameter:

```js
axios.defaults.paramsSerializer = function(params) {
  // You can use other libraries like `qs` to stringify params:
  return qs.stringify(params);
};
```

Hope this helps!

**Comment by Schlogen** [comment]
How is this not supported? Seems like a very basic thing to do
