### ISSUE TITLE
Client certificate 

### ISSUE THREAD

**Issue by corporatepiyush** [mzabriskie/axios#284]
I am using axios on node.js 4.2.x. how do i mention SSL CA certificate for connecting to one of the secured services ?

Can anybody point me to an example working code ?

**Comment by nickuraltsev** [comment]
You should be able to use a custom `Agent` as follows:

```js

var agent = new https.Agent({ 
  ca: fs.readFileSync('ca.pem') 
});

axios.get(url, { agent: agent });

// or 

var instance = axios.create({ agent: agent });
instance.get(url);
```

Hope it helps!

**Comment by corporatepiyush** [comment]
In my case, its a `.crt` file which has bunch of certificates in it from Godaddy.
when  i try to do follow the example code @nickuraltsev  mentioned, i get following error. 

`{ [Error: unable to get local issuer certificate] code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }`

**Comment by nickuraltsev** [comment]
axios uses `https` module under the hood. All certificate related config parameters are passed to `https`. You can even configure `https` directly:

```js
https.globalAgent.options.ca = fs.readFileSync('ca.pem'); // Note: this is a global setting
```

If you need help with using an SSL certificate with `https` module, please ask a question on StackOverflow.

**Comment by voraparth91** [comment]
I am trying to run this project in browser. I cannot find https module available. Can you tell me how this was made possible?

**Comment by nickuraltsev** [comment]
@voraparth91 You can configure axios to use specific certificates in Node.js, but not in browsers.

**Comment by voraparth91** [comment]
@nickuraltsev Is there any other way you can suggest me where I can configure specific certificates in browser for XHR requests?

**Comment by zatziky** [comment]
Careful, the correct way to assign `agent` is by using the field `httpsAgent`.

'''
const instance = axios.create({ httpsAgent: agent });
'''

**Comment by alterhu2020** [comment]
Try below code  worked ,thanks team.
```
const Agent = new https.Agent({
  rejectUnauthorized: false
})
const instance = axios.create()
instance.defaults.baseURL = `http://${process.env.HOST || 'localhost'}:${process.env.PORT || 3000}`
instance.defaults.httpsAgent = Agent
instance.defaults.headers.common['Authorization'] = 'Basic YWx0ZXJodTIwMjBAZ21haWwuY29tOmd1Y2hhbjEwMjY='
instance.defaults.timeout = 14500

```

**Comment by bingxiao** [comment]
Not advisable to set`rejectUnauthorized: false`. It puts https connections under threat.

**Comment by LNyears** [comment]
> In my case, its a `.crt` file which has bunch of certificates in it from Godaddy.
> when i try to do follow the example code @nickuraltsev mentioned, i get following error.
> 
> `{ [Error: unable to get local issuer certificate] code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }`



> In my case, its a `.crt` file which has bunch of certificates in it from Godaddy.
> when i try to do follow the example code @nickuraltsev mentioned, i get following error.
> 
> `{ [Error: unable to get local issuer certificate] code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }`

I also encountered this problem, can you tell me how you solved it?
