### ISSUE TITLE
Getting "(0 , _request2.default) is not a function" after setting defaults

### ISSUE THREAD

**Issue by rasmuswoelk** [mzabriskie/axios#286]
After setting defaults like this:

     axios.defaults.headers.post['X-XSRF-TOKEN'] = App.token;
     axios.defaults.xsrfHeaderName = NULL;

Or 

        var instance = axios.create({
          headers: {'X-XSRF-TOKEN': App.token},
          xsrfHeaderName: null
        });

I get the following error on SOME requests:

    react.js:48246 Uncaught TypeError: (0 , _request2.default) is not a function

![image](https://cloud.githubusercontent.com/assets/640976/14280036/8925a34a-fb30-11e5-89e9-3873877973e8.png)

I don't know if I am doing anything wrong, but this seems strange, since some requests works.

This way of defining a request fails with above error:

				return axios({
							method: 'post',
							url: API.USER.LOGIN,
							data: querystring.stringify(credentials)
						})

Where as this succeeds:

    axios.post(API.USER.UPDATE + userData.id, userData)

**Comment by johndvorakHR** [comment]
? I am currently facing this same problem.

**Comment by rasmuswoelk** [comment]
@johndvorakHR  My problem was that I was setting `axios.defaults.xsrfHeaderName` to `null` which IE didn't like. I renamed it to a random string instead and it worked :-)
