### ISSUE TITLE
Document agent and proxy options

### ISSUE THREAD

**Issue by nickuraltsev** [mzabriskie/axios#292]
* `agent` option was added by #102
* `proxy` option was added by #133

**Comment by rubennorte** [comment]
Maybe you should take a look to https://github.com/mzabriskie/axios/issues/370 before documenting the `agent` option publicly.

**Comment by rubennorte** [comment]
`httpAgent` and `httpsAgent` are already documented ;)

**Comment by nickuraltsev** [comment]
Yeah. #366 documents the `proxy` option but it has not been merged yet (waiting for the author to fix an issue).
