### ISSUE TITLE
How can i get set-cookie header ?

### ISSUE THREAD

**Issue by YukSeungChan** [mzabriskie/axios#295]
Hello.

"Set-Cookie" header exist in HTTP response header. But axios response didn't have "set-cookie" header.

Response header have only "content-type".

How can i get "set-cookie" header ?

**Comment by zsajjad** [comment]
u found the solution?

**Comment by machineghost** [comment]
There is in fact a `response.headers['set-cookie']` (I'm guessing that this was the solution found).

**Comment by rmartins90** [comment]
Can't find it too. Does anyone have any hint on this?

**Comment by ViswanathLekshmanan** [comment]
Any update ?

**Comment by MuraraAllan** [comment]
there is a "set-cookies" in response headers.

**Comment by sunnynegi** [comment]
Same problem unable to get set cookies from the header also try with withcredential : true. Any help on this

**Comment by ankitsinghaniyaz** [comment]
I'm also facing this. The cookie is there on the network tab, but nothing inside the response from axios.

**Comment by sunnynegi** [comment]
ankitsinghaniyaz Use withCredentials: true, in axiios they will help.
`method: 'GET',
      url: BACKEND_URL+'/notification/new/?pageNum='+pageNum+'&pageSize='+resultSize,
      withCredentials: true,
      headers : {'Content-Type': 'application/x-www-form-urlencoded'}`
This one work for me.

**Comment by ankitsinghaniyaz** [comment]
So I had some gaps in my knowledge regarding how cookies work. Putting it here so that someone else can benefit from this.

1. HTTP ONLY (Secure) cookies cannot be accessed in JavaScript. If you try to read some token, etc from a secure cookie it's not going to work.
2. Cross-domain cookies cannot be accessed. In case you are building a single page application and your server is on a different domain. You cannot access the cookies from another domain on another domain where you are using this. `withCredentails` flag will just make sure that the network calls made include the cookies and accept any incoming cookies.

I hope this will help someone. :)

**Comment by gil-air-may** [comment]
> So I had some gaps in my knowledge regarding how cookies work. Putting it here so that others can benefit from this.
> 
> 1. HTTP ONLY (Secure) cookies cannot be accessed in JavaScript. If you try to read some token, etc from a secure cookie it's not going to work.
> 2. Cross-domain cookies cannot be accessed. In case you are building a single page application and your server is on a different domain. You cannot access the cookies on your SPA. The `withCredentials` flag will just make sure that the network calls made include the cookies and accept any incoming cookies.
> 
> I hope this will help someone. :)

This saved me a lot of time. Thank you !

**Comment by enBonnet** [comment]
Look this master https://stackoverflow.com/questions/53898031/how-to-set-cookies-express-react-js/55804086#55804086

**Comment by asmakhalfallah2018** [comment]
Did you find solution to get the value of set-cookie please ? adding withCredentials: true doesn't fix the issue

**Comment by enBonnet** [comment]
Hey @asmakhalfallah2018 look at this https://stackoverflow.com/questions/53898031/how-to-set-cookies-express-react-js/55804086#55804086

**Comment by lromor** [comment]
@ankitsinghaniyaz That answer is only true if considering the usage of axios inside a browser.
There are many applications where axios is used in a server context to do SSR.

**Comment by rohanshar** [comment]
Did anyone here find a solution ? None of the above solutions are solving it when axios is running on the server.
