### ISSUE TITLE
Problems with axios on Windows (IE 11)

### ISSUE THREAD

**Issue by rasmuswoelk** [mzabriskie/axios#297]
Hi

I'm trying to figure out why axios isn't working on Windows (Internet Explorer 11).

When I try to make a post or get request it sends the data just fine but returns an syntax error in .catch():

```

My call:

axios.post(API_URL, {
    some: data
}).then(function(response) {
    console.log('Yaaaay:', response);
}).catch(function(response) {
    console.log('Noooo :(', response)
});

The response in catch():

{   [functions]: ,   __proto__: { },   
      ABORT_ERR: 20,   
      code: 12,  
      constructor: { },   
      DATA_CLONE_ERR: 25,   
      DOMSTRING_SIZE_ERR: 2,   
      HIERARCHY_REQUEST_ERR: 3,   
      INDEX_SIZE_ERR: 1,   
      INUSE_ATTRIBUTE_ERR: 10,   
      INVALID_ACCESS_ERR: 15,   
      INVALID_CHARACTER_ERR: 5,   
      INVALID_MODIFICATION_ERR: 13,   
      INVALID_NODE_TYPE_ERR: 24,   
      INVALID_STATE_ERR: 11,   
      message: "SyntaxError",   
      name: "SyntaxError",   
      NAMESPACE_ERR: 14,   
      NETWORK_ERR: 19,   
      NO_DATA_ALLOWED_ERR: 6,   
      NO_MODIFICATION_ALLOWED_ERR: 7,   
      NOT_FOUND_ERR: 8,   
      NOT_SUPPORTED_ERR: 9,   
      PARSE_ERR: 81,   
      QUOTA_EXCEEDED_ERR: 22,   
      SECURITY_ERR: 18,   
      SERIALIZE_ERR: 82,   
      SYNTAX_ERR: 12,   
      TIMEOUT_ERR: 23,   
      TYPE_MISMATCH_ERR: 17,   
      URL_MISMATCH_ERR: 21,   
      VALIDATION_ERR: 16,   
      WRONG_DOCUMENT_ERR: 4
   }

```
I'm not sure what to read of this.

The code **works perfect** in all other browsers on Windows/Mac.

I thought it might be a polyfill problem, so I included the [es6-polyfill](https://github.com/stefanpenner/es6-promise) to my bundle but still no success.

Any suggestions?

Thanks!

**Comment by nickuraltsev** [comment]
Maybe if the `data` parameter is not specified, axios fails in IE 11. (If so, this is a bug that needs to be fixed.) Could you please try to make a request with some data? 

```js
axios.post(API_URL, {})
```

**Comment by rasmuswoelk** [comment]
@nickuraltsev Good point. Actually I am sending data with my post requests - I just forgot to add it to the example here. I have now added it.

I am having problems with get requests as well.

**Comment by rasmuswoelk** [comment]
I have now tested the same code with ajax $.get instead of axios and then it works fine. So the problem should be narrowed down to some compabillity problem with axios I guess?

**Comment by rasmuswoelk** [comment]
Update: I have now tried to use the [fetch](https://github.com/github/fetch) library and this works fine. All of my code is tied up to axios so I would like to be able to use this instead though 👍 

Any suggestions?

**Comment by nickuraltsev** [comment]
@rasmuswoelk Could you please provide a code snippet that reproduces the problem?

**Comment by rasmuswoelk** [comment]
@nickuraltsev I have now tried to reproduce the problem by creating an isolated piece of code and then it worked just fine. 

Kinda frustrated a looked through my own code and since IE didn't provide me with a very useful error code, I had to uncomment stuff until I narrowed down the root of the problem.

**What I found out was this:**

I have created a small module that I use in my project called request.js. All it really does is take an instance of axios, add some defaults and then export it.

It _looked_ like this:

`import axios from 'axios';

axios.defaults.headers.post['X-XSRF-TOKEN'] = Athliit.token;
axios.defaults.xsrfHeaderName = null;

export default axios;`

The reason why I am overwritting the "xsrflHeaderName" is that in my project I supply my own token and therefore had to deactivate the default token. I did this by making it `null` and this apparently caused an error in IE.

Instead I just renamed it to some random string: 

`axios.defaults.xsrfHeaderName = 'xsrf_default_overwritten';`

**And then it worked! **

So the problem wasn't directly caused by axios but the reason I had to overwrite it was (as mentioned earlier) that axios suplies it's own token and I needed to use my own like this:

`axios.defaults.headers.post['X-XSRF-TOKEN'] = App.token;`

Now, I am not aware of any obvious solutions to this problem already provided by axios, so please refer me if so. 

If not; maybe the default token should be overwritten when I set my own custom token under the same name.

Thanks for a good library though and I am just glad that I found the bug so I can continue using it :-) 👍

**Comment by shyamchandranmec** [comment]
@nickuraltsev 
 I am facing the same issue in IE edge. Its not even firing the request. The response which I get is same as what @rasmuswoelk  posted. I am following the same approach by creating a module and making a generic instance of axios. It works in other browsers like chrome and firefox and safari. 
Here is the code which I am using:

 var req = axios.create({
        baseURL: config.fullURL,
        timeout: 1000000000000000000000,
    })
req.defaults.headers.common['Authorization'] =  'JWT ' + token;

Any help would be of great help.

**Comment by shyamchandranmec** [comment]
@nickuraltsev 
I have opened a new issue. Here is the link : https://github.com/mzabriskie/axios/issues/486

**Comment by anhvoduy** [comment]
at Client Side, can set headers for request:
        axios.defaults.headers.get['Pragma'] = 'no-cache';
        axios.defaults.headers.get['Cache-Control'] = 'no-cache, no-store';
at Server Site, set headers for response:
        https://www.npmjs.com/package/nocache

**Comment by ralphtheninja** [comment]
> at Client Side, can set headers for request:
> - axios.defaults.headers.get['Pragma'] = 'no-cache';
> - axios.defaults.headers.get['Cache-Control'] = 'no-cache, no-store';

Disabling cache on the client side was enough to fix my problems. @anhvoduy Thanks!
