### ISSUE TITLE
Client side support for protecting against XSRF

### ISSUE THREAD

**Issue by js08** [mzabriskie/axios#298]
hi,

- i am new to js.
- i am trying to learn how you guys implemented,  the Promise API and Client side support for protecting against XSRF
- can you tell me which files I need to look for in axios to get those codes

**Comment by mzabriskie** [comment]
XSRF protection is done with this code https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L107-L121

**Comment by js08** [comment]
@mzabriskie hey I went through the code but not sure how you guys implemented...any documentation will help us in understanding the implementation...

**Comment by js08** [comment]
@mzabriskie can you help me :(
