### ISSUE TITLE
my endpoint isn't receiving the data parameters from a post 

### ISSUE THREAD

**Issue by phantom42** [mzabriskie/axios#304]
I've got an existing form endpoint that works when submitting via a standard ajax/jQuery call, but when I use Axios to post to it, the endpoint is not receiving any of the data from the data attribute.

I am posting to a file on the same server, not a CORS. 

Anything I put in the URL reaches the endpoint as expected.

```
export function selectSubscription(data){
	const url = '/remoting/credits.cfc';
	let params = {};
	const requiredFields = [
		'PRODUCT_PACKAGE_ID', 
		'REPLENISH_PACKAGE_ID', 
		'REPLENISH_THRESHOLD',
		'SCHOOL_SUBSCRIPTION_ID'
	];
	let validFormData = jsonHasFields(data, requiredFields);

	if (!validFormData.success) {
		return {
			type: 'INVALID_FORM',
			keys: validFormData.keys
		}
	}
	params.method = 'selectSubscription';
	for (let i=0; i < requiredFields.length; i++) {
		let key = requiredFields[i];
		params[key] = data[key];
	}

	//const request = axios.post(url, params); 
	const request = axios({
		method: 'post',
		url: url,
		data: params
	})
	//$.post(url, params, function(result){debugger;});
	return {
		type: 'SELECT_SUBSCRIPTION',
		payload: request
	}
}
```

**Comment by nickuraltsev** [comment]
Do you see any outgoing requests in Chrome Dev Tools Network panel?

**Comment by phantom42** [comment]
Yes, I'll get a screenshot in the morning. The response sent back is the error message that the post variables are missing from the data sent.

**Comment by mzabriskie** [comment]
This seems related to #302

**Comment by phantom42** [comment]
@mzabriskie definitely sounds similar. 

Sorry for the delay. Here's some screenshots from my network inspector. I've only called the actioncreator and axios once, but It's sending two POSTS. The second one is getting a 302, but again, if I change this to just a standard jQuery ajax post, everything works fine. 

![axios1](https://cloud.githubusercontent.com/assets/1358377/14854635/7c2e5e18-0c5e-11e6-8f5a-5d77474b4760.PNG)

![axios2](https://cloud.githubusercontent.com/assets/1358377/14854644/80e306fc-0c5e-11e6-82c3-73b15c4825cd.png)

**Comment by nickuraltsev** [comment]
@phantom42 It is possible that the first request was sent via jQuery? The reason why I'm asking this is that jQuery uses x-www-form-urlencoded format by default while axios serializes objects to JSON by default. (This could happen if `$.post(url, params, function(result){ ... })` line was uncommented.)

**Comment by phantom42** [comment]
No, I just added that commented line into the example so I could reference exactly how I have successfully sent the data via jQuery. I've removed it entirely from the code that is running.

**Comment by phantom42** [comment]
If I use the jQuery POST instead, this is what I see in my network tab. Just the one connection is made, and all the data is posted correctly.

![jquerypost](https://cloud.githubusercontent.com/assets/1358377/14859451/30413b4c-0c72-11e6-855e-1d6d5a04186d.png)

**Comment by phantom42** [comment]
Ok, I think the extra post must have had something to do with redux-logger, which I removed yesterday, and now I'm only getting the single post going out, resulting in the 302 and the payload not being submitted properly.

**Comment by nickuraltsev** [comment]
It looks like your endpoint expects data to be in x-www-form-urlencoded format while axios sends data in JSON format by default. axios does not support x-www-form-urlencoded format at the moment (please see #97), but it will soon. Meanwhile, you can do the following:

```js
axios({
  method: 'post',
  url: url,
  data: 'param1=value1&param2=value2' // Note: values need to be properly encoded
})
```

Hope this helps!

**Comment by phantom42** [comment]
Damn. Any expected timeline? We have some forms with too much data for url strings. This should work short-term for my specific problem right now, though.

**Comment by nickuraltsev** [comment]
Your data will not be sent as query string params. It will be sent in the request body. 

As for timeline, I hope we will add support for x-www-form-urlencoded format by the end of next week.

**Comment by phantom42** [comment]
Awesome on both counts. Thanks so much.

**Comment by nickuraltsev** [comment]
axios v0.12.0 supports x-www-form-urlencoded. Please see [this comment](https://github.com/mzabriskie/axios/issues/97#issuecomment-223650368).
