### ISSUE TITLE
Using Axios for integration testing

### ISSUE THREAD

**Issue by jsonmaur** [mzabriskie/axios#309]
First off, thanks for this library--it's really well put together. I've been using it for integration testing with my Node API, and I would love to be able to pass in the `http.Server` of the app rather than manually running a server with an unused port for each test (similar to how [supertest](https://github.com/visionmedia/supertest) works).

Maybe this is something that would be better for a separate library, something like `axios-test`? I have a lot of the code written for creating an instance of axios optimized for testing, I'd be happy to submit a PR if this is something that could be useful for others. I'd also be happy to put together a separate package as well. Let me know what your thoughts are on this.

**Comment by nickuraltsev** [comment]
I think a separate library is the right way to go. I'd be happy to list it on Axios [Ecosystem page](https://github.com/mzabriskie/axios/blob/master/ECOSYSTEM.md). Thank you!
