### ISSUE TITLE
Axios never makes service call, throws no error, just hangs with large payload

### ISSUE THREAD

**Issue by skdavies** [mzabriskie/axios#311]
I've been using Axios for a couple months now without a single problem, its fantastic. Today, I tried to write a service call to post an image using my custom API. I am sending the image data as base64 encoded strings. When I test this with a tiny image, the call works correctly. However, on a bigger image (~3MB), Axios never makes the post call. The code just hangs at the spot where the call should be made. Is there a maximum size on the payload? Why won't this call go through?

Thanks for any help.

**Comment by nickuraltsev** [comment]
Are you sending the data from the browser on Node?

**Comment by skdavies** [comment]
What do you mean by the "browser on Node"?

**Comment by nickuraltsev** [comment]
axios can be used in a browser application (in which case XMLHttpRequest is used under the hood) or on in a Node application running on the server.

**Comment by skdavies** [comment]
I'm using it in a browser app

**Comment by nickuraltsev** [comment]
Could you please check if there are any outgoing requests in Chrome Dev Tools Network panel?

**Comment by skdavies** [comment]
There are 2 requests. The first one is successful but the second with the actual request payload says "with provisional headers shown." Preview and response are unavailable, the request never hits the server, and has no status. I can make the same call successfully using postman.

Thanks very much for the fast response time.

**Comment by nickuraltsev** [comment]
Please take a look at this discussion: http://stackoverflow.com/questions/21177387/caution-provisional-headers-are-shown-in-chrome-debugger . Looks like there are multiple potential reasons why your requests can be blocked.

**Comment by skdavies** [comment]
Using chrome://net-internals, I can see the request is being cancelled. Can't tell why yet, but it doesn't appear to be an issue with axios so I am closing the issue. Thanks for the help.

**Comment by nickuraltsev** [comment]
You are welcome!
