### ISSUE TITLE
`delete` doesn't support payload nor query params

### ISSUE THREAD

**Issue by musbaig** [mzabriskie/axios#312]
Axios doesn't seem to support adding payloads and/or query params to `delete`. Note, I'm referring to using the config object instead of the convenience `delete` method.
In particular, the following does not work, in chrome devtools the request is poorly formed:
```
axios(R.merge({
      method: 'delete',
      url: `/entities/someId`,
      data: payload,
      params: {
        force: true,
      }
    }, axios.config))
```
Any reason why this should be so?

**Comment by nickuraltsev** [comment]
You should not merge your config with axios.config when making a request. Could you please try to use the following?

```javascript
axios({
  method: 'delete',
  url: `/entities/someId`,
  data: payload,
  params: {
    force: true
  }
})
```

**Comment by musbaig** [comment]
Hi there: ah sorry my bad, I should have written `config.axios` not its reverse, where: 
```
config.axios={headers: {
      "X-Requested-With": "XMLHttpRequest",
      "Expires": "-1",
      "Cache-Control": "no-cache,no-store,must-revalidate,max-age=-1,private",
      "Content-Type": "application/json"
    },
    responseType: "json"}
```

**Comment by nickuraltsev** [comment]
Ok, and how does your request look like in Dev Tools?

**Comment by musbaig** [comment]
```
**General:** 
Request URL:http://localhost:3000/api/v1.0/entities/experiment:738c52aa-0280-483b-a9ca-77d9b17bdccc/lock
**Request Headers:**
Provisional headers are shown
Accept:application/json, text/plain, */*
Cache-Control:no-cache,no-store,must-revalidate,max-age=-1,private
Content-Type:application/json
Expires:-1
Origin:http://localhost:3000
Referer:http://localhost:3000/elements/workspace/experiment/experiment:fbd71a4e-6dd7-4cac-8167-0eca47c85cab
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
X-Requested-With:XMLHttpRequest
**Request Payload:**
{lockToken: "12345"}
lockToken: "1234"

**Comment by musbaig** [comment]
Note the request is malformed, the http verb **(Request Method)** is missing.

**Comment by nickuraltsev** [comment]
The message "Provisional headers are shown" indicates that your request has never been sent or the server has never responded. Could you please use chrome://net-internals as suggested [here](http://stackoverflow.com/a/21179105) to see what's going on with the request?

**Comment by musbaig** [comment]
Ok, will try that and let you know, thanks!

**Comment by musbaig** [comment]
Looks like there was an api issue on our side, axios is handling `delete` correctly! Sorry for the confusion, thanks again @nickuraltsev for your help and the pointer above.

**Comment by nickuraltsev** [comment]
You are welcome!
