### ISSUE TITLE
response interceptor should have request infomation

### ISSUE THREAD

**Issue by hcapp01** [mzabriskie/axios#315]
response interceptor should return request information also, so it can do some common action like resend request or logging the request url.

proxy.interceptors.response.use((response) => {
    return response;
}, (error) => {
    // resend error.request
})

**Comment by cludden** [comment]
This would also be useful for global error handling with helpful info
```javascript
axios.interceptors.response.use(function(res) {
    return response;
}, function(err, config} {
    // log all failed/errored requests with their config details
    bugsnag.notify(err, config);
});
```

**Comment by mzabriskie** [comment]
The response includes the original config and request that was made.

```js
axios.interceptors.response.use((response) => {
    return response;
  }, (error) => {
    let response = error.response;
    console.log(response.config);
    console.log(response.request);
  });
```

**Comment by lidianhao123** [comment]
@mzabriskie 
const instance = axios.create({
    baseURL: host,
});

instance.interceptors.response.use((response) => {
    return response;
  }, (error) => {
    let response = error.response;
    console.info(response); // undefined
  });

**Comment by felix9ia** [comment]
(error) =>{
console.info(error.config);
}
