### ISSUE TITLE
Refused to set unsafe header 'Cookie'

### ISSUE THREAD

**Issue by damamsrinivas** [mzabriskie/axios#319]
const request = axios.create({
         baseURL: 'http://www.someurl.com/',
         headers: {
            'Cookie': 'some_string_value'
         }
});

throws an error `Refused to set unsafe header 'Cookie'`

**Comment by nickuraltsev** [comment]
XMLHttpRequest does not allow to set some headers including Cookie. This is described here: https://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader%28%29-method

Hope this helps!

**Comment by kokizzu** [comment]
btw, but this works on server side right?

**Comment by samayo** [comment]
Well this is strange. If I am sending post request to login in to a server via axios, then axios does not let me see the cookie on the body response, so how do we get the cookie? Does anyone know?  Currently I am doing this 

```json
headers: {
  Accept: "application/json",
  Cookie:
   "connect.sid=s%..........g"
},	
```
but this gives me the above error

**Comment by Sergstm** [comment]
headers: {
  Accept: "application/json",
  Cookie:
   "connect.sid=s%..........g"
},

**Comment by joembaya** [comment]
@samayo Your axios header should look like this:

In your Javascript code:
const axiosConfig = {
    headers: {
        'content-Type': 'application/json',
        "Accept": "/",
        "Cache-Control": "no-cache",
        "Cookie": document.cookie
    },
    credentials: "same-origin"
};
        axios.defaults.withCredentials = true;
       axios.get('/url',
        axiosConfig)
        .then((res) => {
             // Some result here
        })
        .catch((err) => {  
            console.log(':(');
        });

I hope it helps...

**Comment by samayo** [comment]
Thanks @joembaya, I have looking for the answer since August 2017 :)

**Comment by duducv** [comment]
thanks @joembaya .. Your answer save me time a lot!!

**Comment by kepikoi** [comment]
Getting this error on node v12.16.1 using axios 0.19.2 in _some_ projects. This is linked to a bug (https://github.com/axios/axios/issues/2731) where axios uses xhr instead of http adapter on node if `XMLHttpRequest` is available in global context (e.g. injected by some other lib):
https://github.com/axios/axios/blob/c120f44d3d29c8e822a92e1d6879b8b77be6b9dc/lib/defaults.js#L16-L26

**Comment by heshamelmasry77** [comment]
so how to test this on localhost very strange

**Comment by joembaya** [comment]
@kepikoi What do you get with following approach, using axios.get ?

const axios = require('axios');

axios.get('https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY')
  .then(response => {
    console.log(response.data.url);
    console.log(response.data.explanation);
  })
  .catch(error => {
    console.log(error);
  });

**Comment by IkennaU** [comment]
Skip to content
 
Search…
All gists
Back to GitHub
@IkennaU 
@IkennaU IkennaU/gist:8a8b7514005c5a05b6b0e43c5039192d
Created 23 hours ago
0
 Code Revisions 2
<script src="https://gist.github.com/IkennaU/8a8b7514005c5a05b6b0e43c5039192d.js"></script>
  
AXIOS: DELETE METHOD NOT WORKING
 gistfile1.txt
THE DELETE RETURNS WITH 404 NOT FOUND, I DO NOT UNDERSTAND WHY, PLS HELP.
xhr.js:178 DELETE http://localhost:3000/api/posts/5e9340c167721b0ae410ad39 404 (Not Found

class PostItem extends Component {
  onDeleteClick(id) {
    this.props.deletePost(id);
  }
  onLikeClick(id) {
    this.props.addLike(id);
  }
  onUnlikeClick(id) {
    this.props.removeLike(id);
  }
  findUserLike(likes) {
    const { auth } = this.props;
    if (likes.filter((like) => like.user === auth.user.id).length > 0) {
      return true;
    } else {
      return false;
    }
  }
  render() {
    const { post, auth, showActions } = this.props;
    return (
      <div className="card card-body mb-3">
        <div className="row">
          <div className="col-md-2">
            <Link to="/profile">
              <img
                className="rounded-circle d-none d-md-block"
                src={post.avatar}
                alt=""
              />
            </Link>
            <br />
            <p className="text-center">{post.name}</p>
          </div>
          <div className="col-md-10">
            <p className="lead">{post.text}</p>
            {showActions ? (
              <span>
                <button
                  onClick={this.onLikeClick.bind(this, post._id)}
                  type="button"
                  className="btn btn-light mr-1"
                >
                  <i
                    className={classnames("fas fa-thumbs-up", {
                      "text-info": this.findUserLike(post.likes),
                    })}
                  />
                  <span className="badge badge-light">{post.likes.length}</span>
                </button>
                <button
                  onClick={this.onUnlikeClick.bind(this, post._id)}
                  type="button"
                  className="btn btn-light mr-1"
                >
                  <i className="text-secondary fas fa-thumbs-down" />
                </button>
                <Link to={`/post/${post._id}`} className="btn btn-info mr-1">
                  Comments
                </Link>
                {post.user === auth.user.id ? (
                  <button
                    onClick={this.onDeleteClick.bind(this, post._id)}
                    type="button"
                    className="btn btn-danger mr-1"
                  >
                    <i className="fas fa-times" />
                  </button>
                ) : null}
              </span>
            ) : null}
          </div>
        </div>
      </div>
    );
  }
}
PostItem.defaultProps = { showActions: true };
PostItem.propTypes = {
  deletePost: PropTypes.func.isRequired,
  addLike: PropTypes.func.isRequired,
  removeLike: PropTypes.func.isRequired,
  post: PropTypes.object.isRequired,
  auth: PropTypes.object.isRequired,
};
const mapStateToProps = (state) => ({ auth: state.auth });

export default connect(mapStateToProps, { deletePost, addLike, removeLike })(
  PostItem
);
DELETE ACTIONS....BELOW

// Delete Post
export const deletePost = (id) => (dispatch) => {
  axios
    .delete(`/api/posts/${id}`)
    .then((res) => dispatch({ type: DELETE_POST, payload: id }))
    .catch((err) => dispatch({ type: GET_ERRORS, payload: err.response.data }));
};
ROUTER PATH...
router.delete(
  "/:id",
  passport.authenticate("jwt", { session: false }),
  (req, res) => {
    Profile.findOne({ user: req.user.id })
      .then((profile) => {
        Post.findById(req.params.id);
      })
      .then((post) => {
        if (post.user.toString() !== req.user.id) {
          return res
            .status(401)
            .json({ notAuthorised: "User Not Authorised..." });
        }
        post.remove().then(() => res.json({ success: true }));
      })
      .catch((err) => res.status(404).json({ Post: "No Post Found" }));
  }
);
 MY REDUCERS
import {
  ADD_POST,
  GET_POSTS,
  GET_POST,
  DELETE_POST,
  POST_LOADING,
} from "../actions/types";

const initialState = { posts: [], post: [], loading: false };

export default function (state = initialState, action) {
  switch (action.type) {
    case POST_LOADING:
      return { ...state, loading: true };
    case GET_POSTS:
      return { ...state, posts: action.payload, loading: false };
    case GET_POST:
      return { ...state, post: action.payload, loading: false };
    case ADD_POST:
      return { ...state, posts: [action.payload, ...state.posts] };
    case DELETE_POST:
      return {
        ...state,
        posts: state.posts.filter((post) => post._id !== action.payload),
      };
    default:
      return state;
  }
}

**Comment by kepikoi** [comment]
> so how to test this on localhost very strange

I've created a repro here https://github.com/kepikoi/axios-repro-319-2731
