### ISSUE TITLE
[Question] Can only add one custom header?

### ISSUE THREAD

**Issue by liukan0211** [mzabriskie/axios#322]
var baseConfig = {
			baseURL: 'xxxx',
			headers: {
				'Origin': '*',
				'access_token': 'xxxx',
			}
		};
axiosInstance = axios.create(baseConfig);

I added two custom headers, captured the request by Fiddler, only the "Origin" header in request header, but "access_token" is in Access-Control-Request-Headers: accept, access_token, and got error from server showed that "The collection of headers 'accept,access_token' is not allowed".
Does Axios only support to add one custom header?

**Comment by nickuraltsev** [comment]
Axios allows you to add as many custom headers as you need. When a cross-origin request is made with custom headers, the client will send the so-called preflight request (with the `OPTIONS` method) first. You should see it in Fiddler. The server needs to respond with `Access-Control-Allow-Headers` that lists your custom headers:

```
Access-Control-Allow-Headers: access_token, <other custom headers>
``` 

The client will then make the actual request.

This is explained in great detail here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Hope this helps!

**Comment by davidyell** [comment]
How does this work if you're authenticating using a custom header?

**Comment by BigChief45** [comment]
^ Same question here.

I am using the following headers to make a `PATCH` request:

```javascript
headers = {'Content-Type': 'application/json', 'Authorization': 'Token <my_token'}
```

Yet Axios doesn't seem to recognize the `Authorization` header....

**Comment by liukan0211** [comment]
@BigChief45 
try the following way:
axios.defaults.headers.Authorization = Token <my_token>

**Comment by BigChief45** [comment]
@liukan0211 Thanks! That seems to work. But it seems odd, why does it have to be set like this? It is not how it is described in the documentation.

I've read through a lot of similar issues about this. Some people keep saying it is not a bug, but it certainly looks like a bug to me.

**Comment by liukan0211** [comment]
@BigChief45 
I reviewed the source code and found that axios will ignore the Authorization header if it's set in custom headers, you can refer to https://github.com/axios/axios/blob/master/lib/helpers/parseHeaders.js.

**Comment by BigChief45** [comment]
@liukan0211 Thanks for the help. Unfortunately I kept experiencing more problems with Axios, so I switched to [got](https://github.com/sindresorhus/got), works like a charm!
