### ISSUE TITLE
Problem with default transformation of FormData in Safari 9.1 (11601.5.17.1)

### ISSUE THREAD

**Issue by kimrgrey** [mzabriskie/axios#323]
In Safari 9.1 (11601.5.17.1) function `toString` for `FormData` returns `[object Object]` instead of `[object FormData]` as it's expected [here](https://github.com/mzabriskie/axios/blob/9e7b1b59933cb5777152252b80b9fd5c0403d178/lib/utils.js#L36). And as a result we have an `TypeError` because of attempt to use `JSON.stringify` for `FormData` [here](https://github.com/mzabriskie/axios/blob/fa9444e/lib/defaults.js#L31). 

I'm not sure about good solution for this problem. As a workaround we can check something like `typeof d.append === "function"` inside of `utils.isFormData`, but I don't think that this variant is a best. Or we can use something like `val instanceof FormData` everywhere in utils. WDYT?

**Comment by nickuraltsev** [comment]
If we do duck typing in `isFormData`, it will return `true` for some other built-in objects like 'URLSearchParams' (as they have almost identical APIs). Please see my comment to #317. Maybe we can do the following instead: 

```javascript
typeof FormData !== 'undefined' && value instanceof FormData
```

@mzabriskie What do you think?

**Comment by kimrgrey** [comment]
@nickuraltsev, I've created a PR with fix that you proposed: https://github.com/mzabriskie/axios/pull/325.

**Comment by mzabriskie** [comment]
I think `instanceof` is a good approach.

**Comment by kimrgrey** [comment]
@nickuraltsev @mzabriskie cool, thanks! Could you please clarify when release with this changes is expected? Support of FormData in Safari is really critical for us 😐

**Comment by mzabriskie** [comment]
We can roll a patch out today.

**Comment by kimrgrey** [comment]
It would be great, thanks! 👍
