### ISSUE TITLE
Benchmark comparison

### ISSUE THREAD

**Issue by rafaelamorim** [mzabriskie/axios#337]
Hey guys, how's going?

First of all, thanks for this AWESOME work! You guys rock!

Since there is no wiki (and i did tried to find someone with the same doubt) how this compares to request.js in terms of performance?
What are the pro's and con's of using this instead of other libs (such as request.js)

As i'm building a node based web service that relies a lot on request.js that's my main doubt.

Best,
Rafa

**Comment by mzabriskie** [comment]
I haven't done a lot of benchmark testing to compare other libs, though that would be very interesting data to have. The biggest pro of axios IMO is that you can use the same library across many platforms; node, browser, web workers, react native. If you're a full stack JS developer this can make it easier by not needing to learn a new HTTP client API for each platform you work on.

**Comment by rubennorte** [comment]
The things that I expected in an API client that made me choose this library where:

- First-class promise support
- Isomorphic / universal usage (Node.js, browser...)
- Default headers & parameters
- Request retries
- Timeouts
- Keep-alive requests
- Logging
- Response times

Extensibility is key in this case. Not all the features I wanted where available in Axios but I could implement them via interceptors. I think it's the most important feature that Axios has.

I used `request-promise` in a site that does ~2K requests/min. and I haven't noticed (inspecting application logs) any different in response times when I migrated to `axios`.

**Comment by rafaelamorim** [comment]
@rubennorte you answered my doubt perfectly. thanks!!!

i'm mesmerised by this lib, much more cleaner than any other, but i were a little bit concerned about performance...

that's solves the case for me! migriting to axios in 3,2,1......

**Comment by nik-kor** [comment]
I made some benchmarks here https://github.com/nik-kor/http-libraries-perf-test . Not sure is the test correct and the numbers very different between libs.

What do you think about it? Why are these libs are so slow compared to `http.request`?)
