### ISSUE TITLE
Updating typings

### ISSUE THREAD

**Issue by silviogutierrez** [mzabriskie/axios#338]
Hi there,

Great library. Very easy to use. Quick question: should the typings be expanded to cover the full API? For example, interceptors? I added this to augment locally, but I think it should be built into the typings.

```typescript
declare module axios {
    interface AxiosRequestMethods {
        interceptors: {
            request: {
                use: (interceptRequest: (config: RequestOptions) => RequestOptions, handleRequestError?: (error: any) => Promise) => number;
            }
            response: {
                use: (interceptResponse: (config: Response) => Response, handleResponseError?: (error: any) => Promise) => number;
            }
        };
    }
}

```

Thanks,

Silvio

**Comment by nickuraltsev** [comment]
Yes, this needs to be fixed. I'm planning to rewrite axios type script definitions soon. I will make sure that interceptors are covered. Thank you!

**Comment by mzabriskie** [comment]
Closing in favor of a single issue for all typescript requests (#379).
