### ISSUE TITLE
Promise interface typing expects only 1 parameter

### ISSUE THREAD

**Issue by checkerplate-bryce** [mzabriskie/axios#339]
The `d.ts` file has the following signature for the Axios `Promise` interface:

```js
interface Promise {
    then(onFulfilled:(response: axios.Response) => void): axios.Promise;
    catch(onRejected:(response: axios.Response) => void): axios.Promise;
  }
```

Note that `then` only expects 1 arg: `onFulfilled`.

But a real `Promise` instance is supposed to accept 2 args in the `.then` method: `onFulfilled` and `onRejected`. Is Axios' `Promise` signature different to the native JS `Promise` signature?

**Comment by nickuraltsev** [comment]
Axios typescript definitions really need work. I'm actually planning to rewrite them completely soon. I will make sure to fix the issue with `Promise`. Thank you!

**Comment by mzabriskie** [comment]
Closing in favor of a single issue for all typescript requests (#379).
