### ISSUE TITLE
Support finally?

### ISSUE THREAD

**Issue by bebraw** [mzabriskie/axios#34]
Would it be feasible to support `finally`? Ie.

```javascript
axios.get(...).then(...).catch(...).finally(...);
```

It would get triggered in both then/catch cases and seems to be common in Promise implementations (handy for cleanup).

**Comment by kentcdodds** [comment]
I found an npm module a few months ago which adds `finally` support to promises. I don't think this is the one, but it's the only one I found after a minute of searching: https://www.npmjs.com/package/promise.prototype.finally

**Comment by kentcdodds** [comment]
well ok then @jmdobry :+1:

**Comment by mzabriskie** [comment]
I'm reluctant to implement this. The ES6 Promise spec doesn't support `finally`, and I want to be able to drop the polyfill when browsers have native support.

If you feel strongly, or if I'm missing something, please present your argument.

**Comment by kentcdodds** [comment]
> I want to be able to drop the polyfill when browsers have native support.

:clap:

**Comment by bebraw** [comment]
Doesn't that effectively mean that if you want to add `finally` to axios, then all you need to do it is to shim `es6-promise` with the aforementioned library? Ie. you would do:

```javascript
var axios = require('axios');
require('promise.prototype.finally');

...
```

If so, it's probably better leave it out of the core library and just document that this is possible. That way you don't bloat the current implementation while keeping options open for people that might want the feature.

**Comment by mzabriskie** [comment]
@bebraw yes exactly. The `es6-promise` polyfill uses the native `Promise` if it exists. In either case the `finally` shim will work as you indicated. Let's leave it out of axios and let others add it to their own project if they desire.

I am working on axios today. I can add some documentation about this to the `README`.

**Comment by toymachiner62** [comment]
Google brought me here, but es6 does support `finally` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally. 

Should this issue be reopened to add support for `.finally`?

**Comment by lzl124631x** [comment]
@mzabriskie

**Comment by JannieT** [comment]
The [docs](https://github.com/axios/axios/blob/master/README.md) says:

```
axios.get('/user')
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
  .then(function () {
    // always executed
  }); 
```

So I recon "always executed" already works the same as this proposed "finally" or am I missing something?

**Comment by javierfvargas** [comment]
> The [docs](https://github.com/axios/axios/blob/master/README.md) says:
> 
> ```
> axios.get('/user')
>   .then(function (response) {
>     console.log(response);
>   })
>   .catch(function (error) {
>     console.log(error);
>   })
>   .then(function () {
>     // always executed
>   }); 
> ```
> So I recon "always executed" already works the same as this proposed "finally" or am I missing something?

As per the docs that's what I have used.  However, I have a question.  

What happens if I just want to use the "always executed then"  because I don't really care for the reply?.

**Comment by lzl124631x** [comment]
Suggest adding some comment like `similar to finally in other libraries` because I was searching for `finally` and the search didn't bring me to the code snippet. Not everyone necessarily read thru the doc.

**Comment by muzi131313** [comment]
after add this ployfill:
````
const promiseFinally = require('promise.prototype.finally')
promiseFinally.shim()
````
`finally` function was added to the `Promise.prototype`

**Comment by toymachiner62** [comment]
I see Promise.finally is available in Node 10. Been a while since I tried this, but maybe this just works if you're using Node 10?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

![image](https://user-images.githubusercontent.com/485782/57318037-470a7980-70ae-11e9-9953-d2e1d2ff6ade.png)

**Comment by marwan2** [comment]
I have solved this issue, by just include polyfill file from CDN
<script src="https://polyfill.io/v3/polyfill.min.js?features=Promise.prototype.finally" defer></script>

**Comment by atilkan** [comment]
Not one soul writes the current status here. 
The syntax **finally** is supported in browsers now.
Also **axios** supports it.

**Comment by jny986** [comment]
FYI for anyone that comes here in the future `.finally()` does now work with axios.

**Comment by jeffblake** [comment]
`finally` has been working fine for me, except (it appears) for Safari Version 10 and 11.  I'm seeing 

`TypeError undefined is not a function (near '...{alert(e)})).finally((function(){e.setSt...')`

Do I need to switch to using `then`, or should I add the polyfill instead?

**Comment by Xationch** [comment]
march 2020. Finally work in safari + safari mobile
