### ISSUE TITLE
instance.defaults.headers.common['Authorization']   deffrence from axios.defaults?

### ISSUE THREAD

**Issue by coolblabla** [mzabriskie/axios#341]
throws `TypeError: Cannot read property 'common' of undefined(…)` while using custom instanec.
```
Custom instance defaults

// Set config defaults when creating the instance
var instance = axios.create({
  baseURL: 'https://api.example.com'
});

// Alter defaults after instance has been created
instance.defaults.headers.common['Authorization'] = AUTH_TOKEN;
```

**Comment by nickuraltsev** [comment]
Yes, I think there is a bug either in the code or the documentation. 

The README.md [suggests](https://github.com/mzabriskie/axios#custom-instance-defaults) that the following should work:

```javascript
// Set config defaults when creating the instance
var instance = axios.create({
  baseURL: 'https://api.example.com'
});

// Alter defaults after instance has been created
instance.defaults.headers.common['Authorization'] = AUTH_TOKEN;
```

But `instance.defaults` is just a copy of the config passed to `axios.create` (https://github.com/mzabriskie/axios/blob/master/lib/core/Axios.js#L17):

```javascript
function Axios(defaultConfig) {
  this.defaults = utils.merge({}, defaultConfig);
  // ...
}
```

So the example above won't work as `instance.defaults.headers` is undefined.

@mzabriskie Should we fix the code, the docs, or both?

**Comment by coolblabla** [comment]
+1 I'd like to merge defaultConfig to instance by default. `var instance = axios.create(axios.defaults);`

**Comment by damianprzygodzki** [comment]
+1 Yeah, this is bug. But i think it is just wrong docs. For me defaults are defaults. We should leave it alone for axios "default" instance. And headers for instance set as baseURL, as a property of instance object.

**Comment by mzabriskie** [comment]
I think a good solution would be to use `defaults` instead of `{}` here https://github.com/mzabriskie/axios/blob/master/lib/core/Axios.js#L17
