### ISSUE TITLE
Setting "async" to true (like jQuery)

### ISSUE THREAD

**Issue by stevenmusumeche** [mzabriskie/axios#344]
Is there a way to set an ajax request as synchronous with Axios (like jQuery's `async: false` option)? 

I know this is an antipattern, however, I am trying to make some ajax requests triggered by the `window.onbeforeunload`, and Chrome automatically cancels these requests.  The only workaround seems to be to set the request to synchronous. See http://stackoverflow.com/questions/4945932/window-onbeforeunload-ajax-request-problem-with-chrome

**Comment by nickuraltsev** [comment]
Axios does not support synchronous requests. I would suggest to look at the [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon). It does exactly what you need (but is not supported by all browsers at the moment).

**Comment by stevenmusumeche** [comment]
Unfortunately that will not work for my use case because I need to set custom headers on the request.
