### ISSUE TITLE
Update typings and set typings in package.json

### ISSUE THREAD

**Issue by emzero** [mzabriskie/axios#346]
The `axios.d.ts` is 6 months old (v0.8.1). 
I don't know if an update is needed or not. Regardless, if would be great if someone set the `typings` key in `package.json` to point to the `d.ts` as explained in the Typescript [docs](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html).

[Related issue in Typings repo](https://github.com/typings/typings/issues/596)

**Comment by mzabriskie** [comment]
Closing in favor of a single issue for all typescript requests (#379).
