### ISSUE TITLE
Axios All Question

### ISSUE THREAD

**Issue by donadley** [mzabriskie/axios#347]
I am trying to use axios.all to call each method. How am I suppose to then get the returned values from axios.all? getEmailCredenital() is similar to the methods getPhoneCredentials() and getQuestionCredentials and they are all functional.
```
function getEmailCredentials(store){
axios({ method: 'get', url: store.endpoint
 	}).then(function(response) {
                console.log(response);
 		return response;
 		})
 	.catch(function(response) {
 			//handle error
 		});
```
Below is the method I am having issue with. credentialResponse from console.log(credentialResponse) is undefined and displayed before the log from the above method.
```
	axios.all([getEmailCredentials(store), getPhoneCredentials(store), getQuestionCredentials(store)])
 		.then(axios.spread(function(email, phone, questions) {
 			var credentialResponse = objectAssign({}, email, phone, questions);
 			console.log(credentialResponse);
```

**Comment by donadley** [comment]
I solve my question.

I removed .then from the method getEmailCredentials(). This allowed axios.all to collect the Promise that the method returnes.

This is the fixed method.
```
function getEmailCredentials(store) {
 	return axios.get(store.endpoint);
}
```

**Comment by uhtred** [comment]
But why axios don't return a promise on "then" and "catch"?
