### ISSUE TITLE
How to send Raw http for Instagram Authentication?

### ISSUE THREAD

**Issue by roblav96** [mzabriskie/axios#350]
I'm trying to connect to the [Instagram API](https://www.instagram.com/developer/authentication/) with axios.

Here's my code:
```javascript
axios( {
	method: 'POST',
	url: '/oauth/access_token',
	baseURL: 'https://api.instagram.com',
	params: { // both data and params don't work
		'client_id': 'CLIENT_ID',
		'client_secret': 'CLIENT_SECRET',
		'grant_type': 'authorization_code',
		'redirect_uri': 'REDIRECT_URI',
		'code': 'CODE',
	},
} )
```
I keep getting the response `No client_id` so it's not reading any of the params.

When I use [restify's StringClient](http://restify.com/#stringclient)
```javascript
return new Promise( function ( resolve, reject ) {
	client.post( '/oauth/access_token', {
		'client_id': 'CLIENT_ID',
		'client_secret': 'CLIENT_SECRET',
		'grant_type': 'authorization_code',
		'redirect_uri': 'REDIRECT_URI',
		'code': 'CODE',
	}, function ( errr, reqq, ress, dataa ) {
		if ( errr ) {
			reject( errr )
		} else {
			resolve( dataa )
		}
	} )
} )
```
It works great.

I think it has something to do with `application/x-www-form-urlencoded` header maybe?

I would like to know how I can get this working with axios. Thank you!

**Comment by nickuraltsev** [comment]
Yes, StringClient uses the `application/x-www-form-urlencoded` format by default while axios uses `application/json` by default (when `data` is an Object).

Here is how to make an `application/x-www-form-urlencoded` request with axios:

### Browser

- You can use `URLSearchParams` as described here: https://github.com/mzabriskie/axios/issues/97#issuecomment-223650368
- Or you can encode the data using a library like [qs](https://github.com/ljharb/qs):

```javascript
var qs = require('qs');
axios.post('/foo', qs.stringify({ 'bar': 123 });
```

### Node

You can use `querystring` module to encode the data:

```javascript
var querystring = require('querystring');

axios.post('/foo', querystring.stringify({
  'bar': 123
});
```

Hope this helps!

**Comment by roblav96** [comment]
I shall test this when I get home. Thank you!!!

**Comment by SudoPlz** [comment]
Thanks @nickuraltsev.
This works, but what about also sending params. 

Can we do:

```javascript 
    var querystring = require('querystring');

    axios.post('/foo', querystring.stringify({
      'bar': 123
    },
    {
        aParam:aValue
    }
    );
```
?
If not, how can I also send params while sending a query string?
Thank you.

**Comment by nickuraltsev** [comment]
@SudoPlz Yes, you can set query string parameters using the `params` config option:

```js
var querystring = require('querystring');

axios.post('/foo', querystring.stringify({
  'bar': 123
}, {
  params: { foo: 'bar' } // query string
});
```

**Comment by SudoPlz** [comment]
Amazing, I assume if we are to use query string params we have to also implement a `paramsSerializer` as well. 
Thanks.

**Comment by nickuraltsev** [comment]
@SudoPlz, no you don't need to implement a params serializer. There is a default one.

**Comment by gitlovenotwar** [comment]
I had the same issue when using 'application/x-www-form-urlencoded'. How should it be sent when using these approach?

<pre>
axios({
  url: 'some_post'
  method: 'post',
  data: {
    name: 'John'
  }
});
</pre>

should be the data be stringify first? ex. data: JSON.stringify(data);

**Comment by jjingrong** [comment]
@gitlovenotwar 

You should do it in this way 

```
import qs from 'qs';
.
.
.
axios({
  url: 'some_post'
  method: 'post',
  data: qs.stringify({
    name: 'John'
  }),
});
```

**Comment by naxir** [comment]
@nickuraltsev  Thanks it really helped in my case

**Comment by BitOfGold** [comment]
You can patch axios to use application/x-www-form-urlencoded
Solution here:
https://github.com/axios/axios/issues/97
```

axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
axios.defaults.transformRequest = [function (data, headers) {
    var str = [];
    for(var p in data)
      if (data.hasOwnProperty(p) && data[p]) {
        str.push(encodeURIComponent(p) + "=" + encodeURIComponent(data[p]));
      }
    return str.join("&");
  }];

**Comment by BitOfGold** [comment]
Other solution: use param: {} instead of data: {} in POST, it works fine!

**Comment by happilymarrieddad** [comment]
Hey guys, 

It's working for me but it's putting all the values in a slice in GO.. am I doing something wrong?

```
 axios.post('http://localhost:8001/session/store',qs.stringify({email:"nkotenberg@fusionware.com",password:""}))
```

```
package main

import (
	"github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"log"
	"net/http"
	"os"
	"time"
)

const (
	DefaultWriteTimeout = 15 * time.Second
	DefaultReadTimeout  = 15 * time.Second
)

func SessionStore(w http.ResponseWriter, r *http.Request) {
	r.ParseForm()

	log.Println(r.Form)
	log.Println(r.PostForm)

	w.Write([]byte("TEST"))
}

func main() {
	port := "8001"
	r := mux.NewRouter().StrictSlash(true)

	r.HandleFunc("/session/store", SessionStore).Methods("POST")

	handler := handlers.LoggingHandler(os.Stdout, handlers.CORS(
		handlers.AllowedOrigins([]string{"*"}),
		handlers.AllowedMethods([]string{"GET", "PUT", "PATCH", "POST", "DELETE", "OPTIONS"}),
		handlers.AllowedHeaders([]string{"Origin", "Authorization", "Content-Type"}),
		handlers.ExposedHeaders([]string{""}),
		handlers.MaxAge(10),
		handlers.AllowCredentials(),
	)(r))

	newServer := &http.Server{
		Handler:      handler,
		Addr:         "0.0.0.0:" + port,
		WriteTimeout: DefaultWriteTimeout,
		ReadTimeout:  DefaultReadTimeout,
	}

	log.Println("Starting server on port", port)
	log.Fatal(newServer.ListenAndServe())
}
```

![selection_016](https://user-images.githubusercontent.com/6416323/36398314-b330338e-1583-11e8-9e70-40becbf5fe07.png)

**Comment by hadeel36** [comment]
@nickuraltsev please what you mean by " StringClient " ?

**Comment by isaaclem** [comment]
@nickuraltsev : Please allow me to ask amateur question. I tried with your suggestion below and it worked.

```
const ax = axios.create({
  timeout: 30000,
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
});

ax.post(
  someURL, 
  qs.stringify({ json: '{ "var1": "value1" }', /**Needed help on this part**/ })
)
```
May I know how to modify the above if I wish to upload image? I've tried to just provide the key with the filePath but it didnt seems to work?

```
qs.stringify({ json: '{ "var1": "value1" }', photo: '/Users/isaac/Library/Developer/CoreSimulator/Devices/B516568B-574F-4058-AA25-E09FBD4D8FE5/data/Containers/Data/Application/637C4CDF-C615-49B3-9300-AB475E5A87EF/tmp/B32F77EE-7003-4704-A674-9E8CEDCDE29C.jpg' })
```

**Comment by happilymarrieddad** [comment]
Hey guys,

I found out that it's normal for it to be in a slice/array... There can be more than 1 of the same property in a URL parameter. Anyways, I hope this helps if anyone has the same question as me.

**Comment by LoganLeopold** [comment]
> Yes, StringClient uses the `application/x-www-form-urlencoded` format by default while axios uses `application/json` by default (when `data` is an Object).
> 
> Here is how to make an `application/x-www-form-urlencoded` request with axios:
> 
> ### Browser
> * You can use `URLSearchParams` as described here: [#97 (comment)](https://github.com/axios/axios/issues/97#issuecomment-223650368)
> * Or you can encode the data using a library like [qs](https://github.com/ljharb/qs):
> 
> ```js
> var qs = require('qs');
> axios.post('/foo', qs.stringify({ 'bar': 123 });
> ```
> 
> ### Node
> You can use `querystring` module to encode the data:
> 
> ```js
> var querystring = require('querystring');
> 
> axios.post('/foo', querystring.stringify({
>   'bar': 123
> });
> ```
> 
> Hope this helps!

Thanks for this bro - saved my ass on a late-night project!

**Comment by smitpatelx** [comment]
> Yes, StringClient uses the `application/x-www-form-urlencoded` format by default while axios uses `application/json` by default (when `data` is an Object).
> 
> Here is how to make an `application/x-www-form-urlencoded` request with axios:
> 
> ### Browser
> * You can use `URLSearchParams` as described here: [#97 (comment)](https://github.com/axios/axios/issues/97#issuecomment-223650368)
> * Or you can encode the data using a library like [qs](https://github.com/ljharb/qs):
> 
> ```js
> var qs = require('qs');
> axios.post('/foo', qs.stringify({ 'bar': 123 });
> ```
> 
> ### Node
> You can use `querystring` module to encode the data:
> 
> ```js
> var querystring = require('querystring');
> 
> axios.post('/foo', querystring.stringify({
>   'bar': 123
> });
> ```
> 
> Hope this helps!

If you don't want to use `qs` module, then use this function.
```
function serialize (obj) {
  var str = [];
  for (var p in obj)
    if (obj.hasOwnProperty(p)) {
      str.push(encodeURIComponent(p) + "=" + encodeURIComponent(obj[p]));
    }
  return str.join("&");
}
```
