### ISSUE TITLE
Interceptors should be called before the data is transformed

### ISSUE THREAD

**Issue by Cristofori** [mzabriskie/axios#352]
This issue was introduced in the 0.9.0 release.

```
axios.interceptors.request.use(function(config) {
  console.log(typeof config.data)
  return config;
})

...

axios.post('/some/url/', {foo: 'bar'})
```

Output in 0.8.1: 'object'
Ouput in 0.9.0+: 'string'

Prior to 0.9.0 the interceptor would be given the actual JS object that was passed to the `post` method. Now it appears to be passed through `transformData` before the interceptor, forcing users to parse the data from JSON back into a JS object before being able to manipulate it, and then turn it back into a JSON string when returning it.

**Comment by mzabriskie** [comment]
You're right, this was broken with #183. Thanks for catching this. Will work on getting a patch out.
