### ISSUE TITLE
`request` api not exposed in babel import

### ISSUE THREAD

**Issue by arempe93** [mzabriskie/axios#354]
This code will raise `Uncaught TypeError: axios.request is not a function`:

```javascript
import * as axios from 'axios'

axios.request({
  method: 'GET',
  url: '/categories/1'
})
```

Outputting the `axios` object to console results in:

```
Object {defaults: Object, interceptors: Object}
  all: function all(promises)
  create: function create(defaultConfig)
  default: function wrap()
  defaults: Object
  delete: function wrap()
  get: function wrap()
  head: function wrap()
  interceptors: Object
  patch: function wrap()
  post: function wrap()
  put : function wrap()
  spread: function spread(callback)
  __proto__: Object
```

Using either `axios({ ... })` or `axios.request({ ... })` will not work for es6 imports

**Comment by arempe93** [comment]
[Made a requirebin to demonstrate](http://requirebin.com/?gist=bd2359e1a5f418c3bf933010a60795e1)

**Comment by mzabriskie** [comment]
I'm not sure why it's failing when using `import *`, but as a work around `import axios from 'axios'` does work. There is only a single export from the axios module, so `import *` isn't really needed.

**Comment by arempe93** [comment]
That seems to expose `axios({ ... })`, but not `axios.request({ ... })`

[RequireBin](http://requirebin.com/?gist=bd2359e1a5f418c3bf933010a60795e1)

**Comment by mzabriskie** [comment]
Works for me using `axios@0.12.0`. Your gist is using `axios@0.5.3`. I would recommend updating. http://requirebin.com/?gist=506cee6804bd4277914e64e6da1db631

**Comment by arempe93** [comment]
Ok - I upgraded from 0.9 to 0.12 in my app and it seemed to fix it for me, along with using `import axios from 'axios'`.

Thanks for the replies
