### ISSUE TITLE
Add axios-vcr to README

### ISSUE THREAD

**Issue by nettofarah** [mzabriskie/axios#355]
I built this library to help me write better tests for projects using axios.
https://github.com/nettofarah/axios-vcr

I've been using it both in personal projects and in multiple projects at IFTTT.
I think I'm finally confident to share it with some more people.

Would it make sense to a link to this library somwhere in the README?
Maybe we could add a Testing section and include the url to axios-vcr with a short explanation.

**Comment by nettofarah** [comment]
Happy to put together a PR if the maintainers are fine with it.

**Comment by nickuraltsev** [comment]
Sure, please feel free to submit a PR. Please add your library to [ECOSYSTEM.md](https://github.com/mzabriskie/axios/blob/master/ECOSYSTEM.md).

**Comment by nettofarah** [comment]
Here's the PR: https://github.com/mzabriskie/axios/pull/359
