### ISSUE TITLE
`progress` config option not working

### ISSUE THREAD

**Issue by alex-phillips** [mzabriskie/axios#358]
I'm attempting to use the `progress` config option as shown below in my code. It appears to mimic exactly what is in the example, but it never actually enters the function.

```
var form = new FormData()
form.append('content', fs.createReadStream('./myfile.mkv');

axios.post("http://example.com", form, {
    progress: (progressEvent) => {
        console.log('progress!');
    }
})
  .then(response => {
      console.log('done');
  })
  .catch(err => {
      console.log('failed');
  });
```

It outputs `done`, but nothing is outputted on progress. Also, it's worth noting I attempted this with very large files (1GB) and no progress function was ever entered.

**Comment by nickuraltsev** [comment]
The `progress` option is only supported for browsers. It won't work in Node.js.
