### ISSUE TITLE
Use it with almond

### ISSUE THREAD

**Issue by RobinBressan** [mzabriskie/axios#36]
Hi,

I would like to be able to do a `require('axios')` with [almond](https://github.com/jrburke/almond). The file is correctly found but the result of the require is always `undefined` (even with `axios.amd` or `axios.standalone`). Do you have any insights on this?

Nice lib by the way!

Thanks

Robin

**Comment by mzabriskie** [comment]
@RobinBressan I'm not familiar with `almond`. I'll have to do some research to see what's going on.

**Comment by RobinBressan** [comment]
Hi, thanks for your quick response! It is a light requirejs which aims to replace requirejs after the optimization process to get a lib working without a requirejs dependency.

**Comment by RobinBressan** [comment]
I switched to browserify and it works.

**Comment by mzabriskie** [comment]
@RobinBressan sounds good. I would recommend using CommonJS with webpack, or browserify, over AMD anyway.
