### ISSUE TITLE
Axios are not following the redirection?

### ISSUE THREAD

**Issue by Kekesed** [mzabriskie/axios#360]
Axios are not following the 301 Moved blabla header.
Are there any options for that?

**Comment by mzabriskie** [comment]
Is this happening in the browser or in node?

**Comment by Kekesed** [comment]
Browser, i think it's got stucked on "Network Error" when no CORS header added.
i havn't examine it really close.

**Comment by mzabriskie** [comment]
Typically `3xx` headers are automatically followed by the browser. I've previously tried to prevent or intercept the redirect, but it's not an option. You are probably right that it's an issue related to CORS.

**Comment by Kekesed** [comment]
ahh okay then, thanks!
have a nice day
