### ISSUE TITLE
Proper typings...

### ISSUE THREAD

**Issue by electricessence** [mzabriskie/axios#361]
Please use:
```"typings": "./axios.d.ts"```
In your package.json.
https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by emzero** [comment]
I have already created an issue on this and the author said he's planning on rewriting the definition file. I don't know when though.

https://github.com/mzabriskie/axios/issues/346

**Comment by electricessence** [comment]
Pull request it? :/

**Comment by JeroenNelen** [comment]
I also have the impression that the definitions aren't complete, for example the defaults attribute is not defined (which makes typescript angry when trying to set it via axios.defaults.baseUrl = ...), correct?

**Comment by nickuraltsev** [comment]
@JeroenNelen Right, our current definitions are outdated. I'm hoping to find some time this week to update them. I will add `typings` to package.json.

**Comment by mzabriskie** [comment]
Closing in favor of a single issue for all typescript requests (#379).
