### ISSUE TITLE
New release with improved error handling

### ISSUE THREAD

**Issue by rubennorte** [mzabriskie/axios#363]
Hi there! Do you have any plans to release a new version with the improved error handling, rejecting always with extended error instances?

I discovered this great library this morning and have been testing it since. In my previous code I used my own wrapper around `request-promise` which had practically the same API than `axios`, so I've replaced it really fast. Everything has been working great until I started testing error handling. I cloned the repo and I was confused because it looked right, but I just discovered that it's implemented in master but not released yet :'(

Tell me if you need any help with this release (important bugs not yet solved, etc.).

**Comment by tarim** [comment]
same as here.It cannot handle errors properly.

**Comment by mzabriskie** [comment]
`axios@0.13.0` has been released with this improvement.
