### ISSUE TITLE
DOMException on older Android devices (4.3)

### ISSUE THREAD

**Issue by raulmatei** [mzabriskie/axios#364]
Hi,

I'm getting an error when trying to use Axios on an older Android device (4.3) with the default browser.

It looks like it happens when creating an instance using `axios.create()` with `responseType: 'json'` in config (see attached image - remote debugging with `weinre`):

![image](https://cloud.githubusercontent.com/assets/1718341/16529299/cbc0073e-3fca-11e6-8ce2-c73816c102a1.png)

Any idea on what may be wrong?

Thanks,
Raul.

**Comment by nickuraltsev** [comment]
Could you please try to replace `axios.get(...)` with the following code

```javascript
Promise.resolve({
  data: {
    autocomplete: [
      ...
    ]
  }
}).then(response => {
  // handle the response
});
```

to check whether the issue is caused by axios?

**Comment by raulmatei** [comment]
Hi,

I have created Axios instance again, as I mentioned in my first post, with `responseType: 'json'`, and then I've replaced the autocomplete service to return the above and it works. I should mention that I use `es6-promise` polyfill and it seems to work well if not using the `responseType` in the config.

Raul.

**Comment by nickuraltsev** [comment]
Thank you! Looks like you are hitting [this](http://stackoverflow.com/questions/9845401/xmlhttprequest-responsetype-json-giving-error-syntax-err-dom-exception-12) issue. As a workaround, you can omit `responseType`. Axios will parse the response string as JSON by default.

**Comment by raulmatei** [comment]
Hi,

Thanks for the clarification. As you said, I've removed `responseType` and it works.

Thanks,
Raul.
