### ISSUE TITLE
Content-Type is missing for both GET and POST request

### ISSUE THREAD

**Issue by mech** [mzabriskie/axios#365]
Hi,

I am using this library to make GET as well POST request to a Rails 5 product. It seems to me the Content-Type is missing outright somehow, either it was being removed or not set totally.

This can lead to rails/rails issues #24827

I only encounter this using IE 9 with CORS. The same code using IE 10 and Chrome latest do not lead to any errors.

**Comment by nickuraltsev** [comment]
IE 9 does uses [`XDomainRequest`](https://msdn.microsoft.com/en-us/library/cc288060(v=vs.85).aspx) to make cross-origin requests. `XDomainRequest` does not allow setting `Content-Type`. Please see [this](https://blogs.msdn.microsoft.com/ieinternals/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds/) post for details.

Hope this helps!
