### ISSUE TITLE
Add global or default response

### ISSUE THREAD

**Issue by tarim** [mzabriskie/axios#367]
Hi there,

I am using axios on my new project, and I like it(used all api calls). But, I have an issue about unauthorized request(401). I am wondering, is that possible to add global or default response for handle all requests please(same as global default header)? 

Thanks,

**Comment by rubennorte** [comment]
You can use a response interceptor for that. Something like this should work:

```javascript
axios.interceptors.response.use(null, function(error) {
  if (error.status === 401) {
    return defaultResponse;
  }
  return Promise.reject(error);
});
```

**Comment by tarim** [comment]
Hi @rubennorte ,

Thank you very much for your response. It works, but, dispatch doesn't work inside interceptors.
for example 
if(err.status===401) {
 			localStorage.removeItem('token');
 			dispatch(sessionOutSuccess(err.message));
 		}

Any idea please?

Thanks,

**Comment by rubennorte** [comment]
I don't know what `dispatch` is in the code you posted, but I think that's out of the scope of Axios. Maybe you haven't imported it or you're using it before it's defined.

**Comment by tarim** [comment]
Hi @rubennorte ,

Sorry, I am using redux, and, anything come up it will update redux store. 

Thanks,

**Comment by haxxxton** [comment]
@tarim, Not sure if you found a solution to this, but you can access `dispatch` as a property of your store. You just need to include where you've defined your store, and then call the function you need. For example:

```
import axios from 'axios';
// assumed locations of your exports/files
import { sessionOutSuccess } from '~/js/actions';
import store from '~/js/configured-store';

axios.interceptors.response.use(null, function(err) {
	if(err.status === 401) {
		localStorage.removeItem('token');
		store.dispatch(sessionOutSuccess(err.message));
	}
	return Promise.reject(error);
});
```

**Comment by luxueyan** [comment]
Can I return a reject promise or err in success callback. And can I set a global err handler for this err?
```javascript
axios.interceptors.response.use(function(err) {
	if(err.status === 401) {
		localStorage.removeItem('token');
		store.dispatch(sessionOutSuccess(err.message));
	}
	return Promise.reject(error);
});

```

**Comment by bennyn** [comment]
With axios v0.16.2 `error.status` became `error.response.status`:

```javascript
axios.interceptors.response.use(null, function(error) {
  console.warn('BENNY', error.response.status);
  return Promise.reject(error);
});
```

**Comment by linesh-simplicity** [comment]
might be a bit late but regarding the redux dispatch thing one of the solutions can be using middlewares where `dispatch` will be passed in as available parameters: 

```js
const createAxiosMiddleware = (axios) => ({ dispatch, getState }) => {
  axios.interceptors.response.use(null, (error) => {
    if (error.response.status === 401) {
      dispatch(actions.logout())
    }
  })
}

export default createAxiosMiddleware(axios)
```
