### ISSUE TITLE
Can I do multiple requests in a row?

### ISSUE THREAD

**Issue by sean-hill** [mzabriskie/axios#371]
For instance:

	axios.get('http://www.google.com')
		.then(function (res) {

		})
		.get('http://www.apple.com')
		.then(function (res) {

		})
		.catch(function (e) {

		})

**Comment by mzabriskie** [comment]
It would look something like:

```js
axios.get('http://google.com')
  .then((res) => {
    // do something with Google res

    return axios.get('http://apple.com');
  })
  .then((res) => {
    // do something with Apple res
  })
  .catch((err) => {
    // handle err
  });
```

Alternatively you can send both requests simultaneously and handle responses at the same time:

```js
axios.all([
    axios.get('http://google.com'),
    axios.get('http://apple.com')
  ])
  .then(axios.spread((googleRes, appleRes) => {
    // do something with both responses
  });
```

**Comment by c0d3ster** [comment]
I just wanted to tack on that there's a small syntax error on the above solution, for anyone reading through this issue trying to use axios.all.  The above solution is missing a closing parenthesis on the call to `.then(`

```
axios.all([
    axios.get('http://google.com'),
    axios.get('http://apple.com')
  ])
  .then(axios.spread((googleRes, appleRes) => {
    // do something with both responses
  }));
```

Happy coding!

**Comment by Cholowao** [comment]
@c0d3ster have you really copy-pasted or had eagle eyes!?

**Comment by c0d3ster** [comment]
@Cholowao lol I did not copy and paste his code block, but I did realize there was an error after trying to implement a similar .all call for three simultaneous requests.  I hadn't seen the axios.spread syntax before, so I figured I'd try to save some people a few minutes counting parenthesis in the future!

**Comment by franciscop-invast** [comment]
You can do the same natively with deconstructing:

```js
Promise.all([
  axios.get('http://google.com'),
  axios.get('http://apple.com')
]).then(([google, apple]) => {
  // do something with both responses
});
```

Or with `await` (you must be inside an `async` function):

```js
(async () => {
  const [google, apple] = await Promise.all([
    axios.get('http://google.com'),
    axios.get('http://apple.com')
  ]);

  // do something with both responses
})();
```

**Comment by Suyash-Purwar** [comment]
Is it possible to handle `.catch()` block for two requests separatelty.

<code>
axios.all([
    axios.get('http://google.com'),
    axios.get('http://apple.com')
  ])
  .then(axios.spread((googleRes, appleRes) => {
    // do something with both responses
  }))
  .catch((googleErr, appleErr) => {
    // do something with request failures
  });
</code>

**Comment by novikovrabota433** [comment]
How can I make sequential requests using this approach? If you insert a different url response from the server at the same time into the link
https://ibb.co/ngPr45p

const s1 = async () => {
axios(url_benzinga)
      .then(response => {
        var html = response.data;
       var $ = cheerio.load(html)

const s2 = async () => {
axios(url_benzinga1)
      .then(response => {
        var html = response.data;
       var $ = cheerio.load(html)

**Comment by nadernt** [comment]
> googleErr, appleErr

I think it doesn't. I tested your code and it returns for second argument (appleErr) all the time undefined.
