### ISSUE TITLE
Is there option to skip HTTPS verification?

### ISSUE THREAD

**Issue by harshithjv** [mzabriskie/axios#374]
This module works great for HTTP requests and also HTTPS websites with authorized signed certificates. Is there a way to skip verification for websites that are self-signed and not yet verified?

**Comment by mzabriskie** [comment]
No work has been done in this lib for addressing your use case.

**Comment by rubennorte** [comment]
You can do that without Axios. Maybe this can help you: http://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired

If you want to use a https `Agent` configured to ignore SSL certificate errors, you can pass it as an `agent` option to your axios instance.
