### ISSUE TITLE
0.13 Error handling does not handle exceptions 

### ISSUE THREAD

**Issue by pr0digy** [mzabriskie/axios#376]
After upgrade from 0.12 to 0.13, `catch` method does not catch an error, an exception occurs and the whole process aborts.

**Comment by mzabriskie** [comment]
Can you provide some more details? Is this using node or the browser? What is the error that is being thrown? Can you provide a stack trace?

**Comment by pr0digy** [comment]
I'm using a webpack build.  The error occurs in a browser, not sure about node, the app is not isomorphic. The error occurs while redux-form is being submitted (the same code from 0.12 worked just fine).  The confusing part is that in a simple test without redux-form everything works as documented. 

I will try to reproduce the error and provide an example.

**Comment by srahulprdxn** [comment]
Same here. There is some issues with the error object. Previously, we were able to retrieve the error object. We are facing issues now. I am rolling back to the previous version.

Below is the error message I get in the console:

```
Error: Request failed with status code 404
    at createError (eval at <anonymous> (https://localhost:8080/vendors.js:34:14382), <anonymous>:15:15)
    at settle (eval at <anonymous> (https://localhost:8080/vendors.js:59:22824), <anonymous>:18:12)
    at XMLHttpRequest.handleLoad (eval at <anonymous> (https://localhost:8080/vendors.js:34:48), <anonymous>:75:7)
```

In the previous version, I used to get the proper error object with status code.

**Comment by srahulprdxn** [comment]
```
POST https://192.168.1.188:3000/vendor/customerlocation/1 404 (Not Found)
vendor-list.js?2389:57 

Object {data: "Unfortunately, No vendor was found.", status: 404, statusText: "Not Found", headers: Object, config: Object…}
```

I reverted to 0.12.0 and now I get a proper error object.

**Comment by alexi21** [comment]
I worked around this by nesting my response call:

```
.catch(response => {
  dispatch(authError(response.response.data.error));
});
```

instead of 

```
.catch(response => {
  dispatch(authError(response.data.error));
});
```

The original error was a type error because response.data didn't exist.

**Comment by pr0digy** [comment]
@alexi21 It's not the same. You are talking about a documented change mentioned [here](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md).  In my case the `catch` method is not even called.

**Comment by alexi21** [comment]
Okay cool, thanks Pr0digy...so I am using 0.13.1 and catching a 422 and it works okay. Is your code online I am happy to have a look at it.

**Comment by pr0digy** [comment]
@alexi21 Thanks for your offer, but it's a private project and I've rolled back to 0.12.0.

**Comment by nickuraltsev** [comment]
@srahulprdxn This is by design. Please see [Upgrade Guide](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#012x---0130) for details.

**Comment by lnmunhoz** [comment]
I am having the same issue @srahulprdxn with the version 0.13.1

I am returning a json with an error message from the server and a status code 401, but the `err` from `catch` is always an exception.

```
POST http://localhost:8080/authenticate 401 (Unauthorized)
bundle.js:54853 Error: Request failed with status code 401
    at createError (http://localhost:3000/bundle.js:37601:16)
    at settle (http://localhost:3000/bundle.js:37579:13)
    at XMLHttpRequest.handleLoad (http://localhost:3000/bundle.js:37472:8)
```

**Comment by nickuraltsev** [comment]
@lnmunhoz Yes, this is by design. Starting from v0.13, Promise is always rejected with an `Error`. Please see [this](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#error-handling) for details.

**Comment by srahulprdxn** [comment]
@lnmunhoz I reverted to the previous version. That's all I could think about. @nickuraltsev 75% of our project is built. So I hope you understand that right now, if we keep changing our pattern, it might be time consuming and our clients won't accept it pleasantly. ;)

**Comment by nickuraltsev** [comment]
@srahulprdxn You don't have to upgrade. You can use v0.12 if it works for you. Please note that minor versions can introduce breaking changes until axios reaches 1.0 as [stated](https://github.com/mzabriskie/axios#semver) in README.md. All breaking changes are documented in the [Upgrade Guide](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md).

**Comment by srahulprdxn** [comment]
@nickuraltsev Awesome and noted. :+1:

**Comment by lnmunhoz** [comment]
@nickuraltsev I followed the examples using `.catch(err)` but the `err` is just an exception. Doesn't contain the returning object like the example shows.

**Comment by SOSANA** [comment]
@nickuraltsev I still have this issue with v 0.13.1 :-1:

**Comment by nickuraltsev** [comment]
@SOSANA There is no 'extra response object' in your example. 

When an `Error` is thrown, the `response` variable will contain the `Error`. I would suggest to rename that variable to `error`:

```js
.catch(error => {
})
```

If a response has been received from the server, the `error.response` will contain a response object. The `data` property of the response object will contain the response payload. (See [this](https://github.com/mzabriskie/axios#response-schema) for details about the response schema.)

```js
.catch(error => {
  if (error.response) {
    // Response has been received from the server
    console.log(error.response.data); // => the response payload 
  }
})
```

Hope this helps!

**Comment by SOSANA** [comment]
@nickuraltsev Thanks brother I will give it a try, for what ever reason when I tried last few days didn't get it to work but I will try your suggestion

**Comment by ummahusla** [comment]
Had this issue

```
Error: Request failed with status code 422
    at createError (bundle.js:34466)
    at settle (bundle.js:34438)
    at XMLHttpRequest.handleLoad (bundle.js:34311)
```

Got it fixed by

```
  .catch(error => {
        if (error.response) {
          dispatch(authError(error.response.data.error));
        }
      })
```
