### ISSUE TITLE
Add support for response stream?

### ISSUE THREAD

**Issue by olalonde** [mzabriskie/axios#377]
It would be useful if the returned response object could optionally be a read stream (similar to how whatwg fetch does).

**Comment by mzabriskie** [comment]
You could do this with a transformer.

```js
var Readable = require('stream').Readable;

axios.get('/some/url', {
  transformResponse: function (data) {
    var stream = Readable();
    var index = 0;
    stream._read = function () {
      stream.push(data.charAt(index++));
      if (index > data.length) stream.push(null);
    }
    return stream;
  }
})
```

**Comment by nickuraltsev** [comment]
@olalonde If you set the `responseType` option to `stream`, the `data` property of the response object will contain a stream.
