### ISSUE TITLE
Update Typings

### ISSUE THREAD

**Issue by mzabriskie** [mzabriskie/axios#379]
This is a catch all for the multiple requests to update the type definition. Needs to be done for the next release.

**Comment by aendrew** [comment]
As somebody trying to use Axios with TypeScript for about two weeks now, I'm still not sure whether it's better to use the `d.ts` file in the main repo or the DefinitelyTyped definition. I started with the latter, which was fine until I tried to use `Axios.all`, which suffers from the issues mentioned in #253. I then did:

`typings install github:mzabriskie/axios/axios.d.ts#8332392 --save --global`

...To install the first-party ones and they seem to work far better.

I'm considering writing a blog entry about using Axios with TypeScript if there's any appetite for it, but it would be nice to get some clarification on which definitions are ultimately the most, uh, definitive? 😅

**Comment by JeroenNelen** [comment]
I'm getting is one: Property 'defaults' does not exist on type 'AxiosStatic'.
Because the typings don't seem to be defined for the default options.
If I find some time I can try to make a PRQ.

Kind regards,

**Comment by nickuraltsev** [comment]
Just a heads up that I'm working on new definitions for axios.

**Comment by JeroenNelen** [comment]
@nickuraltsev in that case, I'll wait until your finished, are you also providing typings for the defaults option?

**Comment by nickuraltsev** [comment]
@JeroenNelen Yes, will do

**Comment by nickuraltsev** [comment]
New TypeScript definitions have landed to master.

**Comment by ericeslinger** [comment]
I'm not sure if I'm suffering from typescript-newbie syndrome, but I had to modify the package.json file distributed with axios to include `"typings": "./axios.d.ts"` in order to build a file that had an import from axios in my project (using gulp-typescript and tsc 2.0.0)

**Comment by shanekenney** [comment]
@ericeslinger The updates haven't been published to npm yet. https://github.com/mzabriskie/axios/pull/419#issuecomment-241912066

**Comment by nickuraltsev** [comment]
axios v0.14.0 has been released with these updates.

**Note:** Please use the following `import` statement to import axios in TypeScript:

```typescript
import axios from 'axios';

axios.get('/foo')
  .then(response => console.log(response))
  .catch(error => console.log(error));
```

**Comment by renke** [comment]
Hi, I know this one is closed, but I noticed I can no longer type the response like this:

`const res = await httpClient.post<string>(url, bookmark);`

I was using the @types/axios typing before and now use the typing that come with axios itself. 

Any reason we can no longer type the response?

**Comment by cjke** [comment]
Ditto - is there any way to use the old typings that supported this?

A sample of what I had set up looked like this:

```
export function index<T>(resource: string): Axios.IPromise<Axios.AxiosXHR<T>> {
    return axiosInstance.get<T>(resourceUrl(resource));
}
```

Meaning, in turn, I could do:

```
const response = await index<IProfile>('me');
```

And I would know that the response would be of type IProfile..

**Comment by Mattwmaster58** [comment]
Any update on this issue?
