### ISSUE TITLE
Concurrent requests: Catching both successful and failed requests

### ISSUE THREAD

**Issue by ihatehandles** [mzabriskie/axios#384]
Hi,

Ran into a situation similar to this: http://stackoverflow.com/questions/38262315/axios-concurrent-requests-any-way-to-get-the-results-from-the-successful-reques

I'd want to capture both successful and failed requests. Currently if one of the request fails then (by design I guess) only `.catch()` evaluates and not the .`then()`.

I should mention I'm using `.all()` with a varying number of requests in a fashion similar to what was done on this [S/O](http://stackoverflow.com/questions/37149466/axios-spread-with-unknown-number-of-callback-parameters):

```javascript
let urlArray = [] // unknown # of urls (1 or more)

let promiseArray = urlArray.map(url => axios.get(url)); // or whatever
axios.all(promiseArray)
.then(function(results) {
  let temp = results.map(r => r.data);
  …
});
```
Has anyone successfully done this?

**Comment by rubennorte** [comment]
Axios returns promises so you can apply any promise-related technique that allows that. Maybe there's an external package for that (Bluebird or standalone) but I'd do something like:

```javascript
function useNull() {
  return null;
}

axios.all([
      axios.request(options[ 0 ]).catch(useNull),
    , axios.request(options[ 1 ]).catch(useNull),
    , axios.request(options[ 2 ]).catch(useNull)
]).then(axios.spread(function (res1, res2, res3) {
    // res1, res2, and res3 contains the response or null if they failed
}));
```

**Comment by ihatehandles** [comment]
I see, thanks. Probably not the best place to ask this, I was going to ask if there's a way to not have the callback called once all the promises are complete - but for the callback to be called for each of them that  completes. Will ask on S/O since maybe that's more to do with promises in general than axios, but would make a great addition to the docs I think (for concurrent requests with progress)

**Comment by vksbansal** [comment]
Thanks for your efforts to provide a solution @rubennorte and request you confirm

will the ```response of the request``` come on the same position on which the ```request``` was placed

e.g.

request 
1
2
3

response after ```axios.spread```
1
2
3

**Comment by ansarikhurshid786** [comment]
you are right. I am facing same issue. @vksbansal

**Comment by ansarikhurshid786** [comment]
@vksbansal 
I think following code resolve : 
```
axios.all([
      axios.request(options[ 0 ]).catch(useNull),
    , axios.request(options[ 1 ]).catch(useNull),
    , axios.request(options[ 2 ]).catch(useNull)
]).then(axios.spread(function (res1, res2, res3) {
    // res1, res2, and res3 contains the response or null if they failed
}));
```
@rubennorte solution.
