### ISSUE TITLE
Cannot do http and https in the same instance with an "agent" option

### ISSUE THREAD

**Issue by rubennorte** [mzabriskie/axios#386]
We cannot reuse an axios instance with a custom `agent` if we plan to do both http and https requests. If we try to do an https request with an http agent (or vice versa) it throws an error.

In this case we have to create different axios instances, one for http requests and another for https requests.

In order to make this work we could replace the `agent` option with `httpsAgent` and `httpAgent`.

**Comment by nickuraltsev** [comment]
Fixed by #387.
