### ISSUE TITLE
[Feature Request] Support for Protocol Buffers

### ISSUE THREAD

**Issue by incubus8** [mzabriskie/axios#388]
Hi @mzabriskie,

It would be nice if Axios will be the library that can support Protocol Buffers response by default not only JSON.

Thank you.

Best,

---

**Comment by rubennorte** [comment]
This is something you can implement using the `transformResponse` config option or using response interceptors.

Supporting it by default in axios would increase significantly the bundled size, given that we need to include a dependency to parse the received data against a schema. It also doesn't look like something most of our users will use, so I think the best way to go is like I said at the beginning. That feature could also be included in some axios plugin so you don't have to repeat the code every time.
