### ISSUE TITLE
Question: Is there a way view/modify config settings prior to request

### ISSUE THREAD

**Issue by j-funk** [mzabriskie/axios#389]
Is there any way to modify the config before a request is made? For instance I'd like to introspect `config.method` and depending on the method choose a setting for `config.headers`.

**Comment by rubennorte** [comment]
Yes, you can use a request interceptor for that. E.g.:

```javascript
axios.interceptors.request.use(function(config) {
  if (config.method === 'get') {
    config.headers.foo = 'bar';
  }
  return config;
});
```

**Comment by j-funk** [comment]
That did the trick, thanks!
