### ISSUE TITLE
route-specific interceptors

### ISSUE THREAD

**Issue by aaronshaf** [mzabriskie/axios#39]
Perhaps there is already a way to do this. It would be nice to be able to do route-specific interceptors in a express-familiar style, such as:

```
var axios = require('axios')
axios.interceptors.request.use('/foo', function(config) {
  // ...
})
```

This is relevant to me lately since I want to put a client-only caching layer in front of my isomorphic controllers in a React app.

**Comment by jmdobry** [comment]
Right now the only way to do this would be to have an interceptor that inspects the route in the `config` argument and then decides what to do/whether to do anything.

**Comment by mzabriskie** [comment]
@jmdobry is right, you would have to add a generic interceptor, then check `config.url` to see if it matches what you are looking for.

If you are just doing this for caching, I have caching on the roadmap for axios. Should be ready soon.

**Comment by nickuraltsev** [comment]
You can create a new instance of axios and set interceptors only for that instance:

```js
var instance = axios.create({
  baseURL: 'https://some-domain.com/api/'
});
instance.interceptors.request.use(function () {/*...*/});
```
