### ISSUE TITLE
[Question] How to get the redirect chain?

### ISSUE THREAD

**Issue by j** [mzabriskie/axios#390]
So, I see that behind the scenes, this library uses the "follow-redirects" package.  I need to be able to access the last requested URL of the redirect chain.  "follow-redirects" adds this to the response, but axios ignores it.  Any way to get the redirect chain ever using res.fetchedUrls or other manual methods?

**Comment by rubennorte** [comment]
It's a bit hacky but you can. With the response you have the original node.js request which has the original response as a `res` property. E.g.:

```javascript
axios.get(...).then(function(response) {
  var fetchedUrls = response.request.res.fetchedUrls;
});
```

**Comment by hbarcelos** [comment]
The solution is not working on `node@8.9.3` and `axios@0.17.1`. Any idea why?

**Comment by heipei** [comment]
Same here, is there still a way to easily get the redirect chain? @hbarcelos did you find out anything?

**Comment by hoanganh25991** [comment]
When debug, i see redirect url under `responseURL` key, get fetchedUrls by:
`const fetchedUrls = response.request.res.responseURL;`

#### Debug screenshot
![image](https://user-images.githubusercontent.com/8801188/37633621-ac57ea9e-2c25-11e8-86b2-0a34d5f09c06.png)

#### Environment
node: v8.9.4
axios: ^0.18.0

**Comment by mcapodici** [comment]
@hoanganh25991 answer works for me - if I change the casing:

`const fetchedUrl = response.request.res.responseUrl;`
