### ISSUE TITLE
Encoding Error caused by react-native XMLHttpRequest.

### ISSUE THREAD

**Issue by wzl002** [mzabriskie/axios#393]
My project request data with Chinese. But some times the data response from server would be a unreadable string.
After debug，we found that it is cause by the ‘XMLHttpRequest’ object support by RN. 
It's a issues of react-native, but we found we just can't change the axios adapter to 'http'. 

dispatchRequest.js
```
 var adapter;

  if (typeof config.adapter === 'function') {
    // For custom adapter support
    adapter = config.adapter;
  } else if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('../adapters/xhr');
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapter = require('../adapters/http');
  }
```
Could you please teach me a way to change the adapter to 'http'?  I don't know if 'http' can work in react-native, or you can show me a adapter for 'fetch'?

For this project, would you like to change the default adapter to 'http' in react-native? or create a 'fetch' adapter?

Thanks

**Comment by nickuraltsev** [comment]
The `http` adapter uses node's `http` module under the hood. I don't believe the `http` module is available in React Native environment so the `http` adapter will not work there.

There are no plans to create a `fetch` adapter at the moment. Have you tried to use `fetch` directly to check if it doesn't have the same issue?

**Comment by wzl002** [comment]
@nickuraltsev  Yes, I tried to use `fetch`, and It's OK. And I write a simple 'fetch' adapter for our RN project by my self, but I thought it didn't support enough `config` correctly, so I wish would you show a official example.
Thanks for reply

**Comment by nickuraltsev** [comment]
@wzl002 You can use the `xhr` adapter as an example. The code can be found here: https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js.
