### ISSUE TITLE
302 received but browser does not redirect.

### ISSUE THREAD

**Issue by kayazinc** [mzabriskie/axios#396]
Use-case:
1.  User clicked on the add button at quote page.
2.  Add quote request is send async (using Axios) to server.
3.  Server check and found user not logon.
4.  Server send a redirect 302 back to browser.
5.  Browser received 302 but does not redirect to the login page.  (view remain in quote page)
![axios 302 does not redirect](https://cloud.githubusercontent.com/assets/19774010/17317523/2a92d4ae-58b1-11e6-8d7b-4011fc6f7f3f.PNG)

Extra notes: using redux (front-end) and nodes (server).

Please advise me on the possible reasons what went wrong.  Thanks in advance.

**Comment by nickuraltsev** [comment]
@kayazinc If you make a request via axios (or the [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) directly), the browser will not automatically redirect on 302. You need to implement this logic in your application.

**Comment by kayazinc** [comment]
@nickuraltsev thanks for the response.

I've googled and find out that the redirect is automatically followed by the browser. (http://stackoverflow.com/questions/282429/returning-redirect-as-response-to-xhr-request).

I'm kinda confused.  Are you able to point me to any links / keyword which describe the overview of implementing the logic for the redirection in my application?

**Comment by ganesharulanantham** [comment]
@kayazinc Did you find the solution?

**Comment by Aterr** [comment]
same problem here.

**Comment by newtrat** [comment]
**The Problem:**
I think that when you send a 302 in response to an Axios request, the browser interprets that to mean you want to redirect the Axios request it just sent out, not the web page as a whole.

The process is:
1. You send a request to `quote` using Axios.
2. Your server responds with a 302, saying "no, redirect to logon." Note that the name for the 302 response is "Found" -- what it means is "The content you were looking for exists, but in a different location." So...
3. Your browser hears that the stuff it was looking for at `quote` is actually at `logon` instead. So it sends another request to `logon` **through Axios**. In other words, it sends another asynchronous request in the background. The user isn't aware of anything happening.
4. Your server responds with a 200, and tells your browser the contents of the `logon` page.
5. Your browser reads these contents, but it's still doing all this work in the background, so the user isn't redirected. The browser sees what `logon` should look like, but it doesn't display anything to the user.

**Possible Solution:**
I think your server should instead respond with something like 401 Unauthorized. Then you'd look for this response in Javascript and, if you saw it, you'd redirect using Javascript. This is what nickuraltsev meant by implementing logic in your application.

Example:
```javascript
axios.post("quote", params)
  .catch(function(error) {
    if (error.response && error.response.status === 401) {
      window.location.href = "logon";
    } else {
      // Handle error however you want
    }
  });
```

**Comment by Vivek205** [comment]
@newtrat , But client side redirections are not safe, so is there any other way to perform server side redirection `using just 302` response and `not` with `window.location.href`

**Comment by newtrat** [comment]
@Vivek205 Could you explain what's unsafe about the Javascript redirection? If your user's on a typical browser with Javascript enabled, it will respect changes to `window.location.href` just like it would respect a 302 response. If your user is malicious, they can ignore the 302 just as easily as they can ignore Javascript. Both of these methods of redirection are clientside.

As long as your server refuses to perform operations for logged-out users, you should be safe no matter what the client does.

If you want to redirect with just 302, you can do that by making the original request run in the foreground. For example, instead of making a request with Axios, you could use an HTML form submission.
```html
<form action="/path/on/your/server" method="post">
  <!-- ... -->
</form>
```

**Comment by Vivek205** [comment]
@newtrat , that is a valid point, but I'm worried about two things
1. whether a third party extension can inject an object to the application and manipulate the behavior of the `window` object.
2. we're using API gateway lambda functions. so we cannot use `form-actions`.

**Comment by newtrat** [comment]
@Vivek205
1) I don't know enough about JS security to talk about this with confidence. Both browser extensions and third-party JS can access JS on the page, but I don't think they're able to change the behavior of `window.location`. Browser extensions (but not JS, as far as I know) can "see" 302 redirects, but I don't think they can prevent them from happening.
    - If your code is accessible globally, they may be able to stop you from trying to set `window.location.href` in the first place. But in this case, they can modify all your code, not just this redirect.
    - If your code isn't accessible globally, like it's hidden in an IIFE, then I don't know of a way third-party JS can stop the redirect.
2) I might be misunderstanding, but it sounds like you're running Javascript on a website whose HTML you don't control. If you can't modify the form, I don't know of a way to force the browser to redirect without Javascript. But a JS redirection is no more vulnerable to attack than the rest of your JS. If you don't control the JS, either, but only your server's response, then I think you have no way to force a redirect.
