### ISSUE TITLE
How can I set authorization token or x-access-token in the header using axios?

### ISSUE THREAD

**Issue by JianSOM** [mzabriskie/axios#398]
Hi, in my REACT app, I am trying to pass the authorization or x-access-token in the header using axios to all my api calls. I keep getting "Response for preflight has invalid HTTP status code 403"

const token = 'xxx';
axios.defaults.headers.common['Authorization'] ='Bearer ' + token;

or 
axios.default.headers['x-access-token'] = token;

Please help! Thanks!

**Comment by nickuraltsev** [comment]
When a web app makes a CORS request (a request to a server that runs on a different host or port than the web app), the browser sends a preflight (`OPTIONS`) request first. (Please see [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) for details.) Make sure that your back-end handles `OPTIONS` request properly.
