### ISSUE TITLE
Example of mocking response with interceptor

### ISSUE THREAD

**Issue by aaronshaf** [mzabriskie/axios#40]
I would like to intercept a request and then pre-emptively resolve with a response (compare https://github.com/trek/pretender). Is there an example of this being done elsewhere?

**Comment by aaronshaf** [comment]
From what I can tell, this isn't possible with the current version of axios.

**Comment by mzabriskie** [comment]
Is this to accommodate a test scenario?

**Comment by aaronshaf** [comment]
Yes, that and caching

**Comment by mzabriskie** [comment]
With version 0.6.0 you will be able to specify a custom adapter, which facilitates testing. There will also be built in caching of GET requests.

There's also this neat lib that is inspired by pretender that you could use https://github.com/aaronshaf/xhr-interceptor :)

**Comment by resistdesign** [comment]
@mzabriskie How do you specify a custom adapter now?

**Comment by mzabriskie** [comment]
@resistdesign functionalist didn't make the cut for 0.6.0. Will work on this for a future release.

**Comment by DominicTobias** [comment]
Any update on this? I much prefer axios's Promise api than superagent's but I would need a way of mocking to adopt it. Thanks

**Comment by aeirola** [comment]
You can do this with axios' interceptors by failing each request, but resolving the promise in the response error handler.

```javascript
// Add request interceptor to force the request to fail
axios.interceptors.request.use((config) => {
  // Mangle URL to skip network request
  config.url = 'http://localhost:0/' + config.url;
  return config;
});

instance.interceptors.response.use((response) => {
  // Shouldn't really be called, ever
  return response;
}, (error) => {
  /* Returning a resolved promise from error handler
     will make final promise resolve as though the request
     would have returned successfully */
  return Promise.resolve({
    data: {/* response data */},
    status: 200,
    statusText: 'OK',
    headers: {},
    config: error.config
  });
});

**Comment by mzabriskie** [comment]
For anyone looking to address mocking for a test scenario I have created [moxios](https://github.com/mzabriskie/moxios).
