### ISSUE TITLE
Cross domain browser version

### ISSUE THREAD

**Issue by ThuyLeVan** [mzabriskie/axios#404]
Nodejs:
```
var  axios  =  require("axios");  

axios.get("https://www.google.com.vn")  
	.then(function (response)  {  
      console.log(response);  
       })  
	.catch(function (error)  {  
         console.log(error);  
     });
```
It work perfect !
But when i run it in browser version:
```
<script src="https://npmcdn.com/axios/dist/axios.min.js"></script> 
<script>
axios.get("https://www.google.com.vn")  
	.then(function (response)  {  
      console.log(response);  
       })  
	.catch(function (error)  {  
         console.log(error);  
     });
</script>
```
Error:
```
XMLHttpRequest cannot load https://www.google.com.vn/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.
localhost/:9 Error: Network Error(…)
```

What  i missing ? Sorry i new to axios

**Comment by nickuraltsev** [comment]
Your code makes a `CORS` request to a resource on another domain, but the server does not support `CORS`. You can learn about `CORS` here:
- http://www.html5rocks.com/en/tutorials/cors/
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by ThuyLeVan** [comment]
So , the browser version used to do while not cross domain?

**Comment by nickuraltsev** [comment]
axios can be used to make cross-origin requests as along as the server supports that.

**Comment by ThuyLeVan** [comment]
Thanks @nickuraltsev !

**Comment by batjko** [comment]
@nickuraltsev So what is a server doesn't send a cors header (and it's not your server so you can't change that), how would axios handle this? 
We're still getting this issue.

**Comment by Uniphix** [comment]
Yeah I am getting this issue to and it's driving me nuts, only happening on firefox

**Comment by ngtranthanhtoan** [comment]
I'm using jquery and it's working just fine. But it's still got error with axios
