### ISSUE TITLE
Unexpected token (2:9) while parsing axios's package.json

### ISSUE THREAD

**Issue by asiniy** [mzabriskie/axios#405]
I'm looking at this strange message every time I'm running my webpack build. How can I fix that?

```
ERROR in ./~/axios/package.json
Module parse failed: /my_project/node_modules/axios/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
```

**Comment by nickuraltsev** [comment]
I have not seen your webpack configuration, but most likely you need to exclude `node_modules`:

```js
module: {
  loaders: [
    {
      test: /\.js$/,
      exclude: /node_modules/,
      // ...
    }
  ]
}
```

**Comment by asiniy** [comment]
@nickuraltsev it's excluded:

``` javascript
module.exports = {
  entry: {
    component: "./web/static/js/application.js",
  },
  target: "node",
  output: {
    path: "./priv/server/js",
    filename: "component.js",
    library: "Application",
    libraryTarget: "commonjs2"
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: "babel-loader",
      query: {
        presets: ["es2015", "react"]
      }
    }, {
      test: new RegExp(`/
        stardust
        |utils/errors.js
        |sign_in
        |modal
        |redux-form
      `),
      loader: "null-loader"
    }],
  },
  resolve: {
    alias: {
      phoenix_html:
        __dirname + "/deps/phoenix_html/web/static/js/phoenix_html.js",
      phoenix:
        __dirname + "./deps/phoenix/web/static/js/phoenix.js"
    }
  }
};
```

**Comment by nickuraltsev** [comment]
Since your code is compiled to run in node.js (`target: "node"`), you need to use `json-loader`:

```js
{
  test: /\.json$/,
  loader: 'json'
}
```

That's because axios node adapter `requires` package.json. You would not need to use `json-loader` if your code was compiled for usage in a browser.

**Comment by Getitdan** [comment]
Just to add on @nickuraltsev's answer, you should use 'json-loader', like:

```
{
  test: /\.json$/,
  loader: 'json'
}
```

> BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
>                      You need to specify 'json-loader' instead of 'json',
>                      see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
>
