### ISSUE TITLE
Axios patch request is not working.

### ISSUE THREAD

**Issue by jaingeet** [mzabriskie/axios#408]
var config = {
    headers: {
         'Content-Type': 'application/x-www-form-urlencoded'
    },
    withCredentials: true,
}
var payload = axios.patch(url, {} , config);

It throws an error -  XMLHttpRequest cannot load "request_url". Response for preflight has invalid HTTP status code 405

**Comment by nickuraltsev** [comment]
Your code makes a `CORS` request, but the server cannot handle preflight (`OPTIONS`) requests. You can learn about `CORS` here:

- http://www.html5rocks.com/en/tutorials/cors/
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by jaingeet** [comment]
@nickuraltsev When Im hitting as POST request it is working fine. And i checked it too that PATCH request is allowed at server.
