### ISSUE TITLE
No release notes/upgrade guide for 0.9.1 -> Latest

### ISSUE THREAD

**Issue by brendensoares** [mzabriskie/axios#411]
The error handling changed by adding a new `response` property to the `error` object on `catch()` since `v0.9.1`, but I see no mention of it anywhere.

Am I missing something? Does a a change log exist?

**Comment by nickuraltsev** [comment]
Yes, it's documented [here](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#error-handling).

**Comment by brendensoares** [comment]
It's not clear that there id a breaking change in subsequent releases.

It seems the [upgrading guide](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md) mentions the breaking change, it just wasn't clear to me that `v0.9.1` was affected.

Thanks for clarifying.
