### ISSUE TITLE
Validate status not properly rejecting

### ISSUE THREAD

**Issue by macnibblet** [mzabriskie/axios#412]
According to the documentation if validateStatus returns false then the promise is rejected. Well thats not the case for me, i'm only seeing the promise being resolved.

```javascript
    let body = new URLSearchParams();

    body.append('grant_type', 'password');
    body.append('username', username);
    body.append('password', password);

    return axios
      .post('backend://oauth/token', body)
      .then((response) => {

        console.dir(response.config.validateStatus(response.response.status));

        this.writeToLocalStorage({
          ownerId: response.data.owner_id,
          accessToken: response.data.access_token,
          refreshToken: response.data.refresh_token,
          expiresIn: response.data.expires_in
        });

        return this
          .getById(this.oauthToken.ownerId)
          .then((user) => {
            this.currentUser = user;
            return user;
          });
      })
      .catch((error) => {
        if (error.response.status === 400) {
          throw new OAuthError(error.response.data);
        }

        throw new UnexpectedApiError(error.response);
      });
```

**Comment by macnibblet** [comment]
The current hack I have to resolve this issue is the following, and it's the first few lines of the resolved fat arrow function. 
```javascript
        // todo: remove this, when the bug is resolved https://github.com/mzabriskie/axios/issues/412
        if (response instanceof Error) {
          return Promise.reject(response);
        }

```

**Comment by mzabriskie** [comment]
What version of axios are you using and are you making requests in node or browser?

**Comment by macnibblet** [comment]
0.13.1 in the browser

**Comment by mzabriskie** [comment]
Thanks for the response. I'll take a look at it.

**Comment by rubennorte** [comment]
Could the error be here?

```javascript
console.dir(response.config.validateStatus(response.response.status));
```

The status code should be in `response.status` not `response.response.status`.

Could you please check?

**Comment by macnibblet** [comment]
@rubennorte Please read the issue again :p

**Comment by rubennorte** [comment]
@macnibblet What I meant is that your way of "debugging" what `validateStatus` was returning is not correct, as you weren't passing the right value.

What's really weird in this case is that Axios is resolving with an error instance (according to your fix). Could you add more information about that error? Does it contain a `response` property? What's its `status` value?

**Comment by macnibblet** [comment]
@rubennorte Actually I found the cause of the issue it was related to an edge-case in a interceptor one of my minions added.

**Comment by hannes-dahlberg** [comment]
@macnibblet Found this issue when having the same problem as you and ended up with the same solution. An interceptor was causing the problem. Thank you.
