### ISSUE TITLE
Headers lower cased

### ISSUE THREAD

**Issue by isterin** [mzabriskie/axios#413]
Why are the header names being lowered cased when parsed?  Per the specification, header names are case sensitive.  I'm not sure if this is a bug or intended that way?

**Comment by rubennorte** [comment]
It is intended. Header names are case insensitive. You can see it in the spec [here](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

**Comment by stephan-v** [comment]
So why bother touching them if it does not matter anyways?

**Comment by FabianoLothor** [comment]
When this will be fixed?

**Comment by TCezarRod** [comment]
> So why bother touching them if it does not matter anyways?
I see this as a convenience. If the headers are case-insensitive, and axios always lower cases them, we can always expect them to be lower cased and deal only with that variant.
If axios didn't lower case the headers, we would always have to deal with all variants of the strings, probably always parsing them to our case of choice before using it.

**Comment by dehghani-mehdi** [comment]
At least add an option to control this behavior.

**Comment by determin1st** [comment]
I think that's the correct logic to justify non-determinism.

Headers SHOULD BE lowercased.
