### ISSUE TITLE
Uploading blob - data is empty

### ISSUE THREAD

**Issue by wojciech-bilicki** [mzabriskie/axios#415]
Hi, 
I am trying to upload blob (image) along with some params, but no matter what I can't seem to put the data in the body of the request.

```
let blob = new Blob(animal.photos, {type: 'image/png'});
      axios.post( API_URL + 'v1/files/upload/' + animal.photos[0].name ,
       {data: blob},
        {
          params: {
            animalId: response.data.id
          }
        })
```

Here's screenshot of google developer tools.

<img width="545" alt="screen shot 2016-08-14 at 14 00 44" src="https://cloud.githubusercontent.com/assets/10365887/17648953/8e2ba9da-6227-11e6-887f-fc1acda8b520.png">

What I am trying to do is to send the image binary data as the body of the request to the API, not sure where I am going wrong with this.

BTW I get 500 code, because body is empty.

**Comment by wojciech-bilicki** [comment]
NVM I was doing it wrong after all

1) Remember to choose correct 'Contect-Type'
2) I'm sending File not a Blob now and it works great

**Comment by codewithcats** [comment]
@wojciech-bilicki What is the correct 'Content-type' you use? I have the same issue and trying to figure it out.

**Comment by bericoberin** [comment]
+1  I need the same!

**Comment by JeSuis** [comment]
@bericoberin `headers: { 'content-type': 'multipart/form-data' }`

**Comment by AtNovember** [comment]
> headers: { 'content-type': 'multipart/form-data' }


I also put the same content-type value,
but in Network tools see, thet my File instanse became empty object, just {}

**Comment by JamesSchiiller** [comment]
The trick is
- FormData()
- boundry in header

```
  const data = new FormData()
  data.append('file', file, file.name)
  
  axios({
    method: 'post',
    url: "http://localhost:4000/upload",
    data: data, 
    headers: {
      'Content-Type': `multipart/form-data; boundary=${data._boundary}`,
    }
  })
```
