### ISSUE TITLE
Progress capturing doesn't work when method names are capitalized

### ISSUE THREAD

**Issue by diesal11** [mzabriskie/axios#417]
The code [here](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L145) relating to ProgressEvents doesn't work when the method type passed to Axios isn't lowercase. I.E. `get` will attach the download handler but `GET` will not.

Also, was there a reason that you only attach to `POST/PUT` for upload and `GET` for download? We've hit a bit of a blocker as the API we're calling can return large files from a `POST/PUT` and we need to attach a download progress listener to those requests which we can't do.
In theory, if someone set the `progress` property of the request config then wouldn't it be a reasonable assumption that they want to get ProgressEvents regardless of the method sent?

Happy to provide PRs, just want to clarify the direction you want first 😄

**Comment by mzabriskie** [comment]
Yes it would be better to use `config.method.toLowerCase()`. I am not sure how we ended up with just `POST/PUT` and `GET`. If you want to expand this, would be happy to accept a PR.

**Comment by diesal11** [comment]
PR is done. :)
#423

**Comment by nickuraltsev** [comment]
Fixed via #423
