### ISSUE TITLE
Post not sending data properly

### ISSUE THREAD

**Issue by Adman** [mzabriskie/axios#418]
Hello,
I have a django application where I want to make POST by clicking on `<button>` which is not in `<form>`
The problem is that data sent to view function are not being sent properly.

Here is axios code:
```javascript
 axios({
        method: 'post',
        url: '/url/to/view'
        data: {
            obj_id: objectid,
            content_type: contenttype,
            like: !is_liked
        },
        xsrfCookieName: 'csrftoken',
        xsrfHeaderName: 'X-CSRFToken',
        headers: {'X-Requested-With': 'XMLHttpRequest',
                  'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'},
    }).then(function (response) { 
        console.log(response);
    });
```

and here view code:
```python
def my_view(request):
    print request.POST
    return HttpResponse('XX')
```

I cannot access request.POST data because the key is entire dict and value empty list:
`<QueryDict: {u'{"obj_id":"182","content_type":"video","like":true}': [u'']}>`

**Comment by nickuraltsev** [comment]
The problem is that objects are serialized to JSON by default while you need to send the data in the `application/x-www-form-urlencoded' format. The easiest solution is to use a library like [qs](https://github.com/ljharb/qs):

```js
var qs = require('qs');
axios.post('/foo', qs.stringify({ 'bar': 123 });
```

See [this comment](https://github.com/mzabriskie/axios/issues/350#issuecomment-227270046) for details.

Hope this helps!

**Comment by bubuzzz** [comment]
Another way is putting the values into the FormData object and post

**Comment by vanpav** [comment]
I wrote [small wrapper](https://gist.github.com/vanpav/99958bd1b583df4b6c42290515d28bdd) aroud axios which works fine with default Django >1.8 settings. Hope this helps somebody!

**Comment by AliNajafi98** [comment]
Hi every body !
How can i use Axios request in my django API with request.body?
actually what i mean is how it works and how can i extract the httpreques data from it? (i know body.request send a json)
