### ISSUE TITLE
Delete not supported?

### ISSUE THREAD

**Issue by chobo2** [mzabriskie/axios#424]
Hi

I keep getting "DELETE http://localhost:54690/api/Storage/Delete 415 (Unsupported Media Type)" when I try to use axios delete.

```
export const axiosInstant = axios.create({
  baseURL: 'http://localhost:54690/api',
  timeout: 10000,
  headers: { 'Content-Type': 'application/json' }
});

export function deleteSelectedStorage(storage) {
    return function (dispatch) {
        return axiosInstant.delete('/Storage/Delete', { storage: storage}).then(function () {
            dispatch({
                type: actions.SELECTED_STORAGE_DELETED,
                payload: {
                    selectedStorage: storage
                }
            });
        });
    }
}


```
am I doing something wrong?

**Comment by nickuraltsev** [comment]
This means that the server does not accept `application/json` content for this URI and HTTP method (`GET /api/Storage/Delete`).

**Comment by chobo2** [comment]
hmm, when I use postman and setup my header to application/json and put a body in it. It works. Just not through axios. So not sure what I am doing wrong.

**Comment by nickuraltsev** [comment]
I think I know what's going on. You are trying to make a request with a body using `axios#delete` which does not accept request body as a parameter. Please try to use `request` method instead:

```js
instance.request({
  url: '/Storage/Delete',
  method: 'delete',
  data: { storage: storage }
});
```

**Comment by chobo2** [comment]
How does the shorthand .delete work then? there is not example on it?

**Comment by nickuraltsev** [comment]
`delete` accepts the following two parameters:
- url
- config (optional)

It's documented [here](https://github.com/mzabriskie/axios#axiosdeleteurl-config).

The available config options are documented [here](https://github.com/mzabriskie/axios#request-config).

**Comment by 8bitjoey** [comment]
So @chobo2 can basically use:

```
axios.delete(url, { data: {storage: storage}})
```

right?
