### ISSUE TITLE
Is there something wrong with my code ,i can't get de correct response with post?

### ISSUE THREAD

**Issue by cddsgtc** [mzabriskie/axios#426]
It's just a test , the get method is ok,but this get a wrong back ,it confused me alot.
js code
```
function getData(){
      var d = document;
      var account = d.getElementById('account').value;
      console.log(account);
      var password = d.getElementById('password').value;
      axios.post('/register.php',{
       firstName:'cdd',
       password:'123456'
      })
   .then(function (response) {
     console.log(response);
     d.getElementsByClassName('h3')[0].innerHTML = response.data;
   })
   .catch(function (error) {
     console.log(error);
   });
 }
```
php code 
```
<?php
	echo 'name is ：'.$_POST['firstName'];

?>
```
Thr response is 
    
    Object {data: "
    ↵<br />↵<b>Notice</b>:  Undefined index: firstNam…register.php</b> on line <b>3</b><br         />↵name is ：", status: 200, statusText: "OK", headers: Object, config: Object…}

**Comment by nickuraltsev** [comment]
Looks like the problem is that the server expects the data to be in the `application/x-www-form-urlencoded` format, while axios sends objects in the `json` format by default.

Please see [this comment](https://github.com/mzabriskie/axios/issues/350#issuecomment-227270046) for details.

Hope this helps!

**Comment by cddsgtc** [comment]
@nickuraltsev ok，if i use the file_get_contents('http://input') in the server side ,it will correctly process.

**Comment by cddsgtc** [comment]
And thank you for your help.

2016-08-28 4:28 GMT+08:00 Nick Uraltsev <notifications@github.com>:

**Comment by bmarchete** [comment]
@cddsgtc  I've handled the same issue. I used this solution:

When you send the `axios.post`, you can attach the parameters in the url, like

`axios.post('http://api?name=some-name')`

Don't forget to receive the values in the server side using $_REQUEST, like

```php
header('Content-type: application/json');
$name = $_REQUEST['name'];
```

It works for me!
