### ISSUE TITLE
Error: Request failed with status code 422

### ISSUE THREAD

**Issue by sajumani** [mzabriskie/axios#428]
Hi,

am getting error,  in my catch function not handling errors
Error: Request failed with status code 422
var error = new Error(message);

**Comment by sajumani** [comment]
Itseem your plugin issue.. i fixed ...!!!

**Comment by jalaluddin94** [comment]
how do you resolve the error 422? I read there must be a semantycal error in the axios request. I am making an axios POST request to fastAPI with correct url, and body/payload data (eg. the username and password inserted). But I keep getting the response 422, and there's:
    createError webpack://[name]/./node_modules/axios/lib/core/createError.js?:16
    settle webpack://[name]/./node_modules/axios/lib/core/settle.js?:17
    handleLoad webpack://[name]/./node_modules/axios/lib/adapters/xhr.js?:59

Please help me.
