### ISSUE TITLE
transformResponse data is passed as String, although it is JSON

### ISSUE THREAD

**Issue by bianca93** [mzabriskie/axios#430]
Similar to #378 
```
axios.get(url, {
  headers: {
    'Content-Type': 'application/json'
  },
  transformResponse: [function(data) {
    console.log(data); // "{ name: "apple", type: "fruit"}"
  }]
})
```

data is a String and I have to parse it every time. I have the latest version of axios 0.14.0

**Comment by mzabriskie** [comment]
In your example you are overriding the default `transformResponse` with your own. The default `transformResponse` will parse JSON. Try this instead:

```js
axios.get(url, {
  headers: {
    'Content-Type': 'application/json'
  },
  transformResponse: axios.defaults.transformResponse.concat((data) => {
    console.log(data) // this should now be JSON
  })
})
```

**Comment by ShakurOo** [comment]
@mzabriskie When I do this i have a typescript error : 
`Property 'concat' does not exist on type : '<U>(data: any) = > U'`

What does it mean ? What is <U> type ?  How bypassing this error ?

**Comment by devrelm** [comment]
@ShakurOo `transformResponse` (including `axios.defaults.transformResponse`) is the type `AxiosTransformer | AxiosTransformer[]`, meaning that it technically might or might not be an array. I fixed this with the following:

```ts
{
    transformResponse: [].concat(
        axios.defaults.transformResponse,
        myTransformResponse,
    ),
}
```

`Array.prototype.concat` [automatically flattens arrays one level deep](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat?v=example#Concatenating_values_to_an_array), so it will work correctly no matter whether `axios.defaults.transformResponse` and `myTransformResponse` are objects, arrays, or mixed.

**Comment by vasilevich** [comment]
why is transformResponse so inefficent? why no checking weather the client expects JSON, or anything, and no ability to access the headers?

**Comment by blowsie** [comment]
To simplify i did this
```
axios.get(url, {
  headers: {
    'Content-Type': 'application/json'
  },
  transformResponse: [
    ...axios.defaults.transformResponse.concat(),
    function(data) {
        console.log(data); // "{ name: "apple", type: "fruit"}"
    }
  ]
})
```
