### ISSUE TITLE
Release version 1?

### ISSUE THREAD

**Issue by achingbrain** [mzabriskie/axios#432]
I've seen #206 and it's wishlist of features for a v1 release, but this library has had over 300,000 downloads in the last month according to npm's website, plus however many bower users too.

The [semver spec](http://semver.org) says:

> **How do I know when to release 1.0.0?**
>
> If your software is being used in production, it should probably already be 1.0.0

It's definitely being used in production, so how about it?

**Comment by mzabriskie** [comment]
I agree. If we can get #50 figured out (being worked on by @nickuraltsev AFAIK) as well as #257 we will release a 1.0.

**Comment by achingbrain** [comment]
Not sure those issues would stop me from releasing a v1 😉  - cancelling Promises is a problem bigger than this library and IMHO the README.md is comprehensive enough to stand in for a documentation website for the time being.

The reason I bring it up is I have a project that has a few different versions of axios in the dependency tree - 0.13, 0.14, etc with no observed functional difference between them - the multiple versions play havoc when trying to stub them in our testing, set global defaults, etc.  If v1 were to be released they could all resolve to the same version (e.g. `^1.0.0`) which would make life much simpler.

**Comment by WillGibson** [comment]
Just stumbled across this after wondering how a project that has been around and so heavily used for over four years has not made it to `1.0.0` yet ;-)
