### ISSUE TITLE
Error: incorrect header check at Zlib._handle.onerror when POST in axios

### ISSUE THREAD

**Issue by iroy2000** [mzabriskie/axios#435]
I setup my own node express application, and when I'm trying to do POST, I got an error when I do a POST from client side

```
// client side code
axios.post(MY_TEST_URL, data)
    .then(response => {
      console.log(response);
      return response.data
    })
```

**And I got this error from my node express server**

```
{ Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR', status: 400, statusCode:
 400 } 'Error: incorrect header check\n    at Zlib._handle.onerror (zlib.js:370:17)'

```

**And the following is the header I received in the error handling from my express error handling**

```
{ host: 'localhost:9898',
  connection: 'keep-alive',
  'content-length': '13',
  accept: 'application/json, text/plain, */*',
  origin: 'http://localhost:8080',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36',
  'content-type': 'application/json;charset=UTF-8',
  referer: 'http://localhost:8080/',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'en-US,en;q=0.8',
  'content-encoding': 'gzip' } 
```

**The following is my "Network Tab"**

( This one is Preflight Check )
![screen shot 2016-09-02 at 8 48 32 pm](https://cloud.githubusercontent.com/assets/487520/18222521/d1c3beb8-714e-11e6-8ad8-d5e7b05e1a15.png)

![screen shot 2016-09-02 at 8 48 52 pm](https://cloud.githubusercontent.com/assets/487520/18222522/d6f37a5e-714e-11e6-9f7a-5cfb71e9d598.png)

**And this is the curl generate from chrome devtool when I observe my frontend application**

```
curl 'http://localhost:9898/api/test' -H 'Content-Encoding: gzip' -H 'Origin: http://localhost:8080' -H
 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' -H 'Content-Type: 
application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Referer: 
http://localhost:8080/' -H 'Connection: keep-alive' --data '{"email":"me@gmail.com"}' --compressed
```

It is totally fine when I do that from POSTMAN.

Any help will be appreciated, thanks.

**Comment by rubennorte** [comment]
Compression is done automatically in the browser, so it must be something unrelated to axios. Please test it with a newer version of your browser or maybe check if there's a bug in Node or Express about this.
