### ISSUE TITLE
peerDependency or devDependency?

### ISSUE THREAD

**Issue by hnordt** [mzabriskie/axios#439]
Hello.

I built a Fetch component on top of axios for React:

```js
const IPAddressWidget = () => (
  <Fetch url="https://api.ipify.org?format=json" lazy={true}>
    {({ fetching, data, error, fetch }) => {
      if (fetching) {
        return <i className="fa fa-spinner fa-spin" />
      }
      if (data) {
        return <p className="text-success">Your IP Address is {data.ip}</p>
      }
      if (error) {
        return <p className="text-danger">Something bad happened</p>
      }
      return (
        <button className="btn btn-link" type="button" onClick={() => fetch()}>
          What is my IP Address?
        </button>
      )
    }}
  </Fetch>
)
```

Source code: https://github.com/smalldots/smalldots/blob/master/src/Fetch.js

At the moment, axios is a peerDependency, it would introduce a problem if I make it a devDependency?

I choose axios because it has cool features like interceptors and global defaults, that's my main concern, if I make axios a devDependency, and my Fetch component uses axios v0.14 version, it will mess up with global axios v0.13 (it's just an example)?

**Comment by mzabriskie** [comment]
I wouldn't use `devDependencies` for this. It is either `peerDependencies` or `dependencies`.
