### ISSUE TITLE
Interceptor returns string on error and object on success

### ISSUE THREAD

**Issue by sorCrer** [mzabriskie/axios#441]
Hi All,

On version 0.14.0, am I missing something? 

`instance.interceptors.response.use(undefined, err => {
            console.log(err);
        });`

Return an object on success: '{data: Object, status: 200, statusText: "OK",...}'

But on a 401 it returns: 'Error: Request failed with status code 401'

**Comment by sorCrer** [comment]
Update: 

In lib/defaults.js:

`validateStatus: function validateStatus(status) {
    return status >= 200 && status < 300;
}`

Fails for greater status codes greater than 300 so a 401 isn't handled. Setting:

`validateStatus: function (status) {
     return true;
 }`

in the instance config is a workaround.

**Comment by leviathan88** [comment]
With that you've created a bug only, that will send to the first (undefined in your case) callback a valid response even if there is an error (>300) response, do something like this

instance.interceptors.response.use(undefined, err => { 
  const res= err.response;
  console.log(res.status);   //401
})
