### ISSUE TITLE
`axios.defaults.adapter` is null by default

### ISSUE THREAD

**Issue by dan-turner** [mzabriskie/axios#442]
Is there any reason why the `axios.defaults.adapter` property doesn't reflect the behaviour inside `dispatchRequest.js`?

https://github.com/mzabriskie/axios/blob/master/lib/core/dispatchRequest.js#L40

I'm trying to build my own adapter that is capable of falling back to the default adapter under certain circumstances.  With the code as it is I'm forced to duplicate the above if-elseif, i.e.:

```
import axios from 'axios';
if (typeof XMLHttpRequest !== 'undefined') {
  // For browsers use XHR adapter
  axios.defaults.adapter = require('axios/lib/adapters/xhr');
} else if (typeof process !== 'undefined') {
  // For node use HTTP adapter
  axios.defaults.adapter = require('axios/lib/adapters/http');
}
```

**Comment by rubennorte** [comment]
There's actually an open PR for that: https://github.com/mzabriskie/axios/pull/437

I hope it'll be merged soon.

**Comment by dan-turner** [comment]
@rubennorte cheers mate. I notice that your PR seems to also include some extra refactoring. I suspect there was a reason @mzabriskie used the `Promise.resolve(config)` approach to support the adapter function async *or* sync.

I submit this PR as the lightest touch to fix the issue of not having access to the default adapter.

**Comment by rubennorte** [comment]
It has to do with error detection/recovery, not with sync/async as adapters must return promises by definition. I'm discussing it with him now so I think we'll solve it soon.

**Comment by rubennorte** [comment]
It has already been merged. I hope it will bd released soon.
