### ISSUE TITLE
Question :  How to force IPv4 

### ISSUE THREAD

**Issue by dparmar74** [mzabriskie/axios#444]
Core "Http" module has a way to force IPv4 by specifying "family" option.  See example below.  How would I achieve this with "axios"?

var http = require('http');
var options = {
  family: 4,
  host: 'www.google.com',
  path: '/index.html'
}
 
http.get(options, (res) => {
  console.log(`Got response: ${res.statusCode}`);
  // consume response body
  res.resume();
}).on('error', (e) => {
  console.log(`Got error: ${e.message}`);
});

**Comment by nickuraltsev** [comment]
axios does not support the `family` option directly, but you can use a custom agent to achieve this as follows:

```js
var http = require('http');
var agent = new http.Agent({ family: 4 });
axios.get('http://www.google.com/', { agent: agent });
```

You can also set the `agent` at the instance level:

```js
var instance = axios.create({ agent: agent });
instance.get('http://www.google.com/');
```

or at the global level:

```js
axios.defaults.agent = agent;
```

Hope this helps!

**Comment by rubennorte** [comment]
Mind that `agent` option has become `httpAgent` and `httpsAgent` in 0.14.0

**Comment by nickuraltsev** [comment]
@rubennorte Thank you! I've updated my comment.

**Comment by dparmar74** [comment]
Thank you for the suggestions.  It worked with 0.12.0   (agent=agent) version but for 0.14.0 (httpAgent=agent) I'm getting ETIMEDOUT error.   My test case involves making a http call to one of our micro service deployed on AWS EC2.  Just wondering why it doesn't work with 0.14.0 version
