### ISSUE TITLE
Response from server is undefined after updating to 0.14 version

### ISSUE THREAD

**Issue by DimitriMikadze** [mzabriskie/axios#447]
It works perfectly with version 0.12, however after updating to version 0.14 response from server is undefined.

Code snippet React/Redux app:

````
export function signupUser(props) {
  return function (dispatch) {
    axios.post(`${API_URL}/signup`, props)
      .then(() => {
        dispatch({ type: SIGNUP_SUCCESS });

        browserHistory.push(`/reduxauth/signup/verify-email?email=${props.email}`);
      })
      .catch(response => {
        console.log(response); // <============== UNDEFINED
        dispatch(authError(SIGNUP_FAILURE, response.data.error))
      });
  }
}
````

**Comment by nickuraltsev** [comment]
Error handling was changed in v0.13. Please take a look at the [Upgrade Guide](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#012x---0130).

It's not clear why `console.log(response)` outputs `undefined`, but trying to access `response.data.error` will cause an error.
