### ISSUE TITLE
Run interceptor.response only once for multiple API calls at the same time

### ISSUE THREAD

**Issue by leviathan88** [mzabriskie/axios#450]
I have an interceptor like this

```
axios.interceptors.response.use(undefined, err=> {
    const error = err.response;
    console.log(error);
    if (error.status===401 && error.config && !error.config.__isRetryRequest) {
        return axios.post(Config.oauthUrl + '/token', 'grant_type=refresh_token&refresh_token='+refreshToken,
            { headers: {
          'Authorization': 'Basic ' + btoa(Config.clientId + ':' + Config.clientSecret),
          'Content-Type': 'application/x-www-form-urlencoded,charset=UTF-8'
         }
       })
        .then(response => {
          saveTokens(response.data)
          error.config.__isRetryRequest = true;
          return axios(error.config)
        })
      } 
  })
```

When I edit an auth token to be incorrect (in order to simulate its expiry) and I refresh the page, and my (react) component has 4 API calls (i.e. get('/users'), get('/planes')...)  they are called simultaneously so for each API call I send a refresh token and get a new auth token, I would want to do this only once, how can I achieve this? Thanks, and yes I've asked at SO to no avail

**Comment by rubennorte** [comment]
I think you can queue authentication requests with something like:

```javascript
let authTokenRequest;

// This function makes a call to get the auth token
// or it returns the same promise as an in-progress call to get the auth token
function getAuthToken() {
  if (!authTokenRequest) {
    authTokenRequest = makeActualAuthenticationRequest();
    authTokenRequest.then(resetAuthTokenRequest, resetAuthTokenRequest);
  }

  return authTokenRequest;
}

function resetAuthTokenRequest() {
  authTokenRequest = null;
}
```

And then in your interceptor...

```javascript
axios.interceptors.response.use(undefined, err => {
    const error = err.response;
    if (error.status===401 && error.config && !error.config.__isRetryRequest) {
      error.config.__isRetryRequest = true;
      return getAuthToken().then(response => {
          saveTokens(response.data);
          return axios(error.config);
       });
     } 
  });
```

I hope this helps you ;)

**Comment by leviathan88** [comment]
Thanks @rubennorte it works! It's so simple, here is the [SO](http://stackoverflow.com/questions/39509265/run-response-interceptor-only-once-when-multiple-api-calls/) question, if you want to answer it I will accept it, thanks

**Comment by johndatserakis** [comment]
@rubennorte your answer needs to go up on a plaque somewhere - literally just saved my life. Also there's little other mention of this seemingly normal situation other then this thread. Thank you.

**Comment by d3vzer0** [comment]
@rubennorte Found your solution after lots of frustration with multiple async request at the same time. I couldn't find an easy fix to only refresh my token ones for the entire batch of requests. You're a lifesaver ❤️
