### ISSUE TITLE
Testing projects that use axios both server-side and client-side

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [mzabriskie/axios#454]
We're using `axios` both on the back-end, to communicate with some third-party APIs, and on the front-end, to communicate with our back-end. I recently ran into some problems trying to add some client-side tests for code that uses axios. Because axios detects its environment at require time, even using something like `jsdom`, one is constrained to setting up axios as either browser-oriented or node-oriented for the entire test suite. This matters in testing because relative URLs fail when running in node (and possibly other differences).

I see several possible workarounds:

 * have two separate client and server test suites
 * always pass baseURL from window.location.href when using axios on the client
 * always force a client environment via `jsdom` for the whole test suite

None of these seem that great though (with the first one probably being the best and least likely to cause trouble, but requiring more duplicate setup). Any suggestions for how to approach this?

**Comment by uhoh-itsmaciek** [comment]
After some consideration, we're going to go with separate test suites. I'm still interested in feedback in case other axios users or devs have thoughts on this, but I'm going to close the issue to avoid cluttering the repo.

**Comment by gustavohenke** [comment]
I haven't used axios yet (still under consideration), but I've been developing an isomorphic app and all my tests are written in Node, no real browsers envolved.

I've been happy using jsdom when testing something that happens only in a DOM environment.

However, this app is still in its early stages, so I know that the time to use real browsers will come... 
Everyone needs to deal with strangeness in old IE behavior, or perhaps bugs dating from Firefox 1.0. Who knows.

**Comment by jabacchetta** [comment]
I believe I'm currently running into the same issues with axios when following the Redux tutorial to writing tests for async action creators. isomorphic-fetch appears to work fine, but it fails with axios.

An other solutions available?

[Related issue](https://github.com/reactjs/redux/issues/1972).
