### ISSUE TITLE
Post nested params

### ISSUE THREAD

**Issue by rohandey** [mzabriskie/axios#455]
Posting nested params 

```
export function createUser(post_data){
 // post_data format => { user: { name: "", email: "", password: ""}}
  const request = axios({
    method: 'post',
    url: 'http://localhost:5000/api/users',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    params: post_data
  });

  return {
    type: 'CREATE_USER',
    payload: request
  }
}
```
In rails server I receive parameters as
Parameters: {"user"=>"{\"name\":\"\",\"email\":\"\",\"password\":\"\"}"}

Which is not the desired format. Please help.

**Comment by rohandey** [comment]
fixed this using

axios.post('http://localhost:5000/api/users', post_data)

**Comment by XXChester** [comment]
I am experiencing the exact same problem via axios.get requests.
