### ISSUE TITLE
missing HTTP adapter?

### ISSUE THREAD

**Issue by UnsungHero97** [mzabriskie/axios#456]
Axios v0.14.0
Node v6.6.0

I'm trying to do a simple GET, and I'm faced with `ReferenceError: XMLHttpRequest is not defined`. I was looking through the code in `dist/axios.js`, and I'm seeing something unexpected:

```
if (typeof config.adapter === 'function') {
  // For custom adapter support
  adapter = config.adapter;
} else if (typeof XMLHttpRequest !== 'undefined') {
  // For browsers use XHR adapter
  adapter = __webpack_require__(10);
} else if (typeof process !== 'undefined') {
  // For node use HTTP adapter
  adapter = __webpack_require__(10);
}
```

Webpack seems to be requiring the same dependency for both XHR and HTTP adapters, `__webpack_require__(10)`. Further, when I search for `httpAdapter` and `dispatchHttpRequest`, nothing comes up.

Is the v0.14.0 release missing the HTTP adapter?

**Comment by UnsungHero97** [comment]
Hmmm... I changed webpack to export to `node` instead of `web`, and it's working now. Not sure what the difference is, but seems like this isn't a real problem.

**Comment by UnsungHero97** [comment]
I just wanted to follow up on this to try and get a better understanding of how this happens. When I run a webpack build with `target: 'web'`, I get the following in the bundle:

```
var adapter;
if (typeof config.adapter === 'function') {
  // For custom adapter support
  adapter = config.adapter;
} else if (typeof XMLHttpRequest !== 'undefined') {
  // For browsers use XHR adapter
  adapter = __webpack_require__("./node_modules/axios/lib/adapters/xhr.js");
} else if (typeof process !== 'undefined') {
  // For node use HTTP adapter
  adapter = __webpack_require__("./node_modules/axios/lib/adapters/xhr.js");
}
```

Now, when I run the same webpack build but with `target: 'node'`, I get the following:

```
var adapter;
if (typeof config.adapter === 'function') {
  // For custom adapter support
  adapter = config.adapter;
} else if (typeof XMLHttpRequest !== 'undefined') {
  // For browsers use XHR adapter
  adapter = __webpack_require__("./node_modules/axios/lib/adapters/xhr.js");
} else if (typeof process !== 'undefined') {
  // For node use HTTP adapter
  adapter = __webpack_require__("./node_modules/axios/lib/adapters/http.js");
}
```

Shouldn't this be consistent no matter what the target is?

**Comment by nickuraltsev** [comment]
The idea here is to not include the `http` adapter and its dependencies to `web` bundles to reduce their size.

**Comment by UnsungHero97** [comment]
@nickuraltsev Got it. Any suggestions on how to build `axios` with both adapters included, with the goal being to bundle a single library that can run both on the web and in node?

**Comment by leepowellcouk** [comment]
@UnsungHero97 Did you resolve this? I'm having the same issue - trying to build a single bundle I can use on both the browser and node. At the moment I'm having to inject the xhr adapter into the defaults in Node. It works but isn't a clean solution.

**Comment by UnsungHero97** [comment]
I ended up creating 2 separate builds, each targeting their respective environments, 1 for web and 1 for node.

**Comment by Naramsim** [comment]
Using the `target: 'node'` with the entry `node: { process: false },` and a plugin
```
plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
    })
  ]
```

Makes the output library both working on the web and node.

**Comment by mx2323** [comment]
where is the code that determines that overrides 'http.js' with xhr.js? 

i compiled using webpack with target 'node', and i'm still getting the XHRAdapter, no matter what i do it appears.
