### ISSUE TITLE
Axios with promise.prototype.finally without shim()

### ISSUE THREAD

**Issue by komirad** [mzabriskie/axios#457]
Just following the cookbook here: https://github.com/mzabriskie/axios/blob/master/COOKBOOK.md

In the finally example, the code only works if I shim() promise.prototype.finally eg. ```require('promise.prototype.finally').shim()```

Error message as seen here: http://stackoverflow.com/questions/39696007/axios-with-promise-prototype-finally-doesnt-work

**Comment by nickuraltsev** [comment]
@komirad I've updated the cookbook. Thank you!
