### ISSUE TITLE
Allow request bodies with GET

### ISSUE THREAD

**Issue by ChrisNLott** [mzabriskie/axios#462]
Hello, we are adding a feature to our product that allows our user to send HTTP requests to their APIs (think Postman). I understand that it is not recommended to add a request body to a GET request, but it is also valid according to the HTTP 1.1 spec, and there are some weird APIs out there. I don't want to deny our users from sending request bodies to endpoints they've already built. If I put in a pull request that allows request bodies for all methods, would it be accepted?

**Comment by nickuraltsev** [comment]
You can use the existing API to make a GET request with a body:

```js
axios.get('/user/12345', {
  data: {
    foo: 'bar'
  }
})
``` 

or 

```js
axios.request({
  method: 'get',
  url: '/user/12345',
  data: {
    foo: 'bar'
  }
})
```

Hope this helps!

**Comment by ChrisNLott** [comment]
@nickuraltsev 

according to the request config:

>   // `data` is the data to be sent as the request body
>   // Only applicable for request methods 'PUT', 'POST', and 'PATCH'
>   // When no `transformRequest` is set, must be of one of the following types:
>   // - string, plain object, ArrayBuffer, ArrayBufferView, URLSearchParams
>   // - Browser only: FormData, File, Blob
>   // - Node only: Stream

Also you can see on line Axios.js line 74 only adds the data property to 'post', 'put', and 'patch' methods. https://github.com/mzabriskie/axios/blob/master/lib/core/Axios.js#L74

**Comment by nickuraltsev** [comment]
I don't think README.md is telling the truth in this case. You should be able to make a GET request with a body by setting the `config.data` property like this:

```js
axios.get(url, { data: { foo: ' bar' } })
```

Please let me know if it doesn't work.

**Comment by jzzj** [comment]
No, It's not working

**Comment by tarun** [comment]
Could the browser be blocking it?

**Comment by dangitos** [comment]
I have the same problem, works fins in Node.js environment though. What a headache.

**Comment by rmchale** [comment]
I have this issue in the browser too.  Works fine in node.

**Comment by 0X1A** [comment]
@nickuraltsev I believe this is still an issue

**Comment by rajeshjonnadula** [comment]
any alternate approach?

**Comment by rafaelsales** [comment]
Can we reopen this?

**Comment by emilyemorehouse** [comment]
When using Axios in a browser, the underlying network request is handled using an [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest). This doesn't support sending data for GET requests and thus this issue can't be fixed if/until that is changed. There are definitely other options for handling requests, but it would cause a loss of browser compatibility and therefore we're super hesitant to make big changes like that.

You can test this out in your browser if you're curious:
```
var xmlhttp = new XMLHttpRequest();   // new HttpRequest instance
xmlhttp.open("GET", "https://jsonplaceholder.typicode.com/posts");
xmlhttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
xmlhttp.send(JSON.stringify({ email: "hello@user.com", response: { name: "Tester" } }));
```
If you look at the request in the network tab of your dev tools, you'll see that no data is sent up.

Sorry if there was any confusion on this issue previously! This is definitely something on my radar for increasing support in the future.

**Comment by cedw032** [comment]
Apparently canary supports this, but I am not sure when it will become mainstream in browsers.

**Comment by shengnoyi** [comment]
xhr spec: https://xhr.spec.whatwg.org/#the-send()-method
>The send(body) method must run these steps:
If state is not opened, then throw an "InvalidStateError" DOMException.
If the send() flag is set, then throw an "InvalidStateError" DOMException.
If the request method is GET or HEAD, set body to null.
