### ISSUE TITLE
EncodeURIComponent within the params option returns a 404 for a GET request

### ISSUE THREAD

**Issue by jeanmichelcote** [mzabriskie/axios#463]
I am fetching a video over the web, convert it to blob/objectURL and return the blob url. The param I am passing to the endpoint URL is a URL itself so I need to encode it to make sure characters that need escaping end up correct. But axios throws me a 404 error in that case. While if I pass the url directly, without encoding it first, status is 200.

This throws a 404:
```
    return axios(endpoint, { 
        method: 'GET', 
        params: { url: encodeURIComponent(url) },
        responseType: 'arraybuffer',
        headers: new Headers({'Access-Control-Allow-Origin': '*'}) 
      })
```

This is OK 200:
```
    return axios(endpoint, { 
        method: 'GET', 
        params: { url: url },
        responseType: 'arraybuffer',
        headers: new Headers({'Access-Control-Allow-Origin': '*'}) 
      })
```

***BUT***, if I include the encoding directly in the endpoint without using the `params` option, status is 200, like so:

```
    return axios(
        `${endpoint}?url=${encodeURIComponent(url)}`, { 
             method: 'GET', 
             responseType: 'arraybuffer',
             headers: new Headers({'Access-Control-Allow-Origin': '*'}) 
           })
```
Is that normal behavior?

**Comment by rubennorte** [comment]
Yes, it is the normal behavior as axios encodes the values in `params` for you. In your example you're getting a 404 because you're encoding the parameters twice.

**Comment by puppeteer701** [comment]
Is there a way to disable encoding of the url?

**Comment by zzfScarecrow** [comment]
When I use axios.get(url, params)，it didn't encodes at all, but if I encode params manually, it will encodes my params twice

**Comment by heiranran** [comment]
why axios encodes the values in params default @rubennorte

**Comment by fkotsian** [comment]
Helped me: https://stackoverflow.com/questions/39116731/how-to-prevent-axios-from-encoding-my-request-parameters
