### ISSUE TITLE
Headers not received in response callback properly

### ISSUE THREAD

**Issue by Vishal0203** [mzabriskie/axios#467]
Hi I was trying out a simple post request, 
I get the proper response data but , the headers key in response object holds only 2 headers as shown in image

![screen shot 2016-10-05 at 2 06 44 pm](https://cloud.githubusercontent.com/assets/8856973/19106469/220ed7de-8b05-11e6-81ac-2d397feec95e.png)

However, the network calls show me my required header that is `Set-Cookie` 

![screen shot 2016-10-05 at 2 07 30 pm](https://cloud.githubusercontent.com/assets/8856973/19106505/538f6dfa-8b05-11e6-93c2-640110d7f775.png)

how do I intercept the `Set-Cookie` header? Why the response doesn't contain the header?

**Comment by nickuraltsev** [comment]
Looks like you are running into [this issue](http://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields).
