### ISSUE TITLE
How can i get response error in response interceptor?

### ISSUE THREAD

**Issue by BrunoQuaresma** [mzabriskie/axios#468]
I try use axios.interceptors.response and get error.config but i not found any status code or specific error message.

**Comment by AlahmadiQ8** [comment]
```
// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Do something with response data
    return response;
  }, function (error) {
    // Do something with response error
    console.log(error.response);
    return Promise.reject(error);
  });
```

hope that helps

**Comment by BrunoQuaresma** [comment]
Thanks @AlahmadiQ8.

**Comment by stevebauman** [comment]
Awesome thanks @AlahmadiQ8!

**Comment by scazzy** [comment]
I tried to search SO and closed issues but couldn't find a proper solution.
I wanted to return `response.data` in first param, and `error.status` or `error.response` in second param, but it didn't work.

The error object doesn't have any response or status. Seems it consumes output from  `response.data` returned in the success/first param

```
axios.interceptors.response.use(res => response.data, function (error) {
    // Do something with response error
    console.log(error.response);
    return Promise.reject(error);
  });
```

**Comment by barefootChild** [comment]
This problem is still there, why is closed?

**Comment by Drumstix42** [comment]
Found this issue via top result on Google. Anyway, the fix for me was ensuring that I call `.use` on the instance of Axios that I'm using within my app.

```
export const http = Axios.create({
    ... config ...
});
```

And then after:
```
http.interceptors.response.use(
    function(response) {
        // response data
        return response;
    },
    function(error) {
        debugger; // <-- this should now trigger correctly
        // response error
        return Promise.reject(error.response); // transform response.response -> response
    }
);
```
