### ISSUE TITLE
axios.delete vs axios({method: 'delete' in Internet Explorer

### ISSUE THREAD

**Issue by AndreaMusumeci** [mzabriskie/axios#469]
Hi,
i have this piece of pseudo-code 

    axios.delete(`${url}`, {withCredentials: true, headers: {'uid': uid}})

and in IE10 doesn't run
but if i use

    axios({
        method: 'delete',
        url: `${url}`,
        data: null,
        withCredentials: true,
        headers: {'uid': uid},
        params: {
        }

All is done. In first case i have a body request "undefined" and server reject my call with "415 http code" response and "Body must have Content-Type application/json": in first case infact it seems to have 
   Content-Type: text/plain; charset=UTF-8, in second i force data to null and parameter to {} all work fine

What is wrong in first piece?
Thanks in advance.

**Comment by mzabriskie** [comment]
Do you get any kind of error in the first example, or does it just not do anything?

**Comment by AndreaMusumeci** [comment]
So.. i haven't errors in client console.. in server side service controls for content type which is "wrong" or at least different than the second way to invoke service

**Comment by GramParallelo** [comment]
Similar issue:  
`axios({method: 'delete', url: '/delete', data: {id: id})` works but 
`axios.delete('/delete', {id: id})` does not - It looks like req.body does not get populated

(note: this is only for the delete method)

**Comment by nickuraltsev** [comment]
@GramParallelo The second parameter to `axios.delete` is `config`, not `data`. Please see [this](https://github.com/mzabriskie/axios#axiosdeleteurl-config) for details.

**Comment by nickuraltsev** [comment]
@AndreaMusumeci Looks like the server requires the `Content-Type` header to be set to `application/json`.  Instead of passing `null` or `{}` as `data`, you can set the `Content-Type`:

```js
axios.delete(url, {
  headers: {
    'uid': uid,
    'Content-Type': 'application/json'
  }
})
```

Hope this helps!

**Comment by GramParallelo** [comment]
@nickuraltsev They have the same signatures: `axios.get(url[, config]) axios.delete(url[, config])`
  [docs](https://github.com/mzabriskie/axios#axiosgeturl-config)

An example in the docs would be helpful to show what config is.  It works if I just pass an object with the info I need.  But with delete as I mentioned it doesn't seem to work.

**Comment by uxlayouts** [comment]
Yeah an example in the docs would be nice.

**Comment by artiship** [comment]
This is not work
```
axios(url, {headers: {'Content-Type': 'application/json'}})
```

add data property as null then it works
```
axios({
method: 'delete'
url: `${url}`,
data: null,
headers: {'Content-Type': 'application/json'}
})
```
