### ISSUE TITLE
HTTP proxy authentication

### ISSUE THREAD

**Issue by peruukki** [mzabriskie/axios#476]
HTTP proxy support was added in #366, but the proxy configuration only takes into account the proxy host and port. We are running in an environment that requires authenticating to the proxy, and as far as I understood, axios doesn't support that. We are using the standard `http_proxy` and `https_proxy` environment variables with the credentials in the URL, like `http://proxy-user:proxy-password@proxy-host:proxy-port`, and passing that works as expected with e.g. [superagent-proxy](https://github.com/TooTallNate/superagent-proxy).

So I'm requesting to have support for HTTP proxy authentication, preferably even taking the credentials automatically from HTTP proxy environment variables.

**Comment by mzabriskie** [comment]
Would be happy to accept a PR for this.

**Comment by mawrkus** [comment]
Hi guys,
First thanks for all @mzabriskie: thanks the good work on Axios, it's great library!  
I've been facing the same issue and been able to make it work properly by:
1. adding the proper "Host" and "Proxy-Authorization" fields to the headers and 
2. adding "hostname" to the options object in Axios http adapter
I hope to find some time to submit a PR this week. I have the feeling it should be straightforward but I suspect it might have other implications.

**Comment by mawrkus** [comment]
Just submitted the PR, let me know how it looks like.

**Comment by peruukki** [comment]
Great, thanks @mawrkus!

**Comment by ChrisDillinger** [comment]
At what time in the lifetime of my nodejs script executing must process.env.http_proxy or process.env.https_proxy be set? My proxy settings don't appear to work. Also, I'm using v0.11.0 of axios, and I'm not sure how to tell what version this PR is a part of.

**Comment by peruukki** [comment]
According to the [changelog](https://github.com/axios/axios/blob/master/CHANGELOG.md#0153-nov-27-2016), the fix was included in v0.15.3. Though it still wouldn't work in our environment and I couldn't figure out why in a reasonable time, so we kept using superagent instead. 🤷‍♂️

I've always seen environment variables being set before/when the application starts, I'm not sure if it's possible to set them afterwards (and it doesn't sound like a good idea anyway).

**Comment by ChrisDillinger** [comment]
Thanks a bunch @peruukki !

I see why one should normally not set env vars after script starts but I wrote a CLI program that optionally let’s the user configure proxy settings for the rest of the lifetime of the script

The root problem here tho was version of library I was using, setting env vars after script starts was just accidental red herring 

Thank u!!
