### ISSUE TITLE
I receive error on catch TypeError: relativeURL.replace is not a function

### ISSUE THREAD

**Issue by Ridermansb** [mzabriskie/axios#478]
I try to save this data.. 

![Object VM](https://cloud.githubusercontent.com/assets/725337/19290926/7f729ba8-8fe8-11e6-8e30-db3ddf2a0aef.png)

> Each property is transformed in getters and setters by Vue.js

```javascript
save () {
let scheduleRequests = []
self.schedule.forEach(it => {
  scheduleRequests.push(self.saveEventSchedule({ // <-- VUEX ACTION
    title: it.title,
    tags: it.tags.map(it => it.id)
  }))
})

return axios.all(scheduleRequests)
  .then(results => {
    self.vm.schedule = results.map(r => r.id)
    return self.saveEvent(self.vm)   // <-- VUEX ACTION
      .then(resolve)
      .catch(reject)
  })
  .catch(reject)
}
```

In my actions ..

```
saveEvent ({ commit }, event) {
  return events.post(event)
    .then(resp => {
      return resp.data
    })
    .then(resp => {
      commit(ADD_EVENT, resp)
      return resp
    })
}

saveEventSchedule ({ commit }, eventSchedule) {
  return eventSchedule.post(eventSchedule)
    .then(resp => {
      return resp.json()
    })
    .then(resp => {
      commit(ADD_EVENT_SCHEDULE, resp)
      return resp
    })
},
```

And I receive this in catch

<img width="813" alt="axios" src="https://cloud.githubusercontent.com/assets/725337/19290952/af7426dc-8fe8-11e6-89b6-af44d10d9331.png">

**Comment by nickuraltsev** [comment]
Could you please provide the code that makes requests using axios?

**Comment by Ridermansb** [comment]
@nickuraltsev I edit the question ..

**Comment by nickuraltsev** [comment]
If `events` and `eventSchedule` are axios instances, you need to pass the url as the first parameter:

```js
axios.post('/foo', {
  bar: 123
})
```

**Comment by Ridermansb** [comment]
@nickuraltsev , i create a instance..

```
var events = axios.create({
  baseURL: '/api/events'
})
```

but you're right.

I thought he would use baseUrl

Thnks

**Comment by iraklisg** [comment]
If this could be any help for somebody, I had the same error occurred when I mistakenly typed `/url/` without using the double` " "`

**Comment by iVapor** [comment]
I meet this problem. Because I add method post in axios.post function. Hope it helps someone.
