### ISSUE TITLE
NodeJS - Cookie Jar Support

### ISSUE THREAD

**Issue by nicholasrobinson** [mzabriskie/axios#48]
axios running on NodeJS does not provide Cookie jar support natively. Ideally the library would either provide built in cookie jar functionality or easily accommodate existing cookie jar libraries.

The Request API could be modified to support the following options:

``` javascript
{
...
  // `jar` is a boolean that controls cookie jar support for the request
  jar: true, // default
...
}
```

or

``` javascript
{
...
  // `jar` is a cookie jar that will be used for the request
  jar: cookieJar, // default
...
}
```

where

``` javascript
var tough = require('tough-cookie');
var cookiejar = new tough.CookieJar();
```

Note:
Trivial cookie support using tough-cookie can be added by leveraging interceptors:

``` javascript
var tough = require('tough-cookie');
var Cookie = tough.Cookie;
var cookiejar = new tough.CookieJar();

axios.interceptors.request.use(function (config) {
  cookiejar.getCookies(config.url, function(err, cookies) {
    config.headers.cookie = cookies.join('; ');
  });
  return config;
});

axios.interceptors.response.use(function (response) {
  if (response.headers['set-cookie'] instanceof Array) {
    cookies = response.headers['set-cookie'].forEach(function (c) {
      cookiejar.setCookie(Cookie.parse(c), response.config.url, function(err, cookie){});
    });
  }
  return response;
});
```

**Comment by mzabriskie** [comment]
@nicholasrobinson you say that using interceptors provides "trivial cookie support". What is missing for full support?

**Comment by nicholasrobinson** [comment]
I would imagine that "full" cookie jar support would:
- respect cookie deletion headers in server response
- respect cookie expiration
- maybe more..?

As for cases where you wouldn't want cookie support:
- Unit testing of http endpoints?
- Deliberately ignoring cookie headers?

IMO there should be a flag to disable cookie jar support. More generally speaking though it is useful to be able to emulate browser functionality in automated testing scenarios.

**Comment by damoclark** [comment]
In Node, you may also wish to use different cookie jars depending on which sites you are accessing.  A default cookie jar could be defined, but an alternate used on specific requests.  Just leverage the existing merging of options that Axios already provides.

**Comment by andreportela** [comment]
I was recently trying to do just that (add trivial cookie support) and I've used the code sample posted by @nicholasrobinson. Unfortunately I couldn't make it work like that. 
It seems that `axios.interceptors.request` is triggered between the request being made and `then` callback being executed. So it doesn't inject the cookie in the request.

I made it work by manually capturing the cookie on the first server response and then manually injecting the cookie into the following requests (which is ugly) like this

```javascript
function getCookie(response) {
    return response.headers['set-cookie'];
}

function makeRequestWithGivenCookie(cookie) {
    return axios.get('/',{headers: {"Cookie": cookie}});
}
```

Am I missing something here? BTW axios is great! Cookie support would really be an awesome feature.

**Comment by rubennorte** [comment]
Please, take a look at https://github.com/mzabriskie/axios/issues/206#issuecomment-233758315

@damoclark, you could do that easily with the kind of plugin that I described in the other thread and use different axios instances for those specific requests.

**Comment by lirantal** [comment]
would definitely like to see cookies/persistent sessions support in axios. A third party module is a great addition but there's no guarantee on it's maintainability in the future.

**Comment by rubennorte** [comment]
@lirantal we're rather short maintaining the functionality Axios has at the moment so adding things that can be implemented in plugins won't help that.

I'm closing this issue as it won't be implemented in core and there's a library that implements this in [ECOSYSTEM.md](https://github.com/mzabriskie/axios/blob/master/ECOSYSTEM.md)

**Comment by nzvtrk** [comment]
@andreportela 
I'm writed simple example for works with cookie/session in node.js

https://gist.github.com/nzvtrk/ebf494441e36200312faf82ce89de9f2

**Comment by andreportela** [comment]
Hi @nzvtrk I didn't have the time to take a look at it. But thanks for sharing! 😃 It may be useful to a lot of people that end up here.
 
It has been a long time since I moved on. But it seems that this feature is already implemented on a lib. Maybe I would rather just use it. 🤷‍♂️
