### ISSUE TITLE
How to typehint promises in typescript

### ISSUE THREAD

**Issue by macnibblet** [mzabriskie/axios#480]
I currently have the following code

``` typescript

  authenticate(credentials: AuthenticationCredentials): Promise<void> {
    return axios
      .post('backend://authentication', credentials)
      .then<void>(response => {
        this.processToken(response.data.token);
      });
  }
```

The error it produces

```
Type 'Promise<void>' is not assignable to type 'Promise<void>'.
  Types of property 'then' are incompatible.
    Type '{ <R1, R2>(onFulfilled: (value: void) => R1 | Promise<R1>, onRejected: (error: any) => R2 | Promi...' is not assignable to type '{ <TResult1, TResult2>(onfulfilled: (value: void) => TResult1 | PromiseLike<TResult1>, onrejected...'.
      Type 'Promise<any>' is not assignable to type 'Promise<any>'.
        Types of property 'then' are incompatible.
          Type '{ <R1, R2>(onFulfilled: (value: any) => R1 | Promise<R1>, onRejected: (error: any) => R2 | Promis...' is not assignable to type '{ <TResult1, TResult2>(onfulfilled: (value: any) => TResult1 | PromiseLike<TResult1>, onrejected:...'.

```

**Comment by levani** [comment]
Not sure but maybe `AxiosPromise` is what you are looking for...

**Comment by croes** [comment]
Ran into the same error. The Promise in axios.d.ts (https://github.com/mzabriskie/axios/blob/master/axios.d.ts#L61) . seems to be incompatible with the ES6 Promise defined in lib.es6.d.ts (https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L1356).

**Comment by pmlamotte** [comment]
I hit a similar error. I'm forcing a type cast to get around it wherever axios is used for now.

```
axios.post(
    ...
}).then(response => {
    return response.data;
}) as Promise<User>;
```

**Comment by pmlamotte** [comment]
I hit a similar error. I'm forcing a type cast to get around it wherever axios is used for now.

```
axios.post(
    ...
}).then(response => {
    return response.data;
}) as Promise<User>;
```

**Comment by pmlamotte** [comment]
Ran into a similar error that is breaking my vscode setup. My hacky workaround right now was to copy the axios typings locally, remove the promise definition, and reference it through includes in .tsconfig. I then had to manually typecast the return values to make it happy.

```
axios.post(
    ...
).then(response => response.data as User) as Promise<User>
```

**Comment by rafaelbiten** [comment]
I'm also new to TS and I've been trying to use it on a very small/simple project.

I'm really confused on how to use TypeScript without using 'any' or getting any TS errors/warnings.

![screen shot 2016-11-03 at 10 23 51 am](https://cloud.githubusercontent.com/assets/5550692/19970033/1ee52762-a1b1-11e6-8615-d475cbb3c9f3.png)

I tried many different things, but the image above was probably my best attempt but for some reason I still get the `Type 'void' is not assinable to type 'string'` error. I was wondering if this could be related to this bug.

If I use `(u: string): Axios.IPromise<any>`, it fixes the issue, but I'm trying to avoid using 'any'.

Tks!

**Comment by DenisCarriere** [comment]
If you use `async` you'll be able to return a `Promise<void>` from that function, I don't think this has anything to do with Axios.

I was able to replicate this function without any Typescript errors using the `axios.d.ts` definition.

```javascript
async authenticate(credentials: AuthenticationCredentials): Promise<void> {
  const response = await axios.post('backend://authentication')
  this.processToken(response.data.token)
}
```

**Comment by mktange** [comment]
This is fixed with the following PR #588

**Comment by gluons** [comment]
Same here.
`Promise` from `then` is not compatible with native `Promise`.
```
error TS90010: Type 'Promise<void>' is not assignable to type 'Promise<void>'. Two different types with
 this name exist, but they are unrelated.
  Types of property 'then' are incompatible.
```

**Comment by acheshkov** [comment]
+1

**Comment by retwedt** [comment]
+1 any progress/solutions on this?

**Comment by shousper** [comment]
+1

**Comment by nickuraltsev** [comment]
Fixed via 3704d57

**Comment by leemove** [comment]
It does't work!

**Comment by luciomartinez** [comment]
This worked for me:

    import axios, {AxiosPromise} from 'axios';

    function get(): AxiosPromise {
      return axios.get('http://my.domain/api');
    }

**Comment by vileen** [comment]
> This worked for me:
> 
> ```
> import axios, {AxiosPromise} from 'axios';
> 
> function get(): AxiosPromise {
>   return axios.get('http://my.domain/api');
> }
> ```

but you don't specify the exact type returned by `AxiosResponse` so it's `any` mplicitly
