### ISSUE TITLE
Warning: a promise was rejected with a non-error

### ISSUE THREAD

**Issue by levrik** [mzabriskie/axios#481]
First off thanks for the opportunity to cancel requests.
Now there is the "problem" if I use Axios with Bluebird the console is getting spammed with `Warning: a promise was rejected with a non-error` on cancelled requests.
Why is this not implemented with a custom Error class? If you're fine with changing this I would submit a PR.

**Comment by nickuraltsev** [comment]
`Cancel` must not derive from `Error` according the cancelable promises spec. Please see [this](https://github.com/tc39/proposal-cancelable-promises/blob/master/Not%20an%20Error.md#api-design) for details.
