### ISSUE TITLE
Not working in IE Edge

### ISSUE THREAD

**Issue by shyamchandranmec** [mzabriskie/axios#486]
I am facing the some issue in IE edge. Its not even firing the request. The response which I get is shown below. I am creating a module and making a generic instance of axios. It works in other browsers like chrome and firefox and safari. 
Here is the code which I am using:

var req = axios.create({
baseURL: config.fullURL,
timeout: 1000000000000000000000,
})
req.defaults.headers.common['Authorization'] = 'JWT ' + token;

Here is the response in catch
 code: 12,  
      constructor: { },   
      DATA_CLONE_ERR: 25,   
      DOMSTRING_SIZE_ERR: 2,   
      HIERARCHY_REQUEST_ERR: 3,   
      INDEX_SIZE_ERR: 1,   
      INUSE_ATTRIBUTE_ERR: 10,   
      INVALID_ACCESS_ERR: 15,   
      INVALID_CHARACTER_ERR: 5,   
      INVALID_MODIFICATION_ERR: 13,   
      INVALID_NODE_TYPE_ERR: 24,   
      INVALID_STATE_ERR: 11,   
      message: "SyntaxError",   
      name: "SyntaxError",   
      NAMESPACE_ERR: 14,   
      NETWORK_ERR: 19,   
      NO_DATA_ALLOWED_ERR: 6,   
      NO_MODIFICATION_ALLOWED_ERR: 7,   
      NOT_FOUND_ERR: 8,   
      NOT_SUPPORTED_ERR: 9,   
      PARSE_ERR: 81,   
      QUOTA_EXCEEDED_ERR: 22,   
      SECURITY_ERR: 18,   
      SERIALIZE_ERR: 82,   
      SYNTAX_ERR: 12,   
      TIMEOUT_ERR: 23,   
      TYPE_MISMATCH_ERR: 17,   
      URL_MISMATCH_ERR: 21,   
      VALIDATION_ERR: 16,   
      WRONG_DOCUMENT_ERR: 4
   }

Any help would be of great help.

**Comment by nickuraltsev** [comment]
Could you please try to remove the `timeout` option and let me know if it fixes the issue? I think the problem is that the value is too large.

**Comment by shyamchandranmec** [comment]
@nickuraltsev  I will try it out and let you know. Thanks for the quick response.

**Comment by shyamchandranmec** [comment]
@nickuraltsev  I reduced the timeout to 5000 and it worked!!!. Thanks a lot. 
The reason for having a huge timeout is because we enable our users to upload huge files close to 25gb. So I need a huge timeout.. Is there any way to keep an infinite timeout if I can't specify a large timeout.

**Comment by rubennorte** [comment]
@shyamchandranmec you can set the timeout to 0. That's the default axios value (no timeout).

**Comment by webhacking** [comment]
In Internet Explorer you have to do the following setup, because EDGE will take those setting from IE:

- Internet Option
- Security tab
- Local intranet click "sites"
- Advanced
- Add here your domain or localhost
- Close IE
- Open EDGE and test your domain or localhost now

Or another ways. you should be set to the same orgin your request end point
