### ISSUE TITLE
better handling of missing protocol in url

### ISSUE THREAD

**Issue by mgmcdermott** [mzabriskie/axios#490]
If the requested url does not have a protocol (http/https) specified, the error given is a bit cryptic. While it is a bit of an edge case, it has actually happened to me on numerous occasions.
Currently, the following is thrown:
```
error checking auth TypeError: Cannot read property 'slice' of null
    at dispatchHttpRequest (.../node_modules/axios/lib/adapters/http.js:84:37)
    at httpAdapter (.../node_modules/axios/lib/adapters/http.js:19:10)
    at dispatchRequest (.../node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
The reason I'm opening a issue rather than a pull request is that I see two different ways of handling it and would like @mzabriskie to chime in.

1. Check explicitly for `parsed.protocol` in the httpAdapter and throw an error if it doesn't exist.
2. Default to using `http://` and continue on as usual

Love axios, long time user, let me know what you think and I can make a PR.

**Comment by mzabriskie** [comment]
I assume that you are specifying a hostname, just not a protocol (`api.example.com/user/1`)?

We already implicitly default to `http:` for the protocol. I am okay with making that default explicit if `parsed.protocol` isn't set.

**Comment by mgmcdermott** [comment]
Yes, can happen by accident if setting baseUrl dynamically. Will make a PR.
