### ISSUE TITLE
Unable to send an authenticated get request

### ISSUE THREAD

**Issue by nitish24p** [mzabriskie/axios#497]
I am using axios for making api calls to my service. I am trying to pass headers into the request but i'm not able to see the headers in the network requests. Hence get a 403. Please could someone tell me what im doing wrong here.

```javascript
export const searchUserByName = (value) => {
  return axios.get(SEARCH_USER_BY_NAME, {
    params: { name: value }
  }, RequestConfig);
}
```
The request Config is 
```
headers: {
    'X-Auth-Token' : #HASH_TOKEN,
    'account-id' : #ACCOUNT_ID
  }
```

**Comment by nickuraltsev** [comment]
`axios.get` accepts only two parameters: `url` and `config` (please see [this](https://github.com/mzabriskie/axios#axiosgeturl-config) for details).

I think your code needs to be changed as follows:

```js
axios.get(SEARCH_USER_BY_NAME, {
  params: { 
    name: value 
  },
  headers: {
    'X-Auth-Token': HASH_TOKEN,
    'account-id': ACCOUNT_ID
  }
});
```

Hope this helps!
