### ISSUE TITLE
Question: why is it necessary to stringify data?

### ISSUE THREAD

**Issue by francoisromain** [mzabriskie/axios#500]
Hello, 
this is not an issue but a few questions: 

Why is it necessary to stringify data before to pass it to axios?
(meaning: what is the use-case where you don't want to stringify?)

```
axios.post(window.authenticationUrl, {
        ajax: true,
        token: token,
        param: param,
      }, {
        transformRequest: [function(data) {
          return qs.stringify(data);
        }],
      })
```
Is this the correct way to do it?

Thank you

**Comment by nickuraltsev** [comment]
It's not necessary to `stringify` data before passing it to axios. You should use `qs.stringify` only if you need to send the data in the `application/x-www-form-urlencoded` format. You should not do that if you'd like to send the data in the `JSON` format.

Hope this helps!

**Comment by francoisromain** [comment]
thanks

**Comment by nickuraltsev** [comment]
@francoisromain You are welcome!

**Comment by zachwhitedev** [comment]
Is there anything wrong with assuming that axios handles doing JSON.stringify() for us?
