### ISSUE TITLE
My header is not set properly

### ISSUE THREAD

**Issue by darshilchapadia** [mzabriskie/axios#502]
Hi @mzabriskie , I want to set my Authentication header for every request for API.

Following is my code snippet:

`axios.defaults.headers.common['Authorization'] = 'Token 122f6477';`

Then i call get method to get data from api like this: 

`axios.get("https://jsonplaceholder.typicode.com/posts/1/comments")
    .then(response => {
      return response.status
    })`

But i don't get Authentication as my request header it gives me en error. 

As seen in picture below, i get my 'authorization' header under 'Access-Control-Request-Header' object, 
![autho](https://cloud.githubusercontent.com/assets/22972546/19635958/bdb1e72a-99e3-11e6-8b9a-be83ba3bf307.png)

but i want my header like this picture. i.e I want to add 'Authorization' direct under 'Request headers'

![autho 2](https://cloud.githubusercontent.com/assets/22972546/19635959/bdb93462-99e3-11e6-8de7-184a0495cded.png)

**Comment by nickuraltsev** [comment]
What you see is a preflight (`OPTIONS`) request. 

You can learn about CORS and preflight requests here:

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
- https://www.html5rocks.com/en/tutorials/cors/

Hope this helps!
