### ISSUE TITLE
Axios cache issue

### ISSUE THREAD

**Issue by kol9n93** [mzabriskie/axios#503]
Hi. I have a issue with cache. I do two requests that returns the same body. First request status is 200, second request status is 304. But both requests have different 'Content-Range' header. First request returns 'items 1-10/11'. Second request return '1-10/12'. I opened response header 'Content-Range' in browser and see 'items 1-10/12', but axios response.headers['Content-Range'] still returns '1-10/11'.
How to fix this issue?

**Comment by nickuraltsev** [comment]
@kol9n93 Could you please provide a code snippet or GitHub repo that reproduces this issue?

**Comment by kol9n93** [comment]
Sorry, I think it's not axios issue. It's browser behavior.

**Comment by rebotak** [comment]
I think I got this too, how do you solve this?

**Comment by nkovalenko-sc** [comment]
I've disabled caching for API that returns Content-Range header. If you do the same request, but some header is different, you still get 304 status, because response body hasn't been changed.
