### ISSUE TITLE
POST example does not work as described

### ISSUE THREAD

**Issue by redheadedstep** [mzabriskie/axios#504]
The POST example on the main page causes issues on a basic Apache install.  

Using the example as is, the data is encoded in json and is not extracted automatically by the web server (I'm using PHP in this case).  It is received as:

```
console> axios.post(url, {first_name: "Fred", last_name: "Flintstone"});

# from apache error log for <?php error_log(var_export($_REQUEST, true)); ?>
array (
'{"first_name":"Fred","last_name":"Flintstone"}' => ''
)
```

In jQuery, for instance, running something similar would be encoded properly:

```
console> $.post(url, {first_name: "Fred", last_name: "Flintstone"});`

// from apache error log for <?php error_log(var_export($_REQUEST, true)); ?>
array (
  'first_name' => 'Fred',
  'last_name' => 'Flintstone',
)
```

Even in the post examples, within server.js, the data has to be unencoded from json (which may be the standard for Node, but it would be nice to have things work out of the box).

The config docs state that you can pass in a plain object, FormData, etc, but they are not handled the same.  Or there is a default encoding or transform that is happening that is not documented.

After hitting a brick wall for a few hours, I was able to figure out a way to make it work using FormData...but if this was documented, this would be great:

```
var data = new FormData();
data.append("first_name", "Fred");
data.append("last_name", "Flintstone");
axios.post(url, data);

// from apache error log for <?php error_log(var_export($_REQUEST, true)); ?>
array (
  'first_name' => 'Fred',
  'last_name' => 'Flintstone',
)
```

**Comment by nickuraltsev** [comment]
axios serializes objects to JSON by default, and there are no plans to change the default format. I agree that the documentation can be improved though. Thank you!

**Comment by redheadedstep** [comment]
Can I ask what is the correct way to pass data to axios.post?  Since the documentation is not correct, having a fix here may help out in the future.

```
axios.post('/user', {
    firstName: 'Fred',
    lastName: 'Flintstone'
  });
```

does not work since it serializes the object to JSON and it all comes through as a single parameter.

**Comment by LostKobrakai** [comment]
@redheadedstep Read this part: https://github.com/mzabriskie/axios#using-applicationx-www-form-urlencoded-format

**Comment by ArturGrigio** [comment]
with jQuery, you can do this
````
var data = {
    firstName: 'Fred',
    lastName: 'Flintstone'
}
axios.post('API?'+jQuery.param(data))

**Comment by gtamborero** [comment]
Thanks LostKobrakai!

By default axios sends JSON data and if you receive POST data on PHP you need to configurate the header as urlencoded:

```
var config = {
headers: {
   'Content-Type': 'application/x-www-form-urlencoded',
}
};

axios.post('URL', { data1: this.data1, data2: this.data2 }, config)
        .then((response) => { ... })
```

**Comment by edoofx** [comment]
@ArturGrigio then why need axios if using jquery ? weird.

**Comment by linkerx07** [comment]
For method post use:

const params = new URLSearchParams();
params.append('param1', 'value1');
params.append('param2', 'value2');

axios.post('/foo', params);

for me in the browser is work!
