### ISSUE TITLE
Request with auth parameter throw an exception on IE11

### ISSUE THREAD

**Issue by vanwalj** [mzabriskie/axios#507]
Hello !

Everything was working fine, until I had to test some code using Axios under IE11

When using the auth param Axios throw an error on btoa https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L42

```es6
axios.post('/sessions', {}, {
    auth: {
      username: 'username',
      password: 'password'
    }
  });
```

error `TypeError: Invalid calling object`

Browser: Internet Explorer 11.0.9600
OS: Windows 7
Axios package.json version: 0.15.2

Thanks !

**Comment by nickuraltsev** [comment]
Fixed via 417913b
