### ISSUE TITLE
Can't set headers for DELETE method

### ISSUE THREAD

**Issue by genomics-geek** [mzabriskie/axios#509]
I create an instance of axios:
`const api = axios.create({
  baseURL: process.env.BASE_URL,
  timeout: 1000,
});`

I am able to set the header for POST:
`api.defaults.headers.post['X-CSRFToken'] = cookie.csrftoken;`

However, if I try to set the header for DELETE:
`api.defaults.headers.delete['X-CSRFToken'] = cookie.csrftoken;`

I get the following error:
Cannot set property 'X-CSRFToken' of undefined

Is this expected behavior?

**Comment by nickuraltsev** [comment]
Fixed via d963368

**Comment by tangshuang** [comment]
Hi @nickuraltsev , I am facing the same problem now. My case:

```
axios.defaults.headers.common['X-Request-Id'] = window.REQUEST_ID
```

```
axios.delete(url, {headers: MyCustomHeaders})
```

`X-Request-Id` is not sent.
Could you have a look?

**Comment by ahlusar1989** [comment]
@tangshuang Do you mind demonstrating the full steps to reproduce this.

**Comment by tangshuang** [comment]
Well, I found the reason.
DELETE method request should not be sent with non-emtpy body. When I sent a delete request I set the request body to be `null`, which contains contect in fact. After I remove the `data` option in `config`, it works correctly.
Thanks all.

**Comment by dnieh** [comment]
You could in theory use the [`axios.delete`](https://github.com/mzabriskie/axios#axiosdeleteurl-config) method correctly and pass in data with the following:
```
const globalAxiosConfig = {
  headers: {
    'X-CSRFToken': 'add csrf token here',
  },
}

async function axiosDelete(url, data = {}) {
  const axiosConfig = {
    ...globalAxiosConfig,
    ...data,
  }
  return await axios.delete(url, axiosConfig)
}
```

However, even with data present, Axios seems to ignore it in the request which makes sense since passing back data on a HTTP DELETE request was not defined in the HTTP 1.1 spec: https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19#section-6.7

>Bodies on DELETE requests have no defined semantics.  Note that sending a body on a DELETE request might cause some existing implementations to reject the request

**Comment by moeinrahimi** [comment]
in my case doing delete with axios in below method doesn't send header.
``` javascript
       let {data} = await axios.delete(baseUrl+`/likepost`,
       {
         postId:postId
       },{headers:{Cookie:`sid=${cookie}`}})
```
but this way it's working correctly
``` javascript
  let {data} = await axios({
        url:baseUrl+`/likepost`,
        method:'delete',
        data : {postId},
        headers:{Cookie:`sid=${cookie}`}
      })
```

**Comment by tangshuang** [comment]
@moeinrahimi Are you sure? You mean you can post data with DELETE method? I will try that.

**Comment by sajidkhaki** [comment]
axios.delete({
                    url: '/system/ABC/delete/' + selectedId,
                    headers: {'Authorization': 'Bearer ' + token},
                    withCredentials: true
                }).then(function (response) {.....................

i try to use csrf in delete , but i am getting this error in nide.js

 DELETE http://localhost:3131/system/ABC/delete/473TL095G3x-HpugwipBP0RAMmyer5cPDafrNg0 403 (Forbidden)

**Comment by badgamerbad** [comment]
yes, even I'm facing the same issue if I'm using the **_axios.delete_** with config _**withCredentials: true**_ and CORS enabled on the backend server with a different domain,

All though I'm explicitly setting the cookies in response headers which I can see in network tab, these are not sent later when I make _**axios.delete**_ request

    axios.delete(
		process.env.GATSBY_URL_DELETE_FILE, 
		{
			data: {
				fileName,
				jwt,
			},
		},
		{ withCredentials: true }
	)
	.then(res => {
		return res.text()
	})
	.catch(error => {
		// handle error from aws lambda
		console.log(error)
	})
