### ISSUE TITLE
global default interceptors

### ISSUE THREAD

**Issue by laumair** [mzabriskie/axios#510]
Is it possible to add a global interceptor for all calls like we set `baseUrl` and authorization header?

**Comment by nickuraltsev** [comment]
You can add an interceptor to a particular axios instance (the default or a custom one), but it's not currently possible to add a global interceptor.

**Comment by laumair** [comment]
@nickuraltsev All right. Thanks

**Comment by lovanwubing** [comment]
I would like to have this feature. In our website we'd like to handle all of response with status 401 to popup a login dialog. I really don't want to handle 401 in all of those axios instance, it looks very stupid.  @nickuraltsev

**Comment by nickuraltsev** [comment]
@lovanwubing So you create multiple axios instances in you app and would like to add the same interceptors to all of them, correct?

**Comment by esmeander** [comment]
@nickuraltsev This still remain the question, each instance would have the duplicated interceptor config code line, still look stupid, global interceptor is useful on this way.

**Comment by harinair** [comment]
@nickuraltsev  @hyper315 
+1
A common example is adding request correlation header or if I have to add a request time header. I need to add an interceptor that will intercept and put a Header named CorrelationId with UUID for every request. This helps services trace every call I am making across different servers. Currently, I have to add this interceptor in every instance.

**Comment by bjunc** [comment]
This would be a nice feature to have.  My use case is to consider any API request as "lastActivity", for front-end based session timeouts (of course, redundancy on the server).

My solution was to hijack `XMLHttpRequest.prototype.send`, add my logic, then call `send`.  Works with axios, but also works for any XHR call.  Not sure how axios could implement this without hijacking _all_ XHR requests. In my case, that was desirable.

**Comment by AousAnwar** [comment]
In a perfect world, it would work like this :
`axios.defaults.interceptors.response.use(resHandler, errHandler)`

From now I'm using it like this :

```
const 
    axios = require('axios'),
    baseURL = process.env.BASE_URL
;

axios.defaults.withCredentials = true;

const instances = [
        axios.create({baseURL: baseURL + '/api'}),
        axios.create({baseURL: baseURL + '/auth'}),
        axios.create({baseURL: baseURL + '/form'}),
        axios.create({baseURL: baseURL + '/page'}),
        axios.create({baseURL: baseURL + '/comment'})
        ...
];

instances.forEach(i => i.interceptors.response.use(resHandler, errHandler))

export const [api, auth, form, page, comment] = instances;
```

**Comment by ywmail** [comment]
Any updates on this?

**Comment by webketje** [comment]
It's ugly, but if you don't want to define all your API's in 1 file like in @AousAnwar 's example, you can do something like:

```js
const _createAxios = axios.create;

axios.create = function createPatchedAxios(conf) {
  const instance = _createAxios(conf);
  const defaultIcs = axios.defaults.interceptors;
  const confIcs = conf.interceptors;

  const resInterceptor =
    confIcs && confIcs.response ? confIcs.response : defaultIcs && defaultIcs.response ? defaultIcs.response : false;
  const reqInterceptor =
    confIcs && confIcs.request ? confIcs.request : defaultIcs && defaultIcs.request ? defaultIcs.request : false;

  if (reqInterceptor) instance.interceptors.request.use(...reqInterceptor);
  if (resInterceptor) instance.interceptors.response.use(...resInterceptor);
  return instance;
};

// usage
const responseInterceptor =[
    res => res.data,
    error => ({
      error: error.response.data
    })
];

axios.defaults.interceptors = {
  response: responseInterceptor
};

// make sure the default exported instance also uses the interceptors
axios.interceptors.response.use(...responseInterceptor);

```
