### ISSUE TITLE
How to transform image from get request to base64

### ISSUE THREAD

**Issue by jjdp** [mzabriskie/axios#513]
any libs out there in npm that can do this?

```
axios.get('http://www.freeiconspng.com/uploads/profile-icon-9.png', {
   transformRequest: [function (data) {
       return data;
   }],
  transformResponse: [function (data) {
    return data;
  }],
});
```

**Comment by nickuraltsev** [comment]
I think this is a question for StackOverflow.

**Comment by geohuz** [comment]
for anyone searching for the solution, I have the following code:
```
get('/getImg', {
    responseType: 'arraybuffer' 
})
.then(function(result) {
    console.log(_imageEncode(result.data))
})
```

```
function _imageEncode (arrayBuffer) {
    let u8 = new Uint8Array(arrayBuffer)
    let b64encoded = btoa([].reduce.call(new Uint8Array(arrayBuffer),function(p,c){return p+String.fromCharCode(c)},''))
    let mimetype="image/jpeg"
    return "data:"+mimetype+";base64,"+b64encoded
}
```

**Comment by runebaas** [comment]
This was our solution, it works like a charm
```javascript
return axios.get('http://example.com/image.png', { responseType: 'arraybuffer' })
      .then((response) => {
        let image = btoa(
          new Uint8Array(response.data)
            .reduce((data, byte) => data + String.fromCharCode(byte), '')
        );
        return `data:${response.headers['content-type'].toLowerCase()};base64,${image}`;
      });
```

The reason this won't work is that axios puts everything in a json object. Since you cannot put binary in a json object it converts it to a string which breaks the binary.

**Comment by sean-hill** [comment]
This worked perfect for me:

```js
function getBase64(url) {
  return axios
    .get(url)
    .then(response => new Buffer(response.data, 'binary').toString('base64'))
}
```

**Comment by b4dnewz** [comment]
if you are on node like me and you are using **v >= 6**, there was a change and you should use **Buffer.from** or similar.

```js
function getBase64(url) {
  return axios
    .get(url, {
      responseType: 'arraybuffer'
    })
    .then(response => Buffer.from(response.data, 'binary').toString('base64'))
}
```
Reference [safe-buffer](https://www.npmjs.com/package/safe-buffer)
`new Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead`

**Comment by samayo** [comment]
@sean-hill Do you have any idea why it can't get the first token of the image?  I don't see `data:image/png;base64,` part for some reason, which makes the base64 data invalid

**Comment by inyee786** [comment]
this work for me
``` 
function getImage(imageUrl) {
var options = {
    url: `${imageUrl}`,
    encoding: "binary"
};

    request.get(options, function (err, resp, body) {
        if (err) {
            reject(err);
        } else {
            var prefix = "data:" + resp.headers["content-type"] + ";base64,";
            var img = new Buffer(body.toString(), "binary").toString("base64");//  var img = new Buffer.from(body.toString(), "binary").toString("base64");
            dataUri=prefix + img;
        }
    })
}
```

**Comment by XAHTEP26** [comment]
```javascript
return axios.get('http://site.com/img.png', { responseType: 'arraybuffer' })
  .then(response => `data:${response.headers['content-type']};base64,${btoa(String.fromCharCode(...new Uint8Array(response.data)))}`);
```

**Comment by voidpls** [comment]
> 
> 
> ```js
> return axios.get('http://site.com/img.png', { responseType: 'arraybuffer' })
>   .then(response => `data:${response.headers['content-type']};base64,${btoa(String.fromCharCode(...new Uint8Array(response.data)))}`);
> ```

Node Version: 
``data:${res.headers['content-type']};base64,${Buffer.from(
      String.fromCharCode(...new Uint8Array(res.data)),
      'binary'
    ).toString('base64')}``

**Comment by weituotian** [comment]
@voidpls 
your method cause error!
`Uncaught RangeError: Maximum call stack size exceeded`

it cause from
`toa(String.fromCharCode(...new Uint8Array(response.data)))`

you can try this picture
![texture 4a95078a](https://user-images.githubusercontent.com/7270968/78753359-393d3280-79a8-11ea-90e7-fec4950d905b.png)
