### ISSUE TITLE
Are there node dependencies and if so, what is the earliest version of node supported?

### ISSUE THREAD

**Issue by SudoPlz** [mzabriskie/axios#514]
Hey there guys. 

I plan to use axios in a sdk used both in the node environment and in react-native.

I want to know :

1. If it uses node dependencies - like for example crypto (because if it does, react-native users won't be able to use it).
2. If the answer above is yes, what's the earliest version of node it can support (I want to know if it will mess things up for legacy node users)

Thank you!

**Comment by nickuraltsev** [comment]
axios uses different [adapters](https://github.com/mzabriskie/axios/tree/master/lib/adapters) for Node.js and browsers. The Node.js adapter does use Node.js APIs, but the browser one (which is also used in react-native) does not.

axios should work fine with old Node.js versions (at least, v0.10+), but you will need to polyfill Promises if you use v0.10. 

Hope this helps!
