### ISSUE TITLE
Is it possible to cancel several requests with the same Cancel token ?

### ISSUE THREAD

**Issue by DjebbZ** [mzabriskie/axios#516]
Hi,

Very happy about the new Cancel feature.

Our use case is a map of Promises for http requests (with axios), that we want to cancel when the user navigates to other pages. Is it possible the pass the same Cancel token to all the requests and call `source.cancel()` only once to cancel them all ?

Thanks in advance !

**Comment by nickuraltsev** [comment]
Yes, you can use the same token to cancel multiple requests.

**Comment by DjebbZ** [comment]
Wonderful. Thank you !

**Comment by tarim** [comment]
Hi @DjebbZ ,

Where I can find an example for this? or could you show me how to use this please?

Thanks,

**Comment by peacechen** [comment]
This is an old thread but Google returns it as one of the top results for axios cancelSource.  Here's sample code that cancels the request after 10 seconds without response:
```
import { CancelToken } from 'axios';

this.cancelSource = CancelToken.source();

let watchdogTimer = setTimeout(() => {
	this.cancelSource.cancel("Operation timed out")
}, 10000);  // 10 second watchdog timer

let apiConfig = {cancelToken: this.cancelSource.token};
Core.api.request.post( 'some/url', {}, apiConfig ).then(response => {
	if (response.ok) {
		// Success
		clearTimeout(watchdogTimer);
	}
});
```

**Comment by dudiharush** [comment]
To make it easier to cancel multiple request, i created [axios-tx](https://www.npmjs.com/package/axios-tx)
