### ISSUE TITLE
De-conflict Typescript typings

### ISSUE THREAD

**Issue by DenisCarriere** [mzabriskie/axios#518]
There's an outdated typings on DT, however there's a lot more JSDocs written which makes it nice for IDE's.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/axios/axios.d.ts

Also with the newest release of Typescript 2.0, `typings` are no longer being used which makes your `axios.d.ts` definition not discoverable.

To fix this, you can change the filename of `axios.d.ts` to `index.d.ts` and everything will work with Typescript 2.0.

**Suggestions:** Drop the DT outdated typings OR contribute to the DT typings by submitted PR's when new changes occur.

**Comment by nickuraltsev** [comment]
> Also with the newest release of Typescript 2.0, typings are no longer being used

Could you please provide a link to docs or release notes?

**Comment by DenisCarriere** [comment]
Oh wait, that's not true, it's when installing axios with `yarn` the `types` value in the package.json is not being used.

I just installed `axios` again using `npm install axio` and the typings get installed.

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md

Regardless, changing your types to `index.d.ts` will import the types by default without having to look into the package.json

**Comment by DenisCarriere** [comment]
Also, Typescript 2.0 is suggesting to have your types managed by DT using `@types/<package>`.

> Packages on under the @types organization are published automatically from DefinitelyTyped using the types-publisher tool. To get your declarations published as an @types package, please submit a pull request to https://github.com/DefinitelyTyped/DefinitelyTyped. You can find more details in the contribution guidelines page.

**Comment by nickuraltsev** [comment]
Fixed via #519
