### ISSUE TITLE
React Native - Error response is not proper(getting string response instead of an object)

### ISSUE THREAD

**Issue by kmanishprdxn** [mzabriskie/axios#524]
I'm working on the mobile app where I'm using **react-native 0.35** and **axios 0.15.2**.

For successful API request I'm getting proper response object (including status, data .. etc). But when API request failed (due to 404 or any know error) catch function simply return string message. I'm expecting error response should be an object but I'm getting string response.

**error response** - `Error: Request failed with status code 404`

**function/action which contains this API request**

```
/* action to get OTP */
export function getOTP(phoneNumber) {
  return dispatch => {
    return axios.post(`${ROOT_URL}/generate/otp`, {'phoneNumber': phoneNumber})
      .then(response => {

        return response;
      })
      .catch(err => {
        console.log(err);

        return err;
      });
  };
}

```

**Comment by nickuraltsev** [comment]
Please see [this](http://stackoverflow.com/questions/39153080/how-can-i-get-the-status-code-from-an-http-error-in-axios/39153411) question on StackOverflow.

**Comment by kmanishprdxn** [comment]
@nickuraltsev Thanks for the links. It works for me.
