### ISSUE TITLE
Module '"axios"' has no default export.

### ISSUE THREAD

**Issue by fernandosouza** [mzabriskie/axios#530]
I'm getting this error by importing axios 0.15.2 in an Angular 2 application using typescript.

import axios from 'axios';

**Comment by djyde** [comment]
Have a try to set `"allowSyntheticDefaultImports": true` in `tsconfig.json`

**Comment by nickuraltsev** [comment]
Could you please provide a GitHub repo that reproduces the issue?

**Comment by fernandosouza** [comment]
Hi, guys. Thx for your comments.

@djyde, allowSyntheticDefaultImports works. Thank you. :)

**Comment by djyde** [comment]
You are welcome :)
