### ISSUE TITLE
[request] add default config for onSend and onStop

### ISSUE THREAD

**Issue by rafgugi** [mzabriskie/axios#531]
`jquery.ajax` library has [global ajax event handlers](http://api.jquery.com/category/ajax/global-ajax-event-handlers/). I use `.ajaxSend()` and `.ajaxStop()` to handle default action like disable all form interaction or adding an overlay.

**Comment by nickuraltsev** [comment]
You can implement this in your apps using interceptors. Please see [this](https://github.com/mzabriskie/axios#interceptors) for details.
