### ISSUE TITLE
when set content-type to 'x-www-form-urlencoded' the post data is wrong format

### ISSUE THREAD

**Issue by libertyAlone** [mzabriskie/axios#536]
when I use Axios like following, the form data is in a strange format in the picture,my code snippet:
```
var param = {
  a: 1,
  b: 2
}
Axios({
      method: 'post',
      url: '/xxx',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      data: param
    }).then(response => {
      dispatch(loginSuccess(response.data))
    })
    .catch(error => {
      throw(error);
    });
```
actual send request like this:
![bug](https://cloud.githubusercontent.com/assets/5511684/20304100/78676d1a-ab69-11e6-91eb-806efd8c9bce.png)
why the param object is transformed to a string key in form data ?

**Comment by nickuraltsev** [comment]
Please see [this](https://github.com/mzabriskie/axios/issues/350#issuecomment-227270046) comment.

**Comment by libertyAlone** [comment]
@nickuraltsev It works, thx~
