### ISSUE TITLE
422 response body

### ISSUE THREAD

**Issue by team5ru** [mzabriskie/axios#538]
I have 422 response from my laravel app with validation error messages in response body

```
axios.put(`myurl`,` form)
     .then(res=>console.log(res) )
     .catch(err=>console.log(err))
```

But axios just throwing 422 error, no response body available in callback arguments.
In the same time vue-resource pass response body and error to callback arguments, it works fine.
I think it have to work this way. Is it possible to do something with that?

**Comment by nickuraltsev** [comment]
Check `error.response.data` property. `console.log(err)` will not output the response body.

**Comment by pcowgill** [comment]
Maybe in the examples in the `axios` `README`, `console.log(error.response.data)` or `console.error(error.response.data)` should be included somewhere so newcomers to the library are more likely to find the error right away?
