### ISSUE TITLE
is there possible to combine with async/await !?

### ISSUE THREAD

**Issue by sky790312** [mzabriskie/axios#539]
is there possible to combine with async/await !?
or it already support..?

thx

**Comment by yanivefraim** [comment]
Async await will work for any promise, as long as you have the appropriate transpile / polyfill.

Take a look at [this example](https://github.com/wix/react-fullstack-seed/blob/master/src/actions/index.js#L22) (it uses babel [`stage-0` preset](https://github.com/wix/react-fullstack-seed/blob/ed664837944895df3bed8241d865adf996098c4b/package.json#L46) + [`babel-polyfill`](https://github.com/wix/react-fullstack-seed/blob/ed664837944895df3bed8241d865adf996098c4b/src/client.js#L1)

Hope this was helpfull

**Comment by sky790312** [comment]
ok, thx!

**Comment by yifeikong** [comment]
I hope this is mentioned in the README file

**Comment by frayhan32** [comment]
I think at this moment there is no possibility to combine **ajax** function with async/await. The only thing you can do is you can use **Promise.all** to get all return value from your promise call. Then use that value to execute your next function

**Comment by kgrosvenor** [comment]
It is possible @frayhan32 

try {
      let response = await http.get('Types/AllOptions');
      commit('setTypes', response.data);
    }
    catch (err) {
      console.log("Types loading error", err);
    }
