### ISSUE TITLE
How to rewrite headers in interceptor ?

### ISSUE THREAD

**Issue by khotey** [mzabriskie/axios#541]
I have interceptor:

```
requestInterceptor = axios.interceptors.request.use(function (config) {
    config.headers = { Authorization: `Bearer ${accessToken}`, 'X-TenantId': X_TENAT_ID};

    return config;
  }, function (error) {
    return Promise.reject(error);
  });
```

But in current request I need to send another header:

```
    const request = axios({
      url: USERS_URL_CREATE,
      method: 'post',
      headers: { Authorization: BASIC_TOKEN },
      data: userData
    });
```

But axios still send headers from interceptor, how fix it, without clearing interceptor ?

**Comment by nickuraltsev** [comment]
You can create two axios [instances](https://github.com/mzabriskie/axios#creating-an-instance) - one with the interceptor, another one without it. Hope this helps!

**Comment by hos4m** [comment]
This is late and I'm sure you already fixed your issue, but for reference. You don't have to create two Axios instances, here is how I managed to solve that:

The Axios instance:
```
let axiosInstance = axios.create({
  baseURL: "http://localhost:9000",
  timeout: 10000,
});
```

The interceptor:
```
axiosInstance.interceptors.request.use(
  config => {
    config.headers.authorization = localStorage.getItem("token");
    return config;
  },
  error => Promise.reject(error)
);
```

**Comment by tarun-nagpal-github** [comment]
@hos4m 

Can you please provide more details?

Like where should I include? In the same where I write services

**Comment by Rajshrishrimalshah** [comment]
You can include it in your app.js file
