### ISSUE TITLE
Cannot change request header Accept-Encoding

### ISSUE THREAD

**Issue by andykmiller** [mzabriskie/axios#542]
Hi, 
I am using 0.13.1. When the GET response from my backend is too big, it is compressed because Axios is sending "Accept-Encoding:gzip, deflate" and the get call “hangs”, as if the server didn’t respond. So I’m trying to figure out either how to handle compressed response or to just change the request header to  'Accept-Encoding': 'identity'. I’m focusing on the latter. I’ve included the things I’ve tried, but the request always sends "Accept-Encoding:gzip, deflate". Do you have any suggestions? 

Thanks,
Andy

axios.defaults.headers.common['Accept-Encoding'] = 'identity';
hubApiConfig.headers = {
  'Accept': 'application/json',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Accept-Encoding': 'identity'
};
hubApiConfig.headers.common = {
    'Accept-Encoding': 'identity'
};
var notifHubApi = axios.create(hubApiConfig);
axios.defaults.headers.common['Accept-Encoding'] = 'identity';
// axios.defaults.headers.get['Accept-Encoding'] = 'identity';
// notifHubApi.defaults.headers.get['Accept-Encoding'] = 'identity';

    return notifHubApi.get('notifications', {
      headers: {'Accept-Encoding': 'identity'}, 
      params: {
        jsonInput: JSON.stringify(queryData)
      }
    }).catch(function(error) {

**Comment by yanivefraim** [comment]
There are some issues with request headers which I hope https://github.com/mzabriskie/axios/pull/533 will solve. 

I'm not sure if the problem you experienced is the same, but worth checking. 

BTW - quickest check will be to take my fork (with this fix), link it to your project, and see if the problem was resolved. You'll have to use the relevant branch. Plz tell me if it works/ if you need help with that.

**Comment by andykmiller** [comment]
Thanks Yaniv. I didn't take your fork (wasn't sure how to do that), but I did take your source code changes and apply them to my version. That didn't help the issue.

**Comment by andykmiller** [comment]
I think XMLHttpRequest (used by Axios) does not allow setting Accept-Encoding header. So maybe I'm on the wrong track and need to focus on why compressed response is causing problems.

**Comment by nickuraltsev** [comment]
Right, `Accept-Encoding` is a forbidden header name (see [this](https://xhr.spec.whatwg.org/#the-setrequestheader()-method) for details).
