### ISSUE TITLE
Question: ECONNREFUSED error

### ISSUE THREAD

**Issue by dparmar74** [mzabriskie/axios#543]
With this code 

```
var x = require("axios");
x.get("http://hostxxx:10001/ping")
.then( (r) => {
  console.log(r);
})
.catch((r) => {
  console.log("ERROR");
  console.log(r);
})


```
I get below error

```
{ Error: connect ECONNREFUSED 10.37.20.102:3128
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.37.20.102',
  port: 3128,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.15.2' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     method: 'get',
     url: 'http://hostxxx:10001/ping',
     data: undefined },
  response: undefined }


```
Below code using "http" works without any issue
```
require('http').get('http://hostxxx:10001/ping', (res) => {
    res.setEncoding('utf8');
    res.on('data', function (body) {
        console.log(body);
    });
});

```
Can someone help me how to make above code work with "axios"

Env:  Node 6.9.1
Axios: 0.15.2 version

**Comment by dparmar74** [comment]
It was proxy issue

**Comment by dany92** [comment]
Hi, I'm having the exact same issue and I'm not sure how to solve it. Could you please share what you did to fix it? Thanks!

**Comment by dany92** [comment]
I think I fixed it by playing around with request config. haha I don't know if that's what you are supposed to do.

**Comment by hellsinglord22** [comment]
@irisdan can you please post your configuration, for now i will use `https` until i get your response ..

**Comment by irisdan** [comment]
@hellsinglord22 It was the proxy issue in my case. I was just testing things locally.
`return axios.get('/api/employees', {
			proxy: {
				host: '127.0.0.1',
				port: 1337
			}
		})
		.then(res => {
		})
		.catch(err => console.log(err));`

**Comment by hellsinglord22** [comment]
Thank you @irisdan, 
in my case i was trying to connect to uncertified https server, 
so i used certificate and worked just fine ....  
just for record the server wasn't on my local machine so i didn't need to use proxy like you ...

**Comment by myckel** [comment]
with the http i fix my problem thanks

**Comment by WhatsAppBott** [comment]
Add baseURL
