### ISSUE TITLE
Issue with axios browser dependencies

### ISSUE THREAD

**Issue by jinxac** [mzabriskie/axios#548]
I am seeing following in the documentation. 
![screen shot 2016-11-22 at 5 07 56 pm](https://cloud.githubusercontent.com/assets/15068096/20522443/56375116-b0d6-11e6-9aea-6c88b0aca749.png)

Getting a little confused about safari browser support here. According to above chart it seems like it does not work on safari 9 however it works fine on safari 6 or 7.

So my concern is that is axios supported on safari 9?

**Comment by nickuraltsev** [comment]
The chart actually shows the opposite: axios has been tested with Safari 9. What makes you think it does not work in Safari 9?
