### ISSUE TITLE
Axios Browser Cross-Origin 302 not followed on POST

### ISSUE THREAD

**Issue by bar4ka** [mzabriskie/axios#549]
I was using the Fetch Api to make a POST on a URL that redirects to another domain. 
After the initial POST and 302 response the Fetch Api follow the redirect but this time sends a *GET* method with no body payload. 

So I have switched to axios browser version hoping the redirects works, and by works I mean another POST with the body payload on the redirected server.

So I included the javascript from cdn and include this code to make a POST:

```
            axios.post('/a/claim', {
                'adcopy_challenge': adcopy_challenge,
                'adcopy_response': adcopy_response
            }).then(function(response) {
                console.log(response);
            }).catch(function(error) {
                console.log(error);
            });
```

And I got 3 requests on Chrome network tab:

First a GET method with no body with a 302 response
![image](https://cloud.githubusercontent.com/assets/21070398/20545179/ea3bd652-b0f4-11e6-84e4-294ae7d0d614.png)

Well here is the POST method with correct body payload but not on the redirected location:

![image](https://cloud.githubusercontent.com/assets/21070398/20545316/a719e3f4-b0f5-11e6-8fdc-10d9bef935d5.png)

Finally some redirection on the right location but this time a *GET* with no payload which got a 400 because there is no payload at all. Luckily server was listening both on GET and POST, if I turned it to route only on POST I will get a 404.

![image](https://cloud.githubusercontent.com/assets/21070398/20545428/4e6ac66e-b0f6-11e6-9791-2823b045ad9d.png)

Hoping for any enlightenment about why there is no second POST on the redirected location or why the first POST was not on the right location after a GET there already received a 302 with the new location.

The Fetch Api is doing almost the same thing but there is only two network calls

**Comment by nickuraltsev** [comment]
Browsers (at least some of them) convert POST requests to GET when following redirects. Please see [this](http://stackoverflow.com/questions/17605915/what-is-the-correct-behavior-expected-of-an-http-post-302-redirect-to-get) and [this](http://stackoverflow.com/questions/8138137/http-post-request-receives-a-302-should-the-redirect-request-be-a-get) for details.
