### ISSUE TITLE
Unable to by pass SSL certificate 

### ISSUE THREAD

**Issue by bairisuresh** [mzabriskie/axios#550]
const https = require('https');
axios({
url: url,
method: 'GET',
headers: {
'Content-Type': 'application/json'
},
responseType: 'json',
httpsAgent: new https.Agent({ rejectUnauthorized: false })
})
.then(response => {
})
.catch(error => {
})
}
}

Self-signed SSL certificate is there in my server but unable to call the service with https from axios..

**Comment by nickuraltsev** [comment]
Are you getting an error?

**Comment by Klaasvaak** [comment]
Did you add the Self-signed SSL certificate to the browser? In Chrome you can add it in `chrome://settings/` at the option `HTTPS/SSL`.

When a certificate is not valid the browser will make sure the requests errors. Axios can not change this, and you shouldn't want that either.

Make sure you have a valid certificate when running in production.

**Comment by nickuraltsev** [comment]
Closing as it does not seem to be an axios issue.

**Comment by hcivelek** [comment]
Thanks @Klaasvaak .
When I read your first sentence then I realized what is wrong..  I didn't go settings. I just opened a new tab and go to my issued ssl page. Then browser ask me about safety and I proceed.. Done! no more error.
