### ISSUE TITLE
Ability to pipe read stream to PUT/POST request (Node)

### ISSUE THREAD

**Issue by jsonmaur** [mzabriskie/axios#553]
Is there a way to pipe a read stream to axios? I know you can send a stream using the `data` option, but I'm not sure how to use `pipe` with that (if it's already possible). My use case is I need to compress files on the fly as they upload. I'm reading files with `createReadStream`, then passing to [archiver](https://github.com/archiverjs/node-archiver), and I need to be able to pipe from archiver to axios. 

With other request libraries (https://visionmedia.github.io/superagent/#piping-data), you can use like this: `readStream.pipe(request.put('/somewhere'))`. But that doesn't currently work with Axios.

**Comment by nickuraltsev** [comment]
You should be able to pass an archiver stream to axios as follows:

```js
archive.append(fs.createReadStream(file), { name: 'file.txt' });
axios.post(url, archive);
```

Please let me know if it does not work.

**Comment by isNeilLin** [comment]
`
var FormData = require('form-data');
var axios = require('axios');
var form = new FormData();
	form.append('bookid',id);
	form.append('classes',classes);
	form.append('data',fs.createReadStream(__dirname + `${file}`));
	axios.defaults.headers.common = form.getHeaders();
	axios.post(`${baseUrl}/outline/create`,form)
	.then((response)=>{
		console.log(response.data)
	})
	.catch(e=>{console.log(e)})`
I try to post formdata,but not success because content-length
![image](https://cloud.githubusercontent.com/assets/18683728/23841370/ad9d62a2-07e7-11e7-91b7-c9c32ac722e0.png)

**Comment by StarpTech** [comment]
Please reopen the answer it doesnt actually answer the question. I also have the same issue and want to pipe any data to request (the node way) 

https://github.com/mzabriskie/axios/issues/961

**Comment by StarpTech** [comment]
Please reopen! Issue is not fixed.

**Comment by AdonRain** [comment]
I have the same problem.

**Comment by InsidiousMind** [comment]
👍

**Comment by ratze90** [comment]
Does someone found a solution for this problem?

**Comment by libasoles** [comment]
I'm doing something tricky that may help someone else. 

Basically, I'm forwarding a stream using `koa` and `axios`. It's a file attachment, so I have to deal with `FormData`.

```
api.post('/registrations/:id/withholding-tax-exclusion', async ctx => {
  const { id } = ctx.params;
  
  const request = (chunk) => {
  
    const data = new FormData();
    data.append('attachment', chunk);
    
    return BACKEND({
      method: 'POST',
      url: `/registrations/${id}/withholding-tax-exclusion`,
      data,
      headers: {
        'Content-Type': ctx.req.headers['content-type'],
      },
    }).then((response) => {
  
      ctx.res.headers = response.headers;
      ctx.body = response.body;
      console.log("UPLOAD OK")
      ctx.status = 200;
    });
  };
  
  await streamToPromise(ctx.req).then(request);
  console.log("END");
});
```

Magic happens here:
`wait streamToPromise(ctx.req).then(request);`

I'm converting the stream to a promise, so I can wait for axios response before sending back the koa response to client.

See:
https://github.com/bendrucker/stream-to-promise

**Comment by iislucas** [comment]
I don't think that solves the problem that the issue is about: it doesn't *stream* the data, instead it locally loads it all in memory. In particular, streaming will work with files larger than fit in memory, but the streamToPromise will fail.

**Comment by gonejack** [comment]
I am facing the same issue wile posting big files in form data with axios with memory overflow.
