### ISSUE TITLE
Request being cancelled with 302 plus request type is being cancelled

### ISSUE THREAD

**Issue by jlubeck** [mzabriskie/axios#557]
Hi!

So, i'm not sure if this is an axios request, but I wouldn't know where else to ask.

I'm making a POST request to my server, with what I'm think is a proper CORS response to handle requests from *, and after a succesful OPTIONS response, the request is being redirected as GET (even though I send POST) and cancelled.

Any idea if this is a  problem with how axios sent the initial request, or what?

Here are 2 images of the 2 requests:

![Alt text](https://monosnap.com/file/Nl1MvIMZvkpMrS8WSeZhFDjb2hTzTY.png)

![Alt text](https://monosnap.com/file/nLjuxUdOCJLfLIKIfpXbYQq1VIRFKX.png)

Thanks

**Comment by mzabriskie** [comment]
Can you `POST` to the URL outside of `axios`? Maybe try `Postman`?

**Comment by jlubeck** [comment]
Mmm, I can't replicate this issue now as I changed the backend language from PHP to NodeJS and now everything is working for me. So I'm not sure if maybe it was a backend issue?

**Comment by mzabriskie** [comment]
In my experience with axios it seems that most CORS related issues stem from improperly configured backends. Glad that it's working now!
