### ISSUE TITLE
Issues with array params after upgrading to 0.15.3

### ISSUE THREAD

**Issue by skmvasu** [mzabriskie/axios#559]
I'm trying to upgrade axios to `0.15.3` from `0.5.4`. I know I'm very late to the party, but better late than never :D

I'm facing some issues with `buildURL` serializer. 

 ```
axios.get('/filter_users',  {
   params: {user__in=[1, 2, 3]}
})
```

Earlier when I do this it used to send the request as `/filter_users?user__id=1&user__in=2&user__in=3`. Now I
 noticed that we're appending a `[]` on [array properties](https://github.com/mzabriskie/axios/commit/7fa69152e952b26c6655a3ee3775b0f90050e5d3).  

Is there a reason why we're appending a `[]` to every array parameter? 

Some of my older API's breaks because of this change. Trying to figure out the rationale behind this before jumping to a solution :)

**Comment by nickuraltsev** [comment]
There is no standard way of serializing arrays. Please see this discussion: http://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string

If you'd like to use another format, you can set a custom `paramsSerializer` as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the [`qs`](https://github.com/ljharb/qs) library:

```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

Hope this helps!

**Comment by skmvasu** [comment]
Thanks @nickuraltsev. I did just that, but was curious to know why this had to be implemented :)
