### ISSUE TITLE
Timeout configuration?

### ISSUE THREAD

**Issue by chrismcv** [mzabriskie/axios#56]
hi, 
I was wondering if there is a way to configure the default timeout for axios requests?

thanks, 
chris

**Comment by mzabriskie** [comment]
Currently no option for this. But it would be a good feature.

**Comment by WillsB3** [comment]
+1 for this feature.

**Comment by chrismcv** [comment]
FYI - I'm doing it like this presently as a workaround

```
timeout = (s, promise) ->
  new Promise (resolve, reject) ->
    promise.then(resolve);
    setTimeout((-> 
      e = new Error('Timeout after '+s+' s')
      e.statusCode = 'timeout'
      reject e
    ), s * 1000);
```

`timeout(10, axios.get(url)).catch globalErrorHandler`

**Comment by mzabriskie** [comment]
This will be available when 0.6.0 is released.

**Comment by WillsB3** [comment]
:+1:

**Comment by mzabriskie** [comment]
I just released 0.6.0 which includes a fix for this.

**Comment by tnrich** [comment]
hey @mzabriskie, could you please provide an example of how to use the timeout config for a single request?

Thanks very much!
Thomas

**Comment by srahulprdxn** [comment]
@tnrich axios.get('your-url', {'timeout': 1000});

I hope this helps.

**Comment by srahulprdxn** [comment]
@mzabriskie I have set axios.defaults.timeout = 1000;

I disconnected the server that provides me with the rest API.

But it takes more that 1 ms to timeout after sending a request.

This is how my request looks:

```
    return axios.post(`${ROOT_URL}/login/${role}`, creds).then((response) => {
      console.log(response);

        if(response.status === 200) {
          // If login was successful, set the token in local storage
          localStorage.setItem(`${role}_log_toks`, JSON.stringify(response.data));

          // Dispatch the success action
          dispatch(receiveLogin(response.data));

          return response;
        }
      }).catch(err => {
        console.log(err);
        // If there was a problem, we want to
        // dispatch the error condition
        if(err.data && err.status === 404) {
          dispatch(loginError(err.data));
        } else {
          dispatch(loginError('Please check your network connection and try again.'));
        }

        return err;
      });
```
