### ISSUE TITLE
Network Error and Status 200 Handling

### ISSUE THREAD

**Issue by miguel-orange** [mzabriskie/axios#562]
I'm able to get a CORS network error message AND status code 200. I'd like to use the response data. However, I can't access it because this case results in a error catch. Is there a way to ignore the network error message?
_axios version: 0.15.2_
![cors](https://cloud.githubusercontent.com/assets/13228659/20686708/9be09668-b56e-11e6-862e-a1c6e8e11e4d.PNG)

![response](https://cloud.githubusercontent.com/assets/13228659/20686611/45cdb364-b56e-11e6-8539-6be8f6820d36.PNG)

**Comment by nickuraltsev** [comment]
The browser will *not* allow you to access the response of a `CORS` request if the `Access-Control-Allow-Origin` header is missing.

Here are some great articles that explain how CORS works:
- https://www.html5rocks.com/en/tutorials/cors/
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Hope this helps!

**Comment by mbistuer** [comment]
i have is the same problem with api  but i resolve error etag express (304 not modified) but i don´t works yet
<img width="411" alt="captura de pantalla 2017-05-30 a las 19 25 13" src="https://cloud.githubusercontent.com/assets/14913444/26596311/98eb345a-456e-11e7-97be-db526ce4ca3a.png">
