### ISSUE TITLE
type with Date not need to change

### ISSUE THREAD

**Issue by AaronChen2012** [mzabriskie/axios#567]
date value is Date {Fri Dec 02 2016 09:33:48 GMT+0800} change to 	
2016-12-02T01:33:48.309Z,
but i not need to changed,how can i do

**Comment by nickuraltsev** [comment]
When data is serialized to `JSON` using [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify), `Date` values are converted to `ISO 8601` format. If you'd like to use another format, you can convert all `Date` values to the desired format in your code before passing data to axios. 

For example:

```js
axios.post('/foo', {
  date: 'Fri Dec 02 2016 09:33:48 GMT+0800'
});
```

Hope this helps!
