### ISSUE TITLE
TypeError: this is undefined

### ISSUE THREAD

**Issue by Sopheakmorm** [mzabriskie/axios#568]
hey guys,

I want to get data from Server and set the response data to state
but I got an error 

here is the code block :

`  getData() {
    const url = "https://jsonplaceholder.typicode.com/todos";
    axios
      .get(url)
      .then(function (response) {
        this.setState({todos:response});
        console.log(JSON.stringify(response));
      })
      .catch(function (error) {
        console.log(error);
      });
  }`

Thank You so much !!

**Comment by rroslaniec** [comment]
You have problem with context. try this:
getData() {
    const url = "https://jsonplaceholder.typicode.com/todos";
    axios.get(url).then(response => { 
    	this.setState({ todos: response });
        console.log(JSON.stringify(response)); 
    }).catch(function(error) { console.log(error); }); 
}

See arrow funcion? This keeps you current context (like var _this = this; in old style)

**Comment by nickuraltsev** [comment]
Here is an article that explains how `this` works in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

Hope this helps!
