### ISSUE TITLE
CORS error No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by andylaci** [mzabriskie/axios#569]
Hello, this is my request:

`
axios({
      method: 'POST',
      url: `${SERVER_ADDRESS}/api/v1/manager/restaurant/${restaurantName}/payment-methods`,
      crossDomain: true,
      data: {
        payment_methods: checkedPayments
      },
    })
      .then(() => {
        dispatch(loadPayments(restaurantName));
      }).catch((error) => {
      console.log(error);
        dispatch(paymentsError());
      });
`

the server is laravel 5, it is responding with:

`XMLHttpRequest cannot load http://localhost:8000/api/v1/manager/restaurant/accusamus/payment-methods. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

Server headers are set with CORS middleware like this:

        return $next($request)
            ->header("Access-Control-Expose-Headers", "Access-Control-*")
            ->header("Access-Control-Allow-Headers", "Access-Control-*, Origin, X-Requested-With, Content-Type, Accept")
            ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS, HEAD')
            ->header('Access-Control-Allow-Origin', '*')
            ->header('Allow', 'GET, POST, PUT, DELETE, OPTIONS, HEAD');

Theese are the response headers, which I get when I use postman:

Access-Control-Allow-Headers →Access-Control-*, Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods →GET, POST, PUT, DELETE, OPTIONS, HEAD
Access-Control-Allow-Origin →*
Access-Control-Expose-Headers →Access-Control-*
Allow →GET, POST, PUT, DELETE, OPTIONS, HEAD
Cache-Control →no-cache
Connection →close
Content-Type →text/html; charset=UTF-8
Date →Sat, 03 Dec 2016 10:33:04 GMT
Host →localhost:8000
X-Powered-By →PHP/7.0.13
X-RateLimit-Limit →60
X-RateLimit-Remaining →59
phpdebugbar-id →0ff14bef1824f587d8f278c87ab52544

AXIOS sends preflight which is:

Request URL:http://localhost:8000/api/v1/manager/restaurant/accusamus/payment-methods
Request Method:OPTIONS
Status Code:200 OK
Remote Address:[::1]:8000
Response Headers
view source
Allow:GET,HEAD,POST
Cache-Control:no-cache
Connection:close
Content-Type:text/html; charset=UTF-8
Date:Sat, 03 Dec 2016 10:25:27 GMT
Host:localhost:8000
X-Powered-By:PHP/7.0.13

Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:localhost:8000
Origin:http://localhost:3000
Referer:http://localhost:3000/restaurant-profile/payment
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

Am I doing something wrong? I can't figure it how to do this. Witch Chrome plugin CORS everything works fine, but this is not the way.

Please help, help is really appreciated, spent hours with this.

**Comment by nickuraltsev** [comment]
Looks like your server does not include the `Access-Control-Allow-Origin` header in response to a preflight request (`OPTIONS`). A `CORS` request will fail if `Access-Control-Allow-Origin` is missing. 

Here are some great articles that explain how `CORS` works:
- https://www.html5rocks.com/en/tutorials/cors/
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Hope this helps!

**Comment by andylaci** [comment]
it was problem in server not acception OPTIONS requests, because routes were declared as GET::sometnig or POST:: something, so the preflight couldn't pass and the POST request was decliend, hope this will help another people to prevent hours of googling

**Comment by scottgrayson** [comment]
@andylaci How exactly did you fix this? i am also using axios with laravel-cors and i would like to know what you did to make the server accept OPTIONS

**Comment by andylaci** [comment]
hmm, backend developers solved it finally 😕 Don't know their names, but I think they inserted some global filters there.

**Comment by scottgrayson** [comment]
@andylaci i found a good example from the vue-auth demo https://github.com/websanova/laravel-api-demo

**Comment by lmiller1990** [comment]
Hey everyone, I had this problem too, not sure is it's the same as everyone else but I had

axios.get('localhost:3000/posts')
.then((res) => { ... })

which I was able to make work by simply adding 

axios.get('_http://_localhost:3000/posts')....

**Comment by hpsoar** [comment]
My server added `Access-Control-Allow-Origin` header to options request.

still get the error.

And it's strange that axios actually received 200 & the data server returned. Don't know why I still get the error.

**Comment by aksperiod** [comment]
Same. Using Flask with flask-cors

**Comment by jameskandau** [comment]
Create a middleware with the headers..
then bind your routes in that middleware group

**Comment by libasoles** [comment]
having the same issue with webpack dev server. Already added the headers:
`headers: { "Access-Control-Allow-Origin": "*" },`

Still won't work. I also tried the proxy approach (with variants):
```
proxy: {
            '/api': {
                target: {
                    host: "localhost",
                    protocol: 'http:',
                    port: '8082',
                    secure: false
                },
                pathRewrite: {
                    '^/api': ''
                }
            }
        }
```

So, maybe I'm missing somethign regarding axios?

**Comment by DavidCWebs** [comment]
I had the same issue sending a POST request from a Vue app to Laravel API. The comment on 4 Dec by @andylaci helped! Fixed by adding a new route responding to the OPTIONS request method in the backend. This gives back the access control headers required for the POST request to proceed.

**Comment by shraddha18** [comment]
Hi @DavidCWebs Is it possible to have a snippet of the code you entered? It will definitely help make things clearer.

**Comment by DavidCWebs** [comment]
Hi @shraddha18 , I've added all relevant code and a few notes to this gist: https://gist.github.com/DavidCWebs/4e4adde53a9c54f94e25e8a72f1251e8
Let me know if you need more info!

**Comment by sigmasoldi3r** [comment]
I have the same problem: My server declares the CORS headers but still get the error (In fact I'm using [CORS JS for express](https://github.com/expressjs/cors)
![screenshot from 2017-10-19 14 58 49](https://user-images.githubusercontent.com/13834659/31771947-3180dfe2-b4de-11e7-8638-1978c88c53c0.png)

But console said:
![screenshot from 2017-10-19 14 59 06](https://user-images.githubusercontent.com/13834659/31771972-47ab8632-b4de-11e7-930e-b78c0f5c0552.png)

**Comment by ilazakis** [comment]
Not sure why this was closed.  I can see 200s for both the ```OPTIONS``` and the subsequent request (PUT). axios still reports it as an error.

**Comment by jameskandau** [comment]
install this https://github.com/barryvdh/laravel-cors.. if it still gives this issue use ngrok to test your apis

**Comment by gbrits** [comment]
I found that when your (backend) method's response isn't interpretable by the front-end, you can receive a CORS-looking issue. For example, I was using `die('message');` in my Laravel method and I received a CORS complaint, despite my CORS being whitelisted. After changing my response to just be `return ['status' => 'success'];` which formats over into JSON to the FE - problem solved. Curious if this may be the issue for some of you too. :)

**Comment by jaime48** [comment]
his error is caused by CORS security. When Browser hits the request to another domain, by default, it denies the request.

Possible Solutions:
We need to allow this origin to Laravel server side. So we need to create one middleware at the backend and apply this middleware to every API request. By putting this middleware, we are explicitly told Laravel that we are allowing this request to access our resources.

Download the following Laravel Specific CORS package to avoid this issue and follow the steps.
composer require barryvdh/laravel-cors
Add the Cors\ServiceProvider to your config/app.php provider’s array

Barryvdh\Cors\ServiceProvider::class,

To allow CORS for all your routes, add the HandleCors middleware in the $middleware property of app/Http/Kernel.phpclass:

protected $middleware = [
    // ...
    \Barryvdh\Cors\HandleCors::class,
];
You can publish the config using this command:

php artisan vendor:publish --provider="Barryvdh\Cors\ServiceProvider"
Now, try again, it will save the data into the database. I have not set the redirect after saving the data but will set in short, while you can check the values in the database.

**Comment by docmattman** [comment]
@gbrits thanks for the tip!  This was the case for me.  I couldn't figure out why CORS wasn't working for me.  Turns out I was debugging some things using `die('...');` in my code which didn't allow the middleware headers to be sent in the response.  Removing the `die` did the trick.  Thanks!

**Comment by lmiller1990** [comment]
I just realized my comment last year got 100+ downvotes. I don't know why - was I doing something bad/insecure? I posted about adding `http` to the request to get it to work when running on localhost (I think my actual situation was axios failing in a test env).

**Comment by andylaci** [comment]
didn't check the thread for longer, but the success to this issue is to

- allow `Access-Control-Expose-Headers: Access-Control-Allow-Origin` on the server side,
- `Access-Control-Allow-Origin: *` < server
- set axios option `crossDomain: true` < axios
- don't forget to enable Access to OPTIONS requests as well < server

**Comment by nithingrao** [comment]
Disable the chrome security.Create a chrome shortcut right click -> properties -> target, paste this "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir="c:/chromedev"

**Comment by m-bryo** [comment]
in my own case, I manage the nginx installation. It was working until I switched to another VPS instance, and even with the same nginx configs, it's not working and I've no clue why.

**Comment by ehsankhfr** [comment]
There is no option as crossDomain inside the Axios. Please study the source-code before giving/using wrong clues.

**Comment by anicarrr** [comment]
Guys, just download a plugin to intercept request like "ModHeaders" in Chrome and then in the response headers add "Access-Control-Allow-Origin" with value "*". That will simulate as your server is sending you that in the header response.

**Comment by Koshukey** [comment]
I use Flask and by adding flask-cors, I could solve this problem !!!!!!!!

**Comment by GraxMonzo** [comment]
My solution is
`axios.get('https://cors-anywhere.herokuapp.com/' + yourUrl)`

**Comment by heyjoy21** [comment]
tried all the solution mentioned above. nothing works.
finally found one - `https://github.com/expressjs/cors`
i hope it helps you guys

**Comment by AleksandarSavic95** [comment]
CORS issue occured to me suddenly, "in the middle of the development", and what helped was to clear the cache. I'm talking about Laravel, so here are the commands:
```
php artisan cache:clear
php artisan config:clear
php artisan route:clear

php artisan config:cache
php artisan route:cache
```

**Comment by aldomendez** [comment]
> I found that when your (backend) method's response isn't interpretable by the front-end, you can receive a CORS-looking issue. For example, I was using `die('message');` in my Laravel method and I received a CORS complaint, despite my CORS being whitelisted. After changing my response to just be `return ['status' => 'success'];` which formats over into JSON to the FE - problem solved. Curious if this may be the issue for some of you too. :)

You hust saved my day. a dd(...) was ruining my day!

**Comment by diegomagikal** [comment]
> I found that when your (backend) method's response isn't interpretable by the front-end, you can receive a CORS-looking issue. For example, I was using `die('message');` in my Laravel method and I received a CORS complaint, despite my CORS being whitelisted. After changing my response to just be `return ['status' => 'success'];` which formats over into JSON to the FE - problem solved. Curious if this may be the issue for some of you too. :)

Thanks a lot! :1st_place_medal:

**Comment by theristes** [comment]
Just avoid using the word "localhost".  Why not IP instead?

**Comment by Cauen** [comment]
If you are using nodejs, use 

```
var cors = require('cors');
var express = require('express');
var app = express();
app.use(cors());
```

It fix CORs at server, if you cant send CORS request, test the Route locally, sometimes route dont work on production (For example, caused by nginx), and wrongly shows the CORS error. That was my case.

Try a simple route, like
```
app.post ('/test', (req, res) => {
	res.send('test route');
})
```
I noticed that the route starting with / auth was giving error in Nginx, and said that it was because of CORS
I fixed only by changing the location of the route with error
From '/auth/login' to /login/
Hope this helps

**Comment by gannher** [comment]
Hello
I think CORS request with Axios doesn't work because Axios doesn't set "origin" in request header :
Origin: http://<url>

I try with JQuery and it works perfectly. The only difference is that request build with JQuery contains "origin" header.

**Comment by vaporwavie** [comment]
I too had this issue with axios, which got solved by using jQuery ajax function (definitely not proud of it though). Looks like axios doesn't handle cross domain requests that well...

**Comment by yanickrochon** [comment]
I wonder how anyone solved this problem. I've been trying to make this work for 3 days on a demo project I wish to present, but this has been halting me ever since. YouTube tutorials make it seem so simple, yet everything I do _exactly_ like them fail, and it seems like the OPTIONS request does not send the request headers I specify.

Instead of passing around a configuration object, I used the supposedly working `axios.defaults` in one module, like this :

```js
   axios.defaults.headers.common = {
      ...axios.defaults.headers.common,
      'Access-Control-Allow-Origin': 'http://localhost:3000',
      "Content-Type": 'application/json',
      "Authorization": token ? `Token ${token}` : undefined
   };
   axios.defaults.preflightContinue = true;
   //axios.defaults.crossDomain = true;
   axios.defaults.withCredentials = !!token;
```

When I perform the actual request, I can check that the options are indeed set : `console.log(axios.defaults);`, but the request ends with a code `200` (success) and I get 

![Selection_125](https://user-images.githubusercontent.com/78461/57060507-aec45d00-6c87-11e9-9e92-4b7ebcbe3bb1.png)

As for the server, I'm using Django, and I watched about half a dozen videos, read the official docs, etc. and then fiddled some more. Nothing works.

**Comment by xgui3783** [comment]
It seems you are trying to call 127.0.0.1:3000 from localhost:3000 , and browser are treating them as separate domains. 

FYI, access-control-allow-origin header needs to be set by the server, not the client. So in your case, you need to check how to configure cors with django, and allow CORS requests from localhost.

**Comment by yanickrochon** [comment]
I tried everything I can find on from Django's side. Nothing works. As for `127.0.0.1:3000`, I have no idea why it echoes this in the console because the browser URL is `localhost:3000` and I'm requesting `localhost:8000/path/to/api/`.

**Comment by xgui3783** [comment]
hmm, definitely different origin (different port = different origin)
you tried following these steps?
https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework

**Comment by yanickrochon** [comment]
Yes. Never really had to bother with CORS before (had everything running from he same domain and port). And I have read nothing but conflicting discussions about what to send, and what the server is supposed to respond from various sources. In fact, even in this very thread some comments suggest things that aren't even valid options! Perhaps the specs will be refined down the road, but this is all very frustrating, just like how browsers now block the access to LAN routers that expose HTTPS management consoles with expired SSL certificates. Good job, Google!

Anyhow, I ended up setting `CORS_ORIGIN_ALLOW_ALL = False` with a set of white list local domains, and it seems to partly work.... now the URL returns an error 405 which has nothing do do with this anymore. Arrgh!

**Comment by jsbimra** [comment]
@yanickrochon even I facing the same kind of error message in console log, but my get request working perfectly fine no issues for response, when I try to make a post request on same API path, it gives error what you have mentioned above! :( 

`const url = 'http://localhost/xxx-api/contacts.php';
            axios({
                method: 'post',
                url,
                data: postData,
                config: {
                    headers: {
                        'Content-Type': 'multipart/form-data',
                        // 'Content-Type': 'application/x-www-form-urlencoded',
                    }
                }
            })
            .then(resp => {
                console.log('Submission response', resp);
            })
            .catch(err => console.error(err));`

Error it throws: 

![image](https://user-images.githubusercontent.com/1294763/57185230-35c24100-6ee5-11e9-9fc2-9823639e4614.png)

Working with get request: 
![image](https://user-images.githubusercontent.com/1294763/57185246-8d60ac80-6ee5-11e9-9a5a-8f3998393784.png)

**Comment by jsbimra** [comment]
> @yanickrochon even I facing the same kind of error message, but my get request working perfectly fine no issues for response, when I try to make a post request on same API, it gives error similar what you have mentioned above!
> 
> `const url = 'http://localhost/xxx-api/contacts.php'; axios({ method: 'post', url, data: postData, config: { headers: { 'Content-Type': 'multipart/form-data', // 'Content-Type': 'application/x-www-form-urlencoded', } } }) .then(resp => { console.log('Submission response', resp); }) .catch(err => console.error(err));`
> 
> Error it throws:
> 
> ![image](https://user-images.githubusercontent.com/1294763/57185230-35c24100-6ee5-11e9-9fc2-9823639e4614.png)
> 
> Working with get request:
> ![image](https://user-images.githubusercontent.com/1294763/57185246-8d60ac80-6ee5-11e9-9a5a-8f3998393784.png)

The issue was $_POST was not able to read normal JSON data, turned into as a FormData it worked and error is gone now.

updated code below:

`const {name, email, city, country, message} = this.state.contact;
            const formData = new FormData();

            formData.append('name', name);
            formData.append('email', email);
            formData.append('city', city);
            formData.append('country', country);
            formData.append('message',message);
            const url = 'http://localhost/xxx-api/contacts.php';
            axios({
                method: 'post',
                url,
                data: formData,
                config: {
                    headers: {
                        'Content-Type': 'multipart/form-data',
                    }
                }
            })
            .then(resp => {
                console.log('Submission response', resp);
            })
            .catch(err => console.error(err));`

**Comment by Satsh24** [comment]
@jsbimra  can you try this : axios.get(url,{crossDomain : true}).then("your code goes here") .
 I hope this will solve your problem.

**Comment by makzylinski** [comment]
@Satsh24 does not work

**Comment by sudeepdk** [comment]
If your backend is Nodejs then -- this is your fix ..

`npm install cors
`

`var express = require('express')
  , cors = require('cors')
  , app = express();
app.options('*', cors()); // preflight OPTIONS; put before other routes
app.listen(80, function(){
  console.log('CORS-enabled web server listening on port 80');
});`


https://stackoverflow.com/questions/46904400/why-do-i-get-an-options-request-after-making-a-post-request

**Comment by JoeXin** [comment]
> I wonder how anyone solved this problem. I've been trying to make this work for 3 days on a demo project I wish to present, but this has been halting me ever since. YouTube tutorials make it seem so simple, yet everything I do _exactly_ like them fail, and it seems like the OPTIONS request does not send the request headers I specify.
> 
> Instead of passing around a configuration object, I used the supposedly working `axios.defaults` in one module, like this :
> 
> ```js
>    axios.defaults.headers.common = {
>       ...axios.defaults.headers.common,
>       'Access-Control-Allow-Origin': 'http://localhost:3000',
>       "Content-Type": 'application/json',
>       "Authorization": token ? `Token ${token}` : undefined
>    };
>    axios.defaults.preflightContinue = true;
>    //axios.defaults.crossDomain = true;
>    axios.defaults.withCredentials = !!token;
> ```
> 
> When I perform the actual request, I can check that the options are indeed set : `console.log(axios.defaults);`, but the request ends with a code `200` (success) and I get
> 
> ![Selection_125](https://user-images.githubusercontent.com/78461/57060507-aec45d00-6c87-11e9-9e92-4b7ebcbe3bb1.png)
> 
> As for the server, I'm using Django, and I watched about half a dozen videos, read the official docs, etc. and then fiddled some more. Nothing works.

Hello, I have encountered the same problem. I have checked a lot of information and have not solved it. How do you deal with it?

**Comment by adimshev** [comment]
Replace Content-Type: application/json by  application/x-www-form-urlencoded or multipart/form-data works for me.

**Comment by nathanielimeyer** [comment]
> I just realized my comment last year got 100+ downvotes. I don't know why - was I doing something bad/insecure? I posted about adding `http` to the request to get it to work when running on localhost (I think my actual situation was axios failing in a test env).

Your comment was off topic. It doesn't throw the same error that this thread addresses. You probably get something like "Access... has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https." This thread is meant to address errors related to missing headers.

Again, off topic, but to your point when a method wants a URL give it a URL. You probably could have gotten away with "//localhost:3000" (browser inserts the protocol of the current page) and maybe gotten warnings. But the modern best practice is always include the schema (protocol). https://en.wikipedia.org/wiki/URL#Syntax

**Comment by OndraRehounek** [comment]
Afrer several desperate hours I realized that cause of my CORS error was request header 

`"Content-Type": 'application/json'`

when I removed it, requests started working like a charm

**Comment by Yamilquery** [comment]
This is not a solution 👎 

We need to use the `Content-Type: "aplication/json"` but we can't do it because the server doesn't allow us to use custom Content-Type headers.

**Comment by Miodragt** [comment]
> Hey everyone, I had this problem too, not sure is it's the same as everyone else but I had
> 
> axios.get('localhost:3000/posts')
> .then((res) => { ... })
> 
> which I was able to make work by simply adding
> 
> axios.get('http://localhost:3000/posts')...

For getting data of localhost port 3000 in developer mode of work , you can use  next code 
axios.get('/posts.json') 
Because,  port 3000  present content of public folder in react app, like default folder all time when you developing your react app. Except you change this setting

**Comment by HusDev** [comment]
I faced the same problem,  then I realized CORS must be enabled from the server middleware, not from the client.
I'm using the Laravel framework, and this article helped me out: 
https://medium.com/@petehouston/allow-cors-in-laravel-2b574c51d0c1

**Comment by mike-seekwell** [comment]
A few have mentioned this, but if you're using Flask, you should really try adding `flask_cors` before doing anything on the front-end. First `pip install flask-cors==3.0.7`, then:


    from flask_cors import CORS

    app = Flask(__name__)
    CORS(app)

**Comment by iKlsR** [comment]
Ok this is beyond me but for some reason, removing a trailing `/` I had at the end of my url fixed this error for me.

**Comment by revanth125** [comment]
[This](https://icetutor.com/question/no-access-control-allow-origin-header-is-present-on-the-requested-resource-when-trying-to-get-data-from-a-rest-api/) Might Be Helpful For You...

**Comment by Shujee** [comment]
Just in case it helps anyone, I finally solved this after banging my head for hours and wandering tirelessly across the wild stretches of Internet forums,

I'm using Laravel (5.8) on the server-side and Vue (CLI 3) for the front-end with axios for my server calls. Chrome constantly gave me CORS error even when I had CORS middleware on the server. I had to do 2 things.

1. My CORS implementation included `Access-Control-Allow-Origin` and `Access-Control-Allow-Methods`, but not `Access-Control-Allow-Headers`. Chrome was constantly screaming about this particular header and I was not reading the err msg carefully, so I included that. My CORS now looks like this:

` 
        if(env('APP_DEBUG'))
        {
            return $next($request)
                    ->header('Access-Control-Allow-Origin', '*')
                    ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS')
                    ->header('Access-Control-Allow-Headers', '*');
        }
        else {
            return $next($request);
        }
`

for safety, I have included APP_DEBUG check, so that cross-origin requests are not served in deployment.

2. I had to enable `OPTIONS` route, which is invoked by the clients before making actual GET or POST call. If you do not have OPTIONS route in your api, this will still fail even when CORS is correct. I added the following route to my `api.php`:

`
    if(env('APP_DEBUG')) {
        Route::options('/{any?}', function() {})->where('any', '.*');
    }
`
and with Almighty's grace I'm all good now. Hope this helps someone down the road.

**Comment by deghtani** [comment]
Solved it finally, been there and did following at my api server (i have built api in node express js and client in next js using axios) 

> npm i cors --save

and then in node server index.js 

```
const cors = require('cors')


app.use(cors())
```

**Comment by dinni69** [comment]
"proxy": "http://localhost:8000",

use this in package.json

**Comment by loginetsolutions** [comment]
> I found that when your (backend) method's response isn't interpretable by the front-end, you can receive a CORS-looking issue. For example, I was using `die('message');` in my Laravel method and I received a CORS complaint, despite my CORS being whitelisted. After changing my response to just be `return ['status' => 'success'];` which formats over into JSON to the FE - problem solved. Curious if this may be the issue for some of you too. :)

Absolutely stupid! I got this the second time and I forgot about die() and CORS! So, you saved my life twice! Thanks!

**Comment by vahe-nikoghosyan** [comment]
`axios.get("http://localhost:8000/api/###", {
	headers: {
	  'Access-Control-Allow-Origin': '*',
	}
	}).then(function (response) {
		console.log('response is : ' + response.data);
	}).catch(function (error) {
		  console.log(error.response);
	})
});`

**Comment by ttran835** [comment]
Hello all, I was stuck on this problem. However, I found a solution to this. Please take a look at these links. I hope it will help you.

**This is only applicable to nodejs server, however. **
https://expressjs.com/en/resources/middleware/cors.html
https://github.com/troygoode/node-cors-client/blob/master/pages/index.js

**Comment by hkmsadek** [comment]
This problem will not be solved until backend allows. So guys stop looking for solution in front end and focus only backend how to allow cors. That's the solution.

**Comment by ianquar** [comment]
**Install this package `cors` by running this commands**
```
npm i cors
```

after that add this 
```js
app.use(cors())
```

to your code after
```js 
const app = express()
```

It should look like this
```js
const express = require('express')
const cors = require('cors')
const app = express()
 
app.use(cors())
```

**I Hope this help**

**Comment by MariuzM** [comment]
For now the only solution that i found that works on front end is this, not ideal using a proxy for for now it works.
```js
  const getData = async () => {
    await axios
      .get(
        'https://cors-anywhere.herokuapp.com/' +
          '<YOURPAGE>',
      )
      .then(({ data }) => setData(data.data))
  }
```
