### ISSUE TITLE
Parameters in url work, but they don't in second parameter as an object.

### ISSUE THREAD

**Issue by sinan92** [mzabriskie/axios#571]
This works fine:

`axios.get('http://****.nl/****/gebruikerOpslaan.php?naam=test')`

But when I try it like this I don't receive anything at all:

```
 axios.get('http://****.nl/****/gebruikerOpslaan.php',
    {
        password: 'pass',
        naam: naam,
        score: score
    })
```

**Comment by nickuraltsev** [comment]
Please see my answer on StackOverflow: http://stackoverflow.com/a/40953463/6218152
