### ISSUE TITLE
cross-site error if the 'withCredentials' is set to true

### ISSUE THREAD

**Issue by zappee** [mzabriskie/axios#572]
Hi,

I get a cross-site error if the '_withCredentials_' property is set to true. If I keep commented this line then the code works fine:

**This is my code:**
```
axios({
            baseURL: 'http://time.jsontest.com/',
            url: '',
            timeout: 20000,
            //withCredentials: true, <- this makes CORS error!
            responseType: 'json',
            method: 'get'
        })
            .then(function(response) {
                console.log('okay');
                console.log(response);
            })
            .catch(function(response) {
                console.log('error');
                console.log(response);
            })
```

Details in case of withCredentials: true is used:

**Request Headers**
GET / HTTP/1.1
Host: time.jsontest.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/demo/
origin: http://localhost:8080
Connection: keep-alive

**Response Headers**
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=ISO-8859-1
Content-Encoding: gzip
X-Cloud-Trace-Context: 46f0d68a28c13555fe4d18c37ceff90f
Vary: Accept-Encoding
Date: Sat, 03 Dec 2016 19:20:25 GMT
Server: Google Frontend
Cache-Control: private
Content-Length: 109

**And the error message:**
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://time.jsontest.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*’).

I need to use withCredentials: true in my real code. Could you please explain me what is happening here?

**Comment by nickuraltsev** [comment]
From https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS :

> when responding to a credentialed request,  server must specify a domain, and cannot use wild carding. The above example would fail if the header was wildcarded as: Access-Control-Allow-Origin: *.

Hope this helps!

**Comment by zappee** [comment]
@nickuraltsev Thank you a lot!
