### ISSUE TITLE
API endpoints with file extensions

### ISSUE THREAD

**Issue by loklaan** [mzabriskie/axios#574]
Hello! Great project.

To jump right in, it is a hacky experience to create an axios client for a single-endpoint API that also uses a file extension. ie `https://coolapi.com/api.php`

All url requests make their way through `combineURLs.js`, to be appended with a `/` regardless of if there was a relative url attached to the client's request config.

The current hack (it feels like hack...) to get around this is to add a request interceptor to remove the ending slash. I'm currently doing this in a project.

Happy to PR this issue with a fix to combineURLs - but I want to run it past owners first for validity.

Cheers! ✨

**Comment by nickuraltsev** [comment]
I'd be happy to accept a PR for this. Thank you!

**Comment by loklaan** [comment]
Cool! #581
