### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by braco** [mzabriskie/axios#58]
Getting this error in node after updating.

Seems to be loading xhr and barfing on this:
```
var msie = /(msie|trident)/i.test(navigator.userAgent);
```

**Comment by mzabriskie** [comment]
What version did you update to/from? Also what does your require statement look like?

**Comment by mzabriskie** [comment]
@braco ping

**Comment by mzabriskie** [comment]
Closing due to lack of response. If you have any further trouble feel free to re-open.

**Comment by laander** [comment]
I'm having a related problem. When using axios in a library and bundling it together in my dist, I'm getting an error when resolving `vertx` in es6-promise:
```
/Users/las/timekit-io/js-sdk/dist/timekit.js:1629
	        lib$es6$promise$asap$$vertxNext(lib$es6$promise$asap$$flush);
	        ^
TypeError: undefined is not a function
```
I'm using webpack myself for bundling and for debugging, I've tried ignoring `vertx` in my build:
```
plugins: [
  new webpack.IgnorePlugin(/vertx/)
]
```
This removes the above error, but instead i get:
`[ReferenceError: navigator is not defined]`

Using Axios v 0.5.4

**Comment by laander** [comment]
On a second revision, I dont think the `vertx` "problem" is related to this one. It just simply happened to be the first error thrown and therefore only one shown.

**Comment by aaayushsingh** [comment]
did anyone happen to find a solution to this?
