### ISSUE TITLE
Can I cancel promise in response interceptor?

### ISSUE THREAD

**Issue by foxinmy** [mzabriskie/axios#583]
```js
  var source = axios.CancelToken.source();
    axios.interceptors.request.use(function (config) {
      config.cancelToken =  source.token;
      return config;
    }, function (error) {
      return Promise.reject(error);
    });
    axios.interceptors.response.use(function (response) {
        source.cancel('Operation canceled by the user.');
        return response;
    }, function (error) {
        return Promise.reject(error);
    });
```

This approach seems not working。

THX。（：

**Comment by mzabriskie** [comment]
@nickuraltsev wrote the implementation for cancelation. Maybe he can answer?

**Comment by nickuraltsev** [comment]
You cannot use the token in a response interceptor, but you can throw a `Cancel` instead:

```js
  axios.interceptors.response.use(function (response) {
    throw new axios.Cancel('Operation canceled by the user.');
  }, function (error) {
    return Promise.reject(error);
  });
```

Hope this helps!

**Comment by JounQin** [comment]
@nickuraltsev What I if want to handle the error but do not reject it further?

``` js
axios.interceptors.response.use(response => response, error => {
   const response = error.response;
   if(response.status === 404) {
       // how to cancel the Promise here?
       return false;
   }
    return Promise.reject(error);
  });
```

**Comment by latel** [comment]
> @nickuraltsev What I if want to handle the error but do not reject it further?
> 
> ```js
> axios.interceptors.response.use(response => response, error => {
>    const response = error.response;
>    if(response.status === 404) {
>        // how to cancel the Promise here?
>        return false;
>    }
>     return Promise.reject(error);
>   });
> ```

same question!

**Comment by wufeng87** [comment]
same question too! I want to handle the error status in interceptors, and do not to call the .catch() anymore. Thanks.

**Comment by shoutcool** [comment]
I have the same question. i'm doing the whole error handling in the interceptor. So i dont want to call .catch() anymore. How can this be achieved?

**Comment by gertjanwytynck** [comment]
Same question here. Doing error handling for 401/404/500 in `interceptor.response`. When triggered I'm redirecting to another page, on that moment I don't want to trigger the `.catch()` anymore. 

I'm using axios in VueJs. 

Anyone has a proper solution for this?

**Comment by kentkrantz** [comment]
```typescript
instance.interceptors.response.use((response) => {
  if (someCondition(response) {
    return new Promise(() => {});
  }
  return response;
});
```
Thanks to [rubennorte](https://github.com/axios/axios/issues/715#issuecomment-290993181)
