### ISSUE TITLE
Unable to send stringified object through Axios...

### ISSUE THREAD

**Issue by smstamm** [mzabriskie/axios#584]
...but it works with a jQuery AJAX call. It seems Axios is wrapping my stringified object with an extra set of double quotes. 

Here's my action:
```
export function customTemplateSave(updatedTemplate) {
	const url = `${ROOT_URL_CT}/TemplateSave`;
	return function(dispatch) {
		axios.post(url, {
			template: JSON.stringify(updatedTemplate),
			headers: { 
				authorization: localStorage.getItem("token"),
				"Content-Type": "application/vnd.api+json"
			}
		})
			.then(response => {
				dispatch({ type: CUSTOMIZED_TEMPLATES_SAVE, payload: response });
				hashHistory.push("templates");
			});
	};
}
```
Here are my headers:
![axios-call](https://cloud.githubusercontent.com/assets/12092523/21024809/1b6bf694-bd43-11e6-9543-449dea16f298.jpg)

When the object reaches the service, it's returned with the top level values all set to null. When viewing the object through Fiddler, it has an extra set of double quotes wrapped around the object when sent with Axios. When this extra set of quotes is removed, the object is successfully passed to the service.

For comparison, here's what my AJAX call looks like:
```
export function customTemplateSave(updatedTemplate) {
	$.ajax({
		method: "POST",
		dataType: "json",
		contentType: "application/json; charset=utf-8",
		data: JSON.stringify(updatedTemplate),
		url: "https://localhost/ApiAdvisor/api/CustomTemplate/TemplateSave"
	});
}
```
And the headers:
![ajax-call](https://cloud.githubusercontent.com/assets/12092523/21025026/1c40a2e4-bd44-11e6-9afc-4fab272939dc.jpg)

Obviously I'd prefer to send my object using Axios, so any help is appreciated.

**Comment by mzabriskie** [comment]
It looks like you are passing your config and data in the same argument. The API for `POST` is `axios.post(url[, data[, config]])`. Also data is sent as JSON by default, so you don't need to `JSON.stringify` the data before it's sent.

Try separating it out like this:

```js
export function customTemplateSave(updatedTemplate) {
	const url = `${ROOT_URL_CT}/TemplateSave`;
	return function(dispatch) {
		axios.post(url, updatedTemplate, {
				headers: { 
					authorization: localStorage.getItem("token"),
					"Content-Type": "application/vnd.api+json"
				}
			})
			.then(response => {
				dispatch({ type: CUSTOMIZED_TEMPLATES_SAVE, payload: response });
				hashHistory.push("templates");
			});
	};
}
```

**Comment by smstamm** [comment]
Thanks, but when I copy and paste in this code I get a 500 error. The service can't even be hit. Any further suggestions?

**Comment by smstamm** [comment]
I got this working by pulling the headers out into their own variable. 
```
export function customTemplateSave(updatedTemplate) {
	const url = `${ROOT_URL_CT}/TemplateSave`;
	return function(dispatch) {
		axios.post(url, updatedTemplate, axiosConfig)
			.then(response => {
				dispatch({ type: CUSTOMIZED_TEMPLATES_SAVE, payload: response });
				hashHistory.push("templates");
			});
	};
}
```

Thanks for your help
