### ISSUE TITLE
Is there a way to know if an api call is running 

### ISSUE THREAD

**Issue by ravic1995** [mzabriskie/axios#585]
I have submit buttons that use axios to make api calls. I want to freeze those buttons when the api call is running. I was wondering if there is any way to do that using axios.

**Comment by mzabriskie** [comment]
You would need to disable the button when it's clicked, then enable it again once the request has completed. A quick & dirty example:

```js
const button = document.getElementById('saveButton')
button.addEventListener('click', () => {
  button.disabled = true
  axios.post('/some/api/call', {foo: 'bar'})
    .then((response) => {
      button.disabled = false
    })
    .catch((error) => {
      button.disabled = false
    })
})
```

**Comment by KKSzymanowski** [comment]
@mzabriskie So there's no easy way of getting the number of pending requests like eg. `jQuery.active`?
Are you planning on adding that?

**Comment by kevinmtrowbridge** [comment]
I had this problem too, today, I solved it by writing some 'interceptors' like this:

```
api.active =  0;

// keep track of the 'active' API requests
axios.interceptors.request.use(function (config) {
  api.active += 1;
  console.log(`Api request, opening, now ${api.active} open requests`);
  return config;
}, function (error) {
  api.active -= 1;
  console.log(`Api request, error, ${api.active} open requests`);
  return Promise.reject(error);
});

axios.interceptors.response.use(function(response) {
  api.active -= 1;
  console.log(`Api response, closing, ${api.active} open requests`);
  return response;
}, function(error) {
  api.active -= 1;
  console.log(`Api response, error, closing, ${api.active} open requests`);
  return Promise.reject(error);
});
```

**Comment by KKSzymanowski** [comment]
Thanks @kevinmtrowbridge.

As I understand interceptors are constructed as follows:
```js
axios.interceptors.request.use(success, error);
axios.interceptors.response.use(success, error);
```
What is the difference between the error callback in request interceptor and response interceptor?
I guess the response error callback acts the same as when passed directly to the Promise handler:
```js
axios.get('/url').then(success, error);
```
but what does the request error callback do?
Does it have something to do with eg. `ERR_NETWORK_CHANGED` or CORS errors handled by the browser?
Or is it called when the request is constructed in somewhat wrong way and axios detects it?
