### ISSUE TITLE
axios can't be used on IE browser

### ISSUE THREAD

**Issue by sjxhgjxf** [mzabriskie/axios#586]
I try to use axios on IE browser,but the browser throw the error:
Promise is not defined,
help!!!!

**Comment by decademoon** [comment]
Please read the README
https://github.com/mzabriskie/axios#promises

**Comment by mzabriskie** [comment]
@sjxhgjxf as @decademoon suggested, you will need to polyfill `Promise` in IE.

**Comment by sjxhgjxf** [comment]
thanks!
