### ISSUE TITLE
Request is returned as undefined on server 4XX JSON responses

### ISSUE THREAD

**Issue by borov333** [mzabriskie/axios#589]
Hi, I'm running on axios 0.15.3. When I submit an api call to the backend (JSON format) for a simple post method, if server responds back with 200 it all works fine. However, if the server responds with let say 400 code (for missing data elements), the axios's "request" object is always received as "undefined". If I get request as undefined I can't read and display proper messages back to user.

Here is my code snippet (I specifically didn't pass data in to trigger error):
```
      axios
        .post('/lead/campaigns', {})
        .then((response) => {
          console.log('In then')
          console.log(response)
        })
        .catch((error) => {
          console.log('In catch')
          console.log(error)
        })
```

Server responds with JSON:
```
{
  "code": 400,
  "message": "Invalid data submitted",
  "errors": [
    {
      "key": "category",
      "val": "Category is required"
    },
    {
      "key": "rule",
      "val": "Rule is required"
    }
  ]
}
```

In the console I get this:
```
POST http://localhost:8080/user/lead/campaigns 400 (Bad Request)
In then
undefined <<-- this is the result of "console.log(response)"
```

Am I doing something wrong here? If so, please help with an example. Thanks.

p.s. I'm using Vue.js 2.1.3

**Comment by mzabriskie** [comment]
Are you using a custom `validateStatus` in your config? I wouldn't expect you to reach the `then` if you are getting a `400` HTTP status in your response. Also will you check in your browser console to verify the HTTP status code that is returned?

**Comment by johngibbons** [comment]
Also having this problem and verified that we are getting `false` returned from `validateStatus` using the following:

```
axios.defaults.validateStatus = function (status) {
  console.log(status);
  console.log(status >= 200 && status < 300);
  return status >= 200 && status < 300;
}
```

**Comment by borov333** [comment]
Thanks guys for helping out. It turned out to be that my return statement was wrapped in the 401 status code check and therefore never returned. More details can be traced in the [original post](https://forum.vuejs.org/t/vue-and-axios-request-undefined/4019/1)

Here is the fix I applied and it started to work:

```
api.interceptors.response.use(
  function (response) {
    // continue sending response to the then() method
    return Promise.resolve(response)
  },
  function (error) {
    // check if unauthorized error returned
    if (error.response.status === 401) {
      router.replace({ name: 'Signin' })
    }
    // request is rejected and will direct logic to the catch() method
    return Promise.reject(error)
  })
```

**Comment by kylecho** [comment]
Thanks @borov333, for me, not returning `Promise.resolve(response)` was what was causing the problem.

**Comment by johngibbons** [comment]
yup was getting `undefined` due to not returning `Promise.reject(error)`.  That solved it thanks

**Comment by JounQin** [comment]
But how can I ignore these error or just alert an error message then not reject promise? There are obviously no need to catch 404 error in every request.

**Comment by JounQin** [comment]
For now I'm using [unhandled-promise-rejections](https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections) to handler the global `Promise.reject`.
