### ISSUE TITLE
question: having problem posting object

### ISSUE THREAD

**Issue by tony-kerz** [mzabriskie/axios#59]
i have (coffeescript) code like this running in a browser: 
```
    axios.post @props.url, {foo: 'bar'}
    .then (res) =>
      dbg 'handle-comment-submit: res=%o', res
      @setState data: res.data
    .catch (err) ->
      console.error 'handle-comment-submit: err=%o', err
```
and server side code like this running in a gulp task:
```
gulp.task 'server', ->
  gulp.src buildApp
  .pipe plug.webserver(
    livereload: false
    directoryListing: false
    open: true
    middleware: [
      bodyParser.urlencoded extended: false

      (req, res, next) ->
        dbg 'middleware: url=%s, method=%s', req.url, req.method
        if (req.url == '/comments.json') and (req.method == 'POST')
          fileName = "#{buildApp}/comments.json"
          fs.readFile fileName, (err, data) ->
            if err
              console.log 'read-file: err=%o', err
            comments = JSON.parse data
            dbg 'middleware: comments=%o, body=%o', comments, req.body # <--------
            comments.push req.body
            fs.writeFile fileName, JSON.stringify(comments, null, 4), (err) ->
              if err
                console.log 'write-file: err=%o', err
              res.setHeader 'Content-Type', 'application/json'
              res.setHeader 'Cache-Control', 'no-cache'
              res.end JSON.stringify(comments)
        else
          next()
    ]
```
the log message with the `<-------` shows that body is empty like `{}`

but when using the following jquery code in the browser, the body is as expected:
```
$.ajax
      url: @props.url
      dataType: 'json'
      type: 'POST'
      data: comment
      success: (data) =>
        dbg 'handle-comment-submit: data=%o', data
        @setState data: data
      error: (xhr, status, err) =>
        console.error @props.url, status, err.toString()
```

i'm sure i'm being a dunce, but any guidance as to what i might do to get the desired effect with axios?

regards,
tony

**Comment by mzabriskie** [comment]
What version are you using?

**Comment by tony-kerz** [comment]
`      "axios": "~0.5.4"`

a little more info:

axios:
![screen shot 2015-04-12 at 9 32 35 am](https://cloud.githubusercontent.com/assets/1223231/7106697/1d87ab52-e118-11e4-930d-903fea0d4c6d.png)

jquery:
![screen shot 2015-04-12 at 9 33 31 am](https://cloud.githubusercontent.com/assets/1223231/7106698/24f8aeea-e118-11e4-84c7-968b44fff175.png)

**Comment by mzabriskie** [comment]
So it looks like the payload is being sent, but the `Accept`, and `Content-Type` headers are different. Is your server ignoring the body since it's expecting a different header value?

**Comment by mzabriskie** [comment]
@tony-kerz ping

**Comment by tony-kerz** [comment]
hey @mzabriskie, sorry to leave you hangin, got distracted, but put in a few cycles just now, and we can safely chalk this up to operator-error. the following setup worked for the [gulp based server](https://github.com/schickling/gulp-webserver) and [body-parser middleware](https://github.com/expressjs/body-parser):

```
gulp.task 'server', ->
  gulp.src buildApp
  .pipe plug.webserver(
    livereload: false
    directoryListing: false
    open: true
    middleware: [
      bodyParser.json()

      (req, res, next) ->
        if (req.url == '/comments.json') and (req.method == 'POST')
          fileName = "#{buildApp}/comments.json"
          fs.readFile fileName, (err, data) ->
            if err
              console.log 'read-file: err=%o', err
            comments = JSON.parse data
            comments.push req.body
            fs.writeFile fileName, JSON.stringify(comments, null, 4), (err) ->
              if err
                console.log 'write-file: err=%o', err
              res.end JSON.stringify(comments)
        else
          next()
    ]
  )
```

i originally tried `bodyParser.json` instead of `bodyParser.json()` which was the issue.

so `axios` was working great, i just wasn't using the `express` components correctly,
sorry bout that, but thanks for the help!

regards,
tony.

**Comment by mzabriskie** [comment]
Glad you got it figured out 👍
