### ISSUE TITLE
How can I set axios to prefer IPv6?

### ISSUE THREAD

**Issue by elgs** [mzabriskie/axios#590]
I set the base url as follows:

```javascript
axios.defaults.baseURL = 'https://my_url/api';
```

My server is capturing the client IP addresses. All is good with the exception that with Nodejs working with axios on the client side sending http request, my server captured the IPv4 address of the client. I am wondering if there is a way to force axios to prefer IPv6? Thanks.

**Comment by rubennorte** [comment]
Axios does not pass the `family` option to `http.request` so it uses the default Node.js value, which is the use of both IPv4 and IPv6. So at the moment it cannot be configured nor forced.

Why do you want to force it? What is your use case?

**Comment by VisualCH** [comment]
Is it now possible?

**Comment by mcmar** [comment]
OSX appears to have a problem with node. People are reporting that setting `family: 4` *might* fix the issue. Neither node-fetch nor axios supports that option. Node team has said this is not their problem and it's a "wont fix". I don't have any opinion on whose problem it is or who's to blame. It would be nice if axios cared enough to support this feature given the problems it poses for Mac users
https://github.com/nodejs/node/issues/5436
