### ISSUE TITLE
Support for axios.default.then?

### ISSUE THREAD

**Issue by ashwinimnnit** [mzabriskie/axios#591]
Hi Is there a way to execute a default function after every axios (get, post)???

**Comment by mzabriskie** [comment]
The best option for this would be to use an [interceptor](https://github.com/mzabriskie/axios#interceptors). This would allow you to execute logic anytime a request is sent, or anytime a response is received. You could also check `config` in the request to test `config.method` and only execute your logic for get/post.

**Comment by ashwinimnnit** [comment]
ThnQ it worked :)
