### ISSUE TITLE
Support for axios before  get/ post is made?

### ISSUE THREAD

**Issue by ashwinimnnit** [mzabriskie/axios#592]
Is there any feature in axios which can execute a logic before a get or post is made to the server???

**Comment by Klaasvaak** [comment]
You can use an interceptor. See: https://github.com/mzabriskie/axios#interceptors

**Comment by ashwinimnnit** [comment]
interceptor executes after a request is made or after a response is received... Is there ant thing in axios which can trigger a logic before a get/post is made !!

**Comment by Klaasvaak** [comment]
A request interceptor executes before a request is made.

**Comment by rubennorte** [comment]
Please, use StackOverflow or a similar service to ask for help. Github issues should be used for bugs or feature requests in this project.
