### ISSUE TITLE
IE8 is determined wrong as non standard browser environment.

### ISSUE THREAD

**Issue by eu81273** [mzabriskie/axios#597]
In IE8, the value of `typeof document.createElemen` is `object`, not `function` so this `isStandardBrowserEnv` returns `false`.

```
function isStandardBrowserEnv() {
  return (
    typeof window !== 'undefined' &&
    typeof document !== 'undefined' &&
    typeof document.createElement !== 'function'
  );
}
```

Because of this wrong determine, XDomainRequest is not working in IE8. I made a pull request for fix this, but failed to pass the CI.

**Comment by nickuraltsev** [comment]
Fixed by #731. Thank you!
