### ISSUE TITLE
Support for gloabal default headers in axios !!

### ISSUE THREAD

**Issue by ashwinimnnit** [mzabriskie/axios#598]
Hi I'm setting default axios headers in request interceptor but these headers are not accessible in another function... in axios documentation it is mentioned that [global-axios-defaults](https://github.com/mzabriskie/axios#global-axios-defaults) are global...below is my sample code need help

` axios.interceptors.request.use(function (config) {`
       ` axios.defaults.headers.accesstoken= "some_access_token"`
      `  axios.defaults.headers.client = "some_client"`
       ` axios.defaults.headers.uid = "some_uid"`
   ` return config;`
  `  },function (error) {`
    `return Promise.reject(error);`
  ` });`

On page load componentDidmount executes but axios default headers are undefined in this function

` componentDidMount: function() {`
  `console.log(axios.defaults.headers) #its giving me undefined`
    `axios.get("http://some_url_for_get_request.json", {`
     ` headers: {`
        `accesstoken: axios.defaults.headers.accesstoken,`
       ` uid: axios.defaults.headers.uid,`
        `client: axios.defaults.headers.client`
     ` }`
    `})`
  ` }`

**Comment by rubennorte** [comment]
Default headers shouldn't be set in interceptors. You'd usually set them after loading axios (using `require` or whichever method).

If you set them outside the interceptor you should be able to access them from your component.
