### ISSUE TITLE
axios keeps throwing errors on console

### ISSUE THREAD

**Issue by mtrabelsi** [mzabriskie/axios#599]
catching the errors can't stop axios from throwing them in console. (normally this should be up to the userland.. ) :

```
	axios.get('https://api.github.com/users/'+e.target.value)
			 .then((res) => {
			 	this.setState({
					bio : res.data.bio,
					name : res.data.name,
					location : res.data.location,
					avatar : res.data.avatar_url
				})
			 }).catch((err) => {
			 	this.setState({
			 		bio : 'no user found',
					name : 'no user found',
					location : 'no user found',
					avatar : 'https://pbs.twimg.com/profile_images/616309728688238592/pBeeJQDQ.png'
			 	})
			 })

```

![error](https://cloud.githubusercontent.com/assets/7538862/21236053/c25c2ae4-c2f9-11e6-922c-6609513d7cbd.gif)

**Comment by Klaasvaak** [comment]
Can you proider the error you are getting in the console? 

Also are you sure it's not the default browser error logging?

**Comment by mtrabelsi** [comment]
@Klaasvaak : the error is already provided in the attached gif 

> Also are you sure it's not the default browser error logging?

Nice catch! I'll check this now..

**Comment by mtrabelsi** [comment]
Yes, it's from the [xhr.js](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L175).

 I actually tried to make a PR, but we need to check it first, if it's a known issue?

That being said, it's ugly having ton of errors in the console this is a bad experience to the user.

**Comment by Klaasvaak** [comment]
I still think it's a browser logging. See for example:
http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest%2Creact%2Cstage-2&experimental=false&loose=false&spec=false&code=fetch('test')%0A%20%20.catch(()%20%3D%3E%20null)%3B&playground=true

When you open the console on this page you also see an error.

**Comment by mtrabelsi** [comment]
Arf.. Also it's seems that it's not [even possible to solve](http://stackoverflow.com/questions/16372271/jquery-ajax-how-to-prevent-404-errors-spam-in-chrome-devtools)  with only Javascript..  Thanks for your sample! @Klaasvaak
