### ISSUE TITLE
Question: Getting the headers for tests

### ISSUE THREAD

**Issue by srph** [mzabriskie/axios#60]
I feel like this is out of topic, though. Anyway --

I'm implementing JWT with Axios, and would like to send the `Authorization` **Header** through the interceptor. Question, how do I test with Sinon that I am able to send the said header? Which do I spy? Thanks.

**Edit**: I just checked the API, and the headers doesn't seem to be covered in the interceptors. In the [**Interceptors** example](https://github.com/mzabriskie/axios#interceptors), is `config` equal to the whole [`request` API](https://github.com/mzabriskie/axios#request-api) or just the `config` in it?

**Comment by mzabriskie** [comment]
This is an example using sinon and jasmine:

```js
describe('jwt', function () {
  beforeEach(function () {
    this.xhr = sinon.useFakeXMLHttpRequest();
    var requests = this.requests = [];
    this.xhr.onCreate = function (xhr) {
      requests.push(xhr);
    }
  });

  afterEach(function () {
    this.xhr.restore();
  });

  it('should have Authorization header', function (done) {
    axios.interceptors.request.use(function (config) {
      config.headers['Authorization'] = 'token';
      return config;
    });

    axios.get('/foo');

    var requests = this.requests;

    setTimeout(function () {
      expect(requests.length).toEqual(1);
      expect(requests[0].requestHeaders['Authorization']).toEqual('token');
      done();
    }, 0);
  });
});
```

**Comment by mzabriskie** [comment]
Just noticed your edit. Yes, `config` is the equivalent of the request API. It is exactly what you passed into the second argument: `axios.get('/some/url', { ... });`, but with some additions such as defaults, etc.

**Comment by srph** [comment]
I see, thanks! Great work, sir :+1:

**Comment by srph** [comment]
Ah, last question -- should I stub out axios? Thanks

**Comment by srph** [comment]
Ah, nevermind! I just realized that you were using `setTimeout` in your examples. Thanks, again.

**Comment by mzabriskie** [comment]
I should probably also mention, that you don't have to use an interceptor for modifying headers. You can use a transformer as well.

```js
axios.get('/some/url', {
  transformRequest: axios.defaults.transformRequest.concat(function (data, headers) {
    headers['Authorization'] = token;
  })
});
```

Or if you want to use the transformer on every request, not just a single request:

```js
axios.defaults.transformRequest.push(function (data, headers) {
  headers['Authorization'] = token;
});
```

**Comment by srph** [comment]
I see, thanks a bunch!

**Comment by BrunoQuaresma** [comment]
I'm trying to use this example but the console shows this error => Error: connect ECONNREFUSED 127.0.0.1:80

**Comment by srph** [comment]
Mind showing the code?
