### ISSUE TITLE
Adding content-type to request interceptor doesn't work

### ISSUE THREAD

**Issue by maxKimoby** [mzabriskie/axios#600]
Using an interceptor to set request header's content-type is not working. It doesn't show in request headers.

    import axios from 'axios'
    axios.interceptors.request.use(function (request) {
	request.headers.common['Content-Type'] = 'application/json; charset=utf-8';
       return request;
    }, function (error) {
      return Promise.reject(error);
    });

And in chrome console : 
![axios issue](https://cloud.githubusercontent.com/assets/12074525/21235439/c429b222-c2c4-11e6-854f-f3ec25bf9261.png)

**Comment by Klaasvaak** [comment]
Does `request.headers['Content-Type'] = 'application/json; charset=utf-8';` work?

**Comment by maxKimoby** [comment]
Setting `request.headers['Content-Type'] = 'application/json; charset=utf-8';` does not work either. 

When using `request.headers.common['Content-Type'] = 'application/json; charset=utf-8';`, the Content-Type is correctly set on the returned request value but it does not apply to the rest of the flow.

This issue seems to be happening only on GET requests. The `request.headers` object contains the following keys : common, put, patch and post. Where are the headers for the GET requests?

**Comment by maxKimoby** [comment]
Bump. Any ideas on this?

**Comment by camerow** [comment]
I am not able to set `{ headers: { 'Content-Type': 'application/json' } }` right now on a request either.

**Comment by rubennorte** [comment]
@maxKimoby how do you perform the requests? Does it work if you set any other header?

**Comment by maxKimoby** [comment]
This is a basic example of a GET request I am performing :

    axios.get('/appointments', {
					params: {
						date: this.$route.params.date
					}
				})
				.then( (response) => {
					this.$store.commit('add_appointments', response.data);
				})
				.catch( (error) => {
				});


I tried setting :

`request['headers']['common']['Content-Type'] = 'text/html; charset=utf-8';`

and it doesn't show in the request headers as well.

**Comment by rubennorte** [comment]
I guess that's normal. GET requests do not have a body so "Content-Type" makes no sense in that context. Do you mean "Accept" instead, to set the desired content type of the response?

**Comment by maxKimoby** [comment]
You were right. The problem here was that, as first pointed out by @rubennorte, you can't set a content-type on a get request. 

Even though, by default, the 'Accept' is set to 'application/json, text/plain, */*', my rails backend would choose the text/plain over anything. 

I had to overwrite the 'Accept' header with the following value so my backend would only accept json :

`request['headers']['common']['Accept'] = 'application/json; charset=utf-8';`

Thank you!
