### ISSUE TITLE
cancelable promises proposal withdrawn

### ISSUE THREAD

**Issue by kentcdodds** [mzabriskie/axios#601]
Just FYI. Not sure whether that changes anything for this lib. But it will no longer become standard.

https://github.com/tc39/proposal-cancelable-promises/issues/70

**Comment by 28inch** [comment]
does anybody know why google are against this?

**Comment by mzabriskie** [comment]
Thanks for the update @kentcdodds. It's unfortunate that this proposal was dropped. I don't think that it changes anything for axios immediately. I think that having cancelable requests, even non-standard, is better than not having it. Once something permanent replaces this proposal we can revisit our implementation.

**Comment by mzabriskie** [comment]
@28inch I am not certain why Google blocked this proposal..
