### ISSUE TITLE
Can i use it in React Native ?

### ISSUE THREAD

**Issue by itxuye** [mzabriskie/axios#602]
Can i use it in React Native ?

**Comment by simonsmith** [comment]
Yes. I currently am.

**Comment by itxuye** [comment]
@simonsmith That's cool . Thanks .

**Comment by raphox** [comment]
Updated url to doc: https://facebook.github.io/react-native/docs/network.html#using-other-networking-libraries

**Comment by dheerajmpai** [comment]
Yes, it looks lke `axios` works on React native too

**Comment by harshit741** [comment]
Why is there a separate package 'react-native-axios' if this works well with native too?

**Comment by elitan** [comment]
> react-native-axios

Anyone can create and name a npm package. A package's name does not indicate if it's a relevant package or not.
