### ISSUE TITLE
Combine chaining sync for async functions

### ISSUE THREAD

**Issue by jicjjang** [mzabriskie/axios#603]
Why do not support this config?
 - XMLHttpRequest: (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#Synchronous_request)
 - axios: (https://github.com/mzabriskie/axios/blob/master/dist/axios.js#L696)

Sometime, people are want this function. (like unlimited scrolling pages..? ex) FB, Insta...)

**Comment by jicjjang** [comment]
Just using async/await...?

**Comment by rubennorte** [comment]
This feature makes no sense in the context of Axios because the whole library is built around Promises (which are inherently asynchronous).

**Comment by asiandrummer** [comment]
@jicjjang If the Promise order preservation was the issue, I would imagine `axios.all` does the work since it uses [Promise.all](https://github.com/mzabriskie/axios/blob/master/dist/axios.js#L108) to resolve the promises.
