### ISSUE TITLE
https request localhost api contradiction for React server rendering 

### ISSUE THREAD

**Issue by EasonWang01** [mzabriskie/axios#605]
That's say I have an express api server along with web server rendering,

axios for react server side render need to specify the domain like `localhost:3001/getUser` 

If the website is https but request api to the same server  from `localhost`,it's `http`.

It will cause Error for untrust request from https to http.

so I change the `axios.post(localhost:3001/getUser)`  to `axios.post(/getUser)`,it solved untrust origin.

But another Error appear is that react server side render need axios to specify domain.

**Comment by rubennorte** [comment]
That isn't an issue in axios. If you want to use the same code in client and server you must use the full URL, including the protocol to solve your issue.
