### ISSUE TITLE
Response headers missing

### ISSUE THREAD

**Issue by OmgImAlexis** [mzabriskie/axios#606]
I'm trying to check if X-Medusa-Server is set but I'm only getting a single header back.

```
axios.post('/auth/login')).then(function (response) {
    console.log(response.headers);
});
```

The above code returns `{"content-type": "application/json; charset=UTF-8"}` where as I expect the other headers that I can see in the network tab as listed below.

```
HTTP/1.1 200 OK
Content-Length: 46
Access-Control-Allow-Methods: POST, OPTIONS
X-Medusa-Server: v0.1.8.1
Vary: Accept-Encoding
Server: TornadoServer/4.3
Date: Mon, 19 Dec 2016 07:22:14 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token, X-Api-Key
Content-Type: application/json; charset=UTF-8
```

**Comment by ckken** [comment]
same problem

**Comment by mzabriskie** [comment]
What version of axios are you using? I just tried this with RunKit and received all the headers.

https://runkit.com/585998a881a05a001491eb0b/585998a881a05a001491eb0c

```js
let axios = require("axios")
axios.get('https://api.github.com/users/mzabriskie').then(function (response) {
    console.log(response.headers)
})
```

**Comment by OmgImAlexis** [comment]
I'm on `^0.15.21.

**Comment by ckken** [comment]
Fixed  it  add expose

**Comment by OmgImAlexis** [comment]
Okay this is weird. Testing in the node cli I get different results than I do inside of Vue 2.

```
import 'axios' from 'axios';
let baseUrl = 'http://localhost:8081/api/v2';
let idToken = '';
let username = 'xo';
let password = 'fakePassword';
const api = axios.create({
    baseURL: baseUrl,
    timeout: 10000,
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-Api-Key': idToken
    }
});
api.post(baseUrl + '/auth/login', {
    username: username,
    password: password
}).then(function(response) {
    console.log(response.headers); // { content-type: "application/json; charset=UTF-8" }
});
```

Where as using node via cli I get this.
```
> let axios = require('axios');
> let baseUrl = 'http://localhost:8081/api/v2';
> let idToken = '';
> let username = 'xo';
> let password = 'fakePassword';
> const api = axios.create({
    baseURL: baseUrl,
    timeout: 10000,
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-Api-Key': idToken
    }
});
> api.post('auth/login', {username: username, password: password}).then(function (response) {console.log(response.headers)}).catch(function(error){console.log(error)});
Promise { <pending> }
> { 'content-length': '46',
  'access-control-allow-methods': 'POST, OPTIONS',
  'x-medusa-server': 'v0.1.8.1',
  vary: 'Accept-Encoding',
  server: 'TornadoServer/4.3',
  date: 'Wed, 21 Dec 2016 02:09:19 GMT',
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token, X-Api-Key',
  'content-type': 'application/json; charset=UTF-8' }
```

**Comment by dmitriid** [comment]
I tried returning various headers, none were picked up

**Comment by dmitriid** [comment]
All right. This might be the problem: http://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields

Found here: https://github.com/mzabriskie/axios/issues/467#issuecomment-252076410

**Comment by rubennorte** [comment]
@dmitriid I think you're right. We get many issues due to the way CORS works. I'm thinking about creating an issue template and warn users there about these kind of problems.

**Comment by OmgImAlexis** [comment]
Yeah, that seems to fix the issue. @rubennorte maybe if the header is missing allow the user to have an error thrown and provide a link back to the wiki explaining the issue. Angular does something similar to that with their errors.

**Comment by rubennorte** [comment]
That would be a good think but we can't distinguish regular network errors from CORS errors programmatically. The W3C spec says that specifically.

The user can see the error in the console but axios can't.

**Comment by dmitriid** [comment]
@rubennorte In README add a small description and a link to https://github.com/mzabriskie/axios/issues/467#issuecomment-252076410 . Something like this:

```
// `headers` the headers that the server responded with
// Note: This may be empty due to CORS, see https://github.com/mzabriskie/axios/issues/467#issuecomment-252076410
  headers: {},
```

Then you kill multiple birds with one stone: you educate people about CORS, prevent further questions about CORS in issues, become more awesome overall :)

**Comment by adammaddox** [comment]
Hit this issue uploading objects to S3 and expecting the etag in response headers.

Resolved by updating the S3 Bucket CORS config to include:

```
    <ExposeHeader>ETag</ExposeHeader>
```

**Comment by Jefwillems** [comment]
I'm running in the same issue, but when i make the same request with postman, i get access to all headers, when i do it trough code, i don't. i don't see how that would be cors related?

**Comment by huby01** [comment]
I m still experiencing this issue. Any fix?

**Comment by yuanchieh-cheng** [comment]
I'm facing this issue.  
Then I change to use node-fetch and I get the all headers supposed to see.

**Comment by gvorster** [comment]
Yep, I'm missing all headers too using Axios in Vue. I see all headers in Chrome devtools.

**Comment by jprimaki** [comment]
We have the same problem here, we can see all headers in "Insomnia", but just "content-type: "application/json; charset=utf-8"" in Axios/Vue, any tips ?

**Comment by stlegion** [comment]
Same problem when making request on same base url, with different port. Browser shows that all expected headers present in server answer, but they all absent in axios answer object. Axios version 0.19.0

**Comment by MichaelJCole** [comment]
Why was this issue closed?

**Comment by gauseen** [comment]
Look [This](https://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields)

**Comment by jinn-k** [comment]
Use Access-Control-Expose-Headers.

For example in NodeJS.
cors({
        origin: [
            "http://localhost", "http://localhost:8080", "http://localhost:8081", 
            "*"
        ],
        credentials: true,
        exposedHeaders: ['Access-Control-Allow-Origin', 'Vary', 'Content-Length']
    })

But, Set-Cookie header might not work.

Reference
- https://www.npmjs.com/package/cors#configuration-options
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Expose-Headers
- https://fetch.spec.whatwg.org/#cors-protocol-and-credentials

**Comment by vjkholiya123** [comment]
Hey I am making an PUT api call to IBM cloud storage where I am storing an object and in response header I am getting ETag value but that I am only able to view through developer mode and not able to fetch that in client part i.e React JS. Any solution how can I do this?

**Comment by determin1st** [comment]
There will be more CORS restrictions. Currently, WATWG spec writers "securing" a lot, so If you really feel that it is wrong and unconfortable - drop a short complain to this repo: https://github.com/whatwg/fetch/issues

They should know the user's opinion.

**Comment by abdelgrib** [comment]
It's not Axios issue, the browser don't allow this header because it dosn't receive a green light (header) from the server  indicating that it can be exposed to the client !

So for those who are using ASP.NET Core you can expose this header as so in Startup.cs :

    void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        ...
        app.UseCors(x => x.AllowAnyOrigin()
        .AllowAnyMethod()
        .AllowAnyHeader()
        .WithExposedHeaders("WWW-Authenticate"));

Or

    void ConfigureServices(IServiceCollection services)
        ...
        services.AddCors(options =>
        {
            var corsPolicy = new CorsPolicy();
            corsPolicy.Origins.Add("*");
            corsPolicy.Methods.Add("*");
            corsPolicy.Headers.Add("*");
            corsPolicy.ExposedHeaders.Add("WWW-Authenticate");
            options.AddPolicy("CorsPolicy", corsPolicy);
        });
    
    void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        ...
        app.UseCors("CorsPolicy")
