### ISSUE TITLE
createError has issue

### ISSUE THREAD

**Issue by tarim** [mzabriskie/axios#610]
Hi There,

I am using axios on my application, and I have an issue. After unauthorized access I got error
![image](https://cloud.githubusercontent.com/assets/453087/21430654/0c0eea7c-c832-11e6-9060-0ca4eede1e87.png)

Here is my code
 ````
axios.interceptors.response.use(undefined, err => {
  if (err.response.status === 401) {
    toastr.error('Message', 'Sorry! Your session timeout.', { timeOut: 5000 })
    localStorage.removeItem('token')
    browserHistory.push('/signin')
  }
  return Promise.reject(err)
})
````

Thanks,

**Comment by rubennorte** [comment]
The error you're seeing is a regular HTTP response (401).

What is the behaviour that you expect? Is the code in your interceptor running correctly?

**Comment by xveganxxxedgex** [comment]
I'm running into the same issue. 

```
axios.interceptors.response.use(resp => {
  console.log("response is fine", resp);
  return stopRecording(resp);
}, error => {
  console.log(error);
  return stopRecording(error, true);
});
```

The first `resp` is always triggered, even though the endpoint is returning a 400. I see the error string as the `resp`, this is what prints in the console:

```
response is fine Error: Request failed with status code 400
    at createError (createError.js:15)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:77)
```

So if there's an error or the endpoint is failing, I'd expect it to go to the second callback method handling the `error` with an error object where I can call error.status or something. It seems the only way I'd be able to get the error handling to trigger is if I searched `resp` to see if it contained `Error: Request failed`? Is this a misunderstanding on my end?

Thanks!

**Comment by rubennorte** [comment]
>  I would expect the behaviour to return the actual response object (so what it currently does for success) on both success and error? Is this a misunderstanding on my end?

That's the intended behaviour so we can define a proper API for errors and we don't always have a response in case of error. Also, rejecting with a non-error is usually considered a bad practice.

**Comment by johhansantana** [comment]
Hello @rubennorte I'm trying to pass a custom error message via my node api using express:

`response.status(500).send('Incorrect password');`

In my front-end code I got this:

```javascript
import axios from "axios";

export const login = (email: string, password: string) => {
  console.log();
  return axios.post(`${API_URL}/login`, { email, password });
};
```

and I use it as:

```javascript
login(e) {
  e.preventDefault();
  const { email, password } = this.state;
  login(email, password)
    .then(res => {
      console.log("success: ", res);
    })
    .catch(err => {
      console.log("ERROR: ", err);
    });
}
```

I'm not sure if I'm doing it right but I expect to receive the custom message I send back but in the console all I get is:
```
ERROR:  Error: Request failed with status code 500
    at createError (eval at evalScript (eval-script.js?3e48208:22), <anonymous>:1998:15)
    at settle (eval at evalScript (eval-script.js?3e48208:22), <anonymous>:731:12)
    at XMLHttpRequest.handleLoad (eval at evalScript (eval-script.js?3e48208:22), <anonymous>:1834:7)
```

When I use `postman` to make the same http request I get the custom message normally.

My question is how do I access the custom message I send back?

Thanks!
