### ISSUE TITLE
POST error when put any options

### ISSUE THREAD

**Issue by fega** [mzabriskie/axios#612]
Hello when I perform a request with any kind of options, Axios changes the POST request to OPTIONS

what can be happened?

**Comment by garmjs** [comment]
Can you provide more info, if possible paste code.

**Comment by rubennorte** [comment]
My guess is that you're making a CORS request and the OPTIONS request is being made by the browser (is a preflight request) before sending the request created through axios.

Is it's not that or you have more information feel free to reopen the issue.
