### ISSUE TITLE
interceptor return local json and cancel request if flag isOffline = true

### ISSUE THREAD

**Issue by filtudo** [mzabriskie/axios#614]
Hi,

I`m trying to implement a interceptor, based on an "isOffline" flag, if is false it does the request to the actual url / if the flag is true, it doesn't do the request instead it returns the data from a local json.

What i can`t figure out is how do you cancel the request inside the interceptor and return the data from local json.

Thank you
Cheers

**Comment by rubennorte** [comment]
You could try with two interceptors. A request interceptor (on resolved) that returns a rejected promise (with a custom "offline error") and a response interceptor (on rejected) that returns a resolved promise with the offline data (when the error is an "offline error").
