### ISSUE TITLE
adding interceptors on instance ignore global interceptors

### ISSUE THREAD

**Issue by alonronin** [mzabriskie/axios#617]
```javascript
import http from 'axios';

http.interceptors.response.use(function (response) {
  // Do something with response data
  return response;
}, function (error) {
  console.log('*** This is not called ***');
  return Promise.reject(error);
});

const instance = http.create();
instance.interceptors.response.use(function (response) {
  return response;
}, function (error) {
  console.log('$$$ This is  called $$$');
  return Promise.reject(error);
});

instance.get('/');
```

**Comment by rubennorte** [comment]
Global interceptors are not inherited by custom axios instances (and global defaults are only applied at instance creation time).

I think in this case is a documentation issue.

**Comment by alonronin** [comment]
@rubennorte ah, you treat them as defaults. got it, Thanx.

**Comment by kemaltatar** [comment]
```
import axios from 'axios';

axios.interceptors.response.use(function (response) {
  // Do something with response data
  return response;
}, function (error) {
  console.log('*** This is not called ***');
  return Promise.reject(error);
});

const instance = axios.create({
	baseURL: someBaseUrl
})
const otherInstance = axios.create({
	baseURL: someOtherBaseUrl	
})


instance.get('/');
```

Is there a way to use an inherited default interceptor like this ? 
Because i have many instances but i want them to be handled by only one interceptor

**Comment by jeffthompson1971** [comment]
I'm seeing quite the opposite.  When i add interceptors onto a created axios instance, I see those interceptors being used in EVERY other axios reference or instance across my app which sucks.  Seems no way to use axios.create() and then add interceptors to just that instance without affecting axios all over the app
