### ISSUE TITLE
Getting error as String instead of an Object inside catch

### ISSUE THREAD

**Issue by matheusml** [mzabriskie/axios#619]
I have a post to import files:

```javascript
export function importFile(file) {
  const data = new FormData();
  data.append('file', file);
  return post(`${API_URL}import-scores`, data);
}
```

And I'm using this inside a react component:

```javascript
uploadFile(file) {
  importFile(file)
    .then(response => {
      console.log(response);
    })
    .catch(error => {
      console.log(error);
    });
}
```

When the post returns 200, it goes inside the then, and the response is an proper object, as expected.
But when it goes inside the catch, it's returning a string instead of an object:

![https://s29.postimg.org/669j3mddj/Captura_de_tela_2016_12_27_11_18_57.png](https://s29.postimg.org/669j3mddj/Captura_de_tela_2016_12_27_11_18_57.png)

**Comment by sanusart** [comment]
You suppose to read it from `error.response.data` of the `.catch()` as it documented in [handling-errors](https://github.com/mzabriskie/axios#handling-errors):

```
uploadFile(file) {
  importFile(file)
    .then(response => {
      console.log(response);
    })
    .catch(error => {
      if (error.response) {
      // This will have your response data as object  
      console.log(error.response.data);
     }
    });
}
```

**Comment by stevenmusumeche** [comment]
@sanusart did this behavior change between .11 and .15? I have code that was receiving response as the catch parameter and now it requires error.response to receive the same info.

**Comment by sanusart** [comment]
@stevenmusumeche Don't know about the changes, but it seems v0.15.3 behaves the same as documented:
Check http://codepen.io/sanusart/pen/qRMNWL with open console

**Comment by stevenmusumeche** [comment]
I see in the upgrade now that the error response was changed.  Thanks!
