### ISSUE TITLE
Issues with cancellation

### ISSUE THREAD

**Issue by shrynx** [mzabriskie/axios#620]
I am trying to cancel request using redux actions, but facing an issue. All the subsequent requests are then automatically cancelled. pretty sure i am doing something stupid, any help is appreciated.

```js
//actions.js
 
...

const CancelToken = axios.CancelToken
const source = CancelToken.source()

export const cancelRequest = () => {
	source.cancel('Operation canceled by the user.')
	return ({
		type: constants.CANCEL_ANALYSIS
	})
}

export const fetchRequest = (data) => {
	const requestConfig = {
		method: 'POST',
		url: constants.Api,
                data: data
		headers: {
	             'Accept': 'application/json',
	            'Content-Type': 'application/json',
	        },
		crossDomain: true,
		cancelToken: source.token
	}

	return ({
		type: constants.FETCH_REQUEST,
		payload: axios(requestConfig)
	})
}
```
Once cancelRequest() is fired it successfully cancels the request. But any other requests made in future using fetchRequest() are also cancelled (even though cancelRequest() is never called again).
I tried creating an instance and intercepting the instance for adding cancel token in cancelRequest method but had no luck.

**Comment by dlakata** [comment]
You only create a single source of cancel tokens, which means that all requests are given the same cancel token. With `source.cancel('...')`, all requests created with that source's token are canceled. You need to create a new source for every request, and use that same source to cancel that request.

**Comment by shrynx** [comment]
@dlakata Ahh alright, i understand. knew there was something silly. Thanks for the help.

**Comment by paladin2005** [comment]
@dlakata how do you fixed this problem???

**Comment by ehsankhfr** [comment]
There is no option as `crossDomain` inside the Axios. Please study the source-code before giving/using wrong clues.
