### ISSUE TITLE
PHP Script Cannot Receive Data from axios's Request in Redux Action Function

### ISSUE THREAD

**Issue by CasperHK** [mzabriskie/axios#621]
I want to sent some data to a php script with the use of `redux` and `promise` as if the following.

    export function fetchFileContent() {
        return {
            type: "FETCH_FILECONTENT",
            payload: axios.post("/api/ide/read-file.php", {
                filePath: document.getArgByIndex(0)[0]
            })
        };
    }

But the php script cannot receive the data. When I print all the data in `$_POST` using `var_dump`. There is nothing inside.

I checked the **Request Payload** in the Google Chrome debugging tool and it seems no problem.
[![enter image description here][1]][1]

How can I get back the data in the php script?

  [1]: https://i.stack.imgur.com/aw9XD.png

**Comment by rubennorte** [comment]
I'm sorry but I think this is not the proper place to ask. This page is meant for issues in Axios (in the library or the documentation). I suggest you use StackOverflow instead.
