### ISSUE TITLE
[Q] Having trouble with HTTP Basic Auth 

### ISSUE THREAD

**Issue by garmjs** [mzabriskie/axios#624]
I'm working in one API wich require HTTP Basic auth wich in response would return token, i'm providing axios config but i don't know if i'm doing it right if someone can check.

```
class Api {
  login (username, password) {
    return axios.get(`${END_POINT}/login/`, { // Yes API require '/' at the end of URL
      auth: {
        username,
        password
      }
    })
  }
}
```

as soon as i provide config HTTP Verbs change from GET to  OPTIONS.

![screen shot 2016-12-29 at 8 42 17 pm](https://cloud.githubusercontent.com/assets/5017156/21553194/596038fa-ce07-11e6-92a4-627b0e3ceb08.png)

And this maybe can be because of CORS but i can verify i'm sending GET request but i don't know why it's not working!

**Comment by MarkHerhold** [comment]
CORS is causing your browser to request the login page with the OPTIONS header and your server is erroring out (500 response code). You need to fix your server.

**Comment by garmjs** [comment]
Yes there was problem with backend, solved thanks
