### ISSUE TITLE
Feature missing - configure default ROOT path

### ISSUE THREAD

**Issue by murbanowicz** [mzabriskie/axios#626]
Hi,
I am trying to move from vue-resource to Axios.
I am buildin SPA and every request has to point the same host with different path.
Would be really good to make it possible with axios to have something like:
`axios.options.root = 'http://localhost:1337'`

**Comment by garmjs** [comment]
You have global axios defaults for this you can set 

```
axios.defaults.baseURL = `http://localhost:1337`
```
or save endpoint in variable like 
```
const END_POINT = `http://localhost:1337`
```
 and use it

**Comment by murbanowicz** [comment]
Thanks. Don't know why but I couldn't find it in docs

**Comment by ebertlast** [comment]
**Configure the base path with interceptors**

<pre>import axios from 'axios'
import join from 'url-join'
var isAbsoluteURLRegex = /^(?:\w+:)\/\//;
axios.interceptors.request.use(function(config) {
  if ( !isAbsoluteURLRegex.test(config.url) ) {
    config.url = join('https://jsonplaceholder.typicode.com/', config.url);
  }

  return config;
});</pre>
