### ISSUE TITLE
Does axios support Caching - Gzip - Redirect For Android and IOS ?

### ISSUE THREAD

**Issue by sahir** [mzabriskie/axios#628]

**Comment by sahir** [comment]
@mzabriskie Does axios support Caching - Gzip - Redirect For Android and IOS ?

**Comment by rubennorte** [comment]
Axios targets Node.js and browsers only, and there is support for gzip and redirection in both environments, but no caching (browser client cache if any).

**Comment by stevenvachon** [comment]
You should mention gzip support in the readme.

**Comment by ryanhomer** [comment]
Found this: [Networking on Android doesn't use Cache](https://github.com/facebook/react-native/issues/16795). When creating the `OkHttpClient`, no cache file is initialized.
