### ISSUE TITLE
Response undefined (Catch) 409 Error

### ISSUE THREAD

**Issue by pserick** [mzabriskie/axios#631]
Hi  there,

I need to get an error message from the API but I'm getting an undefined response from Axios!!

```
axios.interceptors.response.use(
  (response) => Promise.resolve(response),
  (error) => {
    console.log({ error });
    return Promise.reject(error);
  });
```
In the console I get this:
![screen shot 2017-01-04 at 6 06 00 pm](https://cloud.githubusercontent.com/assets/18693794/21657382/1ecaeafe-d2a9-11e6-9b65-da5785090c0d.png)

But the response from API is: 
![screen shot 2017-01-04 at 6 01 26 pm](https://cloud.githubusercontent.com/assets/18693794/21657408/3b0c423a-d2a9-11e6-899e-275076aefa72.png)

I have no ideia what is happening and how to fix it!!

Thanks!!

**Comment by Chathula** [comment]
you need to enable CORS(cross-origin resource sharing) from the server(API) side
what do you use for API.. 

you can add this code into your API . (DEV Only)

` header("Access-Control-Allow-Origin: *");`

for production you can use something like this...

```php
    public function handle($request, Closure $next)
    {
        $domains = ['http://localhost:8080'];

        if (isset($request->server()['HTTP_ORIGIN'])) {
            $origin = $request->server()['HTTP_ORIGIN'];
            if (in_array($origin, $domains)) {
                header('Access-Control-Allow-Origin: ' . $origin);
                header('Access-Control-Allow-Headers : Origin, Content-Type, Authorization');
            }
        }

        return $next($request);
    }
```

using this, if you want you can give access only to the specific client domains.

**Comment by rubennorte** [comment]
Agreed with @Chathula, this is a CORS issue, not a problem in Axios.

**Comment by ryannealmes** [comment]
This was happening to me as well and I thought it was axios.Thought I would just pass on the way post that help me solve it in a couple of minutes :) 

https://coderwall.com/p/wprykg/cors-with-nginx-for-401-404-501-and-any-other-http-status

**Comment by ryannealmes** [comment]
It would be great for someone with knowledge on the internals of axios to potentially explain why axios couldn't provide a response even though the response is clearly in the network tab. I know the issue is clearly CORS related, but why is this preventing CORS from getting to the information even though the browser has it.

Curios cat here 🐱
