### ISSUE TITLE
TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by hyosh** [mzabriskie/axios#632]
Hi,

i've an error, and i can't solved it alone :)

my error message is : 

> TypeError: Cannot read property 'protocol' of undefined
>     at isURLSameOrigin (bundle.js:53725)
>     at dispatchXhrRequest (bundle.js:53397)
>     at xhrAdapter (bundle.js:53301)
>     at dispatchRequest (bundle.js:53953)

i call this url http://api.bookapp/war-machine/auth/remember with post method.
like that :

```
axios.post(url,{remember_token:token})
  .then(authSuccess)
  .catch(authError);
```
my callback functions :

```
function authError(err){
  dispatcher({
    type: AUTH_FAIL,
    payload: err.response.data
  })
}

function authSuccess(response){
  //Définition du header
  axios.defaults.headers.common['Authorization'] = 'Bearer '+response.data.token;
  saveTokenRemember(response.data.remember_token);
  dispatcher({
    type:LINK_UPDATE,
    payload:response.data.links
  });

  delete response.data.links;

  dispatcher({
    type: AUTH_FULFILLED,
    payload: response.data
  });
}

```

If someone have an idea :)
Thanks for you'r help and sorry for my english..

**Comment by hyosh** [comment]
I've solved it,
The probleme was in an other axios.get()
and the url was undefined

**Comment by shapl** [comment]
// Vue.use(axios) 
ok。。。

**Comment by wusiyi** [comment]
@shapl  that‘s the right way

**Comment by psycho5** [comment]
You'll probably need a wrapper to use axios in vue components.
https://github.com/imcvampire/vue-axios

**Comment by michaelbrawn** [comment]
I was getting this with 
```
Vue.use(axios, VueAxios); 
```
Instead of the correct 

```
Vue.use(axios, VueAxios); 
```

**Comment by davidsneal** [comment]
Old issue, but for anyone that might have a facepalm moment such as myself...

I was using a new `process.env` as the URL I was calling (Vue project), and hadn't stop/started `npm run dev`.

**Comment by jsingletaryiv** [comment]
> I was getting this with
> 
> ```
> Vue.use(axios, VueAxios); 
> ```
> 
> Instead of the correct
> 
> ```
> Vue.use(VueAxios, axios); 
> ```

Thanks @michaelbrawn - 

I'm glad I scrolled down far enough to see your post... I wasn't even considering that the Vue API would be involved in this issue.

Although in my case I was passing `Vuex` along with `axios`:
> ```
> Vue.use(Vuex, axios);
> ``` 

...and now that you pointed it out, does all this come down to a plugin's dependencies and the order ops? Hmm... I'm never getting those 3 hours back! ;)

Cheers -

**Comment by colinwilson** [comment]
Just encountered this working with Gatsby. Couldn't figure out why the URL (environment variable) axios was querying at runtime was coming back undefined. Turns out I needed to RTFM!

> In addition to these Project Environment Variables defined in .env.* files, you could also define OS Env Vars. OS Env Vars which are prefixed with GATSBY_ will become available in browser JavaScript.

_Source: https://www.gatsbyjs.org/docs/environment-variables/_

**Comment by mamadfar** [comment]
GuyyyyyyyyyyyyyyyyyyyyyyyyyYYYYYYYYYYYYYYYYYYYYYYYYYYYyyyyyyyyyyyyyyyyyyyyyyyyyyyS

just use this 4 line code and DONE !

import Vue from 'vue'
import axios from 'axios'
import VueAxios from 'vue-axios'

Vue.use(VueAxios, axios)

.
.
.
JUST DO THIS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by farukhchik** [comment]
> GuyyyyyyyyyyyyyyyyyyyyyyyyyYYYYYYYYYYYYYYYYYYYYYYYYYYYyyyyyyyyyyyyyyyyyyyyyyyyyyyS
> 
> just use this 4 line code and DONE !
> 
> import Vue from 'vue'
> import axios from 'axios'
> import VueAxios from 'vue-axios' ### **_this line is important for destroy :) 'protocol' ERROR_** ###
> 
> Vue.use(VueAxios, axios)
> 
> .
> .
> .
> JUST DO THIS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**WOW!**

**Comment by MarionWallace** [comment]
what if youre using react tho?

**Comment by MarionWallace** [comment]
Because I'm using React with Axios.

**Comment by mamadfar** [comment]
sorry
i can't help u
because i don't know how it work in React

**Comment by mossa-Sammer** [comment]
@MarionWallace just check if the url you are doing a request on is undefined
