### ISSUE TITLE
Handling 401 Error

### ISSUE THREAD

**Issue by Chathula** [mzabriskie/axios#634]
i can't handle the 401 Unauthorized error. but before that axios always console.log() the  POST 401 (Unauthorized) error. i don't want to see that. how to fix it.

![alt tag](https://i.imgsafe.org/e42b3424a2.png)

This is the error i got as result.. i use Next.js / React
```
Error: Request failed with status code 401
    at createError (eval at evalScript (http://localhost:3000/_next/next-dev.bundle.js:36657:9), <anonymous>:971:16)
    at settle (eval at evalScript (http://localhost:3000/_next/next-dev.bundle.js:36657:9), <anonymous>:2964:13)
    at XMLHttpRequest.handleLoad (eval at evalScript (http://localhost:3000/_next/next-dev.bundle.js:36657:9), <anonymous>:813:8)
```

**Comment by rubennorte** [comment]
This is a regular HTTP response, not an issue in Axios.

You should check the documentation of the API you're using in order to solve your problem.

**Comment by Vietworm** [comment]
Hi @Chathula, I also research about to handle this. You can using `validateStatus` config in this case.

See about this [here](https://github.com/mzabriskie/axios/blob/4882ce5359c0ea5238de1cda21fb40a0584f9858/test/typescript/axios.ts#L39) !

**Comment by Chathula** [comment]
@Vietworm I'l give a try! 

Thank you!!

**Comment by achilleskineur** [comment]
validateStatus work Fine 

Thank you

**Comment by Bilal112** [comment]
![image](https://user-images.githubusercontent.com/23139110/41286407-c8097fb2-6e58-11e8-94eb-717fff07154b.png)

**Comment by Bilal112** [comment]
getting this error how can solve it

**Comment by guastallaigor** [comment]
@Bilal112 Did you try catching the error with `error.response.data.error`? See example:

```
this.$http.$post('url', user).then((response) => {
  //
})
.catch((error) => {
  this.showErrors(error.response.data.error)
})
```
Btw, i'm using Nuxtjs and axios module.

**Comment by AlokSuman** [comment]
login = () => {
    axios.post("https://192.168.0.10:8244/authenticateUser/1.0.0/outh", {
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Authorization": "Bearer df498c83-1c88-308e-a224-5408dd67bb7f"
      },
      data: {
        "authKey": "YWRtaW46YWRtaW4=",
        "clientId": "dWZkSHJnd05ZUjNDTXVpa3NDakJ4anNvaWZZYTpqcks5ZmFjZjBBbHRLVzY1UFVNZjl0OWRSck1h",
        "username": "KPFACTORS/Alok.Suman",
        "passkey": "Alok@123"
      }
    })
      .then(response => response.json())
      .then(response => console.log("hi" + response))
      .catch(err => console.log("error " + err));
  };

**Comment by MuhammetALAPAN** [comment]
Some APIs have property like "apikey" and you should indicate that property when you are using axios. 

You should look your **API's doc** for properties and also you can use **Postman** for indicate your url, header, params etc. easily.

@rubennorte, @lephuhai, @AlokSuman  thank you :)

```
componentDidMount () {
    axios
      .get("https://api.hurriyet.com.tr/v1/newsphotogalleries?$top=20", {
        params : {"$top": "20"},
        headers : {"apikey": "b21x5457136cxa5fdafc7v1x645526vb"}})
        .then(news => console.log(news))
}
```

**Comment by waqaramjad** [comment]
i received some different response in postman while the same thing i get an error in axios

**Comment by Bilal112** [comment]
> i received some different response in postman while the same thing i get an
 Hi 
What is the error
waqar

**Comment by waqaramjad** [comment]
@Bilal112 

that's my error
`Request failed with status code 401
    at createError (E:\React Native\EximApp\EximApp\node_modules\axios\lib\core\createError.js:16)
    at settle (E:\React Native\EximApp\EximApp\node_modules\axios\lib\core\settle.js:17)
    at XMLHttpRequest.handleLoad` 

while with postman that my response 
`{
    "error": "Unauthorised"
}`

**Comment by vidorifaldy** [comment]
> @Bilal112
> 
> that's my error
> `Request failed with status code 401 at createError (E:\React Native\EximApp\EximApp\node_modules\axios\lib\core\createError.js:16) at settle (E:\React Native\EximApp\EximApp\node_modules\axios\lib\core\settle.js:17) at XMLHttpRequest.handleLoad`
> 
> while with postman that my response
> `{ "error": "Unauthorised" }`

check this https://github.com/axios/axios/blob/4882ce5359c0ea5238de1cda21fb40a0584f9858/test/typescript/axios.ts#L39
line 39, axios just get status in range 200-300
if you change status on backend, you can get your response like in postmant

hope this can help you guys

**Comment by ashish9342** [comment]
Added debugger to check the object, so this is how the error object looks like.
Refer screenshot. Right side(under scope)


[https://i.stack.imgur.com/y3ixv.png](url)
