### ISSUE TITLE
GET request with axios header not working

### ISSUE THREAD

**Issue by AlisonWonderlandApps** [mzabriskie/axios#638]
Sorry if this is a noob question, but I'm trying to use axios for a get request with an API which requires an Authorization header

My current code:

> const AuthStr = 'Bearer ' + USER_TOKEN;

 //where USER_TOKEN is the access_token needed & may be the issue as if I post this as AuthStr = 'Bearer 41839y750138-391' it works and gets the data im after!)

> axios.get(URL, { 'headers': { 'Authorization': AuthStr } })
>   .then((response => {
>     console.log(response.data);
>   })
>  .catch((error) => {
>    console.log(error);
> });

I also tried setting this as a global header with no success :(

Further, I tried using concat on my string, same result. I also explicitly set it to String with the same result... I've also checked that typeof USER_TOKEN is a string.

And hard caoding the Auth string works :(:(
eg: 
> axios.get(URL, { 'headers': { 'Authorization': 'Bearer 512783098714-0' } })
>   .then((response => ...........

ANY HELP WOULD BE GREATLY APPRECIATED!

Also for additional context is is urlencoded post which i use Querystrong.stringify on (in case its relevant)

**Comment by AlisonWonderlandApps** [comment]
For anyone else that comes across this post and might find it useful...
There is actually nothing wrong with my code. I made the mistake of requesting client_credentials type access code instead of password access code (#facepalms).
So for those that may be looking for some example code.. here is my full request


``    const data = {
      grant_type: USER_GRANT_TYPE,
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      scope: SCOPE_INT,
      username: DEMO_EMAIL,
      password: DEMO_PASSWORD
    };
    axios.post(TOKEN_URL, Querystring.stringify(data))
      .then(response => {
        console.log(response.data);
        USER_TOKEN = response.data.access_token;
        console.log('userresponse ' + response.data.access_token);

        //AsyncStorage.setItem('clientToken', response.data.access_token);
      //  AsyncStorage.setItem('clientRefreshToken', response.data.refresh_token);

      })
      .catch((error) => {
        console.log('error ' + error);
      });

const AuthStr = 'Bearer '.concat(USER_TOKEN);
    axios.get(URL, { headers: { Authorization: AuthStr } }).then(response => {
            // If request is good...
            console.log(response.data);
          })
          .catch((error) => {
            console.log('error 3 ' + error);
          });
```

**Comment by ediferchancusig** [comment]
This worked for me:
const headers = {
    'PARAM_HEADER': eyJ0eXAiOiJKV1QiLC
  }
axios.post(URL, PARAM, { headers })
.catch((error) => {
      console.log('error ' + error);     
});

In the php:

header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, PARAM_HEADER");

**Comment by elsayednofal** [comment]
`
axios.get(URL, {
params:{},
headers: { 'Authorization': AuthStr } 
})

`

**Comment by adjieindrawan** [comment]
I have issue with `origin 'http://localhost:3000' has been blocked by CORS policy`

**Comment by cross28** [comment]
@adjieindrawan That's not a front end issue. That has to do with the way your backend is set up. Fairly simple thing to do in .Net Core but I don't know what backend you're using...

**Comment by shamoon-test** [comment]
> I have issue with `origin 'http://localhost:3000' has been blocked by CORS policy`

just add this before your URL: `https://cors-anywhere.herokuapp.com/`
it can help for develop
example (if your API url is `http://url.net/api`): 
`axios.get('https://cors-anywhere.herokuapp.com/http://url.net/api')`

**Comment by legitcode267** [comment]
@shamoon-test 
THANK YOU SOOOOOOO MUCH.
I was solving the CORS issue for 3 days and I found your comment.

**Comment by alansarluv** [comment]
> > I have issue with `origin 'http://localhost:3000' has been blocked by CORS policy`
> 
> @adjieindrawan
> just add this before your URL: `https://cors-anywhere.herokuapp.com/`
> it can help for develop
> example (if your API url is `http://url.net/api`):
> `axios.get('https://cors-anywhere.herokuapp.com/http://url.net/api')`

Thank you this is really help for quick fix development
