### ISSUE TITLE
onUploadProgress returns 100% before the request is actually done 

### ISSUE THREAD

**Issue by firaskrichi** [mzabriskie/axios#639]
This is the code I'm using : 
        
onUploadProgress : (progressEvent) => {
    let progress = Math.round( (progressEvent.loaded * 100) / progressEvent.total )
}

Progress is 100% while it still shows the request pending in the inspector. How do I make sure that progress is 100% only when the request is done? 

Thank you!

**Comment by rubennorte** [comment]
That's the upload progress so it's called for the progress of the content you're sending to the server. It's normal that the progress is 100% before the request is done. If you want the download progress you need `onDownloadProgress`.

**Comment by firaskrichi** [comment]
Thanks for the quick reply. Makes sense! I'm uploading files with a post request so wouldn't make sense to use onDownloadProgress I guess. 

I just need a way to wait for the server response before setting progress to 100%. Is there a way I could do that? 

Cheers!

**Comment by rubennorte** [comment]
You can just update the progress bar in a handler for the request promise.

```javascript
axios.post(...)
  .then(function(response) {
    // The request is completed here
  });
```

**Comment by firaskrichi** [comment]
Awesome! I'll use uploadprogress to 95% and then set 100% when promise is done.

**Comment by mikeynova** [comment]
@firaskrichi I'm having the same issue that you were dealing with. Could you tell me how you resolved this? 
I'm a little confused as to how you did it based off of the past few comments here.

**Comment by rugaard** [comment]
I also have this issue. I'm uploading images as well.

I'm testing the upload request with a 10 MB image. The `onUploadProgress` returns `100%` almost instantly and then the promise returns successfully after a whole 9-10 seconds.

@rubennorte Can you maybe help out with an example or a snippet of what you mean? I'm not greatest JS coder, so a little help would be much appreciated 😊

**Comment by Sharklegs** [comment]
I have this issue too.
onUploadProgress console.log() only once and the percent is 100%
image 5m and the network is slow 3g

**Comment by YL2014** [comment]
@Sharklegs The same with you. Did you resolved  that ?

**Comment by arist0tl3** [comment]
Dropping this here in case it helps anyone:

```
const options = {
  headers: {
    'Content-Type': file.type,
  },
  onUploadProgress: (progressEvent) => {
    const { loaded, total } = progressEvent;
    // Do something with the progress details
  },
};

axios.put(url, file, options)
  .then(() => {
    // Do your complete callback
  });
```

**Comment by hetzbr** [comment]
@Sharklegs 
Problem for me was that my server was running on localhost. If you host the server it works just fine

**Comment by YL2014** [comment]
@hetzbr Thanks, that worked for me. when the server was running on localhost, if i visit the server `http://127.0.0.1:port` rather than `http://localhost:port`, the`onUploadProgress `will called many times

**Comment by cahyowhy** [comment]
i have this issue too. i try both in localhost & 127.0.0.1 . but its still same

**Comment by yashSrijan** [comment]
i am facing the same issue.. the progress bar immediately goes to 100 % but the actual response comes seconds later.. i tried this with files of 40 to 50MB

**Comment by hetzbr** [comment]
@yashSrijan try running your server on a different machine (ex: VM, docker, etc.)

**Comment by riksnelders** [comment]
onDownload returns 0 total value. 
Anyway to check what is actually sent back then ?
running localhost btw, nog on prod server

**Comment by ChristianGerdes** [comment]
Did anyone solve this issue?

**Comment by 0plus1** [comment]
I have the same issue.
Server is remote, file is 50mb+ instantly goes to 100%. Content-Type is multipart/form-data

Can someone that solved the issue explain how?

**Comment by bledarhaxhia** [comment]
I think this is not a problem. If you are using a web server locally this upload is instantaneously and show just 100% value. Try to throttle the request in chrome and this will show some other numbers before upload is completed.

**Comment by kaankucukx** [comment]
@bledarhaxhia Thank you for your hack advice. 🥇 

Throttling worked for me both on localhost and 127.0.0.1:port 👍

**Comment by Shaker-Hamdi** [comment]
I had this issue as well, and throttling the connection solved it as @bledarhaxhia mentioned. so I don't think this is an issue with Axios.

**Comment by zis-wtag** [comment]
> I think this is not a problem. If you are using a web server locally this upload is instantaneously and show just 100% value. Try to throttle the request in chrome and this will show some other numbers before upload is completed.

Yeah, throttling the network to "Slow 3G" I see the progress. Thanks.
