### ISSUE TITLE
Getting the XHR instance

### ISSUE THREAD

**Issue by srph** [mzabriskie/axios#64]
Hmm, I'm currently implementing a progress bar with `xhr.upload`. I just checked the docs, but I couldn't squeeze out any info at all. Is the instance exposed with the latest versions?

**Comment by mzabriskie** [comment]
It is not currently possible to access the XHR instance.

**Comment by mzabriskie** [comment]
This would be solved with #82

**Comment by AurelioDeRosa** [comment]
I think this should be a different issue. While there are cases where only the `onProgress` is needed (addressed by #96), there are other cases where an application need to access the XHR instance to perform other operations.
