### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled  promise rejection

### ISSUE THREAD

**Issue by kfir91** [mzabriskie/axios#640]
When i use axios i got error:

[2017-01-08 17:30:09] <START> Transforming files
transformed 364/394 (92%)(node:1948) UnhandledPromiseRejectionWarning: Unhandled
 promise rejection (rejection id: 306): UnableToResolveError: Unable to resolve
module http from F:\ReactNative\test\node_modules\apisauce\node_modules\axios\li
b\adapters\http.js: Module does not exist in the module map or in these director
ies:
  F:\ReactNative\test\node_modules\apisauce\node_modules
,   F:\ReactNative\test\node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cac
he`.
(node:1948) DeprecationWarning: Unhandled promise rejections are deprecated. In
the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.

i doing all the resolves in the introductions and its didnt help...

the error came when i add to my code:
`import {create} from 'apisauce';`

tnx a lot

**Comment by JamesAnthonyMart** [comment]
I'm also getting this.

**Comment by hungdev** [comment]
I'm also getting this.

**Comment by tsnolan23** [comment]
I am also getting this error

**Comment by kfir91** [comment]
I solved the problem.
i downgrade my react-native version to 0.35.0 and the problem was solved.

**Comment by tsnolan23** [comment]
@kfir91 Thanks for the suggestion, it worked for me as well.
