### ISSUE TITLE
error and response are undefined

### ISSUE THREAD

**Issue by r3wt** [mzabriskie/axios#643]
I need to get the response body in case of http error. the api returns a json like so:

```js
{
status: HttpStatusCode,
data: Data,
message: ErrorMessage
}
```
It would be beneficial to be able to read the response data here.

**Comment by r3wt** [comment]
i've found a workaround for now by wrapping axios in an jQuery helper. leaving it here for anyone else who needs the response object even if error. this is the inherent problem with promises.

*http.js*
```js
!function(axios,$){
	$.http = function(/* method uri[ ,data],callback */){
		var self = this.http;
		if( !self._agent ){
			if(!self._config){
				return console.warn('You must configure axios before using the http client.')
			}
			self._config.transformResponse = [function (data) {
				self._res = JSON.parse(data);
				return data;
			}];
			self._agent = axios.create(self._config);
		}
		
		var args = arguments[0].split(' ');
		var method = args[0].toLowerCase();
		var uri = args[1];
		
		if(arguments.length == 3){
			var data = arguments[1];
			var cb = arguments[2];
		}else{
			cb = arguments[1];
		}
		if(data){
			var p = self._agent[method](uri,data);
		}else{
			var p = self._agent[method](uri);
		}
		
		p
		.then(function(res){
			cb(null,res.data);
		})
		.catch(function(err,res){
			cb(err,self._res);
			delete self._res;
		});
	};
	
	$.http.config = function( c ){
		$.http._config = c;
	};
}(axios,jQuery);
```

*usage*
```js

$.http.config({
	  baseURL: location.protocol + '//' +location.host + '/api/v1',
	  timeout: 10000,
});

$.http('PUT /users/login',$('#login-form').serialize(),function(err,res){
	if(err) 
		console.log(res);
	else
		location.href="/";
});
```

i realize this is probably a bit weird for most people but its easy to understand with me. first argument is Method + Uri, second arg is optional data/params and final arg is callback.

best of luck, thanks for the client. i still like it better than jQuery.

**Comment by rlambertsen** [comment]
Check the docs my friend.  [Error handling](https://github.com/mzabriskie/axios#handling-errors)

You need to add a `.catch` after the call like so:

```javascript
axios.get('/user/12345')
  .catch(function (error) {
    if (error.response) {
      // The request was made, but the server responded with a status code
      // that falls out of the range of 2xx
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    console.log(error.config);
  });
```
Or if you want the response error inside the success, something like this : (though I don't recommend it)

```javascript
axios.get('/user/12345').then((data) => {
 console.log(data)
}, (errorResponse) => {
console.log(errorResponse)
})

**Comment by ionull** [comment]
I have the same issue on 0.16: response either 401 or 422 status code get 'undefined' response body while I can see the body with network tools on Chrome.
<img width="716" alt="chrome-network" src="https://cloud.githubusercontent.com/assets/242295/26655207/79fb3742-468c-11e7-9b58-1f9acceb282f.png">
<img width="750" alt="axios-response" src="https://cloud.githubusercontent.com/assets/242295/26655208/7a2a72f0-468c-11e7-8686-4af245d346a5.png">
