### ISSUE TITLE
catch unhandled errors, not possible with promises

### ISSUE THREAD

**Issue by tzookb** [mzabriskie/axios#644]
I need to catch all errors that are not handled, for example:

     axios.get("/")
      .then(function(){
          throw new Error("something");
     })
     .catch(function(err) {
          //this is ok
     });

     axios.get("/")
      .then(function(){
          throw new Error("something");
     })

now the second example will simply output an error...
I want to catch it globally with something like:

    window.onerror = function() {
         alert("error");
    }

is that possible? I noticed interceptors, but they will work just before the exception is sent,not after...

**Comment by rubennorte** [comment]
You can do it. Here you have an article that explains it: http://www.2ality.com/2016/04/unhandled-rejections.html

I recommend you to catch all possible rejections in your promises manually to avoid ignoring errors and not displaying proper information to your users.
