### ISSUE TITLE
how could I send message log when I cancel request

### ISSUE THREAD

**Issue by L-Jovi** [mzabriskie/axios#645]
I use redux-saga to trigger axios cancel behaviour like below code ,

```
import axios, { CancelToken } from 'axios'
import { CANCEL } from 'redux-saga'

export default function fetchAPI(url) {
  const source = CancelToken.source()
  const request = axios.get(url, { cancelToken: source.token })
  request[CANCEL] = () => source.cancel()
  return request
}
```

and in my saga I could cancel the promise, but I notice that after I successfully cancel the promise by using saga's `cancel` operator, console could show me the log from saga,

![image](https://cloud.githubusercontent.com/assets/7262199/21806773/444c6d30-d776-11e6-9304-d79369f2765e.png)

but I can't see the result from axios, even if I try

```
request[CANCEL] = () => source.cancel('========== cancel from axios =========')
```

how could I actually confirm result from axios's cancel behaviour?

thanks for your time.

**Comment by rubennorte** [comment]
You can see the request being cancelled in the Network section of the developer tools.

**Comment by L-Jovi** [comment]
@rubennorte  thanks for your reply, but in react native chrome debug network, I can't watch history of request from js side like below image, it only record local behaviour of request

![image](https://cloud.githubusercontent.com/assets/7262199/23110419/3e3f95a6-f75c-11e6-9824-6390b7dcf726.png)
