### ISSUE TITLE
Unable to resolve axios module with RN 0.40.0 [Android]

### ISSUE THREAD

**Issue by JacobRAllen** [mzabriskie/axios#648]
The new 0.40.0 release of RN has broken axios for me. 
I've done two test cases in which I create a blank application, install axios, then import axios on the index page. The only difference between the two projects are the RN version number. 

`react-native init TestProject` (this is @latest which is currently 0.40.0)
`cd TestProject`
`npm install axios --save`
I then go into the index.android.js file and add: `import axios from 'axios'`
`react-native run-android`
In this case, I get the following error: 
Unable to resolve module http from C:\ReactNative\Projects\TestProject\node_modules\axios\lib\adapters\http.js: Module does not exist in the module map or in these directories: C:\ReactNative\Projects\TestProject\node_modules.

However, when I install an older version of RN like below, axios works fine.
`rninit init TestProject --source react-native@0.39.2`
`cd TestProject`
`npm install axios --save`
I then go into the index.android.js file and add: `import axios from 'axios'`
`react-native run-android`

As a workaround to fix this I have downgraded my RN back down to 0.39.2 rather than using 0.40.0.

**Comment by dekm** [comment]
I'm seeing the same issue.  Looks like axios doesn't work with latest RN.

I've tried cleaning the gradlew cache and reinstalling everyhthing but none of that works.

**Comment by mrpatiwi** [comment]
+1

**Comment by agarcia17** [comment]
+1

**Comment by davebro** [comment]
+1

**Comment by shirilad** [comment]
+1

**Comment by jussisaurio** [comment]
+1

**Comment by wyvasi** [comment]
+

**Comment by anthony-skr** [comment]
+1

**Comment by AndrewMarkley** [comment]
+1

**Comment by GantMan** [comment]
+1

**Comment by GantMan** [comment]
https://github.com/facebook/react-native/issues/11498#issuecomment-273972902

**Comment by wilomgfx** [comment]
+1

**Comment by rubennorte** [comment]
Looks like it's an issue in that version of RN. See https://github.com/facebook/react-native/issues/11498#issuecomment-274163448

**Comment by JacobRAllen** [comment]
I am aware it is an issue with this version of RN, but none of my other packages where experiencing this issue when using RN 0.40.0, so I assumed this issue belonged here.

**Comment by Gvade** [comment]
Still +1

**Comment by t2** [comment]
+1

**Comment by oun** [comment]
Is there any workaround?

**Comment by JacobRAllen** [comment]
As mentioned in my original post, you can use an older version of RN. 

Rubennorte has also made progress with addressing this issue with the RN team and this issue is supposedly going to be fixed in RN 0.41

**Comment by GantMan** [comment]
@oun - yes, see my link above.

**Comment by oun** [comment]
Thanks @GantMan. Does this work on Mac OS machine?

**Comment by yaronlevi** [comment]
+1

**Comment by NicolasdeTiesenhausen** [comment]
+1

**Comment by rubennorte** [comment]
This could be solved in RN 0.41. Could you test it?

**Comment by franzejr** [comment]
@rubennorte, it works on the RN 0.41 version! Cool!

**Comment by jinxac** [comment]
its working for me on RN 0.40. But after reading the comments here I am little confused. Is it suppose to work?
