### ISSUE TITLE
posting with formdata not working

### ISSUE THREAD

**Issue by flogball00** [mzabriskie/axios#65]
tried doing something like 
```
var fileData = new FormData();
      fileData.append("File1", file);

return axios({
                    method: 'post',
                    url: response.data.ChunkUri,
                    data: fileData,
               
                });
```
this returned an error from the server saying that there was no file sent. But...

vs jquery which worked and the file uploaded successfully.

```

                var options = {
                    type: "POST",
                    url: response.data.ChunkUri,
                    data: fileData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function(e){
                            console.log("YAY:: " + e);
                    },
                    error: function(a){
                        console.log("failed:: ");
                    }

                };
                return $.ajax(options);
```

**Comment by srph** [comment]
Can you put "not working" into detail?

**Comment by mzabriskie** [comment]
@flogball00 are you still having this problem?

**Comment by flogball00** [comment]
Yep,  both axios and superagent were not able to transmit the filename.  When i looked at the request payload, i would get something like "Content-Disposition: form-data; name="File1"; filename=""

**Comment by mzabriskie** [comment]
Odd. I'll have to look into jQuery's source, and see what's different.

**Comment by kalaspuffar** [comment]
Have you tried to use the third argument for formData suppling the filename?

https://developer.mozilla.org/en-US/docs/Web/API/FormData/append

**Comment by pnkapadia6** [comment]
Any updates on this?

**Comment by nickuraltsev** [comment]
As @kalaspuffar pointed out, filename can be passed as the third parameter to `FormData#append`:

```js
fileData.append("File1", file, "file.js");
```

**Comment by ConAntonakos** [comment]
@nickuraltsev's answer in https://github.com/mzabriskie/axios/issues/318#issuecomment-218948420 really helped me out.

**Comment by besabellacyrus** [comment]
@ConAntonakos  that is the solution to my problem.

**Comment by jasperf** [comment]
@ConAntonakos Would be great if you could share how you adjusted your code in the end. Working on passing data with .append now as well as it won't with my regular setup.
