### ISSUE TITLE
Axios handle cut error message after comma

### ISSUE THREAD

**Issue by IronGhost63** [mzabriskie/axios#655]
this is the actual error message (using CocoaRestClient)

```
{
  "code": "rest_missing_callback_param",
  "message": "Missing parameter(s): email, password, name, phone",
  "data": {
    "status": 400,
    "params": [
      "email",
      "password",
      "name",
      "phone"
    ]
  }
}
```

but in Chrome dev tool. when I console.log showing payload.response.data.message (using with Redux) it only shown "Missing parameter(s): email" everything after comma just gone

**Comment by rubennorte** [comment]
You must have an error in the request configuration passed to Axios. The library doesn't modify the response returned by the server, even if it's an error. Please review your code and reopen if you're sure there's something wrong with Axios.
