### ISSUE TITLE
Why is the data surrounded by quotes?

### ISSUE THREAD

**Issue by rightaway** [mzabriskie/axios#657]
```js
  console.log((await axios('http://api.ipify.org')).data)
```

Why does this print my IP address surrounded in quotes? (`'1.2.3.4'`) It shouldn't do this, if you go to api.ipify.org in the browser or with `curl` it doesn't have quotes.

**Comment by SteveEdson** [comment]
Thats just showing that the logged data is a string (as opposed to a number, array, object etc). If you try

```js
axios('http://api.ipify.org').then(response => console.log(response));
```

It will log the entire JS object, and
JS object, and

```js
axios('http://api.ipify.org').then(response => console.log(response.data));
```

will log the response value, i.e the IP address.
