### ISSUE TITLE
Error when trying to connect to HTTPS site through proxy

### ISSUE THREAD

**Issue by rightaway** [mzabriskie/axios#658]
I get this error when connecting to an HTTPS site through a proxy. It works fine when I connect to that same site using HTTP (the site is available in both HTTP and HTTPS). To test it you can try with any HTTPS proxies (test ones available at https://free-proxy-list.net/, I've tried only the ones with a 'Yes' in the 'Https' column.)

```
(node:11581) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): 
Error: write EPROTO 140378207070016:error:140770FC:SSL
routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
```

The  code

```js
async function download() {
  const response = await axios('https://api.ipify.org', {
    timeout: 5000,
    proxy: {
      host: '104.154.142.106',
      port: 3128
    }
  })
  console.log(response.headers)
}
```

**Comment by rubennorte** [comment]
I think the problem is that the proxy you're configuring is an HTTP server, not HTTPS.

**Comment by rightaway** [comment]
Is that the error message you'd expect to see if if were at HTTP not HTTPS server? Because I tried proxies with the `https` field set to true.

**Comment by rubennorte** [comment]
I think so. I tried HTTP and it worked.

**Comment by chovy** [comment]
if i use curl i can fetch it fine. if i use axios I get a 503 not sure url i'm querying is https

**Comment by etayluz** [comment]
Same here,
curl -x 144.217.207.164:3128 -L 'https://www.walmart.com/ip/22790128'

This works totally fine!

But this will fail:
    var config = {
      proxy: { host: '144.217.207.164', port: 3128 }
    }
    axios.get('https://www.walmart.com/ip/22790128', config).
   .then(result => {
       // I want to be here
    })
   .catch(error => { 
       // But I'm stuck here!!!
   }

**Comment by chovy** [comment]
yes, that's what I've come to conclude. https urls must be sent to https proxy. Which is not really all that useful. Most proxies are not https.

**Comment by etayluz** [comment]
@chovy I don't see any proxy support with request-promise?
https://github.com/request/request-promise

**Comment by chovy** [comment]
The options are passed on to `request` -- `{ proxy: 'http://user:pass@x.x.x.x:8080' }`

**Comment by etayluz** [comment]
Hey @chovy could you help me out for a second and see if you can get it to work with this URL?
https://www.walmart.com/ip/24032132

For the life of me I can't get this to work - I'm wondering if it's something special with Walmart

**Comment by chovy** [comment]
You'd have to give me your proxy.

**Comment by chovy** [comment]
It works for me:


	const request = require('request-promise');

	request({
	  url: 'https://www.walmart.com/ip/24032132',
	  proxy: 'http://user:pass@x.x.x.x:8080',
	  headers: {
	    'User-Agent': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36.'
	  }
	})
	  .then(console.log)
	  .catch(console.error);


Looks like walmart requires a user agent.

**Comment by etayluz** [comment]
Thanks for the reply @chovy !

So this is what I'm trying:
```
const request = require('request-promise');

request({
  url: 'https://www.walmart.com/ip/24032132',
  proxy: 'http://52.8.172.72:4444',
  headers: {
    'User-Agent': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36.'
  }
})
  .then(console.log)
  .catch(console.error);
```

But I receive this error message:

> { RequestError: Error: tunneling socket could not be established, statusCode=401

Could this be an issue with the proxy I'm using?

**Comment by chovy** [comment]
Free proxy lists are no good. Get a paid proxy.

**Comment by etayluz** [comment]
what's a good place to get them? should I make my own on AWS or Azure?

**Comment by chovy** [comment]
There's many providers. Search for "paid proxies" there are premium proxies (that are yours and yours alone) and there are "shared proxies" which you pay for (much more reliable) but others use as well. Typically it ranges from .50 cents - $1 USD per proxy depending on who you buy from.

**Comment by futurmat** [comment]
I think I have the same problem. I used a paid proxy provider (crawlera) and set it up the following way:
```
axios(url, {
	method: 'get',
	httpsAgent: new https.Agent({
		ca: fs.readFileSync(`${parentDir}/crawlera-ca.crt`),
	}),
	proxy: {
		host: 'proxy.crawlera.com',
		port: 8010,
		auth: {
			username: 'XXXXXXXXXXXXXXXXXXXXXXXXX'
		}
	},
	headers: {
		'User-Agent': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Safari/537.36.'
  }
```

I get the error: 
`Error:` write EPROTO 140736707912640:error:140770FC:SSL routines:SSL23_GET_SERVER_H
ELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794`

Not sure if I miss an option? If I set `port: 443` in `https.Agent` I get a timeout.

**Comment by etayluz** [comment]
@futurmat not only did I give up on axios for this purpose, but I also gave up on Javascript. I was able to get request-promise to work, but then I noticed performance and memory issues with it. Since then I've switched over to Python using Tornado for networking - and things are running along much more smoothly. Python is really so much easier work with than Javascript.

**Comment by justbill2020** [comment]
+1

is this issue ever going to be addressed? or is it out of sight out of mind???

**Comment by americos** [comment]
Had a very similar issue using axios 0.18.0 in different node versions: 8.5, 8.6, 9.7.1, 10.8.0. Using `request-promise` as suggested above fixed my issue.
