### ISSUE TITLE
Catching errors from other things

### ISSUE THREAD

**Issue by zackify** [mzabriskie/axios#66]
The .catch from one ajax call is catching errors completely unrelated. One time I had required a file that did not exist, and it was being caught inside a module that I was making an ajax request in using axios. Promises seem to be messed up.

**Comment by Nicolab** [comment]
Here also. Axios catch an Exception generated by a Chrome extension

**Comment by zackify** [comment]
Glad I'm not the only one, I don't get how more people aren't seeing this.

**Comment by Nicolab** [comment]
May be because an exception is thrown into the `then()` method.
In my case in the then() method I have an events dispatcher and the Chrome extension explain the Flow.

**Comment by Nicolab** [comment]
Hmm, Axios even catch exceptions thrown out of the method `then()`.

**Comment by mzabriskie** [comment]
This is definitely not expected behavior. For those experiencing this, can you please provide a gist, or some example how to reproduce? Thanks.

**Comment by csm123** [comment]
I'm using the same sort of promises as Axios on a project, and the promise catches exceptions in `then`. That is, exceptions in `then` don't throw an error in the Chrome console - instead the promise has the error. You can tack on `.catch(function(err) { console.error(err); });` for debug purposes, but that's not really a lasting solution. Unsure of what to do here.

**Comment by csm123** [comment]
Related: https://github.com/jakearchibald/es6-promise/issues/40

**Comment by csm123** [comment]
Also, this is how it's handled in es6-promise's parent library, RSVP.

https://github.com/tildeio/rsvp.js#error-handling

**Comment by dmt0** [comment]
I'm getting this in one (but not all) of my projects. Any time I hit an `undefined.member` in the `render()` function of any React component, Axios catches it.

**Comment by nickuraltsev** [comment]
This issue is not actionable as is. Please provide a code snippet that reproduces the problem and reopen.

**Comment by dmt0** [comment]
According to [this](http://jamesknelson.com/are-es6-promises-swallowing-your-errors/) it's actually the correct behavior apparently.

**Comment by JSW5297** [comment]
I am also getting this error. Is there an explanation for this?
