### ISSUE TITLE
Is there a timeout function?

### ISSUE THREAD

**Issue by joetidee** [mzabriskie/axios#660]
Is there a way to run a perform an action if a request times out?

**Comment by rubennorte** [comment]
You can check the error that is thrown when a request times out (error.code == 'ECONNABORTED').

**Comment by joetidee** [comment]
Thank you. Worth adding in as a seperate API option? Just because I would have thought handling timeouts was a very common occurrence.

**Comment by rubennorte** [comment]
I don't think so. There are more cases where a promise can be rejected (cancellation, custom logic in interceptors, etc.) so I don't think it'd be a good idea to provide specific callbacks for each one.

**Comment by joetidee** [comment]
Hmm, I would have thought that every single request to a server should handle timeouts - this is a common  problem outside the programmers control.

**Comment by rubennorte** [comment]
I agree, but you should handle any kind of error in the request, not just timeouts, so adding a special case doesn't seem relevant.

**Comment by joetidee** [comment]
It would save writing (error.code == 'ECONNABORTED') for every request case. I might also help point out to developers that they should be handling timeouts if they have overlooked the idea.
