### ISSUE TITLE
HTTPS request works using the https module but not in Axios

### ISSUE THREAD

**Issue by jamesw201** [mzabriskie/axios#662]
This request works with the https library:
```
const options = {
    hostname: 'baseurl.com',
    path: '/accounts',
    method: 'GET',
    ca: fs.readFileSync(`${path}CA.pem`),
    cert: fs.readFileSync(`${path}CERT.pem`),
    key: fs.readFileSync(`${path}KEY.pem`),
    auth: 'user:password',
    rejectUnauthorized: false
};
const req = https.request(options, (res) => {
    res.on('data', (data) => {
        process.stdout.write(data);
    });
});
req.end();
req.on('error', (e) => {
    console.error(e);
});
```

but this seemingly equivalent request does not work using Axios:

```
const instance = axios.create({
    baseURL: 'https://baseurl.com',
    httpsAgent: new https.Agent({
        ca: fs.readFileSync(`${path}CA.pem`),
        cert: fs.readFileSync(`${path}CERT.pem`),
        key: fs.readFileSync(`${path}KEY.pem`),
        auth: 'user:password',
        rejectUnauthorized: false
    })
});

instance.get('/accounts')
  .then(_ => console.log(`response: ${_}`))
  .catch(err => console.log(`error: ${err.stack}`));
```

Instead it throws this error: 
error: Error: write EPROTO
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)

I've tried these variations of base url but no luck:
- 'https://baseurl.com:443'
- 'baseurl.com'
- 'baseurl.com:443'

any help much appreciated.

**Comment by sylvainpina** [comment]
Hi,
I have practically the same issue  :(
Did i miss something ?

nodejs script :
```node
var axios = require('axios')
var params = {
  url: 'https://raw.githubusercontent.com/mzabriskie/axios/master/README.md',
  method: 'get'
}
axios(params)
  .then(res => res.data)
  .catch(error => {
    console.error('$http:ajax:catch', error)
  })
```
error : 
```node
$http:ajax:catch { Error: write EPROTO 140735204655104:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)
  code: 'EPROTO',
  errno: 'EPROTO',
  syscall: 'write',
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.15.3',
        host: 'raw.githubusercontent.com' },
     method: 'get',
     url: 'https://raw.githubusercontent.com/mzabriskie/axios/master/README.md',
     data: undefined },
  response: undefined }
```

**Comment by sylvainpina** [comment]
I just tested under windows on another pc (and another netword) and there is no problem ...
i'm under osx (10.11.6).
i tested with node 6.9.1 and 6.9.4

maybe a proxy issue or another bullshit 😭 

best regards :)

**Comment by chovy** [comment]
I still have this issue not being able to hit an https url with an http proxy. I can do it fine in request and also in curl from shell. Something not working with axios. I get an EPROTO error.

**Comment by jamesw201** [comment]
Thanks @sylvainpina, looks like your issue was slightly different as I
could get the request working using the https library but not with axios.

@Anthony, does your Axios request look the same as mine? It would be
interesting to see your code.

**Comment by chovy** [comment]
@jamesw201 

This works fine in request() and with curl -x <proxy-url> https://ipinfo.io

	const http = rp.defaults({
      proxy: 'asdf:asdf@x.x.x.x:8080',
      timeout: 4000,
      resolveWithFullResponse: true
    });


Axios returns an `EPROTO` error if I send an https url:

	const http = axios.create({
	  proxy: {
	    host: 'x.x.x.x',
	    port: 8080,
	    auth: : {
	      username: 'asfd',
	      password: 'asdf'
	    }
	  }	
	});

**Comment by mashley** [comment]
I'm having the same problem as @chovy when sending https through http proxy

**Comment by chovy** [comment]
I found the problem in the code. Easy fix but I'm not sure how `transport` should be defined.

`options.path = protocol + '//' + parsed.hostname + (parsed.port ? ':' + parsed.port : '') + options.path;`

This should be something like:

```
options.protocol = proxy.protocol || protocol;
options.path = options.protocol + '//' + parsed.hostname + (parsed.port ? ':' + parsed.port : '') + options.path;
```

This allow us to use an `http` proxy server with an `https` url:

```
{
 	proxy: {
 		...
    	        protocol: 'http' 
	}
 }
```

**Comment by chovy** [comment]
I tried adding this change and get a `protocol mismatch` assertion error when running tests. Not sure what that's about. I'm guessing the method of sending https url to httpFollow is not working.

**Comment by FastNinja** [comment]
we have exactly same issue after upgrading to latest version of `axios`. Is anyone is looking at creating pull request?

**Comment by husayt** [comment]
This is a show stopper for us too. We have to switch to request.js because of it now.

**Comment by jamesw201** [comment]
My original post was wrong, I didn't read the documentation closely enough. The request should have looked like this: 

```
var instance = axios.create({
      baseURL: 'https://baseurl.com',
      httpsAgent: new https.Agent({
        ca: fs.readFileSync(`${path}CA.pem`),
        cert: fs.readFileSync(`${path}CERT.pem`),
        key: fs.readFileSync(`${path}KEY.pem`),
        rejectUnauthorized: false
      }),
      auth: {
        username: 'username',
        password: 'password'
      }
});

instance.get('/accounts')
    .then(_ => console.log(`response: ${_}`))
    .catch(err => console.log(`error: ${err.stack}`));
```

**Comment by gigachel** [comment]
I'm having the same problem. Has anyone solved the problem of https request over proxy? I do not want to move to request.js. (request.js in this situation works well).

**Comment by blizzardzheng** [comment]
i have the same issue here, very simple usage to used in nodejs , just do the https request,

**Comment by kparkov** [comment]
This ticket was closed, but the problem described by @chovy is still there.

> I still have this issue not being able to hit an https url with an http proxy. I can do it fine in request and also in curl from shell. Something not working with axios. I get an EPROTO error.

**Comment by fairyly** [comment]
if  not  in  node  ,how  to get https module
??? @FastNinja

**Comment by JamesMcGuigan** [comment]
There is a bug in lib/defaults.js::getDefaultAdapter ()

In Jest unit tests, it returns ./lib/adapters/xhr.js even when httpsAgent: is present. XHR adapter has no support for httpsAgent:

The workaround solution is:
```
let axiosOverride = axios.create({
  baseUrl: 'https://localhost:5000',
  adapter: require('axios/lib/adapters/http'),
  httpsAgent: new spdy.createAgent (sslOptions),
  withCredentials: true
});

export default axiosOverride
```

**Comment by ricokahler** [comment]
@JamesMcGuigan thanks for your post.

I've been scratching my head for a while about why I'm getting an error similar to OP's (though it seems unrelated now).

More googling lead me to https://github.com/axios/axios/issues/1180 and setting jest's `testEnvironment` to `node` also fixes that problem.

hope this helps anyone else having this issue!

**Comment by hanzichi** [comment]
@sylvainpina  thanks for your comments, but why the other http modules do not meet the questions? such as node-fetch?

**Comment by sylvainpina** [comment]
@hanzichi, no idea.
i don't have the problem with [reqwest](https://github.com/ded/reqwest)
maybe Axios is more advanced and do more check.
best regards
