### ISSUE TITLE
Something that tells me the entire request is complete

### ISSUE THREAD

**Issue by andreyluiz** [mzabriskie/axios#663]
jQuery Ajax has the `complete` callback that is called when the request is done.

Is there something similar from axios?

For example, in the following code I need to call the `transitionTo` in both success and fail cases:

```javascript
axios.post('/user/validate', data)
  .then(() => {
    // success
    router.transitionTo('/');
  })
  .catch(() => {
    // whoops
    router.transitionTo('/');
  })
```

How can I structure this to call `transitionTo` only once?

**Comment by lnfnunes** [comment]
As Axios follows [API Promise specs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) and it doesn't have an _"always/finally"_ interface, my suggestion (actually I don't know if it's the best) to achieve what you want is to wrap your _**axios.post**_ into a _**axios.all**_ and handle it:

```javascript
axios.all([axios.post('/user/validate', data)])
  .catch(error => console.log(error))
  .then(() => router.transitionTo('/'));
```

**Comment by andreyluiz** [comment]
Yeah, it works as I expected. However, I was able to solve this way:

```javascript
const buildResult = (succeeded: boolean, message: string) => ({ succeeded, message });

axios.post('/api/forgot', data)
    .then(response => buildResult(true, response.data.message))
    .catch(error => buildResult(false, error.response.data.message)));
```

Not the prettier solution, but for now it works fine. :)

Thank you for the help.
