### ISSUE TITLE
Axios.all for dynamic post calls?

### ISSUE THREAD

**Issue by githubitsme** [mzabriskie/axios#665]
I have to make dynamicpost call to my server for that I am using axios.all this seems to be easy at first.I don't how to get the response for dynamic changing post queries Still don't get it see the example

```
    function getThatAxiosMultiple(PhotoDataBlob,postId) {
        let ReturnThatAxios = [];
        PhotoDataBlob.map(data => {
            let pushThis = axios.post('/postthispic',{data,postId})
            ReturnThatAxios.push(pushThis)
        })
      
        return ReturnThatAxios
    }

    function getResponseLength(PhotoDataBlob) {
        let returnThis = []
    
        for(let i=0;i < PhotoDataBlob.length;i++){
            let response = `response${i}`;
            returnThis.push(response)
        }
        return returnThis.join() // response1,response2,response3....
    }
    
    let postId = 'XXXXX';
    let getReadyresponseLength = getResponseLength(PhotoDataBlob);     //this dynamic changing variable is not accesible
    console.log(getReadyresponseLength)
    let axiosMultipleArray = getThatAxiosMultiple(PhotoDataBlob,postId)
    axios.all(axiosMultipleArray).then(axios.spread((  getReadyresponseLength )//response1,response2... => { 
        console.log(getReadyresponseLength)
    }))
```

Any other way how to do it ?

**Comment by rubennorte** [comment]
Not sure about what you want to accomplish but as long as this isn't a feature request, a bug or a specific question about axios but about general promise handling please use StackOverflow, our gitter channel or any other means.

**Comment by techlab23** [comment]
@vignestion Following is the code to demonstrate how i used axios.all and axios.spread in my code. Basically the code query cryptocompare api to pull historical crypto currency data for number of days.  

// Number of days to pull the data 
const numberOfDays = 4

// Initializing days array
const days = [...Array(numberOfDays)].map((v,i) => ++i)

// Fetch function to make get request to cryptocompare api
let fetch = (curr,day) => axios.get(`https://min-api.cryptocompare.com/data/pricehistorical?fsym=${curr}&tsyms=USD&ts=${day}`)

// Building the dynamic array of fetch calls for number of days  
let fetchCalls = days.map((t) => fetch('BTC',moment().subtract(t, 'days').unix()))

// Using axios.all and axios.spread with es6 spread operator to access results
axios.all(fetchCalls).then(axios.spread((...res) => res.map(d => console.log(d.data))))
