### ISSUE TITLE
XML responseType?

### ISSUE THREAD

**Issue by ngocketit** [mzabriskie/axios#667]
Hi,

Is XML response type supported? If server returns `application/xml`, what should be the correct way to get the response XML?

`response.request.responseXML` or parsing `response.data` text to XML document?

**Comment by rubennorte** [comment]
You need to configure the `responseType` option. From the README:

```
  // `responseType` indicates the type of data that the server will respond with
  // options are 'arraybuffer', 'blob', 'document', 'json', 'text', 'stream'
  responseType: 'json', // default
```

If you use `text` then `response.data` will be a string.

**Comment by graingert** [comment]
@rubennorte what is 'document'?

**Comment by rubennorte** [comment]
An HTML or XML DOM tree.

**Comment by graingert** [comment]
Like jsdom or what?

**Comment by rubennorte** [comment]
@graingert an instance of [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document). Only valid for the browser.

**Comment by graingert** [comment]
Ah ok. Where's the docs for it?

**Comment by zdila** [comment]
> Ah ok. Where's the docs for it?

@graingert see https://github.com/axios/axios/issues/667#issuecomment-335013993 :-)

**Comment by graingert** [comment]
I mean the axios specific docs, that say it returns a Document

**Comment by goppman** [comment]
Is it possible to parse XML output from a web-service with an Axios Method?

**Comment by goppman** [comment]
I receive this = <anyType xmlns:q1="http://www.w3.org/2001/XMLSchema" xmlns:d1p1="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://tempuri.org/" d1p1:type="q1:string">
[{"ID":"4a22b17b-0390-47a6-9e18-861ac37ab212","MatchExceptionCodeID":27,"ME_Code":"CARD","Confidence":"High","ContributingFactor":"The vendor is Cardinal Health,"}]
</anyType> 

All I need = [{"ID":"4a22b17b-0390-47a6-9e18-861ac37ab212","MatchExceptionCodeID":27,"ME_Code":"CARD","Confidence":"High","ContributingFactor":"The vendor is Cardinal Health,"}]

**Comment by graingert** [comment]
@goppman https://www.npmjs.com/search?q=parse%20xml%20browser

**Comment by goppman** [comment]
@graingert Thank you! I will use this today!  Will let you all know how it goes, Cheers.

**Comment by vikrampariharcodereadr** [comment]
I have updated my code as

`axios.post(apiUrl, qs.stringify(params), {responseType: 'document'});`

And now i can get xml as document object

**Comment by jayarjo** [comment]
@vikrampariharcodereadr for using axios in the browser or in nodejs?

**Comment by vikrampariharcodereadr** [comment]
@jayarjo Hi, I am using in browser.

**Comment by jayarjo** [comment]
In NodeJS it returns the string for `document` response type, so got to use some parser either way.
