### ISSUE TITLE
Method options is sent before request

### ISSUE THREAD

**Issue by israeleriston** [mzabriskie/axios#668]
Hi,
I have a problem, that every call rest in my api the axios sends a call with the options method before, I wonder if this is standard and if you have how to disable this function?

Ps: backend written in python with django, but also tested with flask and also the same situation occurs

Thank you

**Comment by rubennorte** [comment]
It's a normal server behaviour and Axios cannot avoid it. Please take a look at this page to learn more about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
