### ISSUE TITLE
Content-Type: application/x-www-form-urlencoded can be supported?

### ISSUE THREAD

**Issue by ustccjw** [mzabriskie/axios#67]
It seems that application/x-www-form-urlencoded can not be supported. 
when i set Content-Type, it also use JSON.stringify(data)

**Comment by af7** [comment]
Hello, is this supported? 

Our server people require that we send data as "URL Encoded".

**Comment by andyhu** [comment]
Same issue here, how can I use `application/x-www-form-urlencoded` as request `Content-Type`? When I set it manually, the content is still converted into JSON string

**Comment by nickuraltsev** [comment]
Yes. Please see this comment: https://github.com/mzabriskie/axios/issues/350#issuecomment-227270046

**Comment by aboutqx** [comment]
Thanks for your work,but this lib is kind of bad to use in browser.
