### ISSUE TITLE
instance.post sends request method as OPTIONS

### ISSUE THREAD

**Issue by uptownhr** [mzabriskie/axios#673]
```
let request = axios.create({
  baseURL: 'http://bambeecom.docker/api'
})

request.post('/admin/terminations/category/create', {name, description})
      .then(res => {
        commit('add', res.data)
      })
      .catch(err => {

      })
```

This request is being sent with REQUEST_METHOD OPTIONS instead of POST

**Comment by thg303** [comment]
same issue here

**Comment by uptownhr** [comment]
@th303 refer to https://github.com/mzabriskie/axios/issues/668. This is a non issue and related to CORS policy standards on the browser. Browsers will first check to see if CORS is enabled on the server with an OPTION request before moving forward with the actual request.

**Comment by romanko89** [comment]
My problem is that it sends **only** options request, not followed by 'get' or 'post' afterwards, despite server sends 200 response to OPTION request.

**Comment by thg303** [comment]
@romanko89 
make sure server response contains afterward requests properties, specifically check `Access-Control-Allow-Origin: <your host> or *` and `Access-Control-Allow-Methods: post, get, options,...` and don't forget about `Access-Control-Allow-Headers` it should contain all headers which you're about to send in the afterward requests.

**Comment by romanko89** [comment]
@thg303 , thanks I've figured out that was the reason.

**Comment by ndeixonne** [comment]
In the case of Axios, you likely need to authorize headers "Content-Type".
