### ISSUE TITLE
maxRedirects still follows a redirect

### ISSUE THREAD

**Issue by consultwithmike** [mzabriskie/axios#674]
I have a request setup like this:

    return {
        type: GET_CURRENT_USER,
        payload: ax.request({
            url: urlJoin(
                config.portal.url,
                'api/CommonApi/GetCurrentUser'
            ),
            method: 'get',
            maxRedirects: 0
        }).then(res => {
            debugger;
        }).catch(err => {
            debugger;
        })
    };

The response from `GetCurrentUser` looks like this:

    HTTP/1.1 302 Found
    Cache-Control: no-cache
    Pragma: no-cache
    Content-Type: application/json; charset=utf-8
    Expires: -1
    Location: http://localhost:15921/Account/Login?ReturnUrl=%2Fapi%2FCommonApi%2FGetCurrentUser
    Server: Microsoft-IIS/10.0
    X-AspNet-Version: 4.0.30319
    X-SourceFiles: =?UTF-8?B?QzpccmVwb1xiaXRidWNrZXRcanJ5bmxkc1xpbmZsb3doZWFsdGhwb3J0YWxcSW5mbG93SGVhbHRoUG9ydGFsXGFwaVxDb21tb25BcGlcR2V0Q3VycmVudFVzZXI=?=
    X-Powered-By: ASP.NET
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
    Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
    Access-Control-Allow-Origin: http://localhost:8080
    Date: Tue, 31 Jan 2017 18:33:51 GMT
    Content-Length: 61

The next network request is to that URL which then returns a `200`; the problem is that causes that promise to resolve as successful. How do I get this request to fail on a redirect response?

**Comment by amit-coditas** [comment]
i have the same problem with box, i am trying to download a file using their API, it returns the url in the location header that we'd need to redirect the user to.  We tried setting maxRedirects to 0 but it still fails.

**Comment by rubennorte** [comment]
The `maxRedirects` option only works in Node.js (it's specified in the README) because browsers don't allow redirections to be disabled (there's no option for that).

**Comment by rayrutjes** [comment]
I just struggle with this one.
Here is the current check: https://github.com/mzabriskie/axios/blob/188334439f9698c8ddd58697f75e7f0b745c9acc/lib/defaults.js#L16

I wrote a simple test in Jest but it seems XMLHttpRequest is available there :/

I guess my left choice is to enforce the adapter ;)

**Comment by Mechazawa** [comment]
This issue can be resolved for browsers by using the fetch api.

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Supplying_request_options
