### ISSUE TITLE
Get request not passing authorization header

### ISSUE THREAD

**Issue by tsongas** [mzabriskie/axios#679]
I'm trying to pass a token like this

axios.get('url', {
  headers: { Authorization: localStorage.getItem('token') }
})

however I don't see the token being added in Chrome's request headers, and the server never receives them even though it does work from Postman:

Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8,mt;q=0.6
Access-Control-Request-Headers:authorization
Access-Control-Request-Method:GET
Connection:keep-alive
Host:foo
Origin:http://bar
Referer:http://baz
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

Any ideas? Also I'm curious if the header value has to be named "Authorization" or can I call it anything? In the response headers I see the following:

Access-Control-Allow-Headers:User-Agent,X-HTTP-Method-Override,Content-Type,Authorization,Accept,Referrer,X-Requested-With,X-CSRF-Token,Origin

**Comment by tsongas** [comment]
Also tried this and it didn't work either:

axios.defaults.baseURL = ROOT_URL;
axios.defaults.headers.common['Authorization'] = localStorage.getItem('token');
axios.get('url')

**Comment by tsongas** [comment]
I'm having the same problem with the fetch API, where I'm getting the error "Response for preflight has invalid HTTP status code 401" so I think IIS is doing something to block my requests before they are even made. Will investigate further....

**Comment by beckler** [comment]
I'm taking a guess that you're making a cross-origin request (aka CORS) by the presence of the `Origin` header?
Make sure your server is returning a `Access-Control-Request-Origin` header that would match the referrer, and then in your config set `withCredentials: true,`

Here's the relevant text from the README
```
  // `withCredentials` indicates whether or not cross-site Access-Control requests
  // should be made using credentials
  withCredentials: false, // default
```

**Comment by tsongas** [comment]
It turned out to be the browser's OPTIONS request, which apparently gets made before any other type of request, that was borking because it didn't include the required auth header. So, I tweaked my API to not require auth credentials for OPTIONS requests, now that I know they exist. Derp.

**Comment by beckler** [comment]
@tsongas Yeah, an OPTIONS request is usually sent before any other request when using CORS. Glad you figured it out! 👍

**Comment by chrise86** [comment]
I'm having this issue using an instance of axios. When setting the headers, logging the object shows the headers on the instance, but the request is made without the `Authorization` header - all other headers work but the authorization is somehow stripped. This doesn't happen when setting the defaults directly on `axios`.

**Comment by beckler** [comment]
@chrise86 if you're making a CORS request and you need to pass authorization, be sure to add `withCredentials: true` to your request config.

**Comment by MINOSai** [comment]
```
axios({
          method: "post",
          url: "http://127.0.0.1:8000/api/create/",
          withCredentials: true,
          headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Credentials":"true"
          },
          auth: {
            username: "username",
            password: "password"
          },
          data: {data1: 10, data2: 20}
        });
```

I'm running a Django REST framework for my backend and Vue.JS for my frontend... I get same type of issue when I make this request.
What could be the issue?
Or am I doing it wrong?
Or maybe is it like I need to ask the guy who wrote the backend to change the code such that it wouldn't accept any auth tokens when getting a OPTIONS request at that endpoint?

**Comment by beckler** [comment]
There's no need to pass those headers to the server, the **server** should be returning those headers to let you know that CORS is supported. You might want to look into middle-ware packages for Django like this: https://github.com/OttoYiu/django-cors-headers

**Comment by MINOSai** [comment]
Thanks !!

**Comment by BigChief45** [comment]
@beckler I am experiencing the exact same issue as @MINOSai , yet I can make a perfect successful CORS request using a Python client. I don't really understand why I have to add additional configuration to the existing Django REST Framework one...

**Comment by MINOSai** [comment]
My guess is that Django REST framework by default doesn't have support for CORS.

**Comment by AlexDel** [comment]
DRF doesn't support CORS out of the box. You have to add CORS features by yourself
https://www.django-rest-framework.org/topics/ajax-csrf-cors/
