### ISSUE TITLE
Option to enable sync XHR request

### ISSUE THREAD

**Issue by pracucci** [mzabriskie/axios#681]
I would like to track some analytics on page unload. When supported, I do use the [`sendBeacon()` API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon), otherwise I do finger cross and call `axios.post()` on `window.onunload` but it basically never works.

The only trick I'm aware of is to send the XHR request on `window.onunload` setting the sync flag, as explained [here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests#Adapting_Sync_XHR_usecases_to_the_Beacon_API). I know it's not elegant at all, but in our specific use case we do need a reliable tracking. Adding such option to axios would help us to use axios for this as well.

What's your take?

**Comment by jcready** [comment]
Maybe try using `window.onbeforeunload` Since this event happens in the tick before the browser actually starts unloading compared to `window.onunload` event which is triggered synchronously before the browser starts unloading.

**Comment by rubennorte** [comment]
I'm sorry but this won't be implemented in Axios as sync requests are deprecated in most browsers and unavailable in Node.js.

**Comment by WinWinHost** [comment]
Just wanted to comment that if a programmer really has to line up calls in a synchronous fashion, they might want to try to use something like async.waterfall. Or a fiber based system, maybe.

**Comment by pracucci** [comment]
It doesn't cover the use case I had when I originally opened this issue. The use case was to issue a tracking URL call on window.unload improving it's likelihood the URL was tracked. The most reliable way I found was to set the sync option on the XHR request.

**Comment by danemacaulay** [comment]
I'd forgotten about the beacon api, but this is exactly whats needed: see discussion here:
https://stackoverflow.com/questions/6162188/javascript-browsers-window-close-send-an-ajax-request-or-run-a-script-on-win/47108290#47108290

and beacon api here:
https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API/Using_the_Beacon_API

**Comment by iapYang** [comment]
> I'm sorry but this won't be implemented in Axios as sync requests are deprecated in most browsers and unavailable in Node.js.
> 
> If you absolutely need this you should implement it using the raw XMLHttpRequest object in supported browsers.

I agree，even jquery donnot recommend aysnc in ajax.
