### ISSUE TITLE
Has function(response) been retired?

### ISSUE THREAD

**Issue by filtration** [mzabriskie/axios#682]
I have an request to get some data and add it to a variable, 

When I use:

```
.then(function(response) {
    this.persons = response.data;
});
```

It does not assign `response.data` to `this.persons` but when I do the following:

`.then(response => this.persons = response.data);`

It assigns it fine to use. Please see the js fiddle:

https://jsfiddle.net/trhhtyxr/2/

**Comment by rubennorte** [comment]
This isn't an Axios issue but a semantics different between arrow functions and regular functions.

With arrow functions `this` is the instance of the method where you call Axios. With regular functions, as you wrote it, `this` can be the globals object or `undefined` depending on you're in sloopy or in strict mode.
