### ISSUE TITLE
Duplicate Exports when using Rollup

### ISSUE THREAD

**Issue by michaelryancaputo** [mzabriskie/axios#683]
I see that recently there has been a change made to support TypeScript exporting default. However this is causing this error when using Rollup as a build tool:

```🚨   Duplicate export 'default'
node_modules/axios/lib/axios.js (72:22)
70: export default axios_1;
71: export { axios_1 as __moduleExports };
72: export { default_1 as default };
                          ^
73: axios_1.default = default_1;
```

**Comment by lukasjuhas** [comment]
Hey @michaelryancaputo,

I had similar problem, I solved it by doing:

`import axios from 'axios/dist/axios';`

Maybe that helps!

**Comment by imelismith** [comment]
Thanks @lukasjuhas that helped, build no longer throwing!

**Comment by iamgoodbytes** [comment]
Thanks @lukasjuhas - I had the same issue!

**Comment by michaelryancaputo** [comment]
I'm quite sure this is how I was calling Axios. It looks like they've changed the way the module is being exported since my initial issue: https://github.com/mzabriskie/axios/blob/master/lib/axios.js#L49-L52
