### ISSUE TITLE
undefined instance with webpack 2.2.1

### ISSUE THREAD

**Issue by khoanguyen96** [mzabriskie/axios#687]
I normally create a instance with this piece of code:
```
import axios from 'axios'

let http = axios.create({
  baseURL: process.env.BASE_URL
})

export default http
```

However, it doesn't work with Webpack 2..
![image](https://cloud.githubusercontent.com/assets/7454142/22664134/1e6c9fd8-ec64-11e6-8995-fa8ab97a285c.png)

**Comment by rubennorte** [comment]
I haven't tested Axios with Webpack 2. It could be an issue. What is you're target in Webpack, browser or node?

**Comment by khoanguyen96** [comment]
I'm using it with vue-loader, so browser :)

**Comment by khoanguyen96** [comment]
I believe it was due to a configuration error on my part.
