### ISSUE TITLE
User-Agent overriden in Node

### ISSUE THREAD

**Issue by terinjokes** [mzabriskie/axios#69]
When using axios in NodeJS, a custom set User-Agent would be overriden by Axios's default, instead of being applied if a User-Agent isn't already set.

https://github.com/mzabriskie/axios/blob/1629a026da17a1e1d8999a02f3fe6b6b60aaac9c/lib/adapters/http.js#L28-L29

**Comment by ralphholzmann** [comment]
Hi friends! Anyway we could get this fix tagged in npm? We need this fix over at Vine, and I would rather not have to peg to a git commit in my package.json.

Thanks :)

**Comment by pahund** [comment]
+1, I could really use this fix in my project

**Comment by nerdgore** [comment]
+1 We could really use this fix but don't want to (read: can't) fetch directly from github.

**Comment by mzabriskie** [comment]
I just released 0.6.0 which includes a fix for this.

**Comment by ralphholzmann** [comment]
@mzabriskie thanks so much!

**Comment by mrozbarry** [comment]
@mzabriskie this might still be a problem when setting default headers in nodejs.

For my unit tests, I have the following config:

```
import axios from "axios"

const instance = axios.create()
instance.defaults.headers.common["User-Agent"] = "unit-test"
global.axios = instance
```

The intent is that I don't want to modify any of my code to conditionally set the user agent.

When I look at my development server, I see the following headers:

```json
{ accept: 'application/json, text/plain, */*',
  'user-agent': 'axios/0.16.2',
  host: 'localhost:3000',
  connection: 'close' }
```

**Comment by user3587412** [comment]
@mrozbarry 

axios.interceptors.request.use(config => {
  config.headers['User-Agent'] = 'unit-test';
  return config;
});

  return config;
});
