### ISSUE TITLE
intercept 401 responses and redirect

### ISSUE THREAD

**Issue by refaelos** [mzabriskie/axios#690]
Is it possible to intercept all responses and see if I get 401 and redirect to login page?

In React: Is it the appropriate way to go?

**Comment by grekier** [comment]
I'd like to know the answer to this as well.

**Comment by refaelos** [comment]
@rlambertsen looks good. Thanks!

**Comment by sverhagen** [comment]
Thanks for the code example. Just curious, are you able to use this without the user getting a dialog in their face, first, asking for user name and password ("Authentication Required")?

**Comment by webhive** [comment]
Got same issue. This dialog appear before interceptor and interceptor called after this dialog closed (no matter how cancelled or submitted).

**Comment by var23rav** [comment]
Hi, The api gives me **Status Code:401 UNAUTHORIZED** error.
But am not able to get the _response code_ using vue-axios interceptor, am getting **undefined** for **error.response**.

Axios: axios@0.17.1, vue-axios@1.2.2

**Comment by NanoDev777** [comment]
@rlambertsen  I followed your example since I am making a login using laravel with the jwt library to generate my token and vue.js ahead, but I have problems in the interceptor, after updating my new token the request should continue however I still receive the error : Uncaught (in promise) Error: Request failed with status code 401, in my console

**Comment by rlambertsen** [comment]
@NanoDev777 Can you show me the code you are using? Also make sure you are updating the token or using the new one in the next request like so 

`originalRequest.headers['Authorization'] = 'Bearer ' + store.state.token // new header new token`

**Comment by Kesavaraja** [comment]
@rlambertsen sorry to ask.  i have a doubt that what if " return Vue.axios(originalRequest) " returns a 400 bad request error and how to handle it.

**Comment by notflip** [comment]
@rlambertsen what does the post to users/token do?

**Comment by james-poulose** [comment]
Just curious -  If you use `window.location`, won't it reload the page and all state will be lost?

**Comment by adshin21** [comment]
@james-poulose  I'm also wondering about it.
Any ideas I want to redirect to a specific page

**Comment by rlambertsen** [comment]
@james-poulose Yes window.location causes the window to reload; 
@nsarvar Each request is handled individually and if you just wrote some code to retry them it would do just that. Look at this line and see how I save the request above so it can be retried
`return Vue.axios(originalRequest) // retry the request that errored out`
set a condition and test for it;
@notflip the post clears the users token in the db so they can set a new on the retry;
@adshin21 you can redirect anywhere you want at anytime in the code snippet above. Set a condition and test for it, if you want to stay inside vue use vue-router to handle it or window.location to go outside your vue app

**Comment by adshin21** [comment]
@james-poulose  Thank you for your quick response.
As I'm using request interceptors ( in react ) and inside that checking for the expiry of the token, if the access token is expired calling the token refresh method and setting the new tokens but if the refresh is also expired then I want to redirect from there. In short, I want to redirect from the request interceptors without using window.location.href or window.reload.
Thank you.

**Comment by rlambertsen** [comment]
@james-poulose you want to use whatever React is using for routing. In Vue.js you can redirect inside the app not using window.location by using vue-router. I assume React-router works the same way by internally routing the user to any page in the app. 

Vue-router code inside the main.js where the axios global code lives;
`router.push('/search')`

I found a neat article that actually explains what you want in React apps

https://bilot.group/articles/using-react-router-inside-axios-interceptors/

**Comment by rlambertsen** [comment]
@adshin21 you want to use whatever React is using for routing. In Vue.js you can redirect inside the app not using window.location by using vue-router. I assume React-router works the same way by internally routing the user to any page in the app. 

Vue-router code inside the main.js where the axios global code lives;
`router.push('/search')`

I found a neat article that actually explains what you want in React apps

https://bilot.group/articles/using-react-router-inside-axios-interceptors/
