### ISSUE TITLE
Pass locale in get request

### ISSUE THREAD

**Issue by ninahaack** [mzabriskie/axios#692]
Hello, I'm new using axios and I would like to pass the user locale in the axios get request. Can I do that? It's better to do that in the header or as a parameter?

I tried to do this, but didn't work. Sorry for anything.

```
axios
  .get(url, { headers: { 'locale': locale } })
  .then(response => (
    dispatch({
      type: actionType,
      payload: response.data
    })
  ))
```

**Comment by rubennorte** [comment]
You need to know what are the requirements of the API you're accessing. Some of them use a custom headers, some of them use parameters, etc. The most common thing is to use the `Accept-Language` header (which is automatically sent by the browser).

I'm closing the issue as it isn't an Axios-related problem.

**Comment by ninahaack** [comment]
Ok, thank you very much for the answer!
