### ISSUE TITLE
Shrink forEach and extends from utils

### ISSUE THREAD

**Issue by anaibol** [mzabriskie/axios#694]
Hi! I think we could save some valuable kbs removing these functions that are pretty common on today browsers. The developer should responsible of adding polyfills.
`extends` could be removed in favor of using Object.assign, spread operator, right?

**Comment by rubennorte** [comment]
At the moment Axios supports IE8+ without polyfills (but Promise), so doing that isn't an option for now. We could consider dropping support for browsers not supporting ES5 but it needs some discussion and work within the contributors.
