### ISSUE TITLE
I have faced some problem with using axios post request

### ISSUE THREAD

**Issue by PeterLEE159** [mzabriskie/axios#698]
Hi, 
my web server is php, laravel.
and client side is javascript, react native.

I have tried using axios connecting php as like

const instance =  axios.create({
        baseURL: url,
});
if(authToken.length != 0) instance.defaults.headers.common['Authorization'] = authToken;
instance.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

instance.post(url, {
     ...body
})
.then(response => console.log(response)
.catch(response => console.log(response);
 
but it reponse like  

Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version

**Comment by rubennorte** [comment]
That is an issue in your server and not in axios itself. Please review your code.

**Comment by Sarmed-armis** [comment]
i have same issue how i can solve it??
