### ISSUE TITLE
axios.post

### ISSUE THREAD

**Issue by vnshah** [mzabriskie/axios#700]
When I make an `axios.post("test.php",{name:"abc"})` request on my local dev server, I can access the data using `$_POST` in `test.php` file but I can't do the same on my live server. I haven't made any changes in the headers in any of the server.

Can anyone think of what could it be? Tried and tested lot of things but no joy.

Thanks

**Comment by Martodox** [comment]
If it works on one env and doesn't in the other then it is most likely an issue with your setup, not axios library itself.

**Comment by vnshah** [comment]
@Martodox Thanks for your reply. All I have is a simple index.php page with the axios.post code which posts data to test.php page and test.php page dumps the $_POST out but for some reason it's empty! Would you know why? May be it's a very broad topic but I tried looking for all the suspects but nothing works. I don't know if you can help me with this? Thanks :)

**Comment by realtebo** [comment]
Same problem here: 

```
 Axios({
          method : 'post',
          url    : 'http://my.server.net/index.php?r=wwwServices/api/setProductCommonCode',
          data   : {
            'product_code' : product_code,
            'common_code' : common_code,
          }
      })
```

I see that in Chrome DevExt

```
Request URL:http://test1.phonix.it/index.php?r=wwwServices/api/setProductCommonCode
Request Method:OPTIONS
```

Also my server see an empty $_POST

**Comment by Martodox** [comment]
What I meant by my first post was that this is not a place for such problems :D

 @vnshah, @realtebo, Have you checked CORS settings on your server?

**Comment by vnshah** [comment]
Yes. Its not cross domain. Still I have added access control header in the
script but no joy.

**Comment by realtebo** [comment]
I added to axios call this header

    headers: { 
            'Content-Type': 'application/x-www-form-urlencoded',
          },

and used this into server php response function

       header('Cache-Control: no-cache, must-revalidate');
        header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
        header('Content-type: application/json');
        header('Access-Control-Allow-Headers: Content-Type');
        header("Access-Control-Allow-Origin: *");

actually it's seems working

**Comment by maullerz** [comment]
Same issue for me, thx @realtebo for solution 👍

**Comment by acmeid** [comment]
Is there any way to configure Axios only？

**Comment by realtebo** [comment]
@acmeid: what do you mean? If you want to do configuration tricks only on client-side actually I'm not able to tell you that it is ever possibile. this is good, otherwise tweaking our code we can do every XS requests to every not-allowed sites... 

If (I think so) I misunderstood, please explain me better your question / intents...

**Comment by acmeid** [comment]
@realtebo Yes, that's what I mean. When using jquery, even if the server without configuration 'header', it's OK. I think axios is the same.

**Comment by rubennorte** [comment]
Closing this as it's not an issue in axios.

**Comment by funway** [comment]
in your php file, use `$jsonData = json_decode(trim(file_get_contents('php://input')), true)`

**Comment by milmaj** [comment]
the solution of @realtebo also worked for me, but there must be a solution doing `data: {key:value}`

**Comment by bscoder2** [comment]
Funway hit the nail on the head.
