### ISSUE TITLE
Error modifying adapter to http

### ISSUE THREAD

**Issue by jhoanjago** [mzabriskie/axios#701]
I am using axios 0.15.3, for an application with ReactJS. Axios uses [XmlHttprequest](http://www.w3schools.com/xml/dom_http.asp) for the client. When I make a request from the browser I only deliver success or error (404 or 200), and I need to know the specific code that the server returns.

I need to implement it from the interceptors so that in each request and validate the information. Axios in its configuration allows to change the Adapter like this:

> import adapter from 'axios/lib/adapters/http';
> axiosInstance.defaults.adapter = adapter;

or

> axiosInstance.defaults.adapter = require('axios/lib/adapters/http');

But when I print this one
> console.log(adapter);

or

> console.log(require('axios/lib/adapters/http'));

In console it appears that I am returning the "adapterxhr" and I need is "adapterhttp". When I run this with NodeJS if it works, but I need this to be used from the client (browser) and get it from the axios interceptors since it is all the requests that I should validate the code.

**Comment by flushentitypacket** [comment]
I'm having the same problem. I dug into it a little and still couldn't figure out what was going wrong.

**Comment by rubennorte** [comment]
The http adapter is not available in the browser and all references to it are replaced by references to the xhr adapter by webpack. That is the expected behaviour.
