### ISSUE TITLE
304 status code being handled as an error

### ISSUE THREAD

**Issue by nowarkdev** [mzabriskie/axios#703]
Hi,

We've recently encountered a scenario where 304 requests are being handled as errors. Is this the expected behaviour?
In the Axios' README file it mentions Axios as being heavily inspired by the $http service provided in Angular. However they are not handling 304 as errors at least not any more as you can see it here https://github.com/angular/angular.js/issues/5384.

Thanks,
Tony Nalesso & Ravin Patel

**Comment by Bnaya** [comment]
Read about the validateStatus handler that you can pass
https://github.com/mzabriskie/axios#handling-errors
