### ISSUE TITLE
Relative path with context path

### ISSUE THREAD

**Issue by skrajath** [mzabriskie/axios#704]
I am using the relative path 
```
axios.get('/customers')
    .then(response => {
	.......
    })
```

It takes the baseUrl as ex: `localhost:8080 `and calls `localhost:8080/customer`
Problem here is, the context path is not considered, the base URL should be, `localhost:8080/myapp` and the complete URL would be like `localhost:8080/myapp/customers`.
How does the basepath retrieved? Should I add any configuration for this?

**Comment by rubennorte** [comment]
This is the expected behaviour. In the browser relative paths are to the directory so:

```
Current URL: http://localhost/myapp
Relative URL: /customers
Absolute URL: http://localhost/customers

Current URL: http://localhost/myapp/
Relative URL: /customers
Absolute URL: http://localhost/myapp/customers
```

Mind the final slash in the current URL.

This is how relative URLs work in the browser. If you want to modify this behaviour you can manually set the `baseUrl` in axios.

**Comment by clool** [comment]
I think there is a typo in your second example. Should it be:
```
Current URL: http://localhost/myapp/
Relative URL: customers //**no slash here**
Absolute URL: http://localhost/myapp/customers

```
