### ISSUE TITLE
How to add browser's http-only cookies to a request?

### ISSUE THREAD

**Issue by williamgranli** [mzabriskie/axios#705]
I'm getting the server's refresh and access token as http-only cookies which means I can't access them with document.cookie or anywhere from javascript. 

Is there a way to tell axios to automatically include these cookies in the header when sending a request to the server?

Thanks.

**Comment by rubennorte** [comment]
If the request is done to the domain configured in the cookie (or exactly the same domain if not configured), the cookie is automatically sent by the browser. Otherwise you there's no way to use it.
