### ISSUE TITLE
Passing Variables in urls

### ISSUE THREAD

**Issue by nitish24p** [mzabriskie/axios#706]
I am unable to pass variables in a get url unless, i hard concat the url string
```javascript
const url = '/post/:id';
export const getPost = (id) => {
  return axios.get(url);
}

```
is there a way for me to pass the id into the string without concatenating the strings
right now i have to set the url as
```javascript
 `/post/${id}`
```

**Comment by rubennorte** [comment]
URL parameters aren't supported and I doubt they'll ever be given the easy it is with template strings.

**Comment by rmariuzzo** [comment]
It would be nice if axios could support url params. That way we don't need to think on escaping values.

**Comment by Doogiemuc** [comment]
For a random number this is fine.  But keep in mind that you MUST encode url parameters!  Especially when the value comes from any user input (SQL injection!)

**Comment by Kepro** [comment]
@Doogiemuc SQL Injection should be handled by the backend, not by UI...

**Comment by hbgl** [comment]
I am also in favor of a URL path parameter feature. From my point of view at least two good reasons for having the feature:

1. It's concise. You don't have to repeat `encodeURIComponent` everywhere in your code.
2. It's harder to forget to encode the parameters. Forgetting to encode the path parameter is a security issue because it allows to inject arbitrary sub-paths and query parameters based on user input. If nothing else it is a source of bugs.

**Comment by lkng** [comment]
I am using an interceptor to add this feature myself.

**Comment by hckhanh** [comment]
I think it's a nice feature to have for `axios`.

**Comment by jesbeerJ** [comment]
> Thought I would post an example regarding template strings.
> The main idea is that axios.get(url) will not work if in function parameter.
> And that axios.get(`${url}`) for function parameters will work.
> Also gathering the function parameter as a new string constant will work.
> 
> Hopefully this will help others.
> I believe it is inline with the discussion of this issue.
> 
> ### Will work
> ```js
> const randomId = 128398723
> const url = `/post/${randomId}`;
> getPost(url)
> export const getPost = (funcParamURL) => {
>   return axios.get(`${funcParamURL}`);
> }
> ```
> 
> ```js
> const randomId = 128398723
> const url = `/post/${randomId}`;
> getPost(url)
> export const makeRequest = (funcParamURL) => {
>   const url = funcParamURL;
>   return axios.get(newUrl);
> }
> ```
> 
> ### Will not work
> ```js
> const randomId = 128398723
> const url = `/post/${randomId}`;
> getPost(url)
> export const getPost = (funcParamURL) => {
>   return axios.get(funcParamURL);
> }
> ```

its does not work for me

**Comment by MichaelDimmitt** [comment]
@jesbeerJ, I updated the comment, there was a typo in the second "will work case"
But I do not work extensively with Axios at the moment. That comment was one year ago. 👍
```javascript
const randomId = 128398723
const url = `/post/${randomId}`;
getPost(url)
export const getPost = (funcParamURL) => {
  return axios.get(`${funcParamURL}`);
}

const randomId = 128398723
const url = `/post/${randomId}`;
getPost(url)
export const makeRequest = (funcParamURL) => {
  const newUrl = funcParamURL;
  return axios.get(newUrl);
}
```

**Comment by Mohammed-Q96** [comment]
> @jesbeerJ, I updated the comment, there was a typo in the second "will work case"
> But I do not work extensively with Axios at the moment. That comment was one year ago. 
> 
> ```js
> const randomId = 128398723
> const url = `/post/${randomId}`;
> getPost(url)
> export const getPost = (funcParamURL) => {
>   return axios.get(`${funcParamURL}`);
> }
> 
> const randomId = 128398723
> const url = `/post/${randomId}`;
> getPost(url)
> export const makeRequest = (funcParamURL) => {
>   const newUrl = funcParamURL;
>   return axios.get(newUrl);
> }
> ```

May I ask what is the method? and the way you use `ti, it seems  it is not in axios API 
```js
getPost(url)
```

**Comment by GrahamLea** [comment]
I was disappointed to find Axios doesn't/won't support URL templates, considering it was recommended to me as a replacement for vue-resource which does support them.

If you're looking for a way to achieve a similar functionality while centralising your urls, I put a possible solution on SO: https://stackoverflow.com/a/60481338/243104

**Comment by thib3113** [comment]
Hum, why didn't you use an interceptor to do this ?

Something like : 
```js
//create your instance
const instanceAxios = axios.create({
  baseUrl: 'http://localhost:3001'
]);

instanceAxios.interceptors.request.use((config) => {
    const currentUrl = new URL(config.url, config.baseURL);
    // parse pathName to implement variables
    Object.entries(config.urlParams).forEach(([
        k,
        v,
    ]) => {
        currentUrl.pathname = currentUrl.pathname.replace(`:${k}`, encodeURIComponent(v));
    });

    const authPart = currentUrl.username && currentUrl.password ? `${currentUrl.username}:${currentUrl.password}` : '';
    return {
        ...config,
        baseURL: `${currentUrl.protocol}//${authPart}${currentUrl.host}`,
        url: currentUrl.pathname,
    };
});


// use like : 
instanceAxios.get('/issues/:uuid', {
   urlParams : {
       uuid: '123456789
   }
})
```

It seems a lot easier than using a a function each times to replace the url you pass to axios ...

---

For typescript users, you will need to add this, in one of your .d.ts
```ts
declare module 'axios' {
    interface AxiosRequestConfig {
        urlParams?: Record<string, string>;
    }
}
```

**Comment by GrahamLea** [comment]
That's the type of functionality I'd like to see built into Axios, but it's a bit of overkill for me when the alternative is a one-line function like:

    export var fetchDateUrl = (date) => `/fetch/${date}`;

If someone's going to go ahead with the above approach, I'd suggest not using the name `urlParams`, as URL parameters are already a thing and this is different. They're called path variables in some tools.

**Comment by thib3113** [comment]
@GrahamLea and need to rewrite your function with each rest endpoint, and/or call you function on each axios request using it :/ ... I really prefer a central solutions, needed to be implemented one time only . 

About the urlParams, are you talking about `params` ? That populate the query string ? 

( The name is just a name, can be changed easily )

**Comment by rmariuzzo** [comment]
I created a small library with no deps that build URLs with params and query string. I also added TS support for typing params and query strings. The lib is [Ruty](https://github.com/rmariuzzo/ruty). It's in an early stage as it doesn't encode params or query string _yet_.

I will still use Axios or any other similar library, and Ruty.
