### ISSUE TITLE
How to send get request with multiple same param?

### ISSUE THREAD

**Issue by g0ld3lux** [mzabriskie/axios#709]
i have this method on my vue js component..

```
getAbandonedCart() {

                let start_date = moment().subtract(6,'d').format('YYYY-MM-DD')
                let end_date = moment().format('YYYY-MM-DD')
                let measurement = 'value'
                let where1 = JSON.stringify([["Campaign Name","=", this.campaignID]])
                let where2 = JSON.stringify([["$attributed_message","=", 'Abandonded Cart: Email 1']])

                axios.get('/api/v1/metric/' + this.metrics[3].id + '/export?start_date=' + start_date + '&end_date=' + end_date + '&measurement=' + measurement + '&where=' + where1 + '&where=' + where2).then(({data}) => {

                    for (let i = 0; i < data.results[0].data.length; i++) {
                       this.series[4]['data'].push(data.results[0].data[i].values[0])
                    }

                });
            },
```
when i check my query string parameters it like this
```
start_date:2017-02-09
end_date:2017-02-15
measurement:value
where:[["Campaign Name","=",null]]
where:[["$attributed_message","=","Abandonded Cart: Email 1"]
```
my first code sucks , but works, i wanna try to use the params object

but i cant do it properly ,
this code only use the 2nd where statement that i have...
```
 params: {
                start_date: moment().subtract(6,'d').format('YYYY-MM-DD'),
                end_date: moment().format('YYYY-MM-DD'),
                measurement: 'unique',
                where: JSON.stringify([["Campaign Name","=", this.campaignName]])
                where: JSON.stringify([["$attributed_message","=",'Abandonded Cart: Email 1']])
                }
```

can anyone help me with this

**Comment by TimonLukas** [comment]
This is not at all recommended (and not possible in JS). While it is theoretically possible to have the same key multiple times in a request, it is not at all recommended, and I wouldn't think that many servers even properly support this kind of behaviour.

Instead it seems like you are deliberately passing an array- why don't you send the second string in the same array?

```javascript
params: {
    start_date: moment().subtract(6, 'd').format('YYYY-MM-DD'),
    end_date: moment().format('YYYY-MM-DD'),
    measurement: 'unique',
    where: JSON.stringify([["Campaign Name", "=", this.campaignName], ["$attributed_message", "=", 'Abandoned Cart: Email 1']])
}
```

But either way, this is not an issue with Axios and should be closed.

**Comment by g0ld3lux** [comment]
but the api we are using uses this kind of method...

it allows them to receive multiple params of same name...

i already tried that method , but their server is only parsing the last array you send... 
seems like there is no solution to this?
:(

**Comment by g0ld3lux** [comment]
if i did what you recommend
yes it would send the params like this
```
start_date:2017-02-10
end_date:2017-02-16
measurement:unique
where:[["Campaign Name","=","feb value 1"],["$attributed_message","=","Abandoned Cart: Email 1"]]
```
but their server is giving me 500 Internal Server Error

**Comment by rubennorte** [comment]
You can use an array parameter, but it'll be sent as "where[]=..." instead of as "where=...".

```javascript
params: {
    start_date: moment().subtract(6, 'd').format('YYYY-MM-DD'),
    end_date: moment().format('YYYY-MM-DD'),
    measurement: 'unique',
    where: [
      JSON.stringify(["Campaign Name", "=", this.campaignName]),
      JSON.stringify(["$attributed_message", "=", 'Abandoned Cart: Email 1'])
    ]
}
```

**Comment by FranckFreiburger** [comment]
Just note that Google Maps API use multiple same param to set multiple map markers (https://developers.google.com/maps/documentation/static-maps/intro#Markers)

**Comment by eino-makitalo** [comment]
I agree even that this is not recommended there are some APIs using this style of repetitive parameters and now have to tackle this different way. (not show stopper but annoying)

**Comment by wellyal** [comment]
Seems like a lot of apis do things like [this](https://github.com/mzabriskie/axios/issues/777).

**Comment by supra28** [comment]
@rubennorte I did this:

```
 return axios.get(url, {
    params: {
      ...params
    },
    paramsSerializer: function(params) {
      return qs.stringify(params, { indices: false })
    }
  })
```

**Comment by leonlibraries** [comment]
@supra28 it works!

**Comment by jarnail1004** [comment]
@supra28 , can you please look whats issue in below code: 

`axios.get('https://apisite.com//api/Stock/GetStockItems',
      
        { 
            keyWord: 5055967419551,
            locationId: '',
            entriesPerPage: 10000,
            pageNumber: 1,
            excludeComposites: true,

            headers: 
            { Authorization: 'XXXXX-XXX-XXX-XXXX-XXXXX' 
            }
        }).then((response) => { console.log(response.data); });`

Working on PHP: 
`$url = 'https://apisite.com/api/Stock/GetStockItems?keyWord=6666777788889&locationId=""&entriesPerPage=10000&pageNumber=1&excludeComposites=true';`

passing paramerters from AXIOS in react-native app.

**Comment by supra28** [comment]
@jarnail1004  This should work:

```
 axios.get('https://apisite.com//api/Stock/GetStockItems', {
    params: {
        keyWord: 5055967419551,
        locationId: '',
        entriesPerPage: 10000,
        pageNumber: 1,
        excludeComposites: true,
    },
    headers: {
      Authorization: 'XXXXX-XXX-XXX-XXXX-XXXXX' 
    }
  })
```

**Comment by jarnail1004** [comment]
@supra28, I achieved that and how it possible pass value from first-api-call to 2nd-api-call. 

> componentWillMount() {
>       axios.post('https://APISITE.COM/api/Auth/AuthorizeByApplication?applicationId=b72fc47a-ef82-4cb3-8179-2113f09c50ff&applicationSecret=e727f554-7d27-4fd2-bcaf-dad3e0079821&token=cd431b31abd667bbb1e947be42077e9d')
>       .then((response) => { console.log(response.data); });
>         
>       axios.get('https://APISITE.COM//api/Stock/GetStockItems',   
>       { 
>           params: {
>               keyWord: 5055967419551,
>               locationId: '',
>               entriesPerPage: 100000,
>               pageNumber: 1,
>               excludeComposites: true,
>               //add other params
>           },
>           headers: {
>              Authorization: '0f32ae0d-XXXX-XXXX-8367-WWWW' 
>           }
>       })//.then((response) => this.setState({ products: response.data }));
>       .then((stockItems) => {
>            this.setState({ products: stockItems.data });
>      axios.get('https://APISITE.COM//api/Stock/GetStockLevel', {  
>             
>                 params: { stockItemId: '2f80b45c-85ff-449b-9ad6-ffcc4bb640dd'
>                     //stockItemId: stockItems.data.StockItemId,
>                 },
>                        headers: {
>                         Authorization: '0f32ae0d-XXXX-XXXX-8367-WWWW'
>                        }       
>             }).then((response) => this.setState({ racks: response.data }));
>     });
> }

Please guide if you can have look of such things.

**Comment by themnd** [comment]
@rubennorte the library should allow to perform a request with the desired parameters, using the same parameter multiple times is perfectly legit and it does not indicate any bad behaviour on the server part (for example also solr use multiple parameters with the same name, see fq https://lucene.apache.org/solr/guide/6_6/common-query-parameters.html).

Do you think to reopen this ticket?

**Comment by jarnail1004** [comment]
I have sorted out and will the post the answer too. Close this

**Comment by bartoszhernas** [comment]
This is a normal case, a lot of API expect `param=1&param=2` instead of `param[]=1&param[]=2`.

Was this already resolved? Do anyone have suggestion how to fetch this kind of URL using axios?

**Comment by themnd** [comment]
This is what I've used:

```
    var apiParamsSerializer = function (params) {
      var parts = [];
      for (var key in params) {
        if (params.hasOwnProperty(key)) {
          var obj = params[key];
          if ($.isArray(obj)) {
            for (var idx = 0; idx < obj.length; idx++) {
              parts.push(key + '=' + encodeURIComponent(obj[idx]));
            }
          } else {
            parts.push(key + '=' + encodeURIComponent(obj));
          }
        }
      }
      return parts.join('&');
    };


      return axios({
        method: 'get',
        url: url,
        headers: headers,
        params: opts.params,

        // to handle multiple parameters with the same name
        paramsSerializer: apiParamsSerializer
      });
```

**Comment by dydokamil** [comment]
If you wish to get something like this `filter=name&filter=date` you would do `paramsSerializer: params => qs.stringify(params, { arrayFormat: 'repeat' })`. Don't forget to install `qs`.
