### ISSUE TITLE
Response headers?

### ISSUE THREAD

**Issue by iam4x** [mzabriskie/axios#71]
Hey,

I can't retrieve all the response headers, it gives me only:

```
headers: {
  cache-control: "max-age=0, private, must-revalidate"
  content-type: "application/json; charset=utf-8"
}
```

**Comment by iam4x** [comment]
My bad, you need to set `Access-Control-Expose-Headers` if you use CORS.

**Comment by tp** [comment]
@iam4x Did just adding the `Access-Control-Expose-Header` header solve this for you?

From this response headers I only get the `Content-Type` from `response.headers` (with axios 0.7.0):

```
Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,X-XS-Test
Access-Control-Allow-Methods: GET,PUT,PATCH,POST,DELETE
Access-Control-Allow-Origin: *
Access-Control-Expose-Header: PROTOCOL,X-Powered-By,Etag
Connection: keep-alive
Content-Length: 3
Content-Type: text/plain; charset=utf-8
Date: Mon, 05 Oct 2015 07:52:51 GMT
Etag: W/"3-dSgDWpPuac7bHb3bLwv8yA"
X-Powered-By: Express
```

Gives me just this:

```json
{"content-type":"text/plain; charset=utf-8"}
```

Thanks for your help!

**Comment by Gnex77** [comment]
I get the same issue. Using axios 0.7.0 I only get the `Content-Type` header in the `response.headers` object.

**Comment by tp** [comment]
In my case it was just a simple typo, I was missing the "s" at the end of `Access-Control-Expose-Headers` :disappointed:

**Comment by incognite** [comment]
Yes in my case, just put in .htaccess file:     
<IfModule mod_headers.c>
Header set Access-Control-Expose-Headers "X-Pagination-Current-Page, X-Pagination-Total-Count"
</IfModule>
This for my custom pagination in yii2.
