### ISSUE TITLE
How to upload images with axios

### ISSUE THREAD

**Issue by Rigorbb** [mzabriskie/axios#710]
I am trying to upload images in this code

```
let data = new FormData();

        for (var i = 0; i < files.length; i++) {
            let file = files.item(i);
            data.append('images[' + i + ']', file, file.name);
        }

        const config = {
            headers: { 'content-type': 'multipart/form-data' }
        }

        return axios.post('/api/images', data, config)
```

Request payload in chrome looks like this

```
------WebKitFormBoundarymm5rBWw14G5kJSX2
Content-Disposition: form-data; name="images[0]"; filename="15-08-22 113.jpg"
Content-Type: image/jpeg


------WebKitFormBoundarymm5rBWw14G5kJSX2--
```

But the server receives an empty array of files. Why?

**Comment by Rigorbb** [comment]
The problem was to limit the file size on the server, I increased it and problem was solved

**Comment by tmaly1980** [comment]
@Rigorbb, where do you get 'files' from? Are they File objects? Or just file names?

**Comment by Grundmanis** [comment]
@tmaly1980
html 
`<input id="my-file-selector" type="file" name="file" v-on:change="onFileChange">`
vue.js
`          
methods: {
   onFileChange(e) {
            let files = e.target.files || e.dataTransfer.files;
            if (!files.length) {
                console.log('no files');
            }
            console.log(files);
            console.log(files[0])
        }
}
`

**Comment by JoelChacon** [comment]
how did you increase the limit in the server

**Comment by Rigorbb** [comment]
@JoelChacon 
max_post_size in php.ini

**Comment by valtido** [comment]
I think this is wide spread problem, and the issue is with the actual `File` API/function, consider the following...

```
const file = files[0]; //this will not work.
const file = new Blob([files[0]]); // kind of works and choses stream as content type of file (not request)
const file = new Blob([files[0]], { type: 'image/png' });// WORKS much better (if you know what MIME type you want.

const formData = new FormData();
formData.append('test', file, file.filename);
axios.post('...url...', formData, {}).then(...).catch(...);
```

I will reference a few other tickets around github which have the same issue. 

- https://github.com/axios/axios/issues/318
- https://github.com/axios/axios/issues/886
- https://github.com/github/fetch/issues/505
- https://github.com/postmanlabs/postman-app-support/issues/191

A lot of spent time to get to the bottom of this :( 

Hope it helps.

**Comment by JonasJonny** [comment]
If your server is `Express` and you use `FormData`, then you have to use something like `Multer`.

```
import multer from 'multer';
const storage = multer.memoryStorage();
const upload = multer({ storage });

server.post('/api/images', upload.any(), async (req, res) => {
   ...
}
```

More at https://stackoverflow.com/questions/37630419/how-to-handle-formdata-from-express-4

**Comment by videni** [comment]
I also have this problem,  @valtido  solution doesn't work. please check [ file is missing when upload file with FormData](https://stackoverflow.com/questions/57493231/javascript-file-is-missing-when-upload-file-with-formdata) can anybody help me please ?
