### ISSUE TITLE
Ability to support all options http and https modules support for node 

### ISSUE THREAD

**Issue by michaelBenin** [mzabriskie/axios#712]
Hello,

Currently we are using axios under heavy load.

We are encountering the error:

```
Error: getaddrinfo ENOTFOUND undefined undefined:80
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

Which is a known node issue:

https://github.com/nodejs/node/issues/7931
https://github.com/nodejs/node/issues/5436

According to 7931, this error can be mitigated by setting the family: v4 option.

After looking through axios's source, I don't believe setting that option is available:

https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L74

The available options in node shows the family property as well as others:

https://nodejs.org/api/https.html#https_https_request_options_callback

Thanks!

**Comment by michaelBenin** [comment]
After forking and modifying to use v4, problem still persists. Next solutions for my team are to upgrade to latest node, as well more aggressive caching strategy.

**Comment by michaelBenin** [comment]
This error was actually unrelated to axios.

**Comment by nathanmalishev** [comment]
Hey @michaelBenin what did this server end up being related to?

**Comment by yss14** [comment]
@michaelBenin Did it work in the end for you by forking and updating node version? I'm currently facing the same error under high load (Node.js 8.9.3).
