### ISSUE TITLE
post method not sending data

### ISSUE THREAD

**Issue by erikpineiro** [mzabriskie/axios#714]
I have posted this question in SO ([link](http://stackoverflow.com/questions/42321083/axios-post-server-does-not-receive-data-from-browser)) but I'm not sure whether it should go here.

In short: a jQuery post call works fine, the server gets the post data ($_POST is populated). If I make the same call through axios the php file at the server finds nothing in $_POST.

Thanks for any suggestions.

**Comment by TracyDa** [comment]
me too,I can send **GET** http request,but post not work.

What a !

**Comment by lbellows** [comment]
Instead of 
`data: { data} `

try 
`params: {data}`

**Comment by lbellows** [comment]
It doesn't make sense according to the docs but it worked for me.

**Comment by bulgariamitko** [comment]
nothing works for me.. jquery.post is working for me fine, but axios both post and/or get are not working. and i tried @lbellows methods, they don't work as well... :-1:

**Comment by pudjamansyurin** [comment]
try to use this lib https://github.com/ljharb/qs,
after that stringify your data before make POST or PUT request, it works for me
