### ISSUE TITLE
Axios and webpack are not working properly

### ISSUE THREAD

**Issue by kbiedrzycki** [mzabriskie/axios#716]
We have an issue with axios which is bundled using webpack. 
We are importing axios with `import axios from 'axios'` so nothing unusual. In attached screenshot you can see part of a source code which shows xhr adapter initialization. The problem is that function does not take `config` as entry point, instead it is using some `y` magic variable (`y.data`, `y.headers` and etc).

Any ideas where is the problem here? We are using axios v0.15.3 and webpack `1.14.0`.

![screen shot 2017-02-20 at 16 29 25](https://cloud.githubusercontent.com/assets/3285274/23131366/04e453a4-f78a-11e6-91c0-b264efb3cc0a.png)

**Comment by JasenWu** [comment]
have you resolve it now ? i get this issue now , what can I do?

**Comment by kbiedrzycki** [comment]
We can close the issue now, we figured it out. The problem was with build step - our code was minified twice and that caused the problem.
