### ISSUE TITLE
Adds support for more complex params through qs

### ISSUE THREAD

**Issue by pirelenito** [mzabriskie/axios#72]
Is there any interest in adding this support though https://www.npmjs.com/package/qs ?

Something like:

```javascript
params: {
  foo: {
    bar: {
      baz: 'foobarbaz'
    }
  }
}
```

Would become the following querystring: `?foo[bar][baz]=foobarbaz`

**Comment by mzabriskie** [comment]
I would be more apt to support passing a string directly for `params`, then you can use whatever you like to build the query string yourself. I am trying to keep the library as minimalist as possible, but make it extensible to handle cases like this.

**Comment by pirelenito** [comment]
Although I would appreciate this feature to be available in the library itself, I understand and support your reasoning.

Thanks.

**Comment by kevinob11** [comment]
Is there a work around until we can get something working for this?

**Comment by mzabriskie** [comment]
You can now use the `paramsSerializer` option to provide your own function for formatting params. This will allow you to use `qs` or any other library.
