### ISSUE TITLE
Response interceptor is ignored when request is not successful

### ISSUE THREAD

**Issue by inooid** [mzabriskie/axios#721]
### Problem:
In the axios read me it's explained that the response interceptor is called before any `.then` or `.catch` blocks, but it is simply being ignored if the response is not succesful.

> You can intercept requests or responses before they are handled by `then` or `catch`.

### Expected behaviour:
Whenever I intercept a response, it should always be intercepted, even when the status code is not successful.

### Actual behaviour:
It does not get triggered at all if the status code is not success.

### Reproducible example:
http://jsbin.com/puyozusova/edit?html,js,console (see developer console)

### Use case:
To get rid of jQuery, we're trying to fire off events like `ajaxComplete` whenever a response comes in. This jQuery event is being called whenever you received a response from the server, so the request is basically done and you've received a response. It does not make any assumptions whether the request was successful or not. In order to achieve this, I wanted to use the response interceptor, to **intercept** the response, but instead it makes the assumption that I only care about the successful requests, which is not the case.

**Comment by rubennorte** [comment]
If the response isn't successful then the second parameter of `axios.interceptors.response.use` is used. E.g.:

```javascript
axios.interceptors.response.use(interceptSuccessful, interceptError);
```
