### ISSUE TITLE
422 response not rejected

### ISSUE THREAD

**Issue by MrChristofferson** [mzabriskie/axios#722]
We have a project that uses axios@0.14.0 (upgrading to 0.15.3 did not resolve the issue) in many parts of the application. In all of the other parts of the app, we're able to `.catch()` 422 response codes. Recently we noticed that 1 request is resolving a promise that gets a 422 response. In all other parts of our application, a 422 causes axios promises to be rejected.
```
export function addTool(name: string): Thunk {
  return (dispatch, getState) => {
    Axios
      .post<Tool>(API.current.toolsPath, { name })
      .then(resp => {
        if (resp instanceof Error) { throw resp; }
        success("Tool has been saved.", "Success");
        dispatch(addToolOk(resp.data));
      })
      .catch((e: Error) => {
        dispatch(addToolNo(e));
        error(prettyPrintApiErrors(e));
      });
  };
}
```

[Source code here](https://github.com/FarmBot/farmbot-web-frontend/blob/master/src/tools/actions.ts#L200)

I was able to work around the issue by adding the following line to my `.then()`:
```
if (resp instanceof Error) { throw resp; }
```
Which works fine, but I'm still confused as to why this particular 422 is resolved (rather than rejected). We also have [some interceptors](https://github.com/FarmBot/farmbot-web-frontend/blob/master/src/auth/actions.tsx#L77) in use, but they haven't cause any issues for the other requests we make.

Are there any circumstances in that would cause axios to resolve a 422 rather than reject it? Please let me know if you need any other information.

Thanks for the help!

**Comment by musbaig** [comment]
Confirmed. I'm also seeing something similar when using axios with `redux-saga` where some 422's aren't being handled as a rejected promise.

**Comment by musbaig** [comment]
Never mind, found my problem. Interceptors weren't properly propagating errors down to the app layer, d'oh! 😳

**Comment by RickCarlino** [comment]
After investigating this issue, I found that it was actually a local type error hidden deep in the call stack somewhere, leading me to believe that it is a local issue rather than a problem with Axios.
