### ISSUE TITLE
Unhandled promise rejection on IE9 when i use axios(url, qs.stringify(data)).then()

### ISSUE THREAD

**Issue by Phlen** [mzabriskie/axios#726]
I had add babel-proyfill in my project, and i can console the Promise object on IE9. But this is an error warning when i use axios(url, qs.stringify(data)).then(). please for help..
my code jest like this:
return axios.post(url, qs.stringify(data)).then(res => {
  console.log(res)
})
.catch(err => {
  console.log(err)
})

error: Unhandled promise rejection[object Object]

**Comment by rubennorte** [comment]
This error could be somewhere else in your code, but doesn't seem an issue related to axios. Please try to debug it better and if you find a specific issue in axios please open a new issue with more details.

**Comment by kobezone** [comment]
same error 无法获取未定义或 null 引用的属性“isReady” Unhandled promise rejection Error: 拒绝访问。 how to do

**Comment by vaibhav-systango** [comment]
@Phlen did you find any solution for this, babel-polyfill doesn't seems to work!
