### ISSUE TITLE
Read headers from 304 response

### ISSUE THREAD

**Issue by hudadiaz** [mzabriskie/axios#727]
I need to read headers from every request. For a `304` response, the headers are retrieved from the previous browser cached `200` response even when the newer response headers are different.

**Comment by hudadiaz** [comment]
I think it is related to https://github.com/mzabriskie/axios/issues/503. Can someone recommends any solution for this?

**Comment by jcready** [comment]
I assume this is in a browser. Does this happen on all browsers? It does seem like a bug but it's not something axios could fix as the caching isn't handled by axios. According to [rfc7234 §4.3.2](https://tools.ietf.org/html/rfc7234#section-4.3.4):

> If a stored response is selected for update, the cache MUST use other header fields provided in the 304 (Not Modified) response to replace all instances of the corresponding header fields in the stored response.

**Comment by rubennorte** [comment]
Closing as the answered by @jcready is correct.
