### ISSUE TITLE
isStandardBrowserEnv not working properly

### ISSUE THREAD

**Issue by Viktor6713** [mzabriskie/axios#728]
Hello we are using axios with react native and react-native-signalr lib.
The signalr does something with document due to which axios in isStandardBrowserEnv is not properly determining where its running and tries to read cookies in react native app and fails.
I propose we detect react native from navigator.product as it was introduced in this commit for react native:
[https://github.com/facebook/react-native/commit/3c65e62183ce05893be0822da217cb803b121c61](url)

**Comment by nickuraltsev** [comment]
Fixed via #731
