### ISSUE TITLE
Typescript Typings error.

### ISSUE THREAD

**Issue by halallahh** [mzabriskie/axios#734]
Hi, I'm using axios on my project but I got this error:

```error TS2339: Property 'get' does not exist on type 'typeof```

version: ```Typescript 2.2.1```

tsconfig.json:
```javascript
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "sourceRoot": "src",
        "outDir": "dist",
        "moduleResolution": "node",
        "noImplicitAny": false,
        "sourceMap": true
    }
}
```

**Comment by polco** [comment]
change your `import * as axios from 'axios` to `import axios from 'axios'`

**Comment by halallahh** [comment]
Thanks @polco solved this problem.

**Comment by pinich** [comment]
@polco you solved my problem too !!!
## Thanks !!!

**Comment by tang-jason** [comment]
Why `import * as axios from "axios"` doesn't work but `import axio from "axios"'?

**Comment by bennadel** [comment]
I just ran into something similar. I had been using:

`import axios = require( "axios" );`

... which successfully obtained the axios reference; but, was complaining when I tried to access `axios.create()` (despite the fact that the code was actually working).

**Comment by bennadel** [comment]
Ah, I see in the axios source that it uses:

```js
// Allow use of default import syntax in TypeScript
module.exports.default = axios;
```

**Comment by trashhalo** [comment]
For those that are one javascript and cant switch to imports. this seems to make ts happy
```javascript
const { default: axios } = require('axios');
```
