### ISSUE TITLE
A suggestion of optimization about callback method

### ISSUE THREAD

**Issue by VincentPat** [mzabriskie/axios#740]
I don't know if this is my mistake, but it seems like axios don't have a complete callback method.
just like jquery：
```
$.ajax({
    url: '/abc',
    method: 'get',
    complete: function() {
        console.log('done!');
    }
});
```

**Comment by yolo2013** [comment]
**Promise based** HTTP client for the browser and node.js

**Comment by rubennorte** [comment]
Promises are part of the core of axios and this is unlilely to change. There's a proposal to implement a "finally" method in promises that you could benefit from if it makes it to the spec.
