### ISSUE TITLE
Axios not parsing JSON but instead returning all the markup on page using React & Redux

### ISSUE THREAD

**Issue by jephjohnson** [mzabriskie/axios#744]
I have a local .json file that I am trying to fetch but instead all the markup for my page is being returned. I've scoured online looking for a solution, but coming up short.

flickrActions.js:

```
export const fetchFlickr = () => {
  return function(dispatch, getState) {
    axios.get("/data/output.json", {
      headers: { 'Content-Type': 'application/json' }
    })
    .then((response) => {
      dispatch({type: "FETCH_TWEETS_FULFILLED", payload: response.data})
    })
    .catch((err) => {
      dispatch({type: "FETCH_TWEETS_REJECTED", payload: err})
    })
  }
}
```

output.json:

```
[
   {
      "code":"BAcyDyQwcXX",
      "id":"1161022966406956503",
      "display_src":"https://scontent.cdninstagram.com/hphotos-xap1/t51.2885-15/e35/12552326_495932673919321_1443393332_n.jpg"
   },
   {
      "code":"BAcyDyQwcXX",
      "id":"1161022966406956503",
      "display_src":"https://scontent.cdninstagram.com/hphotos-xap1/t51.2885-15/e35/12552326_495932673919321_1443393332_n.jpg"
   },
   {
      "code":"BAcyDyQwcXX",
      "id":"1161022966406956503",
      "display_src":"https://scontent.cdninstagram.com/hphotos-xap1/t51.2885-15/e35/12552326_495932673919321_1443393332_n.jpg"
   }
]
```

What is being returned:

<img width="901" alt="screen shot 2017-03-08 at 7 46 01 am" src="https://cloud.githubusercontent.com/assets/1817084/23677524/97c55a46-03d4-11e7-9283-6ab76da33782.png">

**Comment by QuentinDejean** [comment]
It looks like the file is not being found in your static assets folder on your server-side .Therefore, your server is returning you whatever you do in your last `app.use('*')` middleware. Presumably returning you a 404 page?

**Comment by jephjohnson** [comment]
Thanks Quentin, it ended up being my config in express. :/

**Comment by jephjohnson** [comment]
I had a scoping issue. Resolved in my server.js config with the following:

```
.....
fs.writeFile(__dirname + '/data/output.json', JSON.stringify(result, null, 4), function(err){
```
