### ISSUE TITLE
2 request with different X-Access-Token headers return the same response

### ISSUE THREAD

**Issue by pke** [mzabriskie/axios#747]
I have 2 requests, issued to the same URL endpoint but a different `X-Access-Header`. However the response is always the same.

A redacted curl looks like this:

`curl 'https://server/api/user' -H 'Accept: application/json' -H 'Accept-Version: v2' -H 'X-Access-Token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' -H 'User-Agent: Mozilla/5.0 (Linux; Android 5.1; LENNY2 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Crosswalk/21.51.546.7 Mobile Safari/537.36' -H 'X-API-Key: iPhahK6j' --compressed`

And the second request:

`curl 'https://server/api/user' -H 'Accept: application/json' -H 'Accept-Version: v2' -H 'X-Access-Token: bbbbbbbbbbbbbbbbbbbbbbbbbbbbb' -H 'User-Agent: Mozilla/5.0 (Linux; Android 5.1; LENNY2 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Crosswalk/21.51.546.7 Mobile Safari/537.36' -H 'X-API-Key: iPhahK6j' --compressed`

Response is in both cases:

``` 
Cache-Control:max-age=0, private, must-revalidate
Connection:keep-alive
Content-Encoding:gzip
Content-Type:application/json; charset=utf-8
Date:Wed, 08 Mar 2017 16:01:15 GMT
Etag:W/"848100dffe226230bf170fedbb951dd9"
Server:Cowboy
Transfer-Encoding:chunked
Vary:Accept-Encoding, Origin
Via:1.1 vegur
X-Request-Id:674f6615-c79e-402c-806d-2c9f1a3b5d8a
X-Runtime:0.316702
``` 

~~What is interesting is the etag. Its the same for both responses. I guess because the response body is the same. Both requests are real server request, no caching is enabled on the device.~~

It seems my Chrome devtools where only telling half the truth. There seems to be a cookie sent from the server that axios saves for later requests. While sending the cookie header back in the response is a bug on the server, is there a way to prevent the storing and usage of the cookie in axios?

~~Any ideas if that could be related to some caching in axios?~~

**Comment by rubennorte** [comment]
The response you're providing doesn't set any cookies, so I'm guessing that's not the problem. It should be something related to your authorization server.

I'm closing the issue because it's not related to axios.
