### ISSUE TITLE
compress post data?

### ISSUE THREAD

**Issue by jasonswearingen** [mzabriskie/axios#748]
How (or can?) you compress the post body of a request?

I tried setting the "Content-Encoding":"gzip" header (and set "Content-Length") and then gzip the post data, but the destination server isn't able to process the result, and my local traffic analyzer shows that the compressed content is malformed (no valid gzip header)

additionally I don't see any refrence to this on the axios docs nor anyone discussing it.

**Comment by rubennorte** [comment]
Are you using axios in the server or in the browser? If you're using the browser the compression is done automatically by it. If you're using Node.js the compression of the body isn't supported for the moment. You can do it manually (piping your stream to one of the transform streams in zlib).

**Comment by jasonswearingen** [comment]
i tried doing compression manually but I always get errors when inspecting or receiving.

**Comment by gianisegatto** [comment]
I have the same problem. How can I specify I want to send a zip request and make my headers only have the content that I want?
