### ISSUE TITLE
jsonp

### ISSUE THREAD

**Issue by aaronagray** [mzabriskie/axios#75]
Hi there, is there a simple way (or plans) to use Axios with jsonp?

**Comment by mzabriskie** [comment]
I have decided not to support JSONP as part of axios. You can see the conversation here #15. Also take a look at [this recipe](https://github.com/mzabriskie/axios/blob/master/COOKBOOK.md#jsonp) as an alternative.

**Comment by aaronagray** [comment]
Awesome. Thanks for the note! I didn't see the cookbook before. Thanks for sharing.
