### ISSUE TITLE
Unable to run code after request sent

### ISSUE THREAD

**Issue by sergop321** [mzabriskie/axios#752]
Is there a way to run code after request is sent but before it received

```javascript
axios.request({ url: '/logout' });
clearCookie();
``` 
this is not working because the axios request using promises inside which mean the cookies is being cleared before the request is actaully being sent.

Is there a way to run clearCookie only after the request is sent (but without waiting for the response), without creating a custom adapter for this?

**Comment by WoLfulus** [comment]
tun the clearCookie call inside then/catch

**Comment by sergop321** [comment]
@WoLfulus If I do this, it will run only after server response. this is not the behavior I am trying to implement.

**Comment by charlesrochati** [comment]
Have you tried using `transformResponse`?
  
`// 'transformResponse' allows changes to the response data to be made before`
  `// it is passed to then/catch`
  `transformResponse: [function (data) {`
  `  // Do whatever you want to transform the data`
  `  return data;`
 ` }],`

**Comment by WoLfulus** [comment]
sorry @sergop321 , have you tried interceptors? you can clear the cookies on response handler, so it will clear the cookies before your `then` executes

**Comment by charlesrochati** [comment]
@WoLfulus, `transformResponse` gives you this behavior, there's no need to create an interceptor.

**Comment by WoLfulus** [comment]
but both are executed at the same time right? the problem is that transformResponse is for... transforming the response. anyways... both methods will work?

**Comment by sergop321** [comment]
Both your suggestions runs the code only after the response from server, I trying to run the cookieClear after the request is sent but not to wait for the server response.

**Comment by jcready** [comment]
You could try something like this:

```js
axios.request({ url: '/logout' });
process.nextTick(clearCookie);
// or setImmediate(clearCookie);
```

**Comment by lcrossan** [comment]
if i'm understanding this correctly, you have some authentication data in your cookie, that you need to clear when you hit your `/logout` endpoint.

two things come to mind -- one, it's a super bad idea to store any sensitive data in a cookie, especially one not flagged HTTP-only as it appears this one is. if i can mount a man in the middle or xss attack on your client, i can grab the cookie from javascript just as easily as you can.

two, i can't think of a reason why the order would matter at all. just clear whatever data you need to clear on the server, and then clear it on the client.

```js
axios.request({ url: '/login' }).then(() => clearCookie())
```

**Comment by sergop321** [comment]
@jcready I think I can make it work with this, I think it should be 
```javascript
axios.request({ url: '/logout' });
setImmediate(() => {
 setImmediate(clearCookie);
});
```
because the axios request execution is promise inside promise. But I haven't tested it yet.
I am afraid to have different behaviors in different browsers, because you rely on the js engine implementation of code execution.

@lcrossan The example I gave was simplified for the clearance. The idea is that I need to update the application state to unauthorized state (this will update the relevant UI and everything else).

this important to do before waiting for server response for 2 reasons:
1) The user won't see an immediate UI update if I am waiting for server response (In mobile networks this can take even several seconds). And won't work at all if there is no internet connection.
2) If user continue do action that require more requests to server, they will be send with the previous credential (Race conditions).

I can do both things even before sending the request the only problem is the cookie, that is being added by browser for the request, so I am not able to clear it before the request is sent (Otherwise the logout request is sent without the cookie). - (I can modify the logout request to pass the auth data in a different way than a cookie, this probably will solve the issue for me - Thanks for the advice).

I understand this is not a part of the promise spec but, this can be easily implemented by providing a callback function in request config for example afterRequest, which will be executed inside adapters after request is sent.

**Comment by rubennorte** [comment]
The use case you have is very specific. I don't recommend you using any approach that involves `setTimeout`, `setImmediate` or `nextTick` as you'd be making too many assumptions about how axios make the request.

I'd recommend you to define a custom adapter that just calls the default one, clears the cookies and returns the result. E.g.:

```javascript
const defaultAdapter = axios.defaults.adapter;
const cookieClearingAdapter = (...args) => {
  const result = defaultAdapter(...args);
  clearCookies();
  return result;
};
axios.request({
  ...,
  adapter: cookieClearingAdapter
});
```

I hope this helps.
