### ISSUE TITLE
Axios doesn't add Content-Type to the request

### ISSUE THREAD

**Issue by igroeg** [mzabriskie/axios#755]
I've got configured :
`axios.defaults.baseURL = 'http://localhost:8080/';
        axios.defaults.headers.common['Content-type'] = "application/json";
        axios.get('something/something1', {
            headers: {
                "Content-Type": "application/json"
            }
        }).then(response => console.log(response));`

This unfortunately this doesn't add Content-Type in the header of the request.

**Comment by cw1997** [comment]
me, too

**Comment by ahles** [comment]
If I visit the axios code I find this section:

``` javascript
// Add headers to the request
if ('setRequestHeader' in request) {
  utils.forEach(requestHeaders, function setRequestHeader(val, key) {
    if (typeof requestData === 'undefined' && key.toLowerCase() === 'content-type') {
      // Remove Content-Type if data is undefined
      delete requestHeaders[key];
    } else {
      // Otherwise add header to the request
      request.setRequestHeader(key, val);
    }
  });
}
```

If there's no requestData, then the "Content-Type" header is removed. The "Content-Type" header is for setting the requestData type. So if there's no request data, the 'Content-Type' header gets removed.

And I found a section in the docs about requestData:

``` javascript
// `data` is the data to be sent as the request body
// Only applicable for request methods 'PUT', 'POST', and 'PATCH'
// When no `transformRequest` is set, must be of one of the following types:
// - string, plain object, ArrayBuffer, ArrayBufferView, URLSearchParams
// - Browser only: FormData, File, Blob
// - Node only: Stream
data: {
  firstName: 'Fred'
},
```

So you can't set data for a GET request, and at the same time the "Content-Type" header for a request without data gets ignored.

One can't set a "Content-Type" header for a GET request in Axios. And that's probably correct behaviour. (I'm only user)

If you want to send data to the server, you should use PUT or POST.

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields

> Content-Type:
> The MIME type of the body of the request (used with POST and PUT requests)

If you want the server to respond with "application/json", you would need ```"Accept": "application/json"```, which is already set by Axios I think.

**Comment by rubennorte** [comment]
Axios probably shouldn't remove a specific header set in the request, but also your request configuration doesn't make sense. You're telling your server that the content you're sending is 'application/json` but you aren't actually sending any content.

**Comment by concubicycle** [comment]
I am doing a post, settings data to an object (verified non-null), and trying to set Content-Type, and it still isn't working: 
```
	var axiosObj = {
			method: this.method,
			params: queryParams,
			data: bodyParams,
			url: this._getUrl(params),
			headers:{
				'Content-Type': 'application/json'				
			}
		};
		
		return axios(axiosObj)
```

**Comment by AbhimanyuVashisht** [comment]
how can one change the default 'Content-Type' in axios

**Comment by Lak0sta** [comment]
+1

**Comment by edwardjyu** [comment]
I have same problem. The strange thing is that 'Content-Type' is added in headers with Electron main.js while it always is missed at Renderer(web). I did put any dummy data.

**Comment by bigfacewo** [comment]
If you don't hava data on post request, you can set ```data:{}``` to avoid this.
