### ISSUE TITLE
Add option for adding a trailing slash automatically

### ISSUE THREAD

**Issue by LeoAref** [mzabriskie/axios#757]
I couldn't find in the docs a way to configure adding a trailing slash to the URLs

---

I can submit PR if we agreed about it

**Comment by nickuraltsev** [comment]
You can add a trailing slash in your code. I don't see why it needs to be done by axios.

**Comment by LeoAref** [comment]
@nickuraltsev Why did you close the issue without listening to my argument!!!!

**Comment by nickuraltsev** [comment]
I didn't realize you were going to provide more details on this. Reopening...

**Comment by cycold** [comment]
Is there a way can ignore baseURL slash?
```
baseURL = "http://testweixin.cn/h5MethodDispatcher?apiMethod="
// when use 
axios.post("user/getBaseUser", {userId: 12}) 
// request url: 
http://testweixin.cn/h5MethodDispatcher?apiMethod=/user/getBaseUser

here,  add a `/` 

but my expected require URL: 
http://testweixin.cn/h5MethodDispatcher?apiMethod=user/getBaseUser
```
Forgive my poor English

**Comment by LeoAref** [comment]
@nickuraltsev My point simply was about having this feature to avoid adding slash to all my URLs

Let's assume that I've 15 services that call various APIs, and the backend expects that all URLs end with a slash

So currently I've to do:
```js
function getUser(id) {
  return axios.get('/user/' + id + '/');
}
```

And repeat adding the slash in all the services

---

Instead we can simply configure axios to add it:
```js
axios.defaults.trailingSlash = true;

function getUser(id) {
  return axios.get('/user/' + id);
}
```

**Comment by rubennorte** [comment]
You can do this using an interceptor. E.g.:

```javascript
axios.interceptors.request.use((config) => {
  if (config.addTrailingSlash && config.url[config.url.length-1] !== '/') {
    config.url += '/';
  }
  return config;
});
```

We're trying to only add features to axios that will be used by most users. Otherwise, if possible, you should use interceptors.

**Comment by LeoAref** [comment]
@rubennorte Thanks a bunch for that code snippet 👍
