### ISSUE TITLE
Problem with 201 status response with Location header

### ISSUE THREAD

**Issue by lkmadushan** [mzabriskie/axios#758]
When server response has 201 status code with Location header. I'm getting this errors. How can I fix his?

```
Cannot read property 'toString' of undefined(…)
```

**Comment by xakep139** [comment]
Maybe not this issue, but I can't find "Location" header in response headers.

**Comment by lkmadushan** [comment]
Can you see location header within interceptors?

For now I did this.

```
axios.interceptors.response.use(function (response) {
    if(response.headers.location) {
        return axios.get(response.headers.location);
    }

    return Promise.resolve(response);
  }, function (error) {
    return Promise.reject(error);
  });
```

**Comment by xakep139** [comment]
This solved the problem: http://stackoverflow.com/a/37931084/4963622

**Comment by rubennorte** [comment]
@lkmadushan I'm closing the issue. Please reopen if what @xakep139 said didn't work and please provide an example of code that fails.
