### ISSUE TITLE
Not receiving progress events when using from node

### ISSUE THREAD

**Issue by alexpsi** [mzabriskie/axios#760]
I am using the latest version and trying to find a way to get progress updates while a file is uploading or downloading. I looked at the code but inside the http adapter it does not seem to have any code that triggers this event. Do progress event work only browserside?

**Comment by nickuraltsev** [comment]
Yeah, progress events work only in browsers at the moment.

**Comment by flo-sch** [comment]
Shouldn't it be mentioned in the documentation, though?
