### ISSUE TITLE
Return an array from axios?

### ISSUE THREAD

**Issue by nifrasbcs** [mzabriskie/axios#761]
I'm working on computed properties of Vue.js

There is a computed method which requests an axios api to get an array(after performed some logics inside the promise).

    computed: {
        filteredTrips: function () {
            var filtered = this.trips;
            if(this.filters_by.indexOf('monitor')>=0) filtered = this.filter(filtered, this.BusMonitorID,'BusMonitorID');
            if(this.filters_by.indexOf('route')>=0) filtered =  this.filter(filtered,  this.TourID,'TourID');
            if(this.filtered_count==0) return this.getFilteredTrips(); //This is the axios method to get an array
            return filtered;
        }
    },
    methods: {
        getFilteredTrips:function(){
          var resource = base_url+'report/transport/filter';
          var self = this;
          axios.post(resource, $.param({filters:this.filters})).then(function(response) {
            // here i'm performing some logics to make self.trips

            self.trips.push(data[trip]); //push data to self.trips

            return self.trips; // i need to return this array
          }).catch(function(response) {
                // error callback
            })
         }
    }

 The problem is `getFilteredTrips()` not return self.trips array,
 How to make it as possible through axios/js?

**Comment by charlesrochati** [comment]
`self.trips.push(data[trip]); //push data to self.trips` Where is the `data` coming from?

Shouldn't it be `response.data`?

**Comment by rubennorte** [comment]
I think the problem is that you're not returning the axios response (`return axios.post(...)`). Next time please try to use issues to report bugs in axios or request specific features.
