### ISSUE TITLE
Queue multiple calls

### ISSUE THREAD

**Issue by refaelos** [mzabriskie/axios#763]
My client side app needs to do multiple calls (sometimes even 100s of calls) to the server. This slows things down dramatically even when the server processing time is fast enough.

What is the recommended way to do it?

**Comment by charlesrochati** [comment]
Do you have to trigger the requests in some specific order?

**Comment by refaelos** [comment]
@charlesrochati not necessarily but I do wonder if queueing them will help?

**Comment by charlesrochati** [comment]
I don't think that queueing the requests will make any relevant performance improvement (if you're doing it with `axios.all`).

Can't you just take those hundreds of requests and refactor them into 5 or 10? Even if those 5 or 10 requests transfer more data, it would be better, once it is not creating lots of process for the client to take care of.

**Comment by rubennorte** [comment]
For general programming questions please use StackOverflow or any other forum platform. We're trying to maintain this only to report bugs or request features in axios.
