### ISSUE TITLE
"Access-Control-Allow-Headers: *" not working as expected

### ISSUE THREAD

**Issue by marktopper** [mzabriskie/axios#766]
I just experienced that if my server did a
```
Access-Control-Allow-Headers: *
```

Then only the `OPTIONS` request would be done, and not the actual `POST` request.
However changing this to the following worked:
```
Access-Control-Allow-Headers: Content-Type
```

Is this meant to be or is this a mistake?

**Comment by rubennorte** [comment]
It seems not all browsers support wildcards in `Accces-Control-Allow-Headers`. Take a look at http://stackoverflow.com/questions/13146892/cors-access-control-allow-headers-wildcard-being-ignored.
