### ISSUE TITLE
Protocol "https:" not supported. Expected "http:" Error

### ISSUE THREAD

**Issue by dparmar74** [mzabriskie/axios#768]
```
const agent = new http.Agent({family: 4});
axios.get("http://mywebsite.com", {
      httpAgent: agent
    })
    .then((response) => {
       console.log(response);
    })

```
With above code, I get below error

http_client.js:55
    throw new Error('Protocol "' + protocol + '" not supported. ' +
    ^

Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:55:11)
 
I am using Axios 0.15.3 and Node 6.10.0 version

**Comment by dparmar74** [comment]
Not an issue.  The website was internally redirecting to https

**Comment by dotbloup** [comment]
dparmar74 , it is an error, it does not return a "redirect" or a target url, how did you do to solve the issue?

**Comment by yadue** [comment]
@dparmar74 its an issue, breaks completly node js server and cant be even catched only if the external url configuration is incorrect.

**Comment by lazharichir** [comment]
Any plan on fixing that? it's literally messing everything up... :/

**Comment by lazharichir** [comment]
What is the right fix for that, even if it has to be done on our app logic?

**Comment by soanvig** [comment]
Experiencing the same issue. Crashes server, cannot be catched.
