### ISSUE TITLE
Get  can't send request header,But Post can send, why??

### ISSUE THREAD

**Issue by longzhaobi** [mzabriskie/axios#769]

**Comment by rubennorte** [comment]
Please, next time provide a code example so we can better determine if that's an issue in axios and help you.

You may be setting a header that you cannot set in the browser (e.g.: host). See https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by hebiao6446** [comment]
Post do not work !!! Is the something wrong with the server ?  HELP !
