### ISSUE TITLE
Is it possible to have a default then

### ISSUE THREAD

**Issue by sofianegargouri** [mzabriskie/axios#770]
Hi !

I was wondering if it was possible to add a default then function, which is triggered for a configured instance of axios. 
When you do a request with this instance, it will trigger the default then provided in the config, and then run the one you manually provided.

I'm asking this because I'm using [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth), and it's boring to manually add the token refresh each time I do a request.

Thanks ! :)

**Comment by rubennorte** [comment]
You can use interceptors for that. You can read more about them in the documentation: https://github.com/mzabriskie/axios#interceptors
