### ISSUE TITLE
Axios is not showing all headers of response

### ISSUE THREAD

**Issue by murbanowicz** [mzabriskie/axios#771]
My backend app is sending JWT after login in Authorization header.
I do not see this header with Axios even if I see that in dev tools.

It is definitely not as it should be.

**Comment by nickuraltsev** [comment]
Please take a look at this question and answer: http://stackoverflow.com/questions/37897523/axios-get-access-to-response-header-fields

**Comment by aerze** [comment]
Also good reading
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers

**Comment by greenlaw110** [comment]
The thing is that it got the `Access-Control-Request-Headers: Authorization` in the preflight OPTIONS request, and it still can't access that  in the response.headers of the response of the following POST request.

**Comment by annso92** [comment]
Got the same problem as @greenlaw110. Any solutions?

**Comment by vinnyfs89** [comment]
Got the same problem as @greenlaw110. Any solutions?

**Comment by greenlaw110** [comment]
@annso92 and @vinnyfs89 

Unfortunately I still don't have a solution to this one. I've posted a SO here: https://stackoverflow.com/questions/61164197/axios-response-headers-missing-data-when-running-in-vuejs-app

In case you guys have a solution, please help to anwser my SO above. Thanks a lot!

**Comment by nemanja-mudrinic** [comment]
At your app under cors ou need to enable `Access-Control-Expose-Headers`

example

nestjs backend app

```
app.enableCors({
    exposedHeaders: 'session-id'
  });
```

Now your client app will be able to access that response header
