### ISSUE TITLE
Bug: Node Buffers less than 8192 bytes

### ISSUE THREAD

**Issue by jerfowler** [mzabriskie/axios#774]
When passing a small "unsafe" node buffer to Axios that is less than the size of `Buffer.poolSize` which is 8192 bytes, axios passes the entire 8192 bytes in the pool which can contain random data.

```javascript
    var buf = new Buffer(1024); // Unsafe buffer < Buffer.poolSize (8192 bytes)
    buf.fill('x');
```
--or --

```javascript
    var buf = Buffer.allocUnsafe(1024).fill('x'); // Unsafe buffer < Buffer.poolSize (8192 bytes)
```

[Buffer.allocUnsafe(size)](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_allocunsafe_size)
> Use of this pre-allocated internal memory pool is a key difference between calling Buffer.alloc(size, fill) vs. Buffer.allocUnsafe(size).fill(fill). Specifically, Buffer.alloc(size, fill) will never use the internal Buffer pool, while Buffer.allocUnsafe(size).fill(fill) will use the internal Buffer pool if size is less than or equal to half Buffer.poolSize. The difference is subtle but can be important when an application requires the additional performance that Buffer.allocUnsafe() provides.

Here is a test to reproduce the issue:

```javascript
  testBuffer: function(test) {
    var buf = new Buffer(1024); // Unsafe buffer < Buffer.poolSize (8192 bytes)
    buf.fill('x');
    server = http.createServer(function (req, res) {
      test.equal(req.headers['content-length'], buf.length.toString());
      req.pipe(res);
    }).listen(4444, function () {
      axios.post('http://localhost:4444/',
        buf, {
        responseType: 'stream'
      }).then(function (res) {
        var stream = res.data;
        var string = '';
        stream.on('data', function (chunk) {
          string += chunk.toString('utf8');
        });
        stream.on('end', function () {
          test.equal(string, buf.toString());
          test.done();
        });
      });
    });
  },
```

Pull Request w/ test: #773

**Comment by nickuraltsev** [comment]
Fixed via #773
