### ISSUE TITLE
Determine number of unresolved requests?

### ISSUE THREAD

**Issue by rringler** [mzabriskie/axios#776]
Is there a way to determine the number of axios requests that have not been resolved yet (similar to `$.active` in jQuery)?  I'm trying to get my integration test framework to wait for requests made via axios to complete before testing assertions.

**Comment by rubennorte** [comment]
You can implement this using (interceptors)[https://github.com/mzabriskie/axios#interceptors] that can run before requests are sent and after responses are received.
