### ISSUE TITLE
Support for basic authentication on XMLHttpRequest.open() ?

### ISSUE THREAD

**Issue by laander** [mzabriskie/axios#78]
As far as I can see, Axios doesn't support easy basic authentication headers in XMLHttpRequest ([xhr.js L37]( https://github.com/mzabriskie/axios/blob/1629a026da17a1e1d8999a02f3fe6b6b60aaac9c/lib/adapters/xhr.js#L37)). The [open()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open()) method on XMLHttpRequest can take a username and password as the 4th and 5th argument, which is a lot easier than base64 encoding the "Authorization" header manually.

Am I missing something or is there a specific reason for this design choice?

**Comment by mzabriskie** [comment]
@laander there is no reason for lack of support. Sounds like something worth looking into.

**Comment by switz** [comment]
+1

**Comment by timjacobi** [comment]
+1

**Comment by adanperez** [comment]
+1

**Comment by idan** [comment]
This is actually a bad idea, see #167

**Comment by laander** [comment]
@idan Support of the `Authorization` header is even better - as long as I don't have to add it manually :)
