### ISSUE TITLE
Complete event 

### ISSUE THREAD

**Issue by mubaidr** [mzabriskie/axios#782]
A function to be called when the request finishes (after success and error callbacks are executed). Just like jquery, would be very helpful to do redundant tasks that needs to be done at either state. (Like show/hide progress or spinner etc)

**Comment by lbausch** [comment]
Try the following (note the second `then`):
```js
axios.post('/api/foo', {
    foo: 'bar'
}).then((response) => {
    // success
}).catch((response) => {
    // error
}).then(() => {
    // always executed
})
```

**Comment by rubennorte** [comment]
Closing as @lbausch's solution should work.
