### ISSUE TITLE
Axios callback called multiple times

### ISSUE THREAD

**Issue by reformer** [mzabriskie/axios#784]
I get callback method twice when I make a call from axios in React Native,
My button JSX,
`  <BuddyButton onPress={this.callPostWebService.bind(this)}>`

My event method on button pressed,
 ```
validateLogin = () => {
   ...
    WebserviceHelper.postValues(webServiceName, valuesJson, this);
  }
```
My Axios calling method

```
exports.postValues = function(webServiceName,valuesJson, callbackRef) {
  instance.post(webServiceName, valuesJson)
  .then(function (response) {
    alert(response);
  })
  .catch(function (error) {
    alert(error);
  });
};
```
Now in above code first i got success message and my response block got call and after within second error block called. In first time i get correct web response, and second time i get error message.
I'm using react-native version 0.34.1 and axios version 0.14.0.
Thanks

**Comment by justanne** [comment]
I'm having a similar issue. It runs the post request twice. Response on first is 200 and the other one gets timed out at with 504 response.

**Comment by reformer** [comment]
@justanne  hi I resolved this issue. My error come from native android code which invoke in react native component. That android callback was undefined (that is reactScript callback). After my login screen i calling 7-8 webservices using axios spread. I fixed my undefined issue... my code worked fine now.

**Comment by justanne** [comment]
@reformer Cool, great to know it works already with you. Thanks for info, will further check my code it might be on my side too. You can already close this issue though - if I'm unable to solve mine I'll open my own. 👍🏼
