### ISSUE TITLE
Axios abort request

### ISSUE THREAD

**Issue by shahromil88** [mzabriskie/axios#785]
Hello,

I want to abort axios http request. However, I am not able to find the Abort functionality inside axios library.

According to below url, it should be included into package: https://github.com/mzabriskie/axios/pull/330/commits/63167431bf1ff15517618f220a7d5809a7cbde05

My axios version is: 0.14.0

Regards,
Romil

**Comment by nickuraltsev** [comment]
Please see this: https://github.com/mzabriskie/axios#cancellation
