### ISSUE TITLE
navigator not defined

### ISSUE THREAD

**Issue by alexey-sh** [mzabriskie/axios#79]
When used nw.js wrote in console

```
require('axios')({method: 'GET', 'url': 'https://google.com'}).catch(function () { console.log(arguments);})
lib$es6$promise$promise$$Promise {_id: 16, _state: undefined, _result: undefined, _subscribers: Array[0], constructor: function…}
VM298:2 [ReferenceError]0: ReferenceErrormessage: "navigator is not defined"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Errorcallee: function () { console.log(arguments);}length: 1Symbol(Symbol.iterator): function ArrayValues() { [native code] }__proto__: Object
```

**Comment by laander** [comment]
Related https://github.com/mzabriskie/axios/issues/58

IMO, it seems that the correct context isn't read (browser vs. server) and the code assumes that its in browser context, thus using the xhr adapter that checks for `navigator`. Could it be somerthing to do with https://github.com/mzabriskie/axios/blob/master/package.json#L58 ?

**Comment by laander** [comment]
Digging a bit deeper, it seems that the webpack build points to the the same adapter file for both browser (window !== undefined) and server (process !== undefined) - `__webpack_require__(8)` which is lib/adapters/xhr.js

See https://github.com/mzabriskie/axios/blob/master/dist/axios.js#L494

I'm honestly not sure why. If i dont use webpack for the packaging (i.e. requires axios in node.js directly), everything seems to work as it should.

**Comment by mzabriskie** [comment]
@laander you are correct. The code found under `dist/` is deployed to bower, and intended for use in the browser. Safer to use `index.js` when using under node.js environment.

**Comment by laander** [comment]
I'm a little sad to see this closed. If the dist version isn't safe for Node/CommonJS, it shouldn't be built as an UMD module. I spent quite a few hours debugging this and it's a false positives IMO. As a minimum there should be warning, a note in the README and it would be even better if the bug could be fixed (and thereby make Axios more embeddable into other UMD-ready libs)

**Comment by mzabriskie** [comment]
@laander I think you may be misusing `dist/`. This is meant to be used in the browser. It deliberately removes any code path used by node for that purpose. It supports CommonJS since some people may be using it with browserify, or webpack, but for node you should just be including `var axios = require('axios');` or using ES6 `import axios from 'axios';`. This will work for node. If you are using `dist/axios` you will be getting a browser friendly version.
