### ISSUE TITLE
[enhancement] axios.all to take in object

### ISSUE THREAD

**Issue by lawrencetvo** [mzabriskie/axios#790]
Right now, the 'axios.all` method takes in a list of functions and returns a list of responses. I believe a good enhancement would be to have the method be able to take in a KVP object and return a KVP object.

Example usage would be:
`const myData = axios.all({ weather: weatherCall() })`
`...`
`const { weather } = myData`

I am willing to work on this enhancement if I get the go-ahead.

**Comment by rubennorte** [comment]
I think we're more likely to remove these helpers from axios than adding new ones. The goal of axios isn't to provide utilities for promises but to make requests easily. I'm sure there are libraries out there to do this better than axios would.
