### ISSUE TITLE
Memory leak with https

### ISSUE THREAD

**Issue by philippevk** [mzabriskie/axios#791]
Hi,

it seems there is a slow memory leak with https urls. Consider the following script:

```javascript
#!/usr/bin/env node
const axios = require('axios');
function pingUrl(url) {
  axios.get(url).then(res => { console.log(res.status); });
  setTimeout(pingUrl.bind(null, url), 1000);
}
pingUrl(process.argv[2]);
```

I ran two instances of the script in parallel, one with with an http url, the other with the same url in https.
After 20 hours, the https process uses 10% of my 16GB memory, compared to 0.1% for the http process.

We discovered this issue since we use axios as part of a home made monitoring tool. The tool pings urls at regular interval and we are having memory issues after a while.

**Comment by philippevk** [comment]
Seems to be coming from node itself. Will try the script again when the 7.8 update hits arch.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#7.8.0
Fix memory leak if certificate is revoked (Tom Atkinson) #12089

https://github.com/nodejs/node/pull/12089

Will keep you posted!

**Comment by rubennorte** [comment]
I'm closing the issue then. Feel free to reopen if you discover anything new.
