### ISSUE TITLE
Is there any function equivalent to always (jQquery)?

### ISSUE THREAD

**Issue by Miguel-Frazao** [mzabriskie/axios#792]
I often make an ajax calls with some callbacks with error or not (jQuery ajax always() callback), specially if it's some recursive functionality, ex:
```
$.ajax({
    url: "example.php",
    type: 'get',
  })
  .done(function(resp) {
    alert( "success" );
  })
  .fail(function() {
    alert( "error" );
  })
  .always(function() {
    alert( "complete" ); // <-- always happens
  }); 
```

I was woundering if there is any axios equivalent? Instead of doing this mess:

```
axios.get( "example.php").then(response => {
   alert('success');
   alert('complete'); // <--- same thing here
 }).catch(function (error) {
   alert(error);
   alert('complete'); // <-- and here
 });
```

**Comment by lbausch** [comment]
Try the following (note the second `then`):
```js
axios.post('/api/foo', {
    foo: 'bar'
}).then((response) => {
    // success
}).catch((response) => {
    // error
}).then(() => {
    // always executed
})
```

**Comment by Miguel-Frazao** [comment]
Thank you, It worked. I think we can close now.

**Comment by adi518** [comment]
What if you want to handle `always` globally? it seems to me the only viable solution is wrapping Axios with the pattern above.

**Comment by noobling** [comment]
Thank you I was searching everywhere for this. Is it included in the docs? I couldn't find it.

**Comment by acidjazz** [comment]
2nd vote to get this in the docs

**Comment by braian125** [comment]
> Try the following (note the second `then`):
> 
> ```js
> axios.post('/api/foo', {
>     foo: 'bar'
> }).then((response) => {
>     // success
> }).catch((error) => {
>     // error
> }).then(() => {
>     // always executed
> })
> ```

It must be specified in the official documentation.

**Comment by acidjazz** [comment]
I'd like to point out a couple things:

1. The second `.then()` won't fire if the `.catch()` is not specified.
2. Ultimately I think a `.always()` would be a better solution, for syntactic sugar reasons.
