### ISSUE TITLE
before: (xhr) is not working

### ISSUE THREAD

**Issue by jericopulvera** [mzabriskie/axios#796]
axios.post('/admin/webapi/products/import', form, {
          before: (xhr) => {
            alert(xhr) 
            fileObject.xhr = xhr
          },
          onUploadProgress: function (e) {
             eventHub.$emit('progress', fileObject, e)
           }
        }).then((response) => {
          eventHub.$emit('finished', fileObject)
        }, () => {
          eventHub.$emit('failed', fileObject)
        })

**Comment by rubennorte** [comment]
`before` isn't an axios option. Please review the documentation. You may want to use an interceptor to implement hooks before requests are sent.
