### ISSUE TITLE
.then being called on 400 response

### ISSUE THREAD

**Issue by uptownhr** [mzabriskie/axios#798]
I'm returning 400 from my api but the then is still being called instead of the catch handler. Anybody else experience this before?

**Comment by cekediz** [comment]
I'm having the same issue. 
Using the CDN version.

**Comment by rubennorte** [comment]
Could you provide more context (axios version, environment, etc.) and a code snippet that shows your problem?

**Comment by cekediz** [comment]
I ran into the issue with axios 0.8.7. Using Laravel 5.4 + VueJS 2.2.4.
Seems like the latest axios (0.16.0) has solved the problem for me. Thanks.

**Comment by uptownhr** [comment]
@rubennorte can we please reopen this. I upgrade to the latest 0.16.1 and I am still experiencing this issue.

Code Snippet

```
signPip ({commit}, payload) {

      const {pip_id} = payload

      return axios
        .post(`/pip/${pip_id}/sign`, payload)
        .then( res => {
          commit('setPip', {pip: res.data})
          return res.data
        })
    }
```
Headers: https://ipfs.io/ipfs/QmRMuQP32EJc94VYCPQ7p39ADrX9gHFQL2B9mUv4D1EbEG

This is being used in my Vuejs project. My axios is a newly created instance with some configuration changes as follows.

```
import axios from 'axios'
import debug from 'debug'

import store from '~store'
import router from '~router'

debug('bambee:nuxt')('axios plugin')

let options = {}

if (process.SERVER_BUILD) {
  options.baseURL = `http://localhost:3000/api`
} else {
  options.baseURL = `/api`
}

let apiHandler = axios.create(options)

apiHandler.interceptors.response.use( response => {
  return response
}, error => {
  if ( error.response.status == 401) {
    alert('You have been logged out')
    return store.dispatch('logout').then( res => {
      router.push('/login')
    })
  }
})

export default apiHandler
```

Basically, it contains a baseUrl override and also an error handler that listens on status of 401.

**Comment by slightlytyler** [comment]
For those stumbling across this: you're probably using a response interceptor that is swallowing the error. Unless your interceptor is ending with `Promise.reject(error)` or a throw you're swallowing it
