### ISSUE TITLE
[question] how to get current location after some 302 redirects

### ISSUE THREAD

**Issue by mu-yu** [mzabriskie/axios#799]
I find the url  in `response.request._currentUrl` after print the hole response. but I wonder if there is a clean and nice way to get it.

**Comment by rubennorte** [comment]
I'm guessing you're doing it in Node.js because you can't get the final URL in the browser.

There isn't a clean way to do this now. You can use your solution or `response.request.res.responseUrl` which doesn't access any "private" property.

**Comment by kevinsimper** [comment]
@rubennorte It does not seem to work? :/

**Comment by markspolakovs** [comment]
@rubennorte 

> can't get the final URL in the browser

Can't you use [XMLHttpRequest.responseURL](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL)?

**Comment by kevinsimper** [comment]
I ended up not using the responseUrl, but instead disabled redirect and just used the header location.

```
return axios
        .get(URL, {
          maxRedirects: 0,
          validateStatus: null
        })
        .then(res => {
          expect(
            res.headers.location,
            'to be',
            '/'
          )
        })
```

**Comment by b4hand** [comment]
Is there any reason not to expose `responseUrl` directly on the request returned by axios?

**Comment by syzer** [comment]
👍
