### ISSUE TITLE
error response after a 'redirect after post'

### ISSUE THREAD

**Issue by mu-yu** [mzabriskie/axios#800]
![image](https://cloud.githubusercontent.com/assets/3822774/24398806/68ee4520-13dd-11e7-9c69-3871244318bd.png)
```js
axios({
      method: 'post',
      url: url,
      data: querystring.stringify(formData),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    }).then(response => {
      console.log(response)
    }).catch(err => {
      console.log(err)
    })
```

The code above will fail with code 504,  what i want is response with code 302 or auto redirect.

request do what i want 
```js
request.post({url: url, form: formData/*, followAllRedirects: true*/}, (err,httpResponse,body) => {
      console.log(httpResponse.headers)
})
```

**Comment by rubennorte** [comment]
Redirects are automatically followed by browsers so you can never get the original 302. It seems that you're server is returning that 504 for the second request.
