### ISSUE TITLE
'Network error' on page refresh (Firefox 52.0.1 (64-bit))

### ISSUE THREAD

**Issue by enheit** [mzabriskie/axios#801]
Hello, i've faced with an issue which occurs after page refresh in Firefox (latest Firefox 52.0.1 (64-bit)) browser when request in loading state.

Steps to reproduce:
I make a request to the server which takes around 1 min to response, meanwhile I refreshing current page and my error statement handle with 'Network Error' issue (but in Chrome and IE this issue doesn't occur).

```
axios.post(url, body, config)
   .then(respone => {
    // success response
   }, error => {
      if(error.response) {
         // error response
       } else { 
         // here is 'Network Error' 
       }
    });
```

I use 'else' statement for handle internet problems and redirect user to appropriate page. But its 'Network Error' occurs even though connection is okay.

Here is my screen shot with error object:
![issueaxios](https://cloud.githubusercontent.com/assets/8645216/24407849/c107f9b2-13d4-11e7-895a-bd99e92f9334.PNG)

**Comment by rubennorte** [comment]
It seems a difference on how browsers handle active requests after a reload, not an axios issue. If you're seeing a network error is that the browser notified an error instead of a response (with any status code). Browsers don't provide more information to XHR than "an error occurred".

**Comment by enheit** [comment]
@rubennorte, any idea how to prevent this? Because it is huge issue for my app flow.

**Comment by enheit** [comment]
I have spent a lot of time to find workaround for the issue. 
I fixed it by wrap network issue handler (or bad request handler) in `setTimeout` function.

Solutions looks like this:

```javascript
const request = axios.get(url, config);

request.then(response => { 
    // success response handler goes here 
}, error => {
    const { response } = error; // same as var response = error.response;
    if(response) {
        // error handler goes here
    } else {
       // Here is wrapper for unexpected errors with i-net/request 
       setTimeout(() => {
           // handle unexpected errors
       }, 1000);
   }
}
```
This is workaround for FireFox 52.0.2 (64-bit). Other browsers have no issues with request interruption.

**Comment by rubennorte** [comment]
Why do you even need to handle this? If the user refreshed the page when it was performing an operation it makes sense to display an error.

**Comment by enheit** [comment]
@rubennorte, for example, when user try to make an action and suddenly i-net connection has lost, application will handle this exception. But there is no possibility to compare real i-net connection problem with FireFox request interruption.

**Comment by HarryCaveMan** [comment]
It is a browser compatibility issue. I have used the following as a workaround in leu of just letting the default event reload happen tested this in firefox 59 and chrome:

```
formSubmit = event => {
        event.preventDefault();
        createPost(this.state) //this function contains the axios post request
        .then(() => window.location.reload());
    }
```
