### ISSUE TITLE
How to pronouce axios

### ISSUE THREAD

**Issue by DanielWLam** [mzabriskie/axios#802]
Sorry to border, but, I can't find the pronunciation of this word. Maybe telling the users on top of the README.md would be great!

**Comment by rubennorte** [comment]
I think this is something @mzabriskie should answer, but I don't think there are many ways to pronounce it.

**Comment by stevenvachon** [comment]
acks--ee--oh-ss

**Comment by DanielWLam** [comment]
Thanks
