### ISSUE TITLE
Multipart-Mixed MIME Message with axios

### ISSUE THREAD

**Issue by sanphandinh** [mzabriskie/axios#803]
I need call POST REQUEST with content type: multipart-Mixed; boundary=XXX. 
Body Request sample:
```
--XXX
Content-Type:application/http
Content-Id:ID000001

PATCH /drive/v1/files/56c5f29275d00204?uid=1nofz3czvb&access_token=aUVW5SkwPFkLlA2&device_id=device1&cid=U8W1YDSu2y
Content-Type:application/json; charset=UTF-8
x-sc-appid:tj9u972o46
Accepts:application/json

{"parent":"56c5f28d6d900203"}

--XXX--
```
I added string to data properity in config of AXIOS, but response from server cannot get data: "Request body 'part' - invalid"?
How to implement POST method with content type: multipart-mixed; boundary=xxx and bodyRequest is raw string???

**Comment by bbsimonbb** [comment]
If you're on the browser, you might be able to fill and post a [DOM form](https://www.w3schools.com/jsref/dom_obj_form.asp), and let the browser construct the multipart message?

**Comment by rubennorte** [comment]
You can use a `FormData` object in the browser. In Node.js the feature isn't supported yet by axios (see #789).

**Comment by sanphandinh** [comment]
Thanks you, I fixed it. Because I forget '\r' character when break line.
