### ISSUE TITLE
Axios and zombie.js

### ISSUE THREAD

**Issue by woutrbe** [mzabriskie/axios#804]
Been breaking my head over this issue for a while now, when I use axios in chrome, my response is like this:
```
//response.data
{ id: 23, text: '2323' }
// response.statusText
OK
```

When I use zombie.js to do testing, my response is:
```
// response.data
undefined
// response.statusText
OK
```
When I dig deeper into the response, I can find my data in `response.request.responseText`, which seems weird.

I was trying to use `transformResponse` to deal with this issue, but that doesn't seem to work either

```
transformResponse: [data => {
		console.log('transformResponse');
		console.log(data); --> undefined when using zombie.js, correct when using a regular browser

		return data;
	}]
```

Is anyone else experiencing this issue? Is it related to axios or zombie.js?

**Comment by rubennorte** [comment]
Closing as this seems duplicated from #265.
