### ISSUE TITLE
Support URI Template RFC 6570

### ISSUE THREAD

**Issue by khalidabuhakmeh** [mzabriskie/axios#806]
URI templating is very helpful and a level 1 implementation would be nice. Below is an overview of how the spec would work.
___

 A URI Template provides both a structural description of a URI space
   and, when variable values are provided, machine-readable instructions
   on how to construct a URI corresponding to those values.  A URI
   Template is transformed into a URI reference by replacing each
   delimited expression with its value as defined by the expression type
   and the values of variables named within the expression.  The
   expression types range from simple string expansion to multiple
   name=value lists.  The expansions are based on the URI generic
   syntax, allowing an implementation to process any URI Template
   without knowing the scheme-specific requirements of every possible
   resulting URI.

   For example, the following URI Template includes a form-style
   parameter expression, as indicated by the "?" operator appearing
   before the variable names.

     http://www.example.com/foo{?query,number}

   The expansion process for expressions beginning with the question-
   mark ("?") operator follows the same pattern as form-style interfaces
   on the World Wide Web:

     http://www.example.com/foo{?query,number}
                               \_____________/
                                  |
                                  |
             For each defined variable in [ 'query', 'number' ],
             substitute "?" if it is the first substitution or "&"
             thereafter, followed by the variable name, '=', and the
             variable's value.

   If the variables have the values

     query  := "mycelium"
     number := 100

   then the expansion of the above URI Template is

     http://www.example.com/foo?query=mycelium&number=100

   Alternatively, if 'query' is undefined, then the expansion would be

     http://www.example.com/foo?number=100

https://tools.ietf.org/html/rfc6570

**Comment by rubennorte** [comment]
This is rather complex and most users won't benefit from it, so it won't make it to axios. You can implement it in an interceptor. We would be glad to add it to ECOSYSTEM.md if you create it and open source it.

**Comment by khalidabuhakmeh** [comment]
ok, thank you for the consideration.
