### ISSUE TITLE
Error Response for blob type

### ISSUE THREAD

**Issue by ecmel** [mzabriskie/axios#815]
Hi,

When the responseType is blob, the error response is converted into a blob as well.

Is there a way to specify a different responseType for errors?

**Comment by rubennorte** [comment]
That isn't supported for the moment but you can implement it yourself specifying a custom `transformResponse` function.

**Comment by adriaanmeuris** [comment]
I'm running into the exact same issue. Server returns a blob on success, on error a JSON object is returned containing error details.

The data returned in the transformResponse function is typed to the responseType (responseType `blob`: data is an `[object Blob]`), and there's no context available to know if the request succeeded or not.

An example how to know if the request succeeded and transform it to JSON if it didn't would be greatly appreciated.

**Comment by adriaanmeuris** [comment]
@nickuraltsev since I can't re-open this issue, any guidance on how we can handle this situation?

**Comment by DaveSweeton** [comment]
Same issue for me. I'd like to be able to use a solution like the one referenced here: [https://stackoverflow.com/a/29039823](https://stackoverflow.com/a/29039823)

But it requires access to the onreadystatechange event of XMLHttpRequest, which isn't exposed. TransformResponse doesn't work since it's too late.

**Comment by fritx** [comment]
+1 for this, I implemented a hack for that:

```js
// If the expected response is a blob,
// and error will be returned in json if exsits.
// Here is a hack, works well for me.
// You can put it into `transformResponse`, etc as well.

opts.responseType = 'blob' // <--- force blob at the beginning, anyway

res = await axios(opts)

let blob = res.data // <--- store the blob if it is

let data = await new Promise((resolve, reject) => {
  let reader = new FileReader()
  reader.addEventListener('abort', reject)
  reader.addEventListener('error', reject)
  reader.addEventListener('loadend', () => {
    let data = JSON.parse(reader.result)   // <--- try to parse it as json
    resolve(data)
  })
  reader.readAsText(blob)
})

// Now you have `data` and `blob` at the same time.
// If `data` exists, it would be the error object,
// otherwise, you have the expected `blob`
```

**Comment by adriaanmeuris** [comment]
@fritx works perfect, but indeed a bit hacky. @nickuraltsev any ideas how to improve this? thanks!

**Comment by farskid** [comment]
@fritx Your workaround worked for me on a blob image sent as response. Thanks.

**Comment by nE0sIghT** [comment]
In case of error response with json:

```
let axios = ...instantiate...;
axios.interceptors.response.use(
           response => { return response; },
           error => {
               if (
                 error.request.responseType === 'blob' &&
                 error.response.data instanceof Blob &&
                 error.response.data.type &&
                 error.response.data.type.toLowerCase().indexOf('json') != -1
               )
               {
                 return new Promise((resolve, reject) => {
                    let reader = new FileReader();
                    reader.onload = () => {
                        error.response.data = JSON.parse(reader.result);
                        resolve(Promise.reject(error));
                    };

                    reader.onerror = () => {
                        reject(error);
                    };

                    reader.readAsText(error.response.data);
                 });
               };

               return Promise.reject(error);
           }
       );
```

**Comment by jandrescossio** [comment]
You can eval responseType and 
`async function getResponseBlobError(error) {
    if (!!error.config && error.config.responseType === 'blob') {
        let errorBlob = await error.response.data.text();
        errorBlob = JSON.parse(errorBlob);

       // do something with response data
        error.response.data = {
            message: errorBlob.message,
            errors: !!errorBlob.errors ? errorBlob.errors : {}
        }
    }
    return error;
}`

Function to dowloand files:
`
export function downloadFile(data, filename) {
    const downloadUrl = window.URL.createObjectURL(new Blob([data]));
    const link = document.createElement('a');
    link.href = downloadUrl;
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    link.remove();
}
`

You can use this function in your request:
`      try {
            const response = await axiosApi({
                url: '/api/path',
                data,
                responseType: 'blob',
                method: 'post'
            });
            downloadFile(response.data, `file-name`);

        } catch (error) {
            error = await getResponseBlobError(error);
            // Do something with error
           
        }
`
