### ISSUE TITLE
axios put withCredentials no work

### ISSUE THREAD

**Issue by HuYaoPing** [mzabriskie/axios#816]
Hello my English is not good.I am simple language to talk about my question
I used POST with cross-domain access to resources withCredentials: true no problem. 
Session can be kept

But when I use put. Will not continue on a session. Session id will be different
I am a .net development 

website web.config 

`  <add name="Access-Control-Allow-Methods" value="GET,PUT,POST,DELETE,OPTIONS" />

        <add name="Access-Control-Allow-Origin" value="http://localhost:21265" />

        <add name="Access-Control-Allow-Credentials" value="true" />

        <add name="Access-Control-Allow-Headers" value="Origin, X-Requested-With,Keep-Alive, Content-Type, Accept" />`

client
`axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

axios.defaults.headers.post['Content-Type'] = 'application/json';

axios.defaults.timeout = 100 * 1000;

axios.defaults.withCredentials = true;`

    axios(url, { method:'put', params: params,  withCredentials: true}).then(function (response) {

        console.log(response);

    }).catch(function (error) {
        console.log(error);
    });

Please help answer
Thank you

**Comment by HuYaoPing** [comment]
![2017-04-04_230219](https://cloud.githubusercontent.com/assets/15228611/24663623/0bc2bf94-198b-11e7-9a7f-88f83f283bcd.jpg)
Post no problem


![Uploading 2017-04-04_230247.jpg…]()

**Comment by HuYaoPing** [comment]
@tomaash @idan @lachenmayer Please help me

**Comment by HuYaoPing** [comment]
i test in egde no problem

chrome 50+ was Exception

**Comment by rubennorte** [comment]
This doesn't seem a bug in Axios so please ask for help in StackOverflow or any other forums. We try to keep this only for bugs and feature requests.
