### ISSUE TITLE
IE9 post request can't accept response content

### ISSUE THREAD

**Issue by dean5277** [mzabriskie/axios#819]
Hi,chrome is normal，but ie9 can't accept response content;

![image](https://cloud.githubusercontent.com/assets/1802631/24736876/4e2f95ae-1abd-11e7-9c38-f92cda5da5d1.png)

![image](https://cloud.githubusercontent.com/assets/1802631/24736884/5d6ead66-1abd-11e7-842d-04059d6e5521.png)

response data  is  {"status":200,"statusText":"OK","headers":{"x-powered-by":"Express","content-type":"application/json;charset=utf-8","transfer-encoding":"chunked","date":"Thu, 06 Apr 2017 03:14:45 GMT","connection":"close"},"config":{"transformRequest":{},"transformResponse":{},"timeout":5000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"headers":{"Accept":"application/json; charset=utf-8","Content-Type":"application/json; charset=utf-8","X-Requested-With":"XMLHttpRequest"},"baseURL":"","responseType":"json","method":"post","url":"/user/list","data":"{\"pageNum\":\"1\",\"pageSize\":\"10\"}"},"request":{"responseType":"json"}} 

response conent is success

![image](https://cloud.githubusercontent.com/assets/1802631/24736990/05deb1ee-1abe-11e7-9b6a-f6b6959ada5e.png)

what reason is this?

**Comment by dean5277** [comment]
![image](https://cloud.githubusercontent.com/assets/1802631/24739983/70063bb0-1ad1-11e7-8eb7-19d6577cd1e7.png)
xhr.js   line 67  responseData is undefined;

if (var responseData = config.responseType || config.responseType === 'text' ? request.responseText : request.response;)  i can accept the data;

![image](https://cloud.githubusercontent.com/assets/1802631/24740067/d729d702-1ad1-11e7-8c85-f804421d5e77.png)

**Comment by dean5277** [comment]
![image](https://cloud.githubusercontent.com/assets/1802631/24740485/091d8540-1ad4-11e7-9cd8-764e6586efcf.png)


![image](https://cloud.githubusercontent.com/assets/1802631/24740498/1bad05aa-1ad4-11e7-915d-ee12de68ff4e.png)

**Comment by dean5277** [comment]
if ie9  ,need return request.responseText;

**Comment by rubennorte** [comment]
Closing as duplicate from #265.
