### ISSUE TITLE
Access the onprogress function for an XHR request 

### ISSUE THREAD

**Issue by NervosaX** [mzabriskie/axios#82]
I need to be able to show progress when downloading a zip file (which can be very large,
so it's really necessary). Currently there is no way to access this functionality in axios.

**Example as an xhr request:**
```javascript
var xhr = new XMLHttpRequest();
xhr.responseType = "arraybuffer";

xhr.open("GET", "/url/here/foo.zip", true);

xhr.onprogress = function(e) {
	if (this.status === 200) {
		var curLoadedMB = (e.loaded / 1024.0 / 1024.0).toFixed(2);
		var totalMB = (e.total / 1024.0 / 1024.0).toFixed(2);
		downloadProgress.setProgress((e.loaded / e.total) * 100);
	}
};

xhr.onreadystatechange = function() {
	// ...
}

xhr.send();
```

**Example possible use in axios:**
```javascript
axios({
	url: "/url/here/foo.zip",
	responseType: "arraybuffer",
	progress: function(loaded, total) {
		// ...
	}
});
```

**Comment by wuct** [comment]
+1 for this feature

**Comment by rafaelfragosom** [comment]
+1

**Comment by pandaiolo** [comment]
+1

**Comment by srph** [comment]
Anybody making any progress?

**Comment by willdady** [comment]
+1

**Comment by SZEth8** [comment]
+1

**Comment by Celsius273** [comment]
+1

**Comment by NervosaX** [comment]
@mzabriskie Is this ticket going to be addressed? Not being able to show progress on the front end is pretty debilitating.

**Comment by srph** [comment]
Yes, he even closed a few tickets related to the issue (and referred this). I don't mean to say anything, but I think a rather polite way to say that is by sending a PR :smile:.

**Comment by NervosaX** [comment]
@srph Yeah, there's one listed above that's been open since July.

**Comment by soluml** [comment]
+1

**Comment by IDontEatSoap** [comment]
+1

**Comment by liuq** [comment]
+1

**Comment by srph** [comment]
+1 doesn't help out here. Check out https://github.com/mzabriskie/axios/pull/96

**Comment by chrisfinch** [comment]
Any progress here?

**Comment by YeaseonZhang** [comment]
+ 1
