### ISSUE TITLE
Using an adapter in testing

### ISSUE THREAD

**Issue by shai32** [mzabriskie/axios#820]
I need to add an adapter to axios like this to work with testing (nock):

<pre>
import axios from 'axios';
import httpAdapter from 'axios/lib/adapters/http';
axios.defaults.adapter = httpAdapter;
</pre>

the problem is that it will run in production also, does it has any side effects?
The adapter will be use for any call from client to server.

**Comment by rubennorte** [comment]
You can just configure that in your tests instead of in your production code. E.g.:

```javascript
import axios from 'axios';
import httpAdapter from 'axios/lib/adapters/http';
axios.defaults.adapter = httpAdapter;

describe('your test', () => {
  ...
});
```

**Comment by shai32** [comment]
@rubennorte 
I can't do that, I am testing Redux store and actions.
so in my test file I am dispatching an action:
    const dispatchResult = await store.dispatch(authRequest({}));

authRequest is an action creator that does the api call and adding 
axios.defaults.adapter = httpAdapter;
to the test file doesn't file.

authRequest.js is independent file that define the action creator and does it's own import axios.

**Comment by rubennorte** [comment]
It should work if you assign the default adapter just after importing axios in the test file. axios defaults are global and they work even if you do it in different files.

It should also work if you assign it before dispatching the the action.

**Comment by shai32** [comment]
I tried it but all my test failes, maybe I am doning somthine wrong:
**In my test file:**
<pre>
import axios from 'axios';
import httpAdapter from 'axios/lib/adapters/http';
axios.default.adapter = httpAdapter;

nockApp.post('/auth', credentials).reply(200, data);
</pre>

in my authRequest.js
<pre>

const app = axios.create({
  baseURL: process.env.SEVER_URL,
  timeout: 2000,
});

app.post('/auth', credentials)
</pre>

If I will move the 'axios.default.adapter = httpAdapter' from test file to authRequest.js, every think will work.

what should I do?

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by rubennorte** [comment]
Sorry but this has nothing to do with Axios but with the way you've written your code. Please use StackOverflow or any other means to get help with that.
