### ISSUE TITLE
form-data module not supported?

### ISSUE THREAD

**Issue by jeffijoe** [mzabriskie/axios#822]
Using `FormData` in the browser works perfectly, but when using the Node.js version `require('form-data')`, I get a `socket hang up` error after waiting for like a minute.

Example:

```js
const FormData = require('form-data')
const fs = require('fs')
const axios = require('axios')

const data = new FormData()
data.append('file', fs.createReadStream('package.json'))

axios.post('/upload', data).then(() => console.log('Done'))
```

This works with `node-fetch`.

**Comment by rubennorte** [comment]
It isn't supported for the moment. Also closing as duplicate from #789.
