### ISSUE TITLE
error.response is undefined

### ISSUE THREAD

**Issue by mahelder** [mzabriskie/axios#824]
Hello,  

I have a React App and I am trying use axios interceptors like this: 

`axios.interceptors.response.use(response => {
  return response;
}, error => {
  console.log(error);
});`

On error, the response property is undefined. 

My backend is an Spring Boot Application. I put the annotation @CrossOrigin(origins = "*") and @CrossOrigin(origins = "http://localhost:3000") and do not work.

Can you help me?

**Comment by rubennorte** [comment]
You need to rethrow the error. If you don't axios considers you have recovered from the error.

You can make it work doing it this way:

```javascript
axios.interceptors.response.use((response) => {
  return response;
}, (error) => {
  console.log(error);
  return Promise.reject(error);
});
```

**Comment by mahelder** [comment]
Thankyou @rubennorte for your answer, but this was not the correct solution. The problem was on my backend, with the Cors on the configuration of the OAuthServer.

Thankyou
