### ISSUE TITLE
Cannot set Params key if using .get

### ISSUE THREAD

**Issue by devotox** [mzabriskie/axios#83]
when we do something like
axios({ url: url, params: params }) it works 
but axios.get(url, null, params) does not

the reason i expect this to work would be the exact same thing works if we do
axios.put(url, body, { headers: headers}) it works

**Comment by mzabriskie** [comment]
`axios.get` only accepts two parameters (https://github.com/mzabriskie/axios#axiosgeturl-config). There is no option for passing the body as get requests have no body, whereas post requests do.

**Comment by devotox** [comment]
ha off course i just needed to move the params to the other argument. thank you
