### ISSUE TITLE
Redirect history?

### ISSUE THREAD

**Issue by stevenvachon** [mzabriskie/axios#834]
Does this library provide one?

**Comment by stevenvachon** [comment]
@mzabriskie  @nickuraltsev ?

**Comment by rubennorte** [comment]
There's no support for the complete history but there's a way to get the last url. See #799.

**Comment by stevenvachon** [comment]
Why is there no complete history, at least for Node.js? Controlled isomorphism?

**Comment by stevenvachon** [comment]
@rubennorte ^

**Comment by rubennorte** [comment]
We use `follow-redirects` internally to implement redirections and it doesn't provide it. In case anyone is interested in this, it should be implemented there and then adapted here.
