### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by msudgh** [mzabriskie/axios#836]
I'm making an app with **`NuxtJs`** and after update Axios from **0.15.3** to **0.16.1**, I got bellow error.

```js
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at serialize (/home/masoud/Sources/cynthia-mobile/node_modules/serialize-javascript/index.js:72:20)

```

------
- axios version: *0.16.1*
- Environment: *e.g.: node v6.10.0, chrome 57, ubuntu 16.04*

**Comment by casank25** [comment]
@msudgh So what happened here? I'm getting same issue. Did you find solution to this since you closed it?

**Comment by sladg** [comment]
I'm also interested in a solution.

**Comment by kmeda** [comment]
I am stuck here too :/

**Comment by Nisthar** [comment]
Use `util.inspect(object)` to convert the data into string

**Comment by kmeda** [comment]
const axios = require('axios');
const CircularJSON = require('circular-json');

  axios.get(url, config).then((response)=>{
    let json = CircularJSON.stringify(response);
    res.send(json);
  }).catch((error)=>{
    console.log(error);
});

This worked for me!

**Comment by gopal-g** [comment]
I am not sure why this issue was closed without any hint. :( What is the right fix for this.

**Comment by sepehrvakili** [comment]
Had this issue and this is how I solved it. 
I passed a response interceptor to axios for handling error responses.

```javascript

const handle_axios_error = function(err) {

	if (err.response) {
		const custom_error = new Error(err.response.statusText || 'Internal server error');
		custom_error.status = err.response.status || 500;
		custom_error.description = err.response.data ? err.response.data.message : null;
		throw custom_error;
	}
	throw new Error(err);

}

axios.interceptors.response.use(r => r, handle_axios_error);
axios.post(....)

```

**Comment by kevrowe** [comment]
We're seeing this issue but, extending the above example, it's the `err.request._currentRequest._redirectable` which is a circular reference.

```javascript
request:
   Writable {
     ...
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: '...',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '...',
        _ended: false,
        _redirectable: [Circular], // <----
        parser: null },
     _currentUrl: '...' },
  response: undefined }
```

**Comment by timneedham** [comment]
Not sure why this is closed, it's still occurring... that said @sepehrvakili's workaround works great.
I'm calling Axios, within another Axios promise and hitting this... is that a bad thing?

**Comment by jordvaug** [comment]
This error will also occur if you are try to include the response from axios in your response to as shown below. 
`apiRouter.post(
  "/mtp/:email",
  jwt({ secret: process.env.SECRET }),
  (req, res) => {
    var host = "https://www.mountainproject.com";
    var path =
      "/data/get-user?email=" + req.params.email + "&key=" + process.env.MTPKEY;
    var url = host + path;
    axios
      .get(url)
      .then(response => {
        console.log(response);
        res.json(response);
      })
      .catch(err => {
        res.status(500).send(err);
      });
  }
);`

Simple fix is to make sure you are referencing response.data
`res.json(response.data);`

**Comment by AlamTheInnov** [comment]
I faced the same issue, and i think its because in some cases the object does contain resources information with scalar/Non scalar data types. so i fixed it like this. 

const response = await axios.post('/url', data); 
const jsonText = JSON.stringify(response.data);  
const responseObject = JSON.parse(jsonText); 

Maybe this help someone reading :)

**Comment by emfluenceindia** [comment]
I am having the same issue. Here is my code:

```
const url = "https://subratasarkar.com/process_login.php";

const data = { action: "json_data" };
const response = await axios.post(url, data);

const jsonText = JSON.stringify(response);
const objResponse = JSON.parse(jsonText);
console.log(objResponse);
```

I am outputting the following simple JSON from my PHP web service:
`{"id":"amzn1.account.AGABBMWJLHV7ESFWIS3F7KWVGO6Q","name":"Jenny Morrison","email":"aws.jennym@gmail.com"}`

What I am doing wrong?!

PS: The above JSON output is available at https://subratasarkar.com/process_login.php?action=json_data.

This is a fake user created for testing purpose only hence I am sharing the actual detail.

**Comment by bashaus** [comment]
If anyone else has this issue, for me it was resolve by doing the following:

```
async function() {
  return axios({ ... })
    .then(() => null)
}
```

The cause was that the response was being passed as my lambda response which was not in the correct format.

**Comment by gecko25** [comment]
This fixed my problem after an hour trying to get it! Thanks


> Simple fix is to make sure you are referencing response.data
> `res.json(response.data);`

**Comment by shadownova65** [comment]
> This fixed my problem after an hour trying to get it! Thanks
> 
> > Simple fix is to make sure you are referencing response.data
> > `res.json(response.data);`

Works for me as well.
Thanks!

**Comment by thenameisdavid** [comment]
Anyone using fancy arrow functions: **.then(data => res.json(res.data))** instead of .then(data => res.json(data))

**Comment by xgqfrms** [comment]
```js
const axios = require('axios');
const CircularJSON = require('circular-json');

axios.get(url, config)
.then((response)=>{
  let json = CircularJSON.stringify(response);
  res.send(json);
}).catch((error)=>{
  console.log(error);
});
```
