### ISSUE TITLE
Can't catch CORS  ERROR 

### ISSUE THREAD

**Issue by ray0324** [mzabriskie/axios#838]
Can't get access to axios.interceptors.response whith cors err No 'Access-Control-Allow-Origin' header is present。

**Comment by jcready** [comment]
Browsers make the entire response opaque when preflight responses fail, see [/lib/xhr.js line 85](https://github.com/mzabriskie/axios/blob/22ce6db383bc61adabfd79e5bfe16a7f6c7cebbb/lib/adapters/xhr.js#L85).

**Comment by lrettig** [comment]
I'm running into this too. What's best practice around handling this sort of situation? Is there any way to get more info on what went wrong so we can interpret the error and report it to the user or attempt to intercept the error?

**Comment by jcready** [comment]
The best you're going to do is something like this:

```js
axios.interceptors.response.use((response) => response, (error) => {
  if (typeof error.response === 'undefined') {
    alert('A network error occurred. '
        + 'This could be a CORS issue or a dropped internet connection. '
        + 'It is not possible for us to know.')
  }
  return Promise.reject(error)
})

**Comment by lrettig** [comment]
Thanks. This is incredibly frustrating because when a CORS request fails
and returns a 400 error, we cannot see the error because of this issue. We
can't even see the error code! This makes it very difficult to handle these
errors.

**Comment by jcready** [comment]
Again, this isn't an issue with axios. Browsers will not allow JS to see any response information when there is a CORS issue for security reasons. You can test this yourself with the following:

```js
x = new XMLHttpRequest()
x.onerror = (e) => console.log('THIS IS ALL THE INFO WE HAVE', e, x)
x.open('GET', 'https://www.google.com')
x.send()
```

You'll see that there is no helpful information. There is no way to distinguish between no internet connection, bad DNS, or CORS issues, etc. All you know is that there was a Network Error.

**Comment by lrettig** [comment]
I understand. It has nothing to do with axios and you should probably close
this issue. I'm just lamenting that the situation is pretty dire and
frustrating.

**Comment by gcollombet** [comment]
The issue is also happening when their is a preflight request OPTIONS that is validated by the server (so no CORS error happen, the request is valid, and then a regular request return a 400 error).
OPTIONS 200 OK
POST 400 Bad Resquest <MyPayload>

**Comment by IAMtheIAM** [comment]
I spent hours trying to figure out why I was getting a 400 response. I tried angular's HttpClient, Axios, and jQuery ajax. Finally I realized it was a CORS issue. Lol there goes a few hours.

**Comment by pxwee5** [comment]
https://github.com/axios/axios/issues/838#issuecomment-304033403

@jcready Can this not be implemented into Axios core as default?

**Comment by inspire22** [comment]
This old, but IMO rendering a console message is the way to handle this, it should create an error with e.message set to the cors error, rather than the generic "Error: Network Error" that is the default.

**Comment by jcready** [comment]
@inspire22 if you read through the old comments on this thread you'll see that axios has no way to know it is anything more specific than a network error.

**Comment by inspire22** [comment]
Oops, my bad.  Definitely not a good design choice / bug by chrome, so we get confused people like me here :)  Thanks for being a part of this nice project!
