### ISSUE TITLE
Question: AngularJS $http API compatibility?

### ISSUE THREAD

**Issue by petejohanson** [mzabriskie/axios#84]
For my [hy-res](https://github.com/petejohanson/hy-res) hypermedia client library, which also has a thin AngularJS wrapper [angular-hy-res](https://github.com/petejohanson/angular-hy-res), most of the library expects an `$http`-like API for making and consuming requests. For the most part, I can interchange axios (e.g. in my integration tests for the hy-res core library) and `$http` in the angular-hy-res case without problem.

The only area where I have hit a true API incompatibility is with the handling of the `headers` in either the resolved promises, or the parameters for things like `transformRequest`. You can see an example [here](https://github.com/petejohanson/hy-res/blob/master/src/form.js#L69-L71).

Question: Is axios' goal to be as API compatible with `$http` as possible? If so, would you consider changes to the `headers` instances to match AngularJS?

**Comment by mzabriskie** [comment]
It's not necessarily a goal to be 100% API compatible with `$http`, at the same time, if it's easy enough to support I'm not against it.

Would you mind elaborating a bit more on where the incompatibility lies? From your example, it looks like headers can be a function?

**Comment by petejohanson** [comment]
AFAICT, headers is *always* a function in AngularJS. Here's the relevant source:

https://github.com/angular/angular.js/blob/master/src/ng/http.js#L192

You can either do:

```
headers('location')
=> '/foo'
```

or:

```
headers()
=> { 'location': '/foo', 'content-type': 'application/json' }
```

**Comment by mzabriskie** [comment]
The `headersGetter` function is only used internally by Angular. This allows either getting the entire headers object passed in the config, or a specific header value by name (case insensitive).

The config itself expects an object of key/value pairs https://docs.angularjs.org/api/ng/service/$http#setting-http-headers.

**Comment by petejohanson** [comment]
It is *not* only internal. See:

* https://github.com/angular/angular.js/blob/master/src/ng/http.js#L1268 - passed as `headers` field of response promise.
* https://github.com/angular/angular.js/blob/master/src/ng/http.js#L918 - passed into transformation function.

You can see this in the docs here: https://docs.angularjs.org/api/ng/service/$http under the Usage of `$http(config)` for `transformRequest`, `transformResponse`, and the return value.

Those are in fact the two cases where the API differs between `$http` and axios.

**Comment by patrickliechty** [comment]
Are there any plans to create a $httpBackend type feature so you can mock out http requests?  $httpBackend also makes testing synchronous with $httpBackend.flush().  Are there any plans to follow this way of testing?

**Comment by mzabriskie** [comment]
@patrickliechty I don't know the exact implementation that will be used, but there are plans to make testing less painful.

**Comment by petejohanson** [comment]
So is there any intention to change this difference in API between the two? This was closed without explanation...

**Comment by nickuraltsev** [comment]
Reopening... Let me take a closer look at this.

**Comment by mzabriskie** [comment]
@patrickliechty check out [moxios](https://github.com/mzabriskie/moxios) for testing axios.

**Comment by mzabriskie** [comment]
It is not the intention of axios to function exactly the same as $http. This lib was definitely inspired heavily by $http, but I am okay with it diverging from here. If there is a strong argument for a feature that you think would make sense in axios I am happy to discuss, but I am not interested in copying $http feature for feature.

**Comment by patrickliechty** [comment]
I will look into moxios thanks.  Ya I don't think it has to work just the same as $http
