### ISSUE TITLE
Axios 0.16.1 adds buffer.js to the browser bundle, tripling its size

### ISSUE THREAD

**Issue by albertogasparin** [mzabriskie/axios#846]
#### Summary

It looks like latest version includes `buffer.js` on the browser bundle even if not actually used.
This makes axios bundle size **3 times bigger**, adding 22kB to the minified size (0.16.0 is 11.9 KB while 0.16.1 is 33.9kB).

#### Context

- axios version: v0.16.1

**Comment by fgnass** [comment]
In the meantime (if you're using webpack) you can add the following to your webpack.config.js to get the bundle size back to normal:

```
{
  node: {
    Buffer: false
  }
}
```
