### ISSUE TITLE
Request hangs behind corporate https_proxy using new axios versions

### ISSUE THREAD

**Issue by tjausten** [mzabriskie/axios#847]
Https request hangs behind corporate proxy when using axios, versions 0.15.3 and above, using the following test code:

```
var axios = require('axios'); 

let httpsProxyAgent = require('https-proxy-agent');
var agent = new httpsProxyAgent(process.env.https_proxy);
var testApi = 'https://www.google.com';

var config = {
  baseUrl: testApi,
  url: '/',
  httpsAgent: agent
}

axios.request(config).then((res) => console.log(res)).catch(err => console.log(err))
```

The corporate proxy is pulled in using the process.env.https_proxy variable.

```
export http_proxy=http://username:password@proxy.company.com:8099
export https_proxy=$http_proxy
```

Google is not blocked by the corporate proxy.

- axios version: *e.g.: v0.15.3*
- Environment: *e.g.: node v6.9.5, OSX El Capitan v10.11.6*

**Comment by eddiewang** [comment]
@tjausten did you ever figure this out?

**Comment by tjausten** [comment]
Hey Eddie, thanks for your response. We found out that the issue was with the SDK we were using rather an issue with Axios itself. I will close this issue.
