### ISSUE TITLE
err with cancelToken

### ISSUE THREAD

**Issue by rainwalkerhu** [mzabriskie/axios#848]
here is my default config 
axios.defaults.cancelToken = new axios.CancelToken(function (c){
                //一个执行器函数接收一个取消函数作为参数
                _this.cancel = c;
            })
but it throws err:
TypeError: config.cancelToken.throwIfRequested is not a function
    at throwIfCancellationRequested (dispatchRequest.js:13)
    at dispatchRequest (dispatchRequest.js:24)

what can i do?

**Comment by SudoPlz** [comment]
I'm getting the same error, did you find a solution @rainwalkerhu ?

**Comment by hesher** [comment]
same here

**Comment by SudoPlz** [comment]
I'm a bit disappointed with the cancellation token system. I thought that I could just have several tokens and cancel only the requests assigned to each of those tokens, but apparently I can only make 1 token and cancel requests from that.

**Comment by hesher** [comment]
I use axios cancelToken to cancel all requests when running in a testing environment:

```
export const axiosCancelToken = axios.CancelToken.source();
axios.defaults.cancelToken = axiosCancelToken.token;
```

and then from the tests:
```
axiosCancelToken.cancel('Cancelling all remaining requests after tests ended');
```

Is this not the right way to work with cancelToken?

**Comment by rubennorte** [comment]
Please take a look at https://github.com/mzabriskie/axios/issues/978#issuecomment-323174552
