### ISSUE TITLE
API calls not working Android 5.0 in Release build

### ISSUE THREAD

**Issue by ashwinkumarsarangula** [mzabriskie/axios#849]
Hello,
I am working on a Cordova Application and have been using axios for making REST API calls.It is working well in all versions, except for Android 5.0 devices and that too on signed APKs.The debug builds are also working fine.Please help me on this.

**Comment by rubennorte** [comment]
That doesn't look like an issue in axios but you haven't provided enough information for us to find out. Please, make sure it's an issue in axios and share a code snippet where something fails (and please be more specific about the error).
