### ISSUE TITLE
Update of axios 0.15.3 to 0.16.1 causes TypeScript error

### ISSUE THREAD

**Issue by smares** [mzabriskie/axios#850]
I have just updated axios from 0.15.3 to 0.16.1 and now I get the following TypeScript compile error:

> error TS2305: Module '"/home/sm/Code/foobar/node_modules/axios/index"' has no exported member 'Promise'

Downgrading back to 0.15.3 for the time being.

**Comment by kokizzu** [comment]
confirmed: `0.16.1` shows an error:
```
ERROR in [at-loader] ./node_modules/axios/index.d.ts:61:39 
    TS2304: Cannot find name 'Promise'.
```

**Comment by nickuraltsev** [comment]
Please see upgrade instructions here: https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#015x---0160
