### ISSUE TITLE
How to enable GZIP compression to get requests to API Calls

### ISSUE THREAD

**Issue by ptums** [mzabriskie/axios#851]
#### Summary

I am using axios to make a GET API call and want to know if it is possible to edit the headers of the call to enable gzip compression. 

This is my code so far. Is there anything I should add to it?
```
const helpers = {
	getAttorney:()=>{
		return axios({
			method: 'get',
			url:'/wp-json/wp/v2/attorney?per_page=100',
			headers: {
        'Content-Encoding': 'gzip'
    }})
		.then((data)=>{
			const info  = data.data;
			if(info){
				info.sort(function(a, b){
				    var nameA=a.last_name.toLowerCase(), nameB=b.last_name.toLowerCase()
				    if (nameA < nameB) //sort string ascending
				        return -1
				    if (nameA > nameB)
				        return 1
				    return 0 //default return value (no sorting)
			})
			}
			return info
		}).catch((error)=>{
    		console.log("error from api call..", error);
  		});
	}
}
module.exports = helpers;


```

#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: React.js, Wordpress*

**Comment by sunnykgupta** [comment]
Generally, browsers automatically add the necessary gzip enabled headers, just like they inject cookies automatically over on XMLRequests.

Did you check if your server has gzip enabled?

**Comment by ptums** [comment]
I did.. I use wp-engine hosting and they said they'd have to retool there entire hosting platform to enable gzip for api calls. Though it may be available in the near future.

**Comment by sunnykgupta** [comment]
So it would have to be supported by the server. You are sending the correct headers in your request.

**Comment by argos83** [comment]
Just for the sake of completion: You seem to want gzip compression on the 'response' body of a get request (since a a GET request shouldn't have a body, so there's nothing to compress). If that the case, the header you are sending it's wrong.. The encoding negotiation is done via the `Accept-encoding` header. See [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) for more details.
