### ISSUE TITLE
has no method like XMLHttpRequest ontimeout ?

### ISSUE THREAD

**Issue by zhaozailin** [mzabriskie/axios#852]
when get a error callback, how to check it is timeout?
like this:
var xhr = new XMLHttpRequest();
xhr.ontimeout = function (e) {
  // XMLHttpRequest timeout do something。
};

**Comment by Sekhmet** [comment]
Just handle it with `catch`.
[https://github.com/mzabriskie/axios/blob/f31317aeca8f7fa385d6aee94ef6ec8ac9d7c072/lib/adapters/xhr.js#L94](ontimeout)

```js
axios.get('https://example.com/api')
    .then((response) =>
        console.log('Success')
    )
    .catch((error) => {
        if (error.code == 'ECONNABORTED') {
            // Timeout.
        }
    });
```

**Comment by zhaozailin** [comment]
thanks
