### ISSUE TITLE
Charset utf8 fixed in header

### ISSUE THREAD

**Issue by andrejunqueira1** [mzabriskie/axios#859]
i'm using axios in my RN app, when i make a post request with Content-type=application/json, the axios aways place ";charset=utf-8" in the end of Content-Type, and the api that i'm using don't recognize the data because the charset is set as utf-8.

**Comment by setzer777** [comment]
Anyone? Having the same problem

**Comment by narodejesus** [comment]
yes we are having the same problem in android

**Comment by beeetooo** [comment]
It happened to me, but it suddenly started working.
```js
axios.defaults.headers['Content-Type'] = 'application/json';
```

Can you guys put a screenshot of your request?

**Comment by WhiteFur** [comment]
I have the same problem, and solve it by adding `headers: {'Content-type': 'application/json'}` to the request config.

**Comment by rubennorte** [comment]
You service should have a better content negotiation strategy, as adding the charset to the content type is perfectly valid.

**Comment by MrSandmanEndless** [comment]
@rubennorte What kind of answer is this? Sure, the service may need improvement, but that solve the problem? And for those developing for third party API and unable to improve it? So, that's ok not being able to configure the request at our will? If you don't want to help, ok. But close the topic with this kind of attitude, without providing any guidance. Shameful.

**Comment by kitsuyui** [comment]
@rubennorte 

I think the point of the problem is not just adding. It does replacing.

This replacing happens when the original charset is not only UTF-8, but latin-1, Chinese, Japanese(), etc too. Even if specifying other charset explicitly.

Axios overwrites these Content-Type setting and replace it to `Content-type: application/json;charset=utf-8`.

So web services cannot treat its original charset.

**Comment by dougludlow** [comment]
I'm running into problems where axios is seemingly setting the charset and not honoring my default configured `Content-Type`. It works fine for a while, then all requests have the charset appended to the `Content-Type` at some point and so requests to the API I'm consuming are failing because it doesn't recognize `application/json;charset=utf-8` as a valid format.

**Comment by beeetooo** [comment]
@dougludlow I ran into that same problem, let me tell you how I solved it (if I remember correctly haha)

I created a file called `client.js` and I did something like
```
import axios from 'axios';

const client = axios.create({
  baseURL: BACKEND_URL
});

client.defaults.headers['Content-Type'] = 'application/json';

return client;
```

And then I made all my gateways or repositories to use that client module to make calls to the back end, and I solved that horrible `application/json;charset=utf-8` problem.

Hopefully that can solve your problem 🙌

**Comment by beeetooo** [comment]
Lol it's good to know where that line was hahaha.
Yeah, tbh I don't work anymore at the codebase where I had to fix that problem, but I'm pretty sure I solved that problem by putting that line of 
`client.defaults.headers['Content-Type'] = 'application/json';`

If not, maybe you can try by replacing `client` with `axios`, and if that doesn't work, at least I tried 😿I'm pretty sure it'll get solved :+1:

**Comment by beeetooo** [comment]
Let me know if that fixed your problem @dougludlow :+1:

**Comment by dougludlow** [comment]
@beeetooo honestly, I'm not sure, I ended up using your solution as well as the interceptor I posted above. Which is probably overkill, but I really need to make sure this doesn't break. So far so good.

**Comment by SEUH** [comment]
This is still an error. I don't know why to hard override the content type. We have implemented a fix on the server side but this should not happen.

**Comment by SeinopSys** [comment]
Needed to get response data from a server that sent back a web page using `windows-1251` encoding specified in the response body.
```
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
```
I could not make axios decode it properly, but `node-fetch`'s `textConverted` method did the trick.

**Comment by alexandr2110pro** [comment]
This "feature" breaks BambooHR API. For example 
`https://documentation.bamboohr.com/reference#add-employee-1`
