### ISSUE TITLE
Setting header: 'Content-Type': 'application/json' is not working

### ISSUE THREAD

**Issue by alejandronanez** [mzabriskie/axios#86]
Hi. I'm passing a custom header like this
```js
axios.get('my/url', {
    headers: {
        'Content-Type': 'application/json'
    }
})
``` 

But it doesn't seem to work. Any ideas?

**Comment by mzabriskie** [comment]
There was an issue with Content-Type having to be cased correctly (see #89). I just fixed it a few minutes ago. Maybe this was the same issue you were experiencing?

**Comment by alejandronanez** [comment]
Well, I wasn't able to send the header 'Content-type' at all on my request. @mzabriskie let me give it a try and I'll let you know.

Thanks.

**Comment by mcmire** [comment]
This doesn't appear to be working for me, either. It looks like perhaps it's this line here? https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L77

**Comment by aprzywara** [comment]
Is your request body empty by any chance?
For me manually passing **data: null** to axios, in order to manually set an empty body, prevented IE from sending **undefined** as body.

**Comment by mcmire** [comment]
Yeah, the request body was empty.

On closer inspection, it appears that Axios is doing the right thing here. Content-Type only applies to the request body, so if it's missing then it shouldn't pass along that header.

**Comment by aprzywara** [comment]
Yes it is correct to remove the headers, you need to pass on an empty body though (IE does not do that, it passes *"undefined"* which triggers errors in some/most backends).

We are using  [Restler](https://github.com/Luracast/Restler) in a project to serve JSON and Restler was throwing 403 errors because the *"undefined"* string gets passed as *Content-Type: text/plain* which doesn't work.

**Comment by dinodsaurus** [comment]
Yep, I can confirm. If there is no data passed it deletes the Content-Type...
I just added `data: {}` to my `GET` request, and it works fine.
It's really weird do pass data on get request but I don't mind :+1:

**Comment by mcmire** [comment]
I'd vote for this issue to be closed, then. @alejandronanez what do you think?

**Comment by reznord** [comment]
@mzabriskie currently, I am doing: 

```
return request
    .get(`/play/audio/${soundFile}`, {headers: {'Content-Type': 'audio/wav'}, data: {}})
    .then(response => response.data)
```

still, when I see the network tab, I am seeing `Content-Type: text/plain`

Can anyone tell me where I might be going wrong?

**Comment by teleyinex** [comment]
This stills an issue. You need to specify the data:null or data:{} to get it to work :-)

**Comment by mcmire** [comment]
@teleyinex `Content-Type` describes what format the request data is in. If there is no request data, there is no need to specify the `Content-Type`. So you can correct me if I'm wrong but I believe the present behavior makes sense, aside from the fact that it should still not add the header if `data` is null. What do you think?

**Comment by teleyinex** [comment]
@mcmire then I agree completely. But, it might be good to add this to the docs, so others can easily find it.

**Comment by mcmire** [comment]
Yeah, agreed about that, it's definitely something worth documenting.

**Comment by teleyinex** [comment]
One example in the README will do the trick :D

**Comment by BenAhlander** [comment]
SignIn = () => {
        console.log('login clicked')
        let data = JSON.stringify({
            password: this.state.password,
            username: this.state.email
        })

        axios.post('url', data, {
            headers: {
                'Content-Type': 'application/json',
            }
        }
        )
    }

**Comment by boon4376** [comment]
Just for other people Googling, this is how I had to format my axios.post request

```
    var postData = {
      email: "test@test.com",
      password: "password"
    };

    let axiosConfig = axios.create({
      headers: {
          'Content-Type': 'application/json;charset=UTF-8',
          "Access-Control-Allow-Origin": "*",
      }
    });

    axios.post('http://<host>:<port>/path', postData, axiosConfig)
    .then((res) => {
      console.log("RESPONSE RECEIVED: ", res);
    })
    .catch((err) => {
      console.log("AXIOS ERROR: ", err);
    })
```

**Comment by EJIqpEP** [comment]
Is there a particular reason to remove content-type in this line if data is not provided?
https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L135
Why my get request can't have content-type: application/json? 
This is super strange to write everywhere 
```
await axios.get(url, {data: null})
```

**Comment by EJIqpEP** [comment]
Thanks for clarifying @dinodsaurus.

**Comment by mcmire** [comment]
@SirSerje While it is probably a good idea to set a default `Accept` header, I just want to point out that the `Accept` header isn't the same as `Content-Type`. The `Content-Type` tells your server the format you, as the client, are sending the server. `Accept` tells your server the format in which you, as the client, want response data.

This bears repeating: if you're here and you want `Content-Type` to always be set because you're using it on the server side to figure out which format to send data *back*, then that's incorrect; you want to be using `Accept` instead. See [this SO question](https://stackoverflow.com/a/35722727).

**Comment by SirSerje** [comment]
@mcmire I've just needed to fix the hole quickly. Now I can go by more sophisticated way, thank you for clarification.

**Comment by adamrbennett** [comment]
If a user of this package wants to set a `Content-Type` header without a body, shouldn't they be able to do that? I don't see the argument for limiting the use here by either forcing a dummy payload or preventing the `Content-Type` header from being set. This choice should be up to the user unless there is a good reason to prevent it.

**Comment by damien-roche** [comment]
If you want to apply this across all your requests (as in my case), you can do this:

`axios.defaults.headers.common.Accept = 'application/json';`

No need to specify `null` data, etc, Just Works.

**Comment by DrCord** [comment]
This comes up for AWS API Gateway endpoints - you want to do a PUT request to an endpoint that expects content type of application/json and the request doesn't work unless you send an empty body, which is contrary to how a PUT request should be sent...

**Comment by vukienha** [comment]
> Is there a particular reason to remove content-type in this line if data is not provided?
> https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L135
> Why my get request can't have content-type: application/json?
> This is super strange to write everywhere
> 
> ```
> await axios.get(url, {data: null})
> ```

you save my life

**Comment by madroneropaulo** [comment]
This is still an issue. I have to do this
    ```
axios.post(url, myData, {
            data: null,
            headers: {
                'Content-Type': 'application/json'
            },
        })
```

**Comment by marcocali** [comment]
Please reopen this ticket. This is still an issue for me too.

Currently performing a `PUT` with `file` and `Content-Type` header.  
`Content-Type` header is lost, unless I add `data:{}` to the `config`. But then the `file` get lost if I do that.

`  componentDidUpdate(prevProps: Props) {
    if (prevProps.preSignedURL !== this.props.preSignedURL) {
      const data = new FormData()
      data.append('file', this.state.file)
      const config = {
        headers: {
          'Content-Type': 'video/mp4',
        },
        onUploadProgress: progressEvent => this.handleUploadProgress(progressEvent),
      }
      axios
        .put(this.props.preSignedURL, data, config)
        .then(() => this.handleUploadCompleted())
        .catch(() => this.handleUploadFailed())
    }
  }`

**Comment by ziaulrehman40** [comment]
Something weird, or just something related to rails, but when i append `.json` at the end of the url for my put request, it correctly goes as json request.

Was struggling for some time on this issue.

**Comment by maxflex** [comment]
Reopen the issue

**Comment by arefaslani** [comment]
@ziaulrehman40 @alejandronanez It seems you guys are using Rails and expect Rails to respond with JSON. The problem is that you're setting the wrong HTTP header to accept JSON as a response. The header you should set is `Accept`:

```js
axios.get('my/url', {
    headers: {
        'Content-Type': 'application/json',
         Accept: 'application/json'
    }
})
```

**Comment by dariuszsikorski** [comment]
I found a workaround by simply setting empty data in the request, so Axios assumed the `Content-Type` is `application/json;charset=utf-8`, but even if it works I would prefer Axios to respect every type of header in GET request.

Hope this helps. 

```
axios.get(some/url', {
  data: {},
})
```

**Comment by manhengest** [comment]
this example fixed for me the issue

  ```
    axios({
        method: 'get',
        url: '/url',
        headers: {'X-Requested-With': 'XMLHttpRequest'},
        params: {
          category_id: 3,
          page: this.page,
        },
      }).then(response => {

      }).catch(error => {
        console.log(error);
      });
```
