### ISSUE TITLE
'Content-Type': 'multipart/form-data'  Can not work normally

### ISSUE THREAD

**Issue by harrydengchao** [mzabriskie/axios#860]
I use {'Content-Type': 'multipart / form-data'} to upload files but not work
I use the following code：
```javascript
let formBox = new FormData();
formBox.append('file', files[0]);
axios({
	method: 'post',
	url: api.pushZipFile,
	data: formBox,
	headers: {'Content-Type': 'multipart/form-data'}
})
```
Return the following results：
![image](https://cloud.githubusercontent.com/assets/13941171/25391997/16ea9ca4-2a0a-11e7-92d6-08c56736acd3.png)
![image](https://cloud.githubusercontent.com/assets/13941171/25392040/3429dfaa-2a0a-11e7-854f-751db8f0747f.png)

I refer to Issues to find a solution, but it did not succeed.
https://github.com/mzabriskie/axios/issues/318

**Comment by harrydengchao** [comment]
This problem has been resolved.
Problem Cause: When I pass the default parameters to create the instance, my FormData object is converted to an empty object.
```javascript
let configDefault = () => {
  return {
    method: 'post',
    url: '',
    responseType: 'json',
    data: {},
    params: {},
    transformRequest: [function (data) {
      return data;
    }],
    transformResponse: [function (data) {
      return data;
    }]
  }
}
Axios.create(defaultConfig())
```

Workaround: When creating an instance, the default parameters are not passed.
```javascript
Axios.create()
```

---
I do not know why this is so, perhaps, only I am a person to encounter this problem

**Comment by yss14** [comment]
Got into the same problem. Applying your workaround, do you also see as `request payload` in chrome `[object Object]`?

**Comment by stop2stare** [comment]
@yss14 I've got the same problem with you. Have you figured it out?

**Comment by yss14** [comment]
@stop2stare Unfortunally not, I temporally switched to jQuery ajax for media uploads until I figure out, what the problem with axios is.

**Comment by stop2stare** [comment]
@yss14 I've switched to Vue-Resource...

**Comment by harrydengchao** [comment]
@yss14 You may need to check whether the Content-Type settings are correct。Maybe you have solved the problem

**Comment by tmaly1980** [comment]
I get the same '[object Object]' string in the payload. Anyone figure this out?

**Comment by CliveTeow** [comment]
I also get the [object Object] in the payload, is it correct?

**Comment by tmaly1980** [comment]
I believe this may just be because of using a debugger with Network Inspect enabled. Just some sort of limitation with file uploads. Try turning Network Inspect off (or the debugger off).

**Comment by CliveTeow** [comment]
I am not sure why I keep getting invalid parameter response.

**Comment by CliveTeow** [comment]
![screen shot 2017-12-14 at 4 54 58 pm](https://user-images.githubusercontent.com/19527543/33983605-bf0324aa-e0ef-11e7-9409-8ecb5a5850b7.png)
@tmaly1980 , does it looks correct? The upload_file is still [object object]

**Comment by tmaly1980** [comment]
@CliveTeow Like i said, you can't inspect file uploads on the client side... It's something you'll have to diagnose/test on the server side exclusively. You have to disable network inspection with your debugger for it to work.

**Comment by jeffersontpadua** [comment]
@harrydengchao Thanks for the insight. So, for anyone still struggling with this, you have to override the "transformRequest" configuration option, and let it return the data, instead of formatting it to JSON. Something like this:

Axios({
      url: process.env.API,
      data,
      method: 'POST',
      headers: {
        'Content-Type': 'multipart/form-data',
        Authorization: `Bearer ${getCurrentToken()}`,
      },
      transformRequest: (data, request) => { // This is all that matters
        return data;
      },
    });

**Comment by KangYoosam** [comment]
What @tmaly1980 said (turning off network inspect of ReactNativeDebugger) solved my problem.

turning on ReactNativeDebugger affects real form upload
