### ISSUE TITLE
application/json    error

### ISSUE THREAD

**Issue by Jarvens** [mzabriskie/axios#861]
Request URL:http://localhost:8088/sys/user/login
Request Method:POST
Status Code:415 Unsupported Media Type
Remote Address:[::1]:8088
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Access-Control-Allow-Headers:Origin,content-type,No-Cache, X-Requested-With, If-Modified-Since, Pragma, Last-Modified, Cache-Control, Expires
Access-Control-Allow-Methods:POST,UPDATE,PATCH,DELETE,OPTIONS
Access-Control-Allow-Origin:*
Access-Control-Max-Age:3600
Content-Language:en
Content-Length:1048
Content-Type:text/html;charset=utf-8
Date:Tue, 25 Apr 2017 16:03:30 GMT
Server:Apache-Coyote/1.1
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Content-Length:37
Content-Type:application/x-www-form-urlencoded, application/json
Host:localhost:8088
Origin:http://localhost:9000
Pragma:no-cache
Referer:http://localhost:9000/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Request Payload
view source
{account: "45346", password: "5436"}
account
:
"45346"
password
:
"5436"

this is my setting
axios.defaults.headers.post['content-type'] = 'application/json'

Vue.prototype.$http = axios

**Comment by rubennorte** [comment]
Sorry but this doesn't point to any actual error in Axios. If you have a concrete use case with examples of Axios failing please reopen with more details.

**Comment by Jarvens** [comment]
Thank you. This is not axios error, it has ended
