### ISSUE TITLE
Track timeout issues

### ISSUE THREAD

**Issue by andresmijares** [mzabriskie/axios#862]
I'm looking for an easy way to be able to track timeout issues without affecting the current behavior, something like `a timeout callback` would be great.

Let's say, I want to track/send a notification to a given message system each time a request takes more than `x` number of milliseconds, without canceling the request, is there a way to get a default config for this? or a single way to tag a request cancelation when it happens cause a timeout?

**Comment by cycold** [comment]
Yeah, Me too.
currently, 

```js
.catch(error => {
          console.dir("error: ", error)
          if (error.code == "ECONNABORTED" && ~error.message.indexOf("timeout")) {
            console.error(error.message)
            Vue.$ui.toast.show({
              text: "request timeout",
              time: 2500,
              type: "error",
            })
        }
```

**Comment by zcoding** [comment]
+1

**Comment by rubennorte** [comment]
You can do this using interceptors so a specific feature for this isn't likely to be implemented.

**Comment by pvinis** [comment]
@rubennorte an example would be nice.

**Comment by hitchcockwill** [comment]
@pvinis 

```
axios.interceptors.response.use((response) => {
  return response;
}, (error) => {
  if (error.code === 'ECONNABORTED') {
    // do a thing
  }
  return Promise.reject(error); 
});
```
