### ISSUE TITLE
Could an Axios request be automatically retried/duplicated by browser, due to connection issues?

### ISSUE THREAD

**Issue by leonardobaggio** [mzabriskie/axios#864]
## Summary

Hi! I'm getting some of my POST requests duplicated at my API, and I was wondering if an axios request could have been automatically retried/sent again in case of connection failure, reset, or any other reason.

As this is a random behavior and it's happening in production/users machines, it is being a kinda difficult to collect any evidence. Maybe you guys have experienced, or have acknowledge of something similar to my scenario.

All users that reported duplication in their actions also experienced a abnormal wait time.

I have checked the action creator that calls axios.create, and it is being dispatched just one time by an onClick event. 

Thanks in advance!

## Context

- "axios": "^0.15.3"
- "react": "15.0.2",
- "react-redux": "^4.0.0",
- Chrome 58.0.3029.81 (64-bit), Windows 10 64-bits
- Asp.net WebApi

**Comment by nouveller** [comment]
Interestingly I'm using Axios and also receiving duplicate requests. I'm triggering them via Redux Sagas and using recipe to throttle the HTTP requests, tested manually trigger 10 requests simultaneously and the throttling works just fine.

After a period of time, duplicate requests start to show up. Oddly it only seems to occur on Android in release mode.

**Comment by leonardobaggio** [comment]
@nouveller I've found out that a late loading state feedback for the users was causing this behavior.

Some people stills double-click stuff on websites. It was naive not to have prevented this by code.

```
export const contentPost = (props) => {
    return function (dispatch) {
        dispatch({ type: CONTENT_POST_ERROR, payload: null })
        dispatch({ type: CONTENT_POST_LOADING, payload: true });
        dispatch({ type: CONTENT_POST_SUCCESS, payload: null })

        const request = axios({
            method: 'post',
            url: `/api/content`,
            headers: auth.getHttpHeader(),
            validateStatus: function (status) {
                return status >= 200 && status < 300; // default
            },
            data: props
        }).then((res) => {
            dispatch({ type: CONTENT_POST_LOADING, payload: false });
            dispatch({ type: CONTENT_POST_SUCCESS, payload: true, data: res })
        }).catch(err => {
            dispatch({ type: CONTENT_POST_ERROR, payload: err.code })
            dispatch({ type: CONTENT_POST_LOADING, payload: false });
            dispatch({ type: CONTENT_POST_SUCCESS, payload: false, data: null })

        });
    }
};
```

There are a lot of ways to accomplish a better user experience in this scenario. I chose to completely change the button while user are sending stuff, using the CONTENT_POST_LOADING state.

```
{this.props.content_post_loading &&
    <a className="btn btn-primary disabled">Creating...</a>
    ||
    <a className="btn btn-primary" onClick={this.handleCreateClick}>Create</a>
}
```
