### ISSUE TITLE
Interceptor didn't work correctly.

### ISSUE THREAD

**Issue by umair-khanzada** [mzabriskie/axios#865]
Interceptor didn't update header immediately, update header after one request.
Ex: 
```
//Interceptor.

axios.interceptors.request.use((config) => {
  let token = localStorage.getItem('token');

  //console is showing token but didn't add in request header
  console.log("token", token)

  if(token){
    axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
  }
  return config;

}, (error) => {
  return Promise.reject(error);

});



//Login Request.
return axios.post(`auth/local`, obj)
    .then(res => {
      localStorage.setItem('token', res.data.token);

      //get user data request.
      return axios.get(`users/me`)
  })
    .then(user => user.data)
    .catch((error) => {
      return error
    });
```

**Comment by rof20004** [comment]
I am with the same problem, my interceptor not update headers, only if I refresh page

**Comment by ir-fuel** [comment]
You should add the header to the `config` object. What you did is add them to the global axios object, so they will only be used on the next request.

**Comment by moljac024** [comment]
axios.interceptors.request.use((config) => {
  let token = localStorage.getItem('token');

  //console is showing token but didn't add in request header
  console.log("token", token)

  if(token){
    return {
      ...config,
      headers: {
         ...config.headers,
         'Authorization': `Bearer ${token}`
      }
    }
  }

}, (error) => {
  return Promise.reject(error);

});

**Comment by atomboulian** [comment]
I am having the same issue. We have multiple axios services so we made a redux middleware function to take in the service, get the token out of the action or the state depending on whether they simply log in or check the "Remember Me" box as they log in, and to set the headers on the axios client accordingly.

```import {path} from 'ramda'

const {types: {PARSED_TOKEN, LOGIN}} = authDux

export default service => ({getState}) => next => action => {
    if ([PARSED_TOKEN, LOGIN].includes(action.type)) {
        service.interceptors.request.use(config => ({
            ...config,
            headers: {
                ...config.headers,
                Authorization: `Bearer ${
                    path(['user', 'token', 'access_token'], action) ||
                    path(['auth', 'parsed_token'], getState())
                }`
            }
        }))
    }
    next(action)
}

The behavior is inconsistent for each subsequent axios call. On some pages that use the very same client, I get 401s until I refresh the page.
