### ISSUE TITLE
axios method dont do anything

### ISSUE THREAD

**Issue by sintram60** [mzabriskie/axios#867]
hello guys, im having a problem retrieving data from a basic URL using axios on Electron.

i was trying to get all my users, just for test and then use them to match with the login information to give or not access to the system.

the problem is when the axios method is executed the window only refresh and dont show any error or result and i just dont know what is going on, 

please help me :)

this is my full class:

![image](https://cloud.githubusercontent.com/assets/23663613/25443251/347147ec-2a9f-11e7-8568-1732f6c6c2dd.png)

**Comment by ashah023** [comment]
You are using `console.log()`, which means it'll print the results in the developer console. 

You're not using the results in the React component, so you'll only see the data in the developer console.

If you're asking how to render the results, then let me know. But that would be a React question, not axios.
