### ISSUE TITLE
Can't build axios for node using Webpack

### ISSUE THREAD

**Issue by binhqd** [mzabriskie/axios#870]
I'm developing a React Server Side Rendering and using Axios as HTTP Client.
I'm trying to use webpack to create a bundle including axios. However, it always use lib/adapter/xhr.js instead of lib/adapter/http.js. That cause "XMLHttpRequest is undefined" when I'm trying to perform a request to API server.

However, when I change http.js to something.js (also change in lib/default.js too) then it working well.

So strange.

Does anybody have any answer?

**Comment by albertogasparin** [comment]
Based on [axios logic](https://github.com/mzabriskie/axios/blob/188334439f9698c8ddd58697f75e7f0b745c9acc/lib/defaults.js#L18) when you are building your webpack bundle `XMLHttpRequest` is defined.
You can try using webpack `webpack.NormalModuleReplacementPlugin` to pick `lib/adapter/http.js` even when axios requires `lib/adapter/xhr.js`

**Comment by dperezmavro** [comment]
Facing a similar issue here. I am using webpack 2.6.0, and axios 0.16.1. The bundle builds successfully, but it looks like axios picks XMLHTTPRequest to send HTTP requests, rather than the http module.

**Comment by dperezmavro** [comment]
Following the suggestions on [this](https://github.com/mzabriskie/axios/issues/456#issuecomment-285287911) answer solved it for me. Basically you need to tell webpack to build for node (by default it builds for the browser)
