### ISSUE TITLE
Since 0.16 big weight gain?

### ISSUE THREAD

**Issue by gplume** [mzabriskie/axios#871]
Hello there,
I use axios since version 0.12 with vuejs and building lightest possible apps for mobile. I was surprised (and disappointed) to notice a weight gain of 22kb since version 0.16, what is the explanation for that?

Here is my vendor file entry:
```
import Vue from 'vue'
import axios from 'axios'
require('es6-promise').polyfill()
Vue.prototype.$http = axios
```

**Comment by albertogasparin** [comment]
Yep, there is already another issue open #846 (with a webpack quick fix) and also an open PR with a proposed fix #887
