### ISSUE TITLE
header function?

### ISSUE THREAD

**Issue by anthonyettinger** [mzabriskie/axios#872]
is it possible to define a function that sets the headers when an instance of axios is used?

I'm having an issue where after I login I have to refresh the page to get the auth token set:

	import Axios from 'axios';

	const baseURL = 'http://localhost:3000/api/1';

	I would like this to evaluate everytime its called not when only created:

	const api = Axios.create({
	  baseURL,
	  headers: {
	    Authorization: `Bearer ${localStorage.getItem('token')}`
	  }
	});

	export default api;

**Comment by rubennorte** [comment]
Axios doesn't support it but you can manually replace the default Authorization header when it's received or use an interceptor to set it automatically.

**Comment by bigriot** [comment]
I hope this feature eventually get's added. It would be very useful for working with endpoints that require auth tokens that are generated from the current timestamp each time a request is sent.
