### ISSUE TITLE
Detect 304/cached response in interceptor

### ISSUE THREAD

**Issue by tybro0103** [mzabriskie/axios#877]
Using axios in a mobile app (react native). For auth, I'm looking for `Set-Cookie` on any response, writing it to disk, and using it to tack on `Cookie` to every request. This keeps the user authenticated after restarting the app.

Works great except for when my server issues a `304`. In that case, Axios gives me the cached body from the last 200 call, but it also gives me the cached headers from the same call. If the cached call had `Set-Cookie` in it, and it's an old cookie, this breaks my setup.

Is there (or should there be) a way in an interceptor to determine that the response was a `304`? Or is there a better way to solve my problem?

**Comment by paul321** [comment]
I have the same problem after the user authenticates the response comes with set-cookie and with a 304 status for redirection, we are using nodejs with custom cookie jar and we save cookies in interceptors but there is no interceptor for 304 responses

**Comment by rubennorte** [comment]
This isn't an issue in Axios but a browser behaviour (probably mimicked by React Native). See https://stackoverflow.com/questions/13783442/how-to-tell-if-an-xmlhttprequest-hit-the-browser-cache for more details.
