### ISSUE TITLE
set validateStatus failed

### ISSUE THREAD

**Issue by xushaocong** [mzabriskie/axios#879]
![image](https://cloud.githubusercontent.com/assets/22735791/25610328/6764afe4-2f55-11e7-9ba5-ee210b6332c2.png)
I set the validateStatus between 200 and 500, when the http status code=302, why it enter to the error function `console.log(444);`  but not `console.log(123)`

**Comment by rubennorte** [comment]
If this code is run in the browser, redirections are automatically followed so there isn't a way to intercept them. In Node.js redirections are followed by default but you can't disable that behaviour by setting `maxRedirects: 0` in the request config.
