### ISSUE TITLE
Provide a Node.js "fs" adapter for local file requests

### ISSUE THREAD

**Issue by lbssousa** [mzabriskie/axios#880]
#### Summary

It would be interesting if axios could provide a backend for requesting local files via `fs` module in Node.js context, without need to setup a local http server.

For example, I'm developing a web app using Quasar Framework, designed to be hosted on an ordinary web server, or wrapped locally as an Electron App. This app requests some JSON files via AJAX, in web context, or via `fs` module, in Electron context.

#### Context

- axios version: *any*
- Environment: *any*

**Comment by rubennorte** [comment]
Sorry but this is out of the scope of Axios (making HTTP requests).
