### ISSUE TITLE
Making requests relative to current domain

### ISSUE THREAD

**Issue by danielo515** [mzabriskie/axios#882]
### Summary

Hello,

I'm developing a web app and I'm using axios. I was a very happy user until I had to deploy to my production server. On the production server, my app is served under a subdomain, so making the entire application work both on a root domain (for development) and on a subdomain was a bit painful. 
However, for my surprise, making axios requests work on both sides was very easy. So easy that I'm not sure if it is intentional or a bug.
Before my requests was like

```js
axios.get('/api/licenses')
```
So serving the app from `https://example.com/licenses` resulted on a request to `https://example.com/api/licenses` instead of the expected `https://example.com/licenses/api/licenses`.

After that, I just tried to remove the prefixing slash, so my request looked like:

```js
axios.get('api/licenses')
```

That produced the desired result of making the request to `https://example.com/licenses/api/licenses`. I am very happy with this, because now I can develop my app without hassle. However, this behavior is not documented on any place, all the examples makes requests to the root of the domain, and I'm scared of this cool feature disappearing on future releases.

### Context

- axios version: *e.g.: v0.16.1*
- Environment: *chrome 57*

**Comment by michaelbukachi** [comment]
I can confirm this too. I don't think it's bug though. However we need confirmation from the developer(s)
axios version: _v0.16.2_

**Comment by rubennorte** [comment]
This is just how relative URLs work in the browser. Axios doesn't have anything special about it.

**Comment by danielo515** [comment]
What about `axios.get('./path')` ? Why isn't that respecting the relative of the path ?

**Comment by Misiu** [comment]
@rubennorte can this be reopened? I think this still is an issue.
If this is how the browser works then maybe there is a workaround?
You sometimes need to rename the folder where the app is and you don't want to change anything in it. In my case I have a react app, so changing base url requires changing the address in the project, building a release and deploying. I'd like to avoid that

**Comment by UndarkAido** [comment]
@Misiu The OP has a workaround

**Comment by sugoidesune** [comment]
This is how relative, root-relative work.
https://www.w3schools.com/html/html_filepaths.asp
