### ISSUE TITLE
Error response object is undefined

### ISSUE THREAD

**Issue by nabs-grg** [mzabriskie/axios#883]
#### Summary
Hello,

I am making an API HTTP request using axios but i don't get an error object in response. The response for the error comes as undefined and I only get the instance of an error object if I console.log(error).

I have followed the same pattern for error handling which is in the documentation.

Here is the screenshot of the console showing only the instance of error when I do console.log(error).

<img width="626" alt="screen shot 2017-05-03 at 16 44 07" src="https://cloud.githubusercontent.com/assets/17575788/25669557/c5ef691a-3021-11e7-9656-1eeb44365541.png">

Here is another screenshot showing **error.response** as undefined.

<img width="1440" alt="screen shot 2017-05-03 at 17 16 37" src="https://cloud.githubusercontent.com/assets/17575788/25670362/595baaa4-3024-11e7-834a-babce107b3c6.png">

I have 404 as status code also the response body is in the image below.

<img width="829" alt="screen shot 2017-05-03 at 17 08 38" src="https://cloud.githubusercontent.com/assets/17575788/25670700/74e487cc-3025-11e7-8c34-20cbe3f2421e.png">

- axios version: v0.16.1
- Environment: node v7.7.4, chrome 58, macOS Sierra

**Comment by fgiarritiello** [comment]
I have the same problem. Did something change?

**Comment by tyleriguchi** [comment]
Hey had this happen to me, the issue is that the api on what a rejected promise returns has changed. Before you did something like this
```
.catch( (response ) => {
  console.log(response.data.errors)
})
```
but now you have to do something like this
```
.catch(  (error) => {
  const response = error.response
  console.log(response.data.errors)
})
```
I had bumped from something pre v0.10.0 to v0.16.1

**Comment by graysonlangford** [comment]
I'm having the exact same issue.

**Comment by nabs-grg** [comment]
Thanks @tyleriguchi and @graysonlangford for the help. And yes the CORS header wasn't present for the response code.

**Comment by nelson6e65** [comment]
This is maybe related...

It happens to me that on authenticated (value is set in `store.getters.authToken`), if I add extra data to `axios.interceptors.request`, I get the error.

```js
// axios-config.js
import Vue from 'vue'
import axios from 'axios'
import store from '~/store'
import router from '~/router'

axios.interceptors.request.use(request => {
  if (store.getters.authToken) {
    request.headers.common['Authorization'] = `Bearer ${store.getters.authToken}`
  }

  request.data.locale = store.getters.locale // <- EXTRA DATA ATTACHED 

  return request
})
```

```js
// store/auth.js
// . . .
async fetchUser ({ commit }) {
    try {
      const { data } = await axios.get('/user/current') //  <-- I GET THE ERROR HERE

      commit(types.FETCH_USER_SUCCESS, { user: data })
    } catch (e) {
      console.error(e)
      commit(types.FETCH_USER_FAILURE)
    }
  },
```

For non successful login it works fine all. I get this error only there (when I try to get the current user). And is gone if I remove the extra data from the interceptors.

So, my problem is then the `authToken` is set.

---- 
I ended up to use **cookies** to get the `locale` value in my back-end, but... I don't understand why this happens.

**Comment by felix9ia** [comment]
`(error) =>{
console.info(error.config);
}`

**Comment by sveinn** [comment]
For me the thrown error actually `was not` undefined, it just looked like that in Chrome's dev tools. (Not sure why but if anyone figures it out, please let me know)
