### ISSUE TITLE
preflight request can't handle http code 204

### ISSUE THREAD

**Issue by freebird0221** [mzabriskie/axios#885]
when send a cors request, axios handler http code 204 as a wrong response

#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v6.9.4, chrome 54, windows 7*

**Comment by peshi** [comment]
having the same issue.

**Comment by ltwaia** [comment]
me too

**Comment by rubennorte** [comment]
Please review your CORS configuration and search for similar issues in the project.
