### ISSUE TITLE
POST sending empty object 

### ISSUE THREAD

**Issue by souljacker** [mzabriskie/axios#886]
Hey guys, 

I'm trying to send a post request in VUE.JS but there's an issue.

I have this TEST object set up in data
`    data () {
      return {
        test:{
          name: 'foo',
          surname: 'bar'
        }
      };
    },`

And here's my method
`       testMethod(){

      axios.post('url',this.test)
      .then(response => {
        console.log(response);
      })
      .catch(error => {
        console.log(error);
      });
      }`

It won't work. It's sending an empty object to my API. If I try this, it works

`       testMethod(){

      axios.post('url',{'name':'foo', 'surname': 'bar'})
      .then(response => {
        console.log(response);
      })
      .catch(error => {
        console.log(error);
      });
      }`

Any idea on what's wrong?

Not sure if that's a bug or not.

Thanks!

**Comment by clarkieryan** [comment]
Do you have the full code for this test - could be that this.test is undefined?

**Comment by dumbringer** [comment]
I got similar problem when sending request with method POST, the backend can't catch the request. here's my vue script

`export default {
    data() {
      return {
          formAddAsset : {
            asset_origin : '',
            year : '',
            id_location : '',
            id_asset_type_detail : '',
          }
      }
    },
    mounted() {
      var self = this;
    },
    methods:{
      addAsset(){
        //console.log(self.formAddAsset);
        axios.post('/api/asset',self.formAddAsset)
        .then(response => {
          console.log(response);
        })
        .catch(error => {
          console.log(error);
        });
      },
    }
  }`

And here's my backend script using laravel (function for /api/asset)

`public function store(Request $request)
    {
		$asset = new Asset($request->all());
		$asset->save();
		return response()->json(['asset' => $asset],201);
    }
`
I have check the vue data (formAddAsset) in google chrome inspect, and it has value. But when sending request to backend, it won't catch the request.

any idea?

**Comment by dumbringer** [comment]
I have solved my own issue. I have to add var self =this; in my methods
so, here's my vue script before update

```
methods:{
      addAsset(){
        axios.post('/api/asset',self.formAddAsset)
        .then(response => {
          console.log(response);
        })
        .catch(error => {
          console.log(error.response);
        });
      },
    }
```
and after update

```
methods:{
      addAsset(){
        var self = this; //----the script I have to add
        axios.post('/api/asset',self.formAddAsset)
        .then(response => {
          console.log(response);
        })
        .catch(error => {
          console.log(error.response);
        });
      },
    }
```

I have no idea why we should add var self = this. I watched many vue tutorial and they just use this.variabel

Anybody has an explanation?

**Comment by clarkieryan** [comment]
By the looks of it self is not defined when you call - addAsset - this could be because the component hasn't been mounted yet - meaning mounted() function to be called after you call addAsset which is where you define self. 

By adding in the define ```var self = this``` inisde the addAsset call it's ensuring it's always defined when you call addAsset.

**Comment by souljacker** [comment]
Mine got fixed but I honestly don't know how, which makes me feel very stupid. I'll try to figure it out and report back

**Comment by zehelvion** [comment]
Some advice for anyone who's stuck.
(1) Check the server-side with a tool like Postman. You might be missing body-parser.
(2) Make sure you are using the current CDN.
(3) Test your code snippet with jsfiddle to avoid state related issues.
Good luck!

**Comment by purplecones** [comment]
I'm having the same issue. Nothing is sent in the body when I use a javascript object.

Here I'm using `api` that I've created with `axios.create`.

```javascript
  api
    .post('/someUrl', { foo: 'bar' })
    .then(res => console.log({ res }))
```

However, when I use a string with equal sign it works.

```javascript
  api
    .post('/someUrl', 'foo=bar')
    .then(res => console.log({ res }))

// returns { foo: 'bar' } on the server
```

The solutions above don't solve my issue. Has anyone encountered this? Seems strange that passing an object would not work.

**Comment by 12343954** [comment]
@purplecones  same issue as yours +1
server can not accept the json values

**Comment by iamendy** [comment]
@12343954 have you resolved it now?

**Comment by 12343954** [comment]
@iamendy 
make the `{data}` to querystring, like: `a=1&b=2&c=3`

`
              var data={a:1,b:2,c:3}
              axios.post('http://your.ajax.url',
                    Object.keys(data)
                        .map(k => `${encodeURIComponent(k)}=${encodeURIComponent(data[k])}`)
                        .join('&')
                )
                .then((response) => {
                    console.log(response);
                })
                .catch((error) => {
                    console.log(error);
                });`

**Comment by 12343954** [comment]
@iamendy 
make the `{data}` to querystring, like: `a=1&b=2&c=3`

`
              var data={a:1,b:2,c:3}
              axios.post('http://your.ajax.url',
                    Object.keys(data)
                        .map(k => `${encodeURIComponent(k)}=${encodeURIComponent(data[k])}`)
                        .join('&')
                )
                .then((response) => {
                    console.log(response);
                })
                .catch((error) => {
                    console.log(error);
                });`

**Comment by iamendy** [comment]
Thanks @12343954. 
I was able to figure it out. Laravel accepts the data and runs the function assigned to that view, but it does not run it as one would expect via forms. To  check whether the data exist do this:

VueJs code:
axios.post('url', data) .then((response) => { console.log(response); }) 

.catch((error) => { console.log(error); });

Laravel code:
Route::post('url', function () {
        return request()->get('data');
});

Check your console and the data being sent will be returned as json. So it works but not like when you send a post request via forms in laravel.

**Comment by iamendy** [comment]
So to get the Jason values, use the global request()->get('key')

**Comment by fabianrios** [comment]
If somebody else is working with express.js changing the bodyparser from 
`bodyParser.urlencoded({ extended: false })`
to 
`bodyParser.json()`
resolves the issue.

**Comment by alittletf** [comment]
thank you @fabianrios !!!

**Comment by donnisnoni95** [comment]
@souljacker If you are working with data to post you must do this

**Comment by donnisnoni95** [comment]
@souljacker hi ... I don't know whether your problem has been resolved or not, I just want to help you or someone else who has the same problem as you.

If you want to send data via `POST` ... you have to use the `FormData` class, this is supported by the default browser.

**Syntax**
```javascript
// Create new form data instance. optional, you can put form elements off your data in the first parameter
const person = new FormData ()

// Add data to FormData instance which is person
// The first parameter is the field name, same as the 'name' property in the HTML element <input name = 'name'>
// The second parameter is the value of the field itself
person.append ('name', 'John Doe')

// Add data again data
person.append ('age', 22)

// Then, send the person's data
axios.post ('url', person)
.then ()
.catch ()

// Done
```

**Comment by alyatwa** [comment]
It looks like you only have two points left to make it work :

one : the http method should be set to POST instead of GET since you want to send something.

two : you can then add the http header (like what you did with the authorization header) Content-Type: 'application/json`

On the back-end don't forget to use some kind of body parser utility package like this one : body-parser and set it up with your app.

I suppose your server is using express, here is how you will do it with express :

```js
const express = require('express');
const app = express();
const bodyParser = require('body-parser')
const jsonParser = bodyParser.json();

app.use(jsonParser); // use it globally
app.get('your_route', jsonParser, otherMiddleware, (req, res) => ...); // use it for specific routes

/* ... rest of your code */
```

**Comment by uinstinct** [comment]
> 
> 
> If somebody else is working with express.js changing the bodyparser from
> `bodyParser.urlencoded({ extended: false })`
> to
> `bodyParser.json()`
> resolves the issue.

THIS HELPED
THANKS.
