### ISSUE TITLE
how remove options before post?

### ISSUE THREAD

**Issue by cmideal** [mzabriskie/axios#888]
when post ,always send options first , can turn off this?

**Comment by 443866786** [comment]
i'm suffering this too

**Comment by larvanitis** [comment]
It sounds like you are making a CORS request. In that case you should read this http://stackoverflow.com/questions/29954037/how-to-disable-options-request.

**Comment by ZevenFang** [comment]
Look at this
https://github.com/mzabriskie/axios#using-applicationx-www-form-urlencoded-format

**Comment by fairyly** [comment]
@rubennorte  I don't understand , how to disable the option before get/post??

**Comment by aztrock** [comment]
same question that @fairyly

**Comment by arivera12** [comment]
**The solution to prevent preflight request is to set the header Access-Control-Max-Age.** 

The **Access-Control-Max-Age** response header indicates how long the results of a preflight request (that is the information contained in the Access-Control-Allow-Methods and Access-Control-Allow-Headers headers) can be cached.

**Comment by bruno-rodrigues** [comment]
Please be aware that the maximum caching time to Access-Control-Max-Age for Chromium is 10 minutes. Not very helpful to my current specific case :P

https://cs.chromium.org/chromium/src/services/network/public/cpp/cors/preflight_result.cc?l=36&rcl=52002151773d8cd9ffc5f557cd7cc880fddcae3e

**Comment by illmoded** [comment]
I found this helpful:

https://medium.com/@praveen.beatle/avoiding-pre-flight-options-calls-on-cors-requests-baba9692c21a

**Comment by larvanitis** [comment]
@bruno-rodrigues Chromium's max cache time has ben increased to 2 hours.

See:
- https://cs.chromium.org/chromium/src/services/network/public/cpp/cors/preflight_result.cc?l=31&rcl=master
- https://bugs.chromium.org/p/chromium/issues/detail?id=131368
