### ISSUE TITLE
Cannot override content-type?

### ISSUE THREAD

**Issue by apoco** [mzabriskie/axios#89]
Doing this:

```
axios({
  method: 'post',
  url: '/some/url',
  data: { prop: value },
  headers: {
    'content-type': 'application/vnd.myapp.type+json'
  }
});
```

...causes a request with `content-type` set to `application/json;charset=UTF-8 application/vnd.peregrine.activation+json`.

Is there a correct way to override `content-type`, or is this just a bug?

**Comment by apoco** [comment]
Figured out that if I used `Content-Type` instead, it works. Maybe this ought to be made case-insensitive.

**Comment by mzabriskie** [comment]
This is definitely an issue. I'll take a look at it.

**Comment by daktwigim** [comment]
it still doesn't work... why did it closed?

**Comment by chadmetcalf** [comment]
@daktwigim It looks like it was closed because if the correct header key is used, the `Content-Type` changes.

```javascript
headers: {
  'Content-Type': 'application/vnd.myapp.type+json'
}
```

**Comment by duyngha** [comment]
I set `Content-Type` to `application/x-www-form-urlencoded` but it seems still not work.
```
headers: {
  'Content-Type': 'application/x-www-form-urlencoded'
}
```
Any helps?

**Comment by samayo** [comment]
I still don't understand why this is closed. Care to explain @mzabriskie

**Comment by RobertWSaunders** [comment]
I can also verify that setting `Content-Type` within the `headers` object is not working! Please could someone explain what is going on here...

**Comment by MattCz** [comment]
Same here. Gonna switch to jQuery AJAX as this package + describe polyfill are almost 10kb in total so it's basically not worth to use axios without a possibility to change content type.

**Comment by mateusmaaia** [comment]
Just use 'content-type' instead of 'Content-Type', it works 😃

**Comment by AgoloAhmedElhady** [comment]
I am facing the same issue but only with ```GET``` Requests

```js
const config = {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${user.jwt}`,
        },
      };
axios.get(url, config)
```

**Comment by RobertWSaunders** [comment]
To follow up my issue was related to CORS.

**Comment by forumact** [comment]
Thanks, after passing empty data its working fine..

**Comment by mi-mazouz** [comment]
Passing empty data is working for me as well

**Comment by AgoloAhmedElhady** [comment]
But semantically why we should pass any data in a GET request ?

**Comment by olkunmustafa** [comment]
Adding "data: {}" didn't work for me but to add "data: null" worked.

**Comment by muboluo** [comment]
I  met this  in GET ,so I add  "data:{}"  when GET ,and do nothing when POST
