### ISSUE TITLE
post sends request method as OPTIONS

### ISSUE THREAD

**Issue by flyliao** [mzabriskie/axios#890]
cors custom headers first send options
my service allow cors，but the method post check token is error

export function fetch(options) {
    return new Promise((resolve, reject) => {
    const instance = axios.create({
      timeout: 2000
    });
    instance(options)
            .then(response => {
              const res = response.data;
              resolve(res);
            })
            .catch(error => {
              Message({
                message: error,
                type: 'error',
                duration: 5 * 1000
              });
              reject(error);
            });
  });
}

**Comment by liuhao1025** [comment]
``javascript
``

**Comment by arvera** [comment]
+1

**Comment by antonioreyna** [comment]
any idea of this?

**Comment by arvera** [comment]
I am not the developer here, but does it has to do with /lib/adapters/http.js line 132?

**Comment by jdtzmn** [comment]
#475
