### ISSUE TITLE
[Question!] In Html, the way to replace form tag with axios

### ISSUE THREAD

**Issue by XOneto9** [mzabriskie/axios#892]
Hi,
I'm making webpage with axios. and this web page is made by React client-side rendering process(in this case, react is not related to this question).

the problem is I use Form tag in Html like this :

```
<form action = '/' method = post>
    <input type='text' value = '' name = 'id'>
    <input type='email' value = '' name='email'> 
    ....
</form>
```

but in this part I'm using axios to transport data to server. and I transport value one by one. like this :

```
axios.post('/', {
        name : name,
        email : email,
    }).then((res) => {
        console.log(res);
    }).catch((err) => {
        console.log(err);
    });
```

but, I think if I use axios to replace form, I think something packaged structure is exist like data in form tag .
SO, I wanna know about way, to transport data not one by one, as one packaged data.

**Comment by apearson** [comment]
@XOneto9 I'm not sure this is the place to be asking this question.  If you shoot me an email (email in my profile) I'll try and answer your questions.
