### ISSUE TITLE
Uncaught (in promise) Error: Request failed with status code 404

### ISSUE THREAD

**Issue by haies** [mzabriskie/axios#893]
When i upload files to another Apache server, the files were upload successfully,but I got the wrong message as this tilte,but not 200 response message.
I guess that is problem about Apache server.

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v6.9.4, chrome 54, windows 7*

**Comment by haies** [comment]
It not axios problem!

**Comment by Sphinxs** [comment]
What was the error and the solution ?

**Comment by Dagge1** [comment]
Same problem here, but with Windows IIS Server 2016
