### ISSUE TITLE
How to create resources?

### ISSUE THREAD

**Issue by tiagomatosweb** [mzabriskie/axios#894]
Hi, does Axios provide somehow to create a resource of url same as what [vue-resource](https://github.com/pagekit/vue-resource/blob/develop/docs/resource.md) does.

Basically, I would like to create a "file" which contains all my resources and then use it across to my app. How would I do it with Axios?

Cheers

**Comment by howareyouo** [comment]
try this
`
/**
 * create resource object
 *
 * Default Actions
 *   get: {method: 'GET'}
 *   save: {method: 'POST'}
 *   query: {method: 'GET'}
 *   update: {method: 'PUT'}
 *   remove: {method: 'DELETE'}
 *   delete: {method: 'DELETE'}
 *
 * @param path the resource path
 * @param http axios instance
 * @param actions custom actions
 * @returns the resource object
 */
function resource (path, http, actions) {
  var obj = {
    get: id => http.get(path + '/' + id),
    save: obj => http.post(path, obj),
    query: params => http.get(path, {params}),
    update: (id, obj) => http.put(path + '/' + id, obj),
    delete: id => http.delete(path + '/' + id)
  }
  return Object.assign(obj, actions)
}
`

**Comment by tiagomatosweb** [comment]
Yeah! I am doing something similar to this but not too complex.
I wonder if there is a native way to do it?

Tks @howareyouo

**Comment by rubennorte** [comment]
You can do it yourself and we're trying to keep Axios not too opinionated.

**Comment by emileber** [comment]
> keep Axios not too opinionated

I like that way of thinking, and that's why I made a package that help define REST resources: [axios-resource](https://emileber.github.io/axios-resource/#/)
