### ISSUE TITLE
Axios expose response headers: Content-Disposition

### ISSUE THREAD

**Issue by pranay-91** [mzabriskie/axios#895]
Summary
Axios expose response headers doesn't contain Content-Disposition 

Description.
I was able to set request headers to expose Content-Disposition by adding:
`  "Access-Control-Expose-Headers": "Content-Disposition"`

I can see the response but the response object does not include Content-Disposition.

![capture](https://cloud.githubusercontent.com/assets/10881744/25944587/2a5e4342-3687-11e7-974d-347ae65246d4.PNG)

Is there any way i can access that value?

- axios version: 0.15.2
- Environment: node v6.9.4, chrome 54, windows 7

**Comment by elowes** [comment]
Same problem, Axios expose response headers doesn't contain Cache-Control .

**Comment by pranay-91** [comment]
I misunderstood the concept of CORS. ```Access-Control-Expose-Headers``` is a response header issued by the service.
This issue has nothing to do with axios. 
The service should allow Content-Disposition header to be exposed for the client, in my case it does.
Due to HTTP access control CORS in browsers, the client application needs a proxy cors (in my case an express middleware) to read the header value.
Apologies for misunderstanding.
