### ISSUE TITLE
ACCESS DENIED

### ISSUE THREAD

**Issue by GuillermoParedes** [mzabriskie/axios#896]
Hi guys.
I have a problem using axios in INTERNET EXPLORER 11, I have error "access denied", but same request in google chrome the success
My code with axios.
`        axios.post(_urlRequest,params, { timeout: pTimeout})
          .then(response => {
            console.log('@response@', response)
            pRetorno(JSON.parse(response.data))
          })
          .catch(error => {
            console.log('@error@', error)
            pRetorno({ correcto: false, mensaje: error, listaResultado: [] })
          })`

**Comment by rubennorte** [comment]
Sorry but this doesn't look like an issue in Axios. Please review your code and reopen if you find more information that points to it.
