### ISSUE TITLE
Spread for catch?

### ISSUE THREAD

**Issue by boxsnake** [mzabriskie/axios#900]
Refer to #76 

I am in another situation, in which I am doing a crawler.

In this situation, I grab all data asynchronously. After all data was grabbed, I want to make a log for the whole crawling task.

However, when some page fails in crawling, axios will throw an error and break the grabbing immediately.

In crawling pages, if some pages not found, we can just simply continue, and be regardless to the broken page. In this background, I am wondering if it is posible to make `pending error(s)`, by which one can deal errors manually after all things are done. Also in this case, spread in catch is needed.

**Comment by boxsnake** [comment]
I found a way, it seems work, but the code seems messy and hard to read. My strategy is to use `.then().catch()` to make pending Promises, then put these pending Promises into all parameters. i.e. (assuming I has an `Array` called `list`, and I am writing with ES6-style)
```js
axios.all(list.map(url => {
    return axios.get(url).then(content => {
        console.log(content.data);
    }).catch(error => {
        console.error(error);
    });
})).then(_ => {
    console.log('All Done.');
});
```

**Comment by rubennorte** [comment]
Sorry but this has nothing to do with Axios but with Promise handling in general. Please refer to StackOverflow or any other means.
