### ISSUE TITLE
utils.merge behavior regarding the config

### ISSUE THREAD

**Issue by fogine** [mzabriskie/axios#902]
#### Summary

merge function of `lib/utils.js` module is currently used to merge request specific config with global (instance) defaults. Currently `undefined` properties of "destination" objects overwrite properties of "source" object. Consider the following example:  

```javascript
    var axios = axios.create({
        headers: {
             common: { origin: 'value' }
        }
    });

    axios.request({
        method: 'get',
        url: 'http://127.0.0.1',
        headers: undefined
    });
```

The above example sends the GET request with `headers`=undefined.
Is the described behavior intended by design?
In my opinion it would make more sense to not overwrite property values with enumerable properties  which have `undefined` value.

Note: lodash `merge` method behaves in proposed way.

#### Context

- axios version: v0.16.1
- Environment: *node 6*

**Comment by rubennorte** [comment]
I agree and we're going to address this together with some other configuration issues. See #812.
