### ISSUE TITLE
https.globalAgent

### ISSUE THREAD

**Issue by jsntghf** [mzabriskie/axios#903]
`https.globalAgent.options.ca = fs.readFileSync('mobile.cer');`

the file mobile.cer is transfered from mobile.crt, and mobile.crt is a server side public key, we will put the file mobile.cer to the app and request by axios, is it ok?

**Comment by rubennorte** [comment]
That doesn't have to do with Axios but with the global agent configuration in Node. If you apply any changes there it'll affect Axios indeed.
