### ISSUE TITLE
when CancelToken call one,will abort all reqeust after

### ISSUE THREAD

**Issue by superchangme** [mzabriskie/axios#904]
I want to use cancelToken to cancel token invalid request,i use like this:
```javascript
var _httpCancel;
var myAxios=axios.create({
cancelToken: new CancelToken(function (cancel) {
    _httpCancel=cancel;
 }})

http.interceptors.request.use(function(config) {
//cancel it when no token
if(noTokenCondition){
_httpCancel()
}
})
```
But i found when i trigger once _httpCancel.
when next time ,use http request and has token,it will still throw promise error Cancel .
I feel helpless and  depressed today, can anyone help me?
Thank you very much!!!

**Comment by superchangme** [comment]
I know the reason,cancelToken should create on each request.

**Comment by phillip-haydon** [comment]
I can't get it to cancel any request...

**Comment by SudoPlz** [comment]
I'm experiencing the same thing also. Cancelling cancels all requests and not each one individually..!

**Comment by rubennorte** [comment]
From #1017:

> you must be using the same cancellation token for all request. You should create a new one for each request so this doesn't happen.

In other words, don't use a default cancelToken as cancelling it will cancel all requests.

**Comment by SudoPlz** [comment]
That makes sense, and I never used a default cancel token. I always create a new cancellation token for each request, but I still get the same problem.

**Comment by rubennorte** [comment]
Passing a `cancelToken` as an option to `axios.create` sets it as the default value. You should pass it in your request config.
