### ISSUE TITLE
Dont send xsrfCookieName

### ISSUE THREAD

**Issue by khotey** [mzabriskie/axios#905]
`
function createCategory(data) {
  return dispatch => {
    dispatch({
      type: CREATE.REQUEST,
    });

    axios
      .post(`${api.url}/categories`, data, { xsrfCookieName: 'XSRF-TOKEN' })
      .then(data => {
        dispatch({
          type: CREATE.SUCCESS,
          payload: data,
        })
      })
      .catch(e => {
        dispatch({
          type: CREATE.FAILURE,
          payload: e.response.data.message
        })
      })
  }
}
`

<img width="1268" alt="screen shot 2017-05-18 at 10 00 36 pm" src="https://cloud.githubusercontent.com/assets/10923916/26219035/f4b332cc-3c15-11e7-9597-33b9b5772663.png">
<img width="935" alt="screen shot 2017-05-18 at 10 15 05 pm" src="https://cloud.githubusercontent.com/assets/10923916/26219407/8334b1dc-3c17-11e7-9088-db42ea795f22.png">

**Comment by rubennorte** [comment]
You're sending a cross-domain request, so the cookie set to `localhost:80` isn't being sent to `localhost:3000`. That isn't an issue in Axios but how cookies work.
