### ISSUE TITLE
Is param/array wrapping supported out of the box?

### ISSUE THREAD

**Issue by grundmanise** [mzabriskie/axios#908]
Does Axios support `param` wrapping out of the box, i.e. is it possible to get something like this without a custom wrapper function?

`?foo[bar]=baz&foo[rar]=baz&foo[car]=baz&foo[dar]=baz`

**Comment by rubennorte** [comment]
Axios serializes objects as JSON by default, but you can pass a custom `paramsSerializer` option to serialize them that way.
