### ISSUE TITLE
Axios sends an OPTIONS (http code-204) request before/ after every get request.

### ISSUE THREAD

**Issue by itsyogesh** [mzabriskie/axios#910]
#### Summary

Hi I am using axios with react, and I am facing a strange issue. After every get request, the axios library makes a 204 request. Is it supposed to be this way, or am I doing something incorrectly ? Here is the required stack trace from the backend.
```
> project-wise@0.1.0 start /Users/Yogesh/Projects/Droidsize/Projectwise/server
> node server.js

App is running
OPTIONS /api/profile 204 5.096 ms - -
GET /api/profile 401 28.648 ms - -
OPTIONS /api/projects 204 0.806 ms - -
GET /api/projects 200 54.032 ms - 2810
OPTIONS /api/projects 204 0.749 ms - -
GET /api/projects 304 12.336 ms - -
OPTIONS /api/projects 204 0.582 ms - -
GET /api/projects 304 8.735 ms - -
OPTIONS /api/projects 204 0.147 ms - -
GET /api/projects 304 3.802 ms - -
OPTIONS /api/profile 204 0.095 ms - -
GET /api/profile 401 5.123 ms - -
OPTIONS /api/profile 204 0.196 ms - -
```
And here is the screenshot of the chrome network tab.
![image](https://cloud.githubusercontent.com/assets/1210943/26286880/b845bdae-3e8c-11e7-87f6-24ed0fc4504f.png)
 

#### Context

- axios version: v0.16.1
- Environment: node v7.6, chrome 58, OS X El Capitan

**Comment by rubennorte** [comment]
Axios isn't making those requests, the browser is. Please take a look at [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).
