### ISSUE TITLE
Internet Explorer 11 gives Promise error without polyfill

### ISSUE THREAD

**Issue by Bram-Zijp** [mzabriskie/axios#911]
Without a Promise polyfill Axios won't work in Internet Explorer.

**Comment by Etheryte** [comment]
The first line of the project description on Github reads: _"**Promise based** HTTP client for the browser and node.js"_  
So it's safe to say the library won't work if the environment doesn't support promises. I think not including the polyfill in the library is a great decision, as many developers have a strong preference when it comes to that.

**Comment by Bram-Zijp** [comment]
@Etheryte It also states that the plugin works with IE8+ If you know Promise is not supported in IE11 and the like you are save. However not everyone is aware of this. I feel like this should be noted near the IE8+ supported icon.

**Comment by Etheryte** [comment]
It's covered [in the readme](https://github.com/mzabriskie/axios#promises), but if you don't know to look for it, then yes, you'll run into the issue.
