### ISSUE TITLE
problem modifying external variable within an axios call

### ISSUE THREAD

**Issue by jcabrerazuniga** [mzabriskie/axios#916]
I have the next JSX code

    answer = true;
     var postAxios = axios({
                method: 'post',
                url:     httpLink,
                params: {table: tableName},
                data: rowInfo
               }          
              )
             .then(function (response) {
                 console.log(response);
                 alert(response);
                 answer = true;

               })
              .catch(function (error) {
                  console.log(error);
                  alert(error);
                  answer = false;
               });  
    return answer;

on the final value for answer some transaction needs to be continued (answer==true) or stopped(answer==false). The problem I have is that answer is always true inclusive when the catch section is executed. Is there a way to arrange this or for me to be able to get a proper value for **answer**?

**Comment by rubennorte** [comment]
You need to add the code that uses that variable in a `then` call of the promise, as the request is asynchronous and you can't access the value immediately after calling axios. This isn't really the proper place to ask, so please use StackOverflow or similar.

**Comment by senocak** [comment]
> var answer = await axios.get('https://reqres.in/api/users?page=1').then(function (response) {
           return response.data
    })
    console.log(answer)
