### ISSUE TITLE
Redirects on React Native App

### ISSUE THREAD

**Issue by wkwyatt** [mzabriskie/axios#919]
I have a react-native project I am using with axios where one of the request receives multiple browser redirects.  I am getting a `Network Error` when the amount of redirects exceeds 16, how do I increase the amount of redirects allowed?

#### Context

- axios version: *e.g.: v0.16.1*
- Environment: *e.g.: node v6.9.4, chrome 54*

**Comment by rubennorte** [comment]
React Native uses XMLHttpRequest under the hood, so we cannot configure the maximum number of redirections as we can with the`follow-redirects` module in Node.js. That should be a restriction of the platform and I don't think you can overcome it with axios.

Next time please add the proper context in that section of the issue description.
