### ISSUE TITLE
Does axios allow me to get cookies from REST API responses?

### ISSUE THREAD

**Issue by dukedougal** [mzabriskie/axios#92]
I have a REST API which my browser client talks to.

I want to be able to pick up the values from cookies returned from the REST API.

Does axios permit this?  Any examples anywhere of how to do so?

thanks

**Comment by dralletje** [comment]
Browser XHR requests do not support getting the 'Set-Cookie' header that contains the cookies.
It would be possible though to get a list of all cookies before the request and compare it to a list all cookies after the request.
On the server it is possible to get the 'Set-Cookie' header, but you'll have to parse it yourself :)

**Comment by creativeux** [comment]
Does this mean that Axios does not support automatic inclusion of JSESSIONID cookies?

**Comment by mzabriskie** [comment]
@creativeux cookie management is handled by the browser. So long as it's not a cross domain request, cookies should be automatically sent with the request, including JSESSIONID assuming it's been set.

**Comment by mzabriskie** [comment]
@dukedougal as @dralletje said, browser doesn't support reading cookies from XHR. You could write a script yourself to find newly set cookies.
