### ISSUE TITLE
Arrow function, this and promise

### ISSUE THREAD

**Issue by darakt** [mzabriskie/axios#920]
Hi, I change recently to Axios and I can't figure why the this isn't "working" properly inside the promise.
`let all = {
            method: 'POST',
            url: 'https://XXXXXX',
            data: data,
            headers: {
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            }
        };

        axios(all)
            .then((response) => {
                this.setState({
                    ...this.state,
                    spin: false,
                });
                self.props.router.push('panel');
            })
            .catch((error) => {
                this.setState({
                    spin: false,
                    errorLogin: 'Username or password wrong',
                });
            });`
In the end my this.setState is not a function which the use of an arrow function should avoid...

**Comment by rubennorte** [comment]
From the code you share I can't really help, as I don't see anything wrong. I'm closing as this isn't an issue in Axios anyway.
