### ISSUE TITLE
Axios catches exceptions that are thrown elsewhere when asynchronous requests are made

### ISSUE THREAD

**Issue by JSW5297** [mzabriskie/axios#921]
Axios catches exceptions that are thrown elsewhere when asynchronous requests are made

- axios version: *e.g.: v0.15.3*
- Environment: *e.g.: chrome 58, windows 10*

**Comment by rubennorte** [comment]
You should review your code structure because it doesn't seem Axios can have anything to do with this. Perhaps the exceptions are thrown within a promise handler or an interceptor.

**Comment by leoi11** [comment]
You're probably running into the same issue as [this](https://stackoverflow.com/questions/35344994/an-error-thrown-by-a-react-component-being-caught-in-an-unrelated-promises-cat/37950465#comment75838393_37950465)
