### ISSUE TITLE
Requires a parameter that can be configured with an instance of xhr

### ISSUE THREAD

**Issue by zhaomenghuan** [mzabriskie/axios#922]
Hello mzabriskie good morning.This issue is not about bug, which is what i want to be able to support a small feature.

I do not use XMLHttpRequest when I make a network request, but instead use [plus.net.XMLHttpRequest](http://www.html5plus.org/doc/zh_cn/xhr.html#plus.net.XMLHttpRequest), in the current method I have no way to configure. I hope xhr.js can set a parameter, you can set me to: 
```
var request = new plus.net.XMLHttpRequest ();
```

**Comment by rubennorte** [comment]
You can do this with the Provide Webpack plugin or a different tool if you're using a different bundler. We won't support providing a custom implementation of XHR, sorry.
