### ISSUE TITLE
Axios doesn't create request headers

### ISSUE THREAD

**Issue by ralphchristianeclipse** [mzabriskie/axios#923]
I'm trying to use axios to fetch json data from oxford dictionary

but it says i need to put request headers for app_id and app_key which is needed on the request

but i tried to do
```js
axios.get('http://oxford.api',{
       headers: {
           'app_id': 'secret',
           'app_key': 'secret',
           'Access-Control-Allow-Origin': '*'
        }
})

```

doing this will not work and puts the headers on allow-control-headers

i'm just new to this enlighten me masters

**Comment by websmurf** [comment]
Running into the same issue.

It seems that axios removes the `Access-Control-Allow-Origin: *` header whenever you push in a custom header with a request.

**Comment by jcready** [comment]
The `Access-Control-` headers are **response** headers that need to be sent by the server back to the client making the request. There's no point in setting them in your request headers.

**Comment by raygesualdo** [comment]
@ralphchristianeclipse I believe, according to the manual, that `app_id` and `app_key` are query parameters. So they could be set like this:
```
axios.get('http://oxford.api',{
       params: {
           'app_id': 'secret',
           'app_key': 'secret'
        }
})
```
