### ISSUE TITLE
Http basic auth always return 401 (Unauthorized)

### ISSUE THREAD

**Issue by kiwo12345** [mzabriskie/axios#926]
I am trying to do a put request using http basic auth:
```
axios.put(www.mysite.com/item/2, {
            title: 'test',
            auth: {
              username: null,
              password: token
            },
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            }
          })
          .then(function(response) {
            console.log(response);
          })
          .catch(function(error) {
            console.log(error);
          });
```
In my auth username should be empty and only password is needed, but it always returns a 401
and if I check the request payload in chrome I can see:

`{"title":"test","auth":{"username":null,"password":"2_Lci2ocfiQPSvOXd2wcKpwrn68Xd4ocuYqdw"},"headers":{"Accept":"application/json","Content-Type":"application/json"}}`

But the server still returns 401 (Unauthorized)

However if I try it Postman it works

This seems to work, so what is the difference between the two?

```
axios({
          method: 'put',
          url: www.mysite.com/item/2,
          data: {
            title: 'test'
          },
          auth: {
            username: null,
            password: token
          },
        });
```

**Comment by micooz** [comment]
Did you use axios in Node.js? I think this is because you set **username** to **null** which seems invalid to Node.js [implementation](https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_http_request_options_callback).

[http.js#L52](https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L52)
[http.js#L82](https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L82)
[http.js#L131](https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L131)

**Comment by kiwo12345** [comment]
@micooz No I am calling an API that is based on Laravel. Though I am setting **username** to **null** in both examples but only the second one works which is strange

**Comment by lewisdiamond** [comment]
I'm seeing the same thing in nodejs without setting the username to null. The auth part is just dropped when using axios.post/put

**Comment by jeimz143** [comment]
i think i have the same problem here :( 

```
var config = {
        //   url:'/api/user',
        // method:'patch',
        headers: {
                    'Authorization': state.token.token_type+' ' + state.token.access_token,
                    'Accept' : 'application/json',
                    'Content-Type' : 'application/x-www-form-urlencoded',
                 },
       data:state.user,
      //  params:{
      //     user:state.user._id
      //  },
      };
      Axios.patch(apipath + url, config)
            .then((response) => Promise.resolve(response))
            .catch((error) => Promise.reject(error));
```

but it returns 401 unauthorize

**Comment by jeimz143** [comment]
in POST method it works fine but when it comes to put/patch it returns err 401..

**Comment by rubennorte** [comment]
Both `username` and `password` must be strings. If you don't use one of those you can just pass an empty string (`''`).

**Comment by wonder95** [comment]
I am dealing with a similar issue using `GET`.  I'm working with a Solr server, and prior to adding basic HTTP authentication, everything worked fine, including the `Access-Control-Allow-Origin` header (which I've verified is still set. My original code was

```
  axios.get('https://my-solr-url.com/solr/my-solr-index/select', {
    params: params,
    withCredentials: true,
    auth: {
      username: 'myusername',
      password: 'mypassword'
    }
  })
```
but I always get a 401 error. If I vary the format like so

      axios.get({
        url: 'https://my-solr-url.com/solr/my-solr-index/select',
        params: params,
        auth: {
          username: 'myusername',
          password: 'mypassword'
        }
      })


I get a different error

`GET http://localhost:8080/[object%20Object] 404 (Not Found)`

As with above, I can query using the exact same credentials in Postman, from PHP, and in a browser. the only problem is when I use Axios.

**Comment by marianagarciaferreira** [comment]
Same problem!

**Comment by maxzhou0** [comment]
i changed my api method from get to post on the server and client, i got the expected result.
seems use axios.get can't send basic auth to server

**Comment by Marian0** [comment]
> The config object should be the third parameter of the `get` method (see https://github.com/axios/axios#instance-methods). Try this instead:
> 
> ```js
> axios.get('https://my-solr-url.com/solr/my-solr-index/select', {}, {
>     params: params,
>     withCredentials: true,
>     auth: {
>       username: 'myusername',
>       password: 'mypassword'
>     }
>   })
> ```

Use instead:

```
axios.get('https://my-solr-url.com/solr/my-solr-index/select', {
    params: params,
    withCredentials: true,
    auth: {
      username: 'myusername',
      password: 'mypassword'
    }
  })
```

axios.get parameters should use two parameters only. At least on version 0.18.*
