### ISSUE TITLE
Seems that onDownloadProgress does not work in nodejs

### ISSUE THREAD

**Issue by micooz** [mzabriskie/axios#928]
#### Summary

In node.js:

```js
(async () => {
  const response = await axios({
    method: 'get',
    url: 'https://github.com/mzabriskie/axios/blob/master/dist/axios.js',
    onDownloadProgress: (progressEvent) => {
      console.log(progressEvent); // seems never to be called
    },
    responseType: 'stream'
  });
  const stream = response.data;

})();
```

After I checked out the code, I found that **onDownloadProgress** is actually an event handler([xhr.js#151](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js#L151)) of **XMLHttpRequest** which doesn't available in nodejs .

How can I get download progress in node.js? Is there any plan to make an implementation in node.js using **http** module?

#### Context

- axios version: **v0.16.1**
- Environment: **node v7.10.0, chrome 57, ubuntu**

**Comment by sen0rxol0** [comment]
is not only in node, it doesn't seems to be working on the browser either

**Comment by hielfx** [comment]
I am using the version *v0.15.3* and it's working there. Also I am using Ubuntu 16.04, Node v6.9.1 and Chrome 58.0.3029.110 (64-bit), in case you  want to try it on those versions

**Comment by rubennorte** [comment]
`onDownloadProgress` only works in the browser indeed. That should be noticed in the documentation.

In this case you're using `responseType: stream` so you can implement the download progress by looking at the `Content-Length` response header and the `data`events in the stream you get in the response.

**Comment by dobeerman** [comment]
@rubennorte seems it not works in the browser. I gets `total: 0` in the properties.

**Comment by athoscouto** [comment]
@rubennorte, any solution for file upload?

**Comment by jayenashar** [comment]
> `onDownloadProgress` only works in the browser indeed. That should be noticed in the documentation.

was this added to the documentation?  i tried using it and found it didn't work in node and don't see it in the documentation.
