### ISSUE TITLE
Fix promise interface in axios.d.ts

### ISSUE THREAD

**Issue by deathmood** [mzabriskie/axios#93]
Hey, you've got such code in your `axios.d.ts`:

```js
interface Promise {
    then(response: axios.Response): axios.Promise;
    catch(response: axios.Response): axios.Promise;
}
```

but according to official spec `then` method can take 1 or 2 params like this

```js
Promise.prototype.then(onFulfilled, onRejected)
```

**Comment by mik01aj** [comment]
It's working as expected. Try it:

```
$ node
> var axios=require('axios')
> axios.get('https://github.com/invalidurl').then(function(){console.log(1)}, function(){console.log(2)});
{ _id: 7,
  _state: undefined,
  _result: undefined,
  _subscribers: [] }
2
```

**Comment by mzabriskie** [comment]
@deathmood would be happy to merge a PR for this.

**Comment by guncha** [comment]
Should probably use the global promise type `Promise<axios.Response>` as it causes incompatibilities when chaining promises.

**Comment by mzabriskie** [comment]
Closing in favor of a single issue for all typescript requests (#379).
