### ISSUE TITLE
Is it possible to add a retry method to axios?

### ISSUE THREAD

**Issue by liuzhen2008** [mzabriskie/axios#934]
In my interceptors, I wish to catch a specific error (say, token expired)

And then I'll run some method to refresh the token.

After that resolves, I wish axios to retry the previous request (with the same result handler).

Do I need to implement this logic manually? Or is there a retry or something similar that allows me to do it directly?

Thanks

**Comment by rubennorte** [comment]
You can do that with an interceptor that handles authentication errors. Something like:

```javascript
axios.interceptors.response.use(null, (error) => {
  if (error.config && error.response && error.response.status === 401) {
    return updateToken().then((token) => {
      error.config.headers.xxxx <= set the token
      return axios.request(config);
    });
  }

  return Promise.reject(error);
});
```

**Comment by UknowHui** [comment]
'return axios.request(config);'
what is config?

**Comment by mmsmsy** [comment]
When using it I get "config is undefined". Where should I get it from?

**Comment by mmieluch** [comment]
@mmsmsy This line:
```
return axios.request(config);
```
should be:
```
return axios.request(error.config);
```

**Comment by skyrpex** [comment]
Be careful if you're using the `transformRequest` option: the data from `error.config` is already transformed into a string.

For example, the code from @rubennorte would crash with this setup:

```js
// Lets use qs to stringify our request.
this.$axios = axios.create({
  transformRequest: [
    data => qs.stringify(data),
  ],
});

this.$axios.interceptors.response.use(null, (error) => {
  if (error.config && error.response && error.response.status === 401) {
    return updateToken().then((token) => {
      error.config.headers.xxxx <= set the token
      // Here, the request data will be double stringified with qs.stringify,
      // potentially leading to 422 responses or similar.
      return this.$axios.request(config);
    });
  }

  return Promise.reject(error);
});
```

A solution to this problem is not to transform the request data if it's already a string. For example:

```js
this.$axios = axios.create({
  transformRequest: [
    data => (isString(data) ? data : qs.stringify(data)),
  ],
});
```

**Comment by remhume** [comment]
@skyrpex Thanks a lot! Your answer brought us on the right track on a long and complicated bug hunt! 
 
It seems the default transformRequest handles transformation like in your example, **but axios notices the data is a string and will set the content type to `text/plain` instead of `application/json`** which lead in our case to our API sending back a 400 error.  

This was a hard bug to catch!

**Comment by NomiasSR** [comment]
remhume can you give me a hand? I'm having an issue with the same wrong behaviour that you had on your program.

**Comment by remhume** [comment]
iirc we just manually set the content type to the correct one (in our case `application/json`), which solved it.

**Comment by NomiasSR** [comment]
Thanks for the answer man I've already found other solution to solve my
issue. Regards

**Comment by FaisalJulaidan** [comment]
> ```js
> error.config && error.response &&
> ```

'config' is not defined

any idea?

**Comment by akhrabrov** [comment]
> You can do that with an interceptor that handles authentication errors. Something like:
> 
> ```js
> axios.interceptors.response.use(null, (error) => {
>   if (error.config && error.response && error.response.status === 401) {
>     return updateToken().then((token) => {
>       error.config.headers.xxxx <= set the token
>       return axios.request(config);
>     });
>   }
> 
>   return Promise.reject(error);
> });
> ```

If i have 10 parralel requests, axios send 10 updateToken requests.
That may cause "ECONNRESET" error.
Maybe u have solution for this case?

**Comment by Flyrell** [comment]
@akhrabrov I made a simple package if you'd like to use it -> [axios-auth-refresh](https://github.com/Flyrell/axios-auth-refresh). I'd be more than happy to see contribution if you're missing some functionality.

**Comment by edmondburnett** [comment]
I wanted to do something similar, except not necessarily with authentication, and retrying after a delay when a particular status code is received. Essentially long-polling via an Axios interceptor. This was my solution:

```
import axios from 'axios';

const instance = axios.create({
    baseURL: 'http://localhost:5000'
});

const sleepRequest = (milliseconds, originalRequest) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve(instance(originalRequest)), milliseconds);
    });
};

instance.interceptors.response.use(response => {
    return response;
}, error => {
    const { config, response: { status }} = error;
    const originalRequest = config;

    if (status === 420) {
        return sleepRequest(1000, originalRequest);
    } else {
        return Promise.reject(error);
    }
});

export default instance;
```

https://gist.github.com/edmondburnett/38ed3451de659dc43fa3f24befc0073b

**Comment by mshojaei88** [comment]
> ```js
> qs
> ```

using below code will fix this bug 
`                    error.config.data = JSON.parse(error.config.data)
`

**Comment by mshojaei88** [comment]
You should also use below code for prevent crash in post requests :
` if(error.config.data)
                    error.config.data = JSON.parse(error.config.data)`
