### ISSUE TITLE
Ask for some methods to inspect the Request Headers

### ISSUE THREAD

**Issue by zheeeng** [mzabriskie/axios#939]
#### Summary

Ask for some methods to inspect the request headers. I want to implement a log saver which record the General Headers, Request Headers, and Response Headers, if it's a POST request, additional record the Request Payload, just like the logs Chrome Network Headers panel printed.

I can get some General Headers from put related fields together from the response data, and the Response Headers come from response `headers`, Request Payload from response `config.data`, but I don't find anyway to collect all the Request Headers. Wish a guide help me out.

**Comment by rubennorte** [comment]
In the browser you don't control all the headers being sent in a request, so that's hard to implement. You can infer some of them ('Accept-Language` for example) but you'd have to do it manually. Axios can only help you giving you the request headers configured in the request config.
