### ISSUE TITLE
cors error, but in chrome network tab response is 200, and terminal curl works fine

### ISSUE THREAD

**Issue by rihannarickeminem** [mzabriskie/axios#942]
XMLHttpRequest cannot load URLURLURLURL. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
But in chrom network tab i see how the server responded with 200 . 
Also with curl everything is workin fine.
What is the problem, how to fix it?

**Comment by sheam** [comment]
When you access that URL with CURL you aren't making a CORS request, because you are directly polling the URL. You need to configure your server to allow CORS requests.

**Comment by rihannarickeminem** [comment]
@sheam i perform the request to third party service ` https://www.tumblr.com/docs/en/api/v1` not to my local server

**Comment by walleXD** [comment]
I am having a very similar issue when it comes box.com api. Fetch works:
```
    window.fetch('https://api.box.com/oauth2/token', {
      method: 'POST',
      body: `grant_type=${'authorization_code'}&code=${token}&client_id=${clientId}&client_secret=${clientSecret}`,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
      }
    }).then(response => console.log(response.json()))
```
But trying to make the same post leads to cors error in chrome
```
axios({
      url: 'https://api.box.com/oauth2/token',
      method: 'post',
      data: {
        grant_type: 'authorization_code',
        code: token,
        client_id: clientId,
        clientSecret: clientSecret
      },
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
      }
    }).then(response => console.log(response))
```

Any ides on why the discrepancy?

**Comment by rubennorte** [comment]
@walleXD by default Axios serializes the data as JSON. Please read the documentation on how to serialize as `form-urlencoded`.
