### ISSUE TITLE
How to set cookies when send a request in node ?

### ISSUE THREAD

**Issue by vifird** [mzabriskie/axios#943]
How to set cookies when send a request in node ?

**Comment by ClickSimply** [comment]
The cookies need to be passed into the headers object.

```js
Axios.request({
     url: "http://example.com",
     method: "get",
     headers:{
         Cookie: "cookie1=value; cookie2=value; cookie3=value;"
     } 
}).then...
```

**Comment by jenskuhrjorgensen** [comment]
Thanks for the great answer @ClickSimply !

Just to add to your answer the alternative way of making a get/post/put/delete/etc. request:
```
axios.get(url, {
            headers: {
                Cookie: "cookie1=value; cookie2=value; cookie3=value;"
            }
        }).then...
```

**Comment by shauvet** [comment]
HI, I've receved this error "Refused to set unsafe header "Cookie"",can anyone help me?

**Comment by vifird** [comment]
@jenskuhrjorgensen @ClickSimply  Thanks a lot.

**Comment by JChermy** [comment]
but I got an error "Refused to set unsafe header "Cookie" when set cookie like above way

**Comment by ClickSimply** [comment]
Could you post your code and the context you're using it in?

**Comment by JChermy** [comment]
I have resolved my problem. The code is below
```
  handleSearch() {
      const form = new FormData()
      form.append('user', 'xxx')
      form.append('password', 'xxx')
      axios('/api/Basic/Login/verify', {
        method: 'post',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        data: form
      }).then(response => {
        console.log(response)
        })
      })
    }
```

**Comment by JChermy** [comment]
and I set proxyTable cookieDomainRewrite option

**Comment by happilymarrieddad** [comment]
@JChermy can you post your code with the cookieDomainRewrite? I think I'm encountering the same problem.

```
_req(path,packet = {},method = 'get') {
		let self = this

		let uri = self.baseurl + path
		let pack = self._package(packet)
		let config = {
			headers:{ Cookie:"token=" + self.token },
			withCredentials:true
		}
		return axios[method](uri,pack,config)
	}
```

![selection_022](https://user-images.githubusercontent.com/6416323/36463554-f2a5ac56-1687-11e8-84ab-da9fb412550b.png)

**Comment by sherlock1982** [comment]
So when used in Node Axios will not respect Set-Cookie and send them back, right? Is it by design?

**Comment by MartinLasek** [comment]
Hey @JChermy, nice you got it working!
I encounter the same issue with `Refused to set unsafe header "Cookie"`.
Could you share your code how you set the `proxyTable` and `cookieDomainRewrite` 😊 ?

**Comment by sherlock1982** [comment]
May be this will give you idea (nodejs). This is how I return XSRF token using tough-cookie.

        import Axios, {AxiosInstance} from 'axios';
        import axiosCookieJarSupport from 'axios-cookiejar-support';
        import {CookieJar} from 'tough-cookie';

        const jar = new CookieJar();
        http = Axios.create({baseURL, withCredentials: true, jar});
        axiosCookieJarSupport(http);
        await login(http, defaultCredentials);

        const cookies = jar.getCookiesSync(baseURL);
        http.defaults.headers['X-XSRF-TOKEN'] = cookies.find((x) => x.key === 'XSRF-TOKEN').value;

**Comment by MartinLasek** [comment]
I guess I've found your code @JChermy here: https://github.com/JChermy/vue-table/blob/16523f310dd13adb2f27c174e172d31e42d21685/config/index.js#L14-L26 😊

**Comment by hungdev** [comment]
i found the answer here:
https://stackoverflow.com/questions/43002444/make-axios-send-cookies-in-its-requests-automatically
```
axios.get('some api url', {withCredentials: true});
```
or: 

```
const api = create({
  baseURL: Configs[env].BACKEND_HOST,
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
    Cache: "no-cache",
  },
`  withCredentials: true,`
  timeout: 60000
})
```

**Comment by nzvtrk** [comment]
@hungdev 
WithCredentials true not work at node.js

I'm writed simple example for works with cookie/session in node.js

https://gist.github.com/nzvtrk/ebf494441e36200312faf82ce89de9f2

**Comment by blueeye113** [comment]
Great answers!!!

**Comment by gemyero** [comment]
I have found a solution. Please look at the following code.
```javascript
const axios = require('axios');
const axiosCookieJarSupport = require('axios-cookiejar-support').default;
const tough = require('tough-cookie');

axiosCookieJarSupport(axios);

const cookieJar = new tough.CookieJar();

(async () => {
  await axios.get('http://localhost:3000/route1', {
    jar: cookieJar,
    withCredentials: true
  });
  await axios.get('http://localhost:3000/route2', {
    jar: cookieJar,
    withCredentials: true
  });
})();
```
