### ISSUE TITLE
Custom instance defaults  axios.all  is not a function

### ISSUE THREAD

**Issue by mrerhuo** [mzabriskie/axios#948]
![image](https://user-images.githubusercontent.com/9547741/26964266-57859ca0-4d23-11e7-9907-05b91f8cac01.png)
![image](https://user-images.githubusercontent.com/9547741/26964353-a6b3b23a-4d23-11e7-92d8-daae008c78cd.png)
![image](https://user-images.githubusercontent.com/9547741/26964363-ae93a3e8-4d23-11e7-888e-e3374bdce8f3.png)

**Comment by shiyuegongsui** [comment]
+1

**Comment by kirakik** [comment]
Did anybody find a solution to this?

**Comment by flcleddie** [comment]
+1

**Comment by ly911222** [comment]
```javascript
instance.all = axios.all
```

**Comment by mrerhuo** [comment]
ly911222 I try is no

**Comment by rameshsunkara** [comment]
+1

**Comment by grimpa** [comment]
@mrerhuo Try to use ```Promisse.all()``` instead

**Comment by rubennorte** [comment]
The `all` helper is only available in the axios object, not in any instance. I'm in favor of removing those helpers from axios, so you should be using `Promise.all` anyway.
