### ISSUE TITLE
Unable to read set-cookie header in node

### ISSUE THREAD

**Issue by jasonkuhrt** [mzabriskie/axios#953]
First sanity check:

```
❯ curl -I "https://httpbin.org/cookies/set?a=1"
HTTP/1.1 302 FOUND
Connection: keep-alive
Server: meinheld/0.6.1
Date: Tue, 13 Jun 2017 15:25:30 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 223
Location: /cookies
Set-Cookie: a=1; Path=/
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0.00121402740479
Via: 1.1 vegur
```

Compare with Axios:

```js
import Axios from "axios"

it("axios supports set-cookie", () =>
  Axios.request({
    method: "get",
    url: "https://httpbin.org/cookies/set?a=1"
  }).then(res => {
    expect(res.headers["set-cookie"]).toMatch(/a=1/)
  }))
```
```
  ● axios supports set-cookie

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined
```

Releatd https://github.com/mzabriskie/axios/issues/295. Am I missing something?

**Comment by ClickSimply** [comment]
Try adding `withCredentials:true` to the request options.

**Comment by ClickSimply** [comment]
Just did some testing, that specific site sets the header and does a 302 redirect, Axios isn't setting the cookie before following the redirect, meaning you just get sent to `https://httpbin.org/cookies/` with no cookie set.

You can see the cookie with this code:

```js
const Axios = require("axios").default;

Axios.request({
    method: "get",
    url: "https://httpbin.org/cookies/set?a=1",
    maxRedirects: 0,
    validateStatus: function(status) {
        return status >= 200 && status < 303;
    },
}).then(res => {
    console.log(res.headers["set-cookie"]);
});
```

**Comment by jasonkuhrt** [comment]
@ClickSimply Thanks for the informative response! Why is the library designed like this?

**Comment by ClickSimply** [comment]
I'm not sure why it does that, not a major contributor to the lib or anything...

**Comment by rubennorte** [comment]
This works this way by design. If you want to check the headers in a redirect response you shouldn't automatically follow redirects and do it manually. You can do this by setting `maxRedirects: 0` in the configuration.

**Comment by samayo** [comment]
This is still an issue that we ought to discuss about. I just sent a `GET` request to http://httpbin.org/headers as: 

```js
var post = axios('http://httpbin.org/headers', {
  method: 'GET',
  mode: 'no-cors',
  data: some.data,
  withCredentials: true
})
```
And I am getting all the responses, except for the cookie.

**Comment by rubennorte** [comment]
@samayo that's a different issue, as this was originally for Node.js and yours is for the browser. With `no-cors` you won't have access to the response nor any of the headers.

**Comment by yipcma** [comment]
i myself am plagued by this issue and finally, got a solution.
Remember: always put the set cookies etc. inside headers: {} which lives inside config. 
It is a very common mistake to put the header accidentally in the place of data.

**Comment by dalirnet** [comment]
`status < 303` to `status <= 303` 

```
const Axios = require("axios").default;

Axios.request({
    method: "get",
    url: "https://httpbin.org/cookies/set?a=1",
    maxRedirects: 0,
    validateStatus: function(status) {
        return status >= 200 && status <= 303;
    },
}).then(res => {
    console.log(res.headers["set-cookie"]);
});
```

**Comment by jasonkuhrt** [comment]
@rubennorte thanks makes sense!

**Comment by zhaoxuyll** [comment]
if use node.js express
see [stackoverflow](https://stackoverflow.com/questions/15298342/express-session-angular-cant-access-connect-sid-cookie)
```
app.use(express.session({
    secret: 'mySecret',
    cookie: { httpOnly: false }
}));
```

**Comment by ming444** [comment]
still can't get cookies by `res.headers["set-cookie"]`, but can get by `document.cookie` .

**Comment by yeecai** [comment]
still can't get response cookie by res.headers["set-cookie"] nor res.headers.get["set-cookie"]
