### ISSUE TITLE
Set Default Promise Implementation

### ISSUE THREAD

**Issue by ClickSimply** [mzabriskie/axios#957]
#### Summary

Sort of re opening #290.

I'd like to see the feature implemented where you can do this:

```ts
import { Promise } from "wherever";
import Axios from "axios";
Axios.defaults.Promise = Promise 
```

#### Context
I have a library that compiles to two different places: one compilation is a webpack browser bundle and the other is a direct typescript compile for use by node js.

For the webpack browser bundle, I do this to provide the `Promise` global and this works great:
```js
        new webpack.ProvidePlugin({
            Promise: ["es6-promise"]
        }),
```

However, when I use the library by calling `npm i` against it's URL, all the `import` statements for the lib are using the NodeJS compilation, performed by typescript instead of webpack.  

A webpack bundle doesn't work well with nodeJS import statements combined with typescript .d.ts files.  

What ends up happening is the app using the custom library (which contains Axios as a dependency) also has to put the Promise provider in it's webpack configuration.

This whole process would be much easier if I could just tell Axios what Promise constructor to use in the library, instead of forcing me to provide a Promise global all the way up the chain.

Hope that makes sense.

**Comment by rubennorte** [comment]
@ClickSimply I already commented there why I don't think this should be implemented. In the browser it could make sense but there are other methods to do it (as you pointed out with Webpack). We need to get used to the fact that `Promise` is now part of the language and we shouldn't replace native language features (as we don't modify `Object` or `Array`). With `async`-`await` being officially added to the spec this makes even more sense, as any modification on the global `Promise` won't affect those functions.
