### ISSUE TITLE
axios.get doesn't make HTTP call the second time on my Windows phone

### ISSUE THREAD

**Issue by c0debreaker** [mzabriskie/axios#958]
I know, Windows phone is old. :) My phone is a Lumia 920 Windows version 8.

I'm using ReactJS and axios. Below is my code
```
  triggerGarage = () => {
    alert('do I get called?');
    axios.get('/api/garage')
       .then(function (response) {
         alert('inside axios .then')
       })
       .catch(function (error) {
         alert('error')
       });
  }
```

When I click a button `onClick={this.triggerGarage}`, it calls the function and my nodejs api applications receives the GET request from my React web app. However, if I click it again, my phone will still display an alert showing "do I get called?" and also "inside axios .then". However, my api didn't receive it.

When I changed it to axios.post as well as added a new express post in my nodejs, it worked very well even if I click the button so many times. There were no issues.

What could be wrong when using .get?

**Comment by VitaliyLogvin** [comment]
Hi, did you find a solution?
I use axios.post requests. And on the Windows phone there is no action. Perhaps this technology does not work with such phones.

**Comment by c0debreaker** [comment]
Yup, I went with .post

```
  shortGarage2WirePins = (doorNum) => {
    axios.post('/api/garage', qs.stringify({ 'doornum': doorNum }));
  }
```
then I use it like this
```
<button className="garage-props" onClick={() => this.shortGarage2WirePins(0)} onChange={() => this.shortGarage2WirePins(0)}>Door1</button>
```

**Comment by c0debreaker** [comment]
I'm not really sure if it's an axios issue or the old ie browser on my phone. I decided to just use `.post` and not waste time trying to get .get working
