### ISSUE TITLE
Reviver

### ISSUE THREAD

**Issue by challenger532** [mzabriskie/axios#968]
Is there any way to customize parsing the response text, like to pass a reviver function to JSON.parse, so we can get a response with customized object ? [JSON.parse(text[, reviver])](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse)

**Comment by rubennorte** [comment]
You can use a custom `transformResponse` option in your request config. Please review the documentation.
