### ISSUE TITLE
IOS 7兼容吗

### ISSUE THREAD

**Issue by zhangle991224** [mzabriskie/axios#970]
IOS 7兼容吗

**Comment by erictt** [comment]
你搞错了吧？ 这是JS。。。

**Comment by gaterking** [comment]
It's ok.

**Comment by rubennorte** [comment]
I'm sorry but for the moment there isn't any contributor that speaks Chinese. If any user translates this we'll reopen.

**Comment by YFengFly** [comment]
I'm sorry for write this closed question.

The question is : Does axios support for iOS 7?

I think he should  use https://caniuse.com to check this question.
Promises is not support iOS 7 & Android 4.4 and lower,URLSearchParams is not support iOS 10 & Android Webview (Chrome) 49 and lower.But I don't know what other ways are incompatible.
@zhangle991224 if you notice that Axios is support IE9 in 2011,why not Axios not support iOS7 in 2013?It depends on how you use it.

------------------------------------------------------------------

Hi,@zhangle991224 .对于歪果仁创建的项目，请尽量使用对应语言进行描述哈——比如你可以把内容通过xx翻译搞过来...
我想这个问题主要取决于你使用了什么。如果只是简单使用，即便是2011年的IE9都支持，为什么会不支持2013年的iOS7呢？
如果你使用了Promises 、URLSearchParams  之类的话，那么要考虑具体这些是否支持（虽然Axios也使用了其中的API，不过只是普通使用是不会碰上的，具体请看源码）。具体请在 https://caniuse.com 查询。
