### ISSUE TITLE
cross-domain request cannot get response headers 

### ISSUE THREAD

**Issue by baixiyang** [mzabriskie/axios#976]
cross-domain request cannot get response headers when it exit .how to get the headers.

**Comment by deepsweet** [comment]
Just faced same issue and found that it's related to server side. For example with Express you can use [CORS middleware](https://github.com/expressjs/cors) with special options: `cors({ exposedHeaders: [ 'my-header' ] })`

**Comment by konieshadow** [comment]
Faced same issue and solved by checking [Mozilla's CORS document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Expose-Headers) about Access-Control-Expose-Headers.
