### ISSUE TITLE
Axios throws error on Nodejs (http adapter) on status 3xx

### ISSUE THREAD

**Issue by paul321** [mzabriskie/axios#981]
Axios throws an error if is used in Node JS with maxRedirects = 0 the promise is rejected not resolved, this shouldn't be an error for example on status 302, we need the headers for a auth page which is redirecting to another one and it sets auth cookies, but right now it cannot be neither intercepted or solved.

**Comment by rubennorte** [comment]
You must provide a custom `validateStatus` option because the default one checks the status code is between 200 and 299.
