### ISSUE TITLE
json parse bigint 9223372036854775807 to 9223372036854776000 

### ISSUE THREAD

**Issue by fyname** [mzabriskie/axios#983]
1 json parse bigint 9223372036854775807 to 9223372036854776000 
2 user version is "axios": "^0.16.1",

you use:
https://github.com/sidorares/json-bigint

var JSONbig = require('json-bigint');

var json = '{ "value" : 9223372036854775807, "v2": 123 }';
console.log('Input:', json);
console.log('');

console.log('node.js bult-in JSON:')
var r = JSON.parse(json);
console.log('JSON.parse(input).value : ', r.value.toString());
console.log('JSON.stringify(JSON.parse(input)):', JSON.stringify(r));

console.log('\n\nbig number JSON:');
var r1 = JSONbig.parse(json);
console.log('JSON.parse(input).value : ', r1.value.toString());
console.log('JSON.stringify(JSON.parse(input)):', JSONbig.stringify(r1));

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.

**Comment by rubennorte** [comment]
You can use the `transformResponse` option to use a custom implementation of JSON.parse or any other transformation on the response you may find appropiate.

**Comment by fewiki** [comment]
transformResponse perfect!
