### ISSUE TITLE
Error: Request failed with status code

### ISSUE THREAD

**Issue by umutozdemir97** [mzabriskie/axios#984]
When there is 404 error, I can't access the response. A request is failed. But whatever, I want to access the response. There is only an error parameter at the catch function. How can I access the response if there is a 404 error? It seems that axios has disabled doing this. 

But sometimes there is a response, even though there is a 404 error.

**Comment by mentos1386** [comment]
Hey @umutozdemir97 
You should check out https://github.com/mzabriskie/axios#handling-errors. Error object itself contains response.
