### ISSUE TITLE
axios IE hell...

### ISSUE THREAD

**Issue by rakmaster** [mzabriskie/axios#985]
I'm using a Laravel 5.4 implementation with Vue.js. Axios is being used to make an ajax call based on a selection. It's a pretty simple method. You click the button, it sends an ajax request, you get a response. It works in every browser, every time... except IE. IE is giving me a 'SCRIPT5007: Object expected' and when you trace the offending line of code you find that Vue's nextTick method is derping out. So, it seems to me to be a promise problem with IE, but I have no idea where to go from here, because it's a very specific thing between Vue, axios and IE.

If you want to see what it's doing, then go here: http://rudolphkc.phantasea.net/products/pulmonary_function_and_exercise_testing

Then click on any of the product categories. But you have to use IE, because everything else in the world works just fine

**Comment by adambloomer** [comment]
I had the same error so I used Babel Polyfill  https://babeljs.io/docs/usage/polyfill/

**Comment by rubennorte** [comment]
This doesn't seem like an issue in Axios but in the environment configuration. I recommend you trying a solution like the one @adambloomer recommends.
