### ISSUE TITLE
"Faked finally" - will this potentially cause any issues?

### ISSUE THREAD

**Issue by manuschiller** [mzabriskie/axios#988]
Hi!

I found an easy solution to "fake" a `finally` callback with axios, without installing any shims or polyfills.

https://codepen.io/lnfnunes/pen/ygzEvY
```
console.clear();

axios.all([
  axios.get('https://httpbin.org/get'),
  axios.get('https://httpbin.org/404')
])
.catch(error => console.log('Catch:', error))
.then(() => console.log('Finally!'))
```

is this considered bad practice, or will this cause any potential issues? I've only seen the order 

```
.then() // resolved
.catch() // rejected
.finally() // always execute me..
```

so far, but never actually thought about changing it..

thanks!

**Comment by jonnywilliamson** [comment]
Wondering the same thing!

**Comment by OwnageIsMagic** [comment]
It's ok, but you should make sure that your `catch` will never throw exception otherwise finally won't be called
