### ISSUE TITLE
withCredentials setting Safari 10.1.1 (12603.2.4) Don't work

### ISSUE THREAD

**Issue by An0nymous0** [mzabriskie/axios#989]
#### Instructions
`var apiInstance = axios.create({
  baseURL: process.env.API_URL,
  timeout: 10000,
  withCredentials: true
});`

#### Summary

withCredentials setting Safari 10.1.1 (12603.2.4) Don't work

#### Context

- axios version: *e.g.: v0.16.2*
- Environment: *e.g.: node v8, Safari 10.1.1 (12603.2.4), macOS 10.12.5*

**Comment by tvtri96** [comment]
Have the same problem as well.

**Comment by rubennorte** [comment]
Closing as this doesn't seem a problem in Axios
