### ISSUE TITLE
es6-promises polyfill is not a polyfill

### ISSUE THREAD

**Issue by TuxujPes** [mzabriskie/axios#99]
Even though i am using Chrome, i can see axios using es6-promise polyfill.
Is this an intended behaviour?

**Comment by mzabriskie** [comment]
The `es6-promise` polyfill should use a native `Promise` implementation if it's available. In any case, the next release will remove the `es6-promise` dependency, and polyfilling will be left up to individual developers.

**Comment by skevy** [comment]
@mzabriskie fwiw, the issue @TuxujPes surfaced it's ugly head when using axios on react-native.

This issue -- es6-promise#140 (https://github.com/jakearchibald/es6-promise/issues/140) -- discusses the problem. The key is this line:

```javascript
Object.prototype.toString.call(P.resolve()) === '[object Promise]' && !P.cast)
```

On chrome (and react-native), that fails, and thus it always gets polyfilled.

It seems like in the next release this won't matter, but I just thought I'd let you know that it actually IS a problem.
