### ISSUE TITLE
Feature request: Multiple uploads: Way to map onUploadProgress's progressEvent to the corresponding file

### ISSUE THREAD

**Issue by ThomasLandauer** [mzabriskie/axios#991]
When doing mutliple file uploads (i.e. `<input type="file" multiple>`), I can't find a way to find out which of the files the `progressEvent` is refering to.

I've asked this question (with more details) at https://stackoverflow.com/questions/44893946/axios-upload-progress-for-multiple-file-uploads - but since nobody answered, I'm figuring it's just not possible.

- axios version: 0.16.2

**Comment by davidbarker** [comment]
I'd also love this feature. I'm currently using jQuery's `xhrFields` to pass an ID to each progress event, which then allows me to find the upload it corresponds to. Is this possible in Axios?

**Comment by rubennorte** [comment]
I don't even know if that's possible with XMLHttpRequest (which is what Axios uses). Could you see if it is and send a code snippet with XHR?

**Comment by ThomasLandauer** [comment]
@rubennorte: So what would you currently (i.e. out of the box) suggest to achieve this? The only thing I could think of is to keep track of the to-be-uploaded files (in some array) and proceed to the next entry, whenever the progress reaches 100%.  
In other words: Relying on the fact that the uploads are done sequentially (i.e. not parallel).
