### ISSUE TITLE
progressEvent.total is giving inconsistent numbers

### ISSUE THREAD

**Issue by ThomasLandauer** [mzabriskie/axios#992]
#### Summary

When uploading the same file several times, I'm getting different numbers from `console.log(progressEvent);` inside `onUploadProgress: function(progressEvent)`:
* 181761
* 181751
* 181766
* 181756

Also, the number differs from the actual file size on my hard drive, which is 181067. That's also what `event.target.files[0].size` (event = file selection dialog) is reporting.

Note: First and foremost, I'm looking for a solution for https://github.com/mzabriskie/axios/issues/991 ! Just as a last resort, I came up with the idea to use the file size for the mapping ;-)

#### Context

- axios version: v0.16.2
- Environment: nginx, Firefox 54.0.1, Windows 10

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.
