### ISSUE TITLE
Hold execution of a request until request interceptor is done

### ISSUE THREAD

**Issue by prionkor** [mzabriskie/axios#994]
Hello,

I am trying to connect with server with request interceptor for certain condition. I am creating axios request from request interceptor but the main axios request doesn't wait until the ajax from request interceptor finishes.

You can see more details here 

https://stackoverflow.com/questions/44985708/axios-request-interceptor-wait-until-ajax-call-finishes

( my apologies for opening a ticket here but there is no response on SO question )

**Comment by rubennorte** [comment]
You can do it but returning a new promise in the interceptor that resolves with the configuration that you want to use.
