### ISSUE TITLE
Using Vue to upload image using Formdata to server

### ISSUE THREAD

**Issue by maryheng** [mzabriskie/axios#997]
Hi all,
When I want to upload an image and send the other data using FormData. Axios seems to serialise the image. Therefore, when i upload the image using Axios, the image is inside the body's payload as a string. As a result, I'm unable to use Multer on the server side to retrieve the uploaded image from the request.

This is my HTML code:
`<input type="file" @change="onFileChange">`

This is my Vue code:
```
export default () {
  name: 'app',
  data () {
    image: ''
  },
  methods: {
      onFileChange (e) {
      var files = e.target.files || e.dataTransfer.files
      if (!files.length) {
        return
      }
      // console.log(files[0])
      // var x = files[0]
      return this.createImage(files[0])
      // return new Buffer(x)
    },
    createImage (file) {
      // var image = new Image()
      var reader = new FileReader()
      var vm = this

      reader.onload = (e) => {
        // vm.image = e.target.result
        vm.image = file.toString('base64')
        console.log(vm.image)
      }
      reader.readAsDataURL(file)
    },
    submitStaff () {
      const formData = new FormData()
      formData.append('file', this.image)
      formData.append('name', this.data.name)
      formData.append('username', this.data.username)
      formData.append('password', this.data.password)

      axios.post('api/myApiUrl', formData)
        .then(function (response) {
          console.log(response)
        })
        .catch(function (error) {
          console.log(error)
        })    
  }
}
```

Request Payload (Error with Vue)
<img width="351" alt="screen shot 2017-07-11 at 8 15 25 pm" src="https://user-images.githubusercontent.com/13627091/28102854-a6daef12-6704-11e7-8832-d5f91f9b8dd2.png">

Request Payload (Successful with Postman) (This is what i want)
![correctone](https://user-images.githubusercontent.com/13627091/28102866-b9135ffc-6704-11e7-8573-ff8a0b7c5ecb.jpeg)

How do i go about doing this? I have posted this on Stackoverflow too.
https://stackoverflow.com/questions/45034456/axios-for-vue-not-uploading-image-to-server

**Comment by lucysyt** [comment]
i don‘t know


------------------ 原始邮件 ------------------
发件人: "Mary Heng";<notifications@github.com>;
发送时间: 2017年7月12日(星期三) 中午1:24
收件人: "mzabriskie/axios"<axios@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [mzabriskie/axios] Using Vue to upload image using Formdata to server(#997)




Hi all,
 When I want to upload an image and send the other data using FormData. Axios seems to serialise the image. Therefore, when i upload the image using Axios, the image is inside the body's payload as a string. As a result, I'm unable to use Multer on the server side to retrieve the uploaded image from the request.
 
This is my HTML code:
 <input type="file" @change="onFileChange">
 
This is my Vue code:
 export default () {   name: 'app',   data () {     image: ''   },   methods: {       onFileChange (e) {       var files = e.target.files || e.dataTransfer.files       if (!files.length) {         return       }       // console.log(files[0])       // var x = files[0]       return this.createImage(files[0])       // return new Buffer(x)     },     createImage (file) {       // var image = new Image()       var reader = new FileReader()       var vm = this       reader.onload = (e) => {         // vm.image = e.target.result         vm.image = file.toString('base64')         console.log(vm.image)       }       reader.readAsDataURL(file)     },     submitStaff () {       const formData = new FormData()       formData.append('file', this.image)       formData.append('name', this.data.name)       formData.append('username', this.data.username)       formData.append('password', this.data.password)       axios.post('api/myApiUrl', formData)         .then(function (response) {           console.log(response)         })         .catch(function (error) {           console.log(error)         })       } }  
Request Payload (Error with Vue)
 
 
Request Payload (Successful with Postman) (This is what i want)
 
 
How do i go about doing this? I have posted this on Stackoverflow too.
 https://stackoverflow.com/questions/45034456/axios-for-vue-not-uploading-image-to-server

**Comment by supra28** [comment]
Have you tried appending the file directly to formData? That's the way I've always done it.
```
var img = e.target.files[0]
formData.append('file',img)
```
