### ISSUE TITLE
Feature support: protocol buffer

### ISSUE THREAD

**Issue by angelathewebdev** [mzabriskie/axios#998]
I'm currently using protocol buffer for data transport and currently, our code base is using `axios` for HTTP requests. I would like to contribute by adding protocol buffer support by extending `axios` with option to use `transformResponse` and `transformRequest` functions that does the encoding and decoding of messages.

As data validation requests and responses depend on protocol buffer message, by adding support to protocol buffer, the transform function would also need to pass in more arguments than it currently does, for example, a `transformOptions` object.

**Comment by rubennorte** [comment]
That is a very specific use case and can be implemented via plugins. We're trying to maintain the Axios core small so this isn't likely going to be implemented.
