### ISSUE TITLE
Axios doesn't appear to support NTLM or Server trust authentication for iOS

### ISSUE THREAD

**Issue by jontowles** [mzabriskie/axios#999]
Axios doesn't appear to support NTLM or Server trust authentication for iOS devices in React Native.

**Comment by rubennorte** [comment]
That seems like a very specific use-case. You may want to check if it can be implemented via interceptors but this isn't likely to be implemented in Axios core.

**Comment by robodude** [comment]
That's too bad. I really prefer axios but I've had to use https://github.com/SamDecrock/node-http-ntlm as an alternative in a recent project.

**Comment by avengerweb** [comment]
@rubennorte may be you change your decision?
